### ISSUE TITLE
Menubar timer not in sync with the main timer

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1027]
timer in OS X topbar lags for 2-3 minutes
case 118904

**Comment by iBobik** [comment]
Happens for me too.

**Comment by tanel** [comment]
cannot reproduce in master branch

**Comment by tanel** [comment]
the menubar timer does not render seconds. this could be a source of confusion, but it's by design.

I'm still not able to reproduce the issue in master branch, maybe its somehow user specific.

**Comment by tanel** [comment]
The issue exists in the current released version, but is fixed in master, as noted above.
