### ISSUE TITLE
massage sqlite error into something more meaningful for user

### ISSUE THREAD

**Issue by tanel** [toggl/toggldesktop#1032]
Generic SQLite error: Unknown error code: 2067: insert into time_entries(id, uid, description, wid, guid, pid, tid, billable, duronly, ui_modified_at, start, stop, duration, tags, created_with, deleted_at, updated_at, project_guid) values(:id, :uid, :description, :wid, :guid, :pid, :tid, :billable, :duronly, :ui_modified_at, :start, :stop, :duration, :tags, :created_with, :deleted_at, :updated_at, :project_guid) in Toggl Desktop

Is this a DB corruption issue or a real SQL error?

**Comment by IndrekV** [comment]
Knows errors should show actionable message to the user.
example: "Something is blocking toggl desktop, please check your Network settings..."

**Comment by tanel** [comment]
duplicate of #1091
