### ISSUE TITLE
File not found: /Users/xxx/Desktop/TogglDesktop…pem in Toggl Desktop

### ISSUE THREAD

**Issue by tanel** [toggl/toggldesktop#1033]
for some reason cacert.pem is either not readable or really not found on users machine.

**Comment by tanel** [comment]
Can't reproduce the issue. Let's contact the user(s) who experience the issue next time.

**Comment by stanilovic** [comment]
Hi tanel, I am experiencing this issue.
In addition, Toggl Desktop on Windows is crashing.

**Comment by IndrekV** [comment]
@stanilovic if possible please send feedback from the app and mention the info is for Indrek. That way we get log files and can look more into it.

**Comment by stanilovic** [comment]
Hi Indrek
Do you have any news on this?

**Comment by IndrekV** [comment]
Haven't been able to reproduce and have not had any other feedback on this issue.
