### ISSUE TITLE
Don't allow user to flood the lib from the UI

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1036]
Should back off.

**Comment by tanel** [comment]
What's the use case for this? Perhaps we should not allow user to flood the app in the first place?

**Comment by tanel** [comment]
At the moment I can click in the OSX app on the start/stop button, then press Return and fall asleep. It will flood the app and spam the backend :/

**Comment by tanel** [comment]
We should block user input in the lib if start/stop occurs more than once per second or similar, I guess.

Backing off when user has created thousands of time entries will not help the backend, since after the backoff period the time entries are still spammed to the backend.
