### ISSUE TITLE
Exe based installer

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1037]

**Comment by tanel** [comment]
http://en.wikipedia.org/wiki/List_of_installation_software#Windows lists a bunch of EXE based installers.

Of those both EXE based, and open source, are only following installers:

http://en.wikipedia.org/wiki/Inno_Setup
http://en.wikipedia.org/wiki/Nullsoft_Scriptable_Install_System

http://en.wikipedia.org/wiki/Nullsoft_Scriptable_Install_System seems to be more popular and is supposedly learnable in a day, whereas InnoSetup requires custom Pascal scripting.

I'll this The NSIS (http://en.wikipedia.org/wiki/Nullsoft_Scriptable_Install_System) first.
