### ISSUE TITLE
New window header design

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1038]

**Comment by pe0ny** [comment]
More info available here: https://drive.google.com/a/toggl.com/file/d/0B3HI5pCjbfU2S1QwcDNRa3hPY3c/view?usp=sharing

All icons, fonts etc here: https://drive.google.com/a/toggl.com/folderview?
id=0B3HI5pCjbfU2OGprbnNCV2VPbVE&usp=sharing
