### ISSUE TITLE
Pressing start keyboard shortcut should start the latest entry, not empty entry

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1045]
This was how it worked before.
Works the same way in Windows.
Was accidentally changed with the latest release.

**Comment by IndrekV** [comment]
Might not be a problem. Needs double checking.
See case 122533 for more.

**Comment by tanel** [comment]
Not really sure what the issue is. "Start" will start a new time entry, whereas "Continue" will continue the last one. Seems to work as advertised.
