### ISSUE TITLE
Windows can't open update

### ISSUE THREAD

**Issue by Carrot-Top** [toggl/toggldesktop#1049]
I get the following error message from Windows Installer: "This installation package could not be opened. Contact the application vendor to verify that this is a valid Windows Installer package."

**Comment by tanel** [comment]
We have no other reports about this. Most probably it's a one-off download issue. Can you please try again?

**Comment by Carrot-Top** [comment]
Thank you, tanel. I was able to download & update Toggl today. Must have been a quirk with my system.
