### ISSUE TITLE
Counts time when laptop is suspended

### ISSUE THREAD

**Issue by shreyaspotnis** [toggl/toggldesktop#1050]
Toggl currently counts the time when my laptop was suspended. Sometimes this is a feature: when I am working away from my laptop, but sometimes I would want it to exclude the time when it was suspended: like when I'm on a short coffee break. It would be great if it could give the option of excluding the time when my laptop was suspended.

**Comment by tanel** [comment]
It should detect that you were away if you have the idle detection enabled in the Preferences. Can you check it out if it helps?

**Comment by shreyaspotnis** [comment]
Ha! That works. It just informs me after a little while. Thank you!

Shreyas Potnis.
