### ISSUE TITLE
Manually entering entry with up to 5s duration is not synced to web

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1051]
If a task is created manually in the Toggl Desktop app of 1s, 2s, 3s, 4s or
5s, it will not sync to the Toggl Web Timer.

If I create a task manually with a duration of 6 seconds, it will
immediately appear in the Toggl Web Timer.

steps to replicate:
- Toggl Desktop app: Type in new task name.
This exact name may be part of the problem.
- Click the 00:00:00 to show the fly-out window
- In the fly-out, set project and change duration to 1 second
- Close fly-out
- The task will appear in the Toggl Desktop app, but not on the web-based
Toggl timer
- If I sync the Toggl Desktop app, it doesn't make a difference
- If I log in / out of either service, it doesn't make a difference
- If I Clear Cache in the Toggl Desktop app, then log back in, the task is
gone

More info in case 113224

**Comment by tanel** [comment]
It's by design :) I'll remove the "time entry too small" check.
