### ISSUE TITLE
Crashes 5 to 10 seconds after opening

### ISSUE THREAD

**Issue by Lomacar** [toggl/toggldesktop#1052]
I started testing out the new desktop app (last time I used Toggl was in March 2014). At first it was working fine. I created a few time entries and tried seeing how to assign them to a project and client (why Toggl uses this backwards approach, I really don't understand). Then I decided to start timing for real. I was starting a new project for a new client so I began the usual awkward process of start-stopping the timer and then going to edit it and create a project for which I need to create a client first. The weird thing is that when I was creating the client I notice I accidentally assigned it to a workspace which I had just deleted from the Toggl website. So then I tried changing the workspace and creating the client again, except somehow I think I was creating a project by accident, but anyway it is about that time that Toggl suddenly crashed. And now whenever I start Toggl it "Stops Working" within a few seconds from launching it.

I deleted all the tasks, I deleted the appdata folders, I re-installed, but still it crashes (but it doesn't ask me to log in, so I guess re-installing didn't clear everything).

**Comment by tanel** [comment]
Hi! It could be a data issue indeed. Please contact support@toggl.com, we'll need to inspect your local database file that is located at:

~/Library/Application Support/Kopsik/production

I'll close this issue, lets continue via support.
