### ISSUE TITLE
Add button to load more history

### ISSUE THREAD

**Issue by oluckyman** [toggl/toggldesktop#1056]
At the bottom of the list of the previous time entries should be the button «Show more».
It is useful in case when you need to continue the task that not in the list but you don’t remember what exactly title was.

**Comment by tanel** [comment]
Currently we auto-purge data older than 9 days or so. I'm not sure what should the app do if user loads more data. Increase the number of days data is kept, perhaps?

**Comment by oluckyman** [comment]
Maybe not to purge the data at all? Or purge the data not by date but by count.
When I come back to work after long holidays or vacation my list is empty. Whereas what I expect is to see this list as it was before I left.

Even if the data is purged why do not fetch it from the server again if the user asks?

**Comment by tanel** [comment]
Perhaps we could fetch more data if users asks to do so, and increase the number of days we keep the time entries. 

We'd increase the number of max days in memory, so that if user restarts the app, the number will be down again and the excessive time entries are purged again.

**Comment by tanel** [comment]
I'll implement this in lib, we'll need design for the button, too.

**Comment by iBobik** [comment]
Too it will be nice to have config option to set default limit of entries to fetch. (last week, last month, last 2 months, ...)

**Comment by tysonclugg** [comment]
@tanel -- do you have a branch you can push for this issue, so someone else might be able to continue your work?

**Comment by tanel** [comment]
there isnt much progress on this issue, at the moment. no separate branch.

**Comment by amulware** [comment]
We have started work on this. See #1791 and #1792.
