### ISSUE TITLE
Group projects by client in the projects combobox 

### ISSUE THREAD

**Issue by oluckyman** [toggl/toggldesktop#1057]
When you have many clients and many projects for each of the client then this is really tiring to find the correct one.
Grouping by client or/and marking by color will help.

**Comment by tanel** [comment]
Implemented in branch tanel-group-projects-by-clients, needs a custom combobox now.

**Comment by amulware** [comment]
This has been implemented on Windows as part of the WPF redesign.

**Comment by oluckyman** [comment]
awesome! 
any chance to see that implemented in macOS version?
