### ISSUE TITLE
Handle server downtime

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1070]
if we get 500 or similar from server. 
Create timestamp.
Try again in random time between 20 mins and 60 mins
first do status req. if this is ok continue with sync.

**Comment by alari76** [comment]
I understood that similar thing should be implemented also for getting 400 from server, e.g. there are some data-related issues that prevent TDesktop from connecting properly.

**Comment by webervin** [comment]
Almost correct, for 40x you may never re-send same request without fixing data first.
