### ISSUE TITLE
7.1 Desktop Update for OS X is corrupted

### ISSUE THREAD

**Issue by Bdemers1055** [toggl/toggldesktop#1085]
![screen shot 2015-01-26 at 8 58 40 am](https://cloud.githubusercontent.com/assets/6231118/5900703/fe5f0190-a539-11e4-9670-083bbb38b0ac.png)

https://github.com/toggl/toggldesktop/issues/459

**Comment by tanel** [comment]
Please verify the checksum of the download.

For build 7.1.179 the md5 checksum is 34294fa21081e98aafdefde54c7ba806

There are no known signing issues with the OSX app at the moment.

Most likely it's a corrupt download.

But to be sure, please verify the checksum and if it's wrong, try to download from another network location / with another browser.
