### ISSUE TITLE
Use proxy settings from system

### ISSUE THREAD

**Issue by tobiOnGitHub** [toggl/toggldesktop#1087]
Create an option (for windows client) to use system/ie proxy settings. If your often on different customer sites with different proxy settings it's a nightmare to change the settings in more than one place.

**Comment by tanel** [comment]
https://github.com/videolan/vlc/blob/master/src/win32/netconf.c

**Comment by tanel** [comment]
vlc has proxy detection code for darwin as well: https://github.com/videolan/vlc/blob/master/src/darwin/netconf.c

**Comment by tanel** [comment]
and linux: https://github.com/videolan/vlc/blob/master/src/posix/netconf.c

other options to automatically detect proxy configuration is:
- https://code.google.com/p/libproxy/

**Comment by tanel** [comment]
Proxy configuration will be taken from the OS by default, now.

Auto-detection is not supported (yet).

Also auto-config using PAC file is not supported (yet).

Linux code uses "proxy" executable from libproxy library. If not installed, will not detect proxy.

HTTPS_PROXY, HTTP_PROXY, https_proxy, http_proxy env variables are used before using system proxy.

**Comment by chipbite** [comment]
This is not working for me at my workplace.
When I enter the proxy settings manually into toggl, it can connect.
If I check use system settings, it cannot and I cannot login.
