### ISSUE TITLE
add online state label to main window, like in the osx app

### ISSUE THREAD

**Issue by tanel** [toggl/toggldesktop#1093]

**Comment by tanel** [comment]
bump

**Comment by IndrekV** [comment]
Should use the footer bar. There are three possible states:
- (status==1) Online, in which case the footer is not shown at all
- (status==2) Offline: shows text "Status: Offline, no network"
- (status==3) Offline: shows text "Status: Offline, Toggl not responding"

status comes from lib `on_online_state`

**Comment by amulware** [comment]
Thanks for the additional info! The offline status is already parsed. Only have to show the correct text in the bar (will be done this week, when polishing the syncing part of the bar in #1190).

**Comment by amulware** [comment]
Everything is implemented, but I'm leaving this on a separate branch so we can test it before releasing it to beta.
