### ISSUE TITLE
Sometimes clicking on Start will just highlight text input field

### ISSUE THREAD

**Issue by liisa105** [toggl/toggldesktop#1094]
I can't tell exactly when it happens, but there are times when I click 'start', but the timer doesn't start, instead I just see this:
![image](https://cloud.githubusercontent.com/assets/7447267/5960439/094602b0-a7de-11e4-9db7-6af7dc7b57f0.png)
After clicking the start button a couple more times, the timer will eventually start.

**Comment by IndrekV** [comment]
Happens when clicking on the left side of the green arrow.
