### ISSUE TITLE
./TogglDesktop: symbol lookup error: /lib64/libxcb-dri3.so.0: undefined symbol: xcb_get_reply_fds

### ISSUE THREAD

**Issue by tanel** [toggl/toggldesktop#1100]
fedora 21

**Comment by artemiy-rodionov** [comment]
the same on ubuntu 14.10

**Comment by francescor** [comment]
Tanel, I had the same problem (fedora 21 64bit), but if you make it from source it works fine.
You just need to execute
  export QMAKE=/usr/bin/qmake-qt5
before any "make"

**Comment by tanel** [comment]
also seeing missing libssl warnings on Fedora

**Comment by tanel** [comment]
Tested on Fedora 21, should work better now.

**Comment by tanel** [comment]
Dear users who experienced this issue - please check the latest stable build if it fixed the issue. It not, please feel free to reopen this issue. Thank you!

**Comment by francescor** [comment]
hi, Tanel
just downloaded toggldesktop_x86_64-7_1_198-2015-02-04-19-24-33.tar.gz

still got 
./TogglDesktop: symbol lookup error: /lib64/libxcb-dri3.so.0: undefined symbol: xcb_get_reply_fds


$ ./TogglDesktop 
QMetaType::registerTypedef: -- Type name 'QVector<' previously registered as typedef of 'QVector<AutocompleteView*>' [1034], now registering as typedef of 'QVector<GenericView*>' [1037].
Log path  "/home/dante/.local/share/TogglDesktop/toggldesktop.log"
DB path  "/home/dante/.local/share/TogglDesktop/toggldesktop.db"
./TogglDesktop: symbol lookup error: /lib64/libxcb-dri3.so.0: undefined symbol: xcb_get_reply_fds

**Comment by tanel** [comment]
Hi! Please check if the new build is any better: https://assets.toggl.com/installers//toggldesktop_x86_64-7_1_199-2015-02-05-04-14-14.tar.gz

Thank you!

**Comment by francescor** [comment]
same same :(
I get the same output.

**Comment by artemiy-rodionov** [comment]
same error

**Comment by Kirhold** [comment]
Hi.
I had the same problem (1 hour ago) on Ubuntu 14.10, but after installing qt4-qmake everythings works great. But app is awful and ugly - i will use web app :D

**Comment by tanel** [comment]
Hehe :) The design will improve.

OK if it started to run with qt4-qmake installed, then I'm missing some libraries when packaging the app.

**Comment by Kirhold** [comment]
I tried compile it from source, and i need that package to solve other problem.
By the way: how it is visible in apt-get when i installed from .deb package? I cant find it.

**Comment by tanel** [comment]
the package name is toggldesktop

**Comment by tanel** [comment]
Since I've been unable to reproduce the issue, I'll close this issue :( :(

It seems that installing from source will fix the issue. 

However I'm working on a deb package, that lists dependencies, instead of packaging them. It should solve this problem. See #1071

**Comment by fagzal** [comment]
It can be fixed by removing libxcb.so.1 from toggledesktop/lib/, and use the lib provided by the system. At least on Fedora 21.

**Comment by mmigdol** [comment]
Thanks, @fagzal.  That solution also worked on Ubuntu 15.
