### ISSUE TITLE
Max post-size for timeline upload

### ISSUE THREAD

**Issue by webervin** [toggl/toggldesktop#1102]
Need to agree maximum upload chunk size (in mb) with backend team. 
 - [ ] pick size MB
 - [ ] split any larger batches
 - [ ] be sure not to upload old timeline (older than 7 days)

**Comment by IndrekV** [comment]
timeline uploads events in patches of 100 this limits the size.

**Comment by webervin** [comment]
one more magic status to take care of:   
 * **413 Request Entity Too Large** - body payload is too big, divide && conquer

**Comment by IndrekV** [comment]
Created separate issue for 413 handling #1106
