### ISSUE TITLE
Duration is cutoff in timer

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1107]
More info in 128956

**Comment by tanel** [comment]
fixed in master

**Comment by sanchitgoyal01** [comment]
Is it still unresolved ?

**Comment by tanel** [comment]
Yes, it looks like the fix I did did not fix every format available in the app.

**Comment by tanel** [comment]
Should be fixed in master; I cannot reproduce the issue on Ubuntu 14. Please try the latest dev build, whoever still has the issue.
