### ISSUE TITLE
Provide options for "Display Density"

### ISSUE THREAD

**Issue by jgindin** [toggl/toggldesktop#1115]
Something like how GMail, Google Groups, etc... have "Display Density: Comfortable, Cozy, Compact".

I find there's far too much whitespace in the current scheme; I only have so much space on my monitors, and while Toggl is _very_ important, I could easily get everything I need out of it from a more compact, dense display.

**Comment by truk** [comment]
+1  The UI could be much more compact which would allow it to stay open on the desktop somewhere
