### ISSUE TITLE
don't remind to track time all the time

### ISSUE THREAD

**Issue by tanel** [toggl/toggldesktop#1120]
“Remind to track time” on desktop app, can it either A) automatically detect when to remind (user normally tracks time every weekday from 7am-4pm) or B) set a schedule of when to notify

**Comment by sanchitgoyal01** [comment]
Could also learn user behaviour intelligently

**Comment by amulware** [comment]
This has since been added, hasn't it?

**Comment by IndrekV** [comment]
This is done with the tracking reminder improvements.
