### ISSUE TITLE
Toggl Desktop invisible when disconnecting external screens

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1128]
Toggl Desktop is visible on an external screen and when disconnecting the screen Toggl Desktop is not able to reposition itself to another screen.

**Comment by Richtor** [comment]
You can work around by right click > Move then use the arrow keys and mouse to move it back onto a visible screen.

**Comment by amulware** [comment]
Assigning to myself so I can see if this still occurs.

**Comment by amulware** [comment]
Cannot reproduce the problem in current build. I suspect that WPF handles this by default, moving the window from one screen to the other, if it becomes invisible.
