### ISSUE TITLE
Changing default workspace from desktop app

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1132]

**Comment by vadimreutskiy** [comment]
And, maybe, ability to select workspace while creating new project in desktop app.

**Comment by msoutopico** [comment]
This feature would be very useful, especially if the Toggl Weekly Report only includes time tracked for one specific workspace. That way I can automatically forward it to my client without them seeing what other projects I work on in other workspaces.

**Comment by IndrekV** [comment]
@vadimreutskiy The workspace selection when adding project is already present. The dropdown is shown only when user has more than one workspace.

**Comment by msoutopico** [comment]
Yes, however the weekly report I get by email includes time tracked for all workspaces.

**Comment by IndrekV** [comment]
@msoutopico You are going off-topic. This issue is about toggl desktop and default workspace. Please write to support if you have questions about reporting there might be a solution available that you are not aware of.

**Comment by msoutopico** [comment]
Thanks. Sorry about that.

**Comment by IndrekV** [comment]
We've decided not to add this feature into desktop app to keep the app light and not have it copy all the features of the web app. Changing default workspace is not a daily task and can be done from web app if needed.

**Comment by vikingcc** [comment]
This feature would still be useful if you are managing a team and want a different default workspace for your desktop app to log personal time.  I am a paying customer and this is very annoying.

**Comment by dmcb** [comment]
It's a daily task for many users. If you do agency work by day, freelancing by night, you are changing workspaces every day.

**Comment by IndrekV** [comment]
@dmcb if you add a project to the entry then the entry will be assigned to the workspace the project belongs to.  Default workspace is used only when timer is started and no project is selected.
