### ISSUE TITLE
Possible issue with New Update Notifications

### ISSUE THREAD

**Issue by chrisatomix** [toggl/toggldesktop#1134]
I'm not 100% sure if this is an issue yet, but since updating to the latest Windows version 7.1.202 I've had 3 popup notifications that my TogglDesktop is "already up to date". It may be checking every hour or so, but I'll need to track it to see if there's a pattern.

Has this code changed? I haven't been manually checking for updates.

**Comment by chrisatomix** [comment]
It just happened again, it does appear to be every hour or so.

![clipboard01](https://cloud.githubusercontent.com/assets/1768449/6181557/bfe16e04-b384-11e4-9c74-870506388148.png)

Probably due to this commit:
https://github.com/toggl/toggldesktop/commit/a672bc68bb4ce8c08ed34f261c785b96b2bc9174

So the code doesn't seem to know the different between manually checking for updates (which should display the popup) and automatically checking (which shouldn't popup unless a new version exists).

**Comment by IndrekV** [comment]
Yes this was changed. Will look into it.
