### ISSUE TITLE
Shortcuts only working when help menu opened

### ISSUE THREAD

**Issue by Domysee** [toggl/toggldesktop#1137]
Shortcuts like Ctrl + N or Ctrl + O to create or continue an entry

**Comment by tanel** [comment]
which OS? :)

**Comment by Domysee** [comment]
Oh, I'm very sorry, tried to add labels but didn't find the option, and then somehow forgot to add the information. 
Windows 8.1 64 bit
TogglDesktop 7.1.203

**Comment by tanel** [comment]
OK, thanks, we'll take a look!

**Comment by IndrekV** [comment]
Fixed with cd2d899c71bed7cc58d607c9e851d58ef4d53a18
