### ISSUE TITLE
Google login not opening browser

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1138]
Clicking on "login with Google account" does nothing. 
Clicking on  "forgotten password" opens up default browser as expected.

Should probably look into bugsnag for hints.

More info 130916

**Comment by darinshepit** [comment]
I'm having the same issue: I can't login via Google either.

I'm getting a similar screen as in Issue #605, though it's saying my email doesn't work because I didn't enter one, I clicked "Login with Google account" instead.

**Comment by tanel** [comment]
works for me
