### ISSUE TITLE
duration is not fully visible in the linux app, Ubuntu 14.04

### ISSUE THREAD

**Issue by tanel** [toggl/toggldesktop#1144]

**Comment by tanel** [comment]
To clarify, it looks like the time only gets cut off when the task name is long.

**Comment by IndrekV** [comment]
Unable to reproduce in master at the moment. If you can produce this issue please write description. If not close the issue.

**Comment by IndrekV** [comment]
Might be connected to Hi DPI #808

**Comment by IndrekV** [comment]
User reports this happening with 120 DPI.
