### ISSUE TITLE
Focus app on global shortcut / Not possible to use UP/DOWN hotkeys

### ISSUE THREAD

**Issue by dandaka** [toggl/toggldesktop#1158]
### I do ###

1. Open application with global shortcut
2. "What are you doing" is getting focus
3. UP/DOWN hotkeys aren't working

### I want to ###

Use these hotkeys anyway.

**Comment by IndrekV** [comment]
If timer description is focused down arrow should open the autocomplete dropdown. To use the UP/DOWN arrows to move in the list you first have to switch focus to the list by pressing SHIFT+DOWN and then you can use UP/DOWN to move in listing.

**Comment by dandaka** [comment]
Works for me, I'm closing this ticket.
