### ISSUE TITLE
broken copy-paste in the 7.1.207 update of windows app?

### ISSUE THREAD

**Issue by tanel** [toggl/toggldesktop#1160]
I installed the most recent update this morning, and now I cannot copy and
paste my projects. I generally get a ticket and then copy and paste the
subject of my ticket into Toggl, but now I cannot paste. Please have this
fixed soon, as it is taking me too long to type everything manually.

**Comment by IndrekV** [comment]
Is this about the multiline paste not working? The multiline issue is fixed.

**Comment by IndrekV** [comment]
case
