### ISSUE TITLE
osx spell check settings default or retained upon update

### ISSUE THREAD

**Issue by cborgia** [toggl/toggldesktop#1169]
every time i update or build (from source) a new toggl app on os x, I have to remember to set "check spelling while typing" (these logs are seen by clients).

Is there not a way for this setting to be retained upon update? or worth considering making the default?

![image](https://cloud.githubusercontent.com/assets/55818/6308073/154f1a96-b90f-11e4-8a2b-767d12be923e.png)

**Comment by tanel** [comment]
We'll try to make it default.

**Comment by IndrekV** [comment]
We've looked into this but haven't found an elegant solution for this issue.
