### ISSUE TITLE
Mac desktop idle time big issue

### ISSUE THREAD

**Issue by ytsvetukhin** [toggl/toggldesktop#1181]
Issue: I constantly have time running for 12+ hours of idle and this idle time recorded on top to my usual activity, which breaks the history and creates big frustration fixing it.
Details: 
1) I run timer of let's say "operations" activity I do some work on the mac for about 2hours
2) I go and talk to people in the room, 
3) Mac sleeps... for 2 hours
4) When I unsleep my mac, but didn't pick any of the 3 idle options, because of another event or other person or sometimes I even don't enter password to unlock my mac.
5) all idle time is applied to my "operations" acitvity and total becomes 4 hours.
6) similar flow happen when stop work, just close my mac, go home and open it only next day and sometimes I see 16hours at some activity.

Expected: As a user I expect this time tracking functionality to work flawlessly and ask me multiple times for my conscious pick and never apply idle time by inactivity, loss of focus, another idle in the row.

**Comment by IndrekV** [comment]
Possible solutions:

- Add additional button to the idle notification with text "continue idle"
- The default behaviour is continue idle. If user doesn't choose anything from the notification it is a fair guess that the user didn't end the idle period in purpose and the idle time continues.

**Comment by ytsvetukhin** [comment]
sorry, bug you are missing main bug here. Idle time is applied to most recent time running w/o user pick that creates big problem of fixing 26hours time entry and trying to remember when it was really stopped and deducting from current time.

**Comment by IndrekV** [comment]
The functionality that timer keeps tracking while idle is something we are not going to change. The timer ticks until user chooses what to do with the time. Either discard the time that has been tracked while being idle or do something else with it.
