### ISSUE TITLE
Idle notification is shown even when there's no running time entry

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1182]
- Track
- Stop tracker
- Leave computer idle
- Come back and Toggl wants to remove idle time even though the tracker was
stopped

 Win 8.1

**Comment by tanel** [comment]
which version number?

**Comment by IndrekV** [comment]
win 7.1.208

**Comment by tanel** [comment]
the app checks now explicitly if the timer is running before notifying. so it should be fixed!
