### ISSUE TITLE
Syncing indicator

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1190]
Currently there is no way to see if application is still syncing or has already synced everything to the web.

 - [x] windows
 - [ ] osx

**Comment by tanel** [comment]
what are the possible sync states?

needs sync / syncing / last sync at xxx?

or just a spinner when the sync is happening?

**Comment by IndrekV** [comment]
Maybe spinner and number of unsynced items. This could be added to the footer

**Comment by IndrekV** [comment]
Number of un-synced items dd27c21169875f19c9af327f9753a36bee2e0887

**Comment by IndrekV** [comment]
Ask designer.

**Comment by IndrekV** [comment]
Bottom bar is bigger in height and is shown only if there is something to show in the bar.
Color #3b3b3b   
opacity 94%

Bottom bar is has 3 different states
- LEFT: Status: offline ( like it is right now )
- LEFT: Un-synced entries (number)    RIGHT: syncing icon that acts as a sync trigger when clicked
- LEFT: Syncing...    RIGHT: syncing icon that acts as a sync trigger when clicked

**Comment by IndrekV** [comment]
osx: unsynced entries count `displayUnsyncedItems` in Appdelegate

**Comment by IndrekV** [comment]
![image](https://cloud.githubusercontent.com/assets/842229/10039472/00fea258-61db-11e5-84d4-9d704b01cd0e.png)

- The bar should move the listing to the top a bit. 
- The color should be similar to the timer background color for consistency.
- Bar should not be transparent.

**Comment by amulware** [comment]
Implemented as such in windows ui. Only waiting for sync-icon now.

**Comment by IndrekV** [comment]
Added two spinner images 14x14 and 28x28

![loader-28x28px](https://cloud.githubusercontent.com/assets/842229/10068762/de908f76-62af-11e5-9ef5-469911387815.GIF)
![loader-14x14px](https://cloud.githubusercontent.com/assets/842229/10068763/de953a76-62af-11e5-867f-a6e8d9c54297.GIF)

**Comment by amulware** [comment]
What will be shown when there are unsynced items, but it is not syncing?

I think it will also be better to do the animation in code, for better transparency. Gifs are... sub-optimal.

**Comment by pe0ny** [comment]
png loaders:

28px
![loader-28px](https://cloud.githubusercontent.com/assets/5064445/10069730/5b305216-62ae-11e5-9670-160e8d958eda.png)

14px
![loader-14px](https://cloud.githubusercontent.com/assets/5064445/10069731/5d51ee38-62ae-11e5-8340-616e31d700f3.png)

**Comment by amulware** [comment]
Thanks @pe0ny!
Only leaving:

> What will be shown when there are unsynced items, but it is not syncing?

(I mean the button that the user can click to start the sync)

**Comment by IndrekV** [comment]
@amulware 
When there are un-synced items and sync is not in progress the icon is shown but not animated. Clicking the icon will start the sync and animate the icon.

**Comment by amulware** [comment]
Fair enough. Let's hope the icon will be clear enough the way it is.

**Comment by IndrekV** [comment]
There should be a hover state, something like a round cornered button that indicated that this is clickable.

**Comment by amulware** [comment]
Everything is implemented on Windows. Still needs testing and potentially polishing.

**Comment by IndrekV** [comment]
Need new design for osx. The flickering bottom toolbar is not the solution. In windows it's a small loader icon in the header. One idea is to show the syncing with animate menubar icon. Like spinning toggl icon. This however poses a question where do we show the number of un-synced items.
