### ISSUE TITLE
Toggl for Desktop not working

### ISSUE THREAD

**Issue by petrhasalik** [toggl/toggldesktop#1199]
It was not syncing first and that is why I have tried to re-login and re-install. 

The app is no longer able to log-in asking me if I am on-line. I have deactivated my firewall, but that did not fixed this issue.

Web version works without any problem. Do you have any difficulties with your serversor is there any maintenance running on your end?

**Comment by tanel** [comment]
Hi, Toggl backend is currently not functioning properly. The issue should resolve ASAP. Please check Toggl Twitter feed for real time updates regarding any Toggl backend issues. 

We're sorry :(
