### ISSUE TITLE
Failed login using Google account

### ISSUE THREAD

**Issue by FredyC** [toggl/toggldesktop#1204]
Windows 7 x64, version 7.1.208

Today the desktop app got somewhat broken, it refused to sync with my account, always showing striked-out icon in the tray. I have decided to clear cache. I had to kill process forcefully because it was just hanging in there without any activity.

Then I started app again and hitting "Login with Google account" opens Google OAuth dialog which I confirm. It then redirects to http://localhost:49250/authorize/?code=4/c5w2q..... and there is message "Received verification code. Closing...". However desktop app itself doesn't login and it shows yellow bar with "Login failed. Are you online?" message.

I tried updating to 7.1.223, but that's even worse as it doesn't open any page in webbrowser, just focus is lost.

**Comment by tanel** [comment]
Hi @FredyC we're having issues with the Desktop app making too many requests. We'll fix this ASAP, so please bear with us.

I'm really sorry about this.

I'm hoping to get the updates out this week.

**Comment by FredyC** [comment]
Ahh, thanks for info @tanel, it's good to hear there is someone fixing the issue. I can manage with web app for a couple days.

**Comment by tanel** [comment]
same as #1223
