### ISSUE TITLE
Constantly failing to login using latest Toggl on Windows 8

### ISSUE THREAD

**Issue by CMCDragonkai** [toggl/toggldesktop#1205]
It just keeps saying that I'm not on online.

This is the version: "toggldesktop-7_1_208-2015-02-20-14-07-36"

Prior to this problem, I logged out and cleared the cache because the desktop toggl no longer synced with my mobile and website.

**Comment by davingreen** [comment]
Having the same issue. Started today it seems

**Comment by NonnEmilia** [comment]
Here the same, on Windows 7.

I've also tried installing from the dev branch unsuccessfully...

**Comment by IndrekV** [comment]
We are having issues with our servers and currently the Desktop applications are blocked from servers. We are working on a fix. Toggl Desktops should be online in 2-3 hours.

**Comment by ohcibi** [comment]
@IndrekV whats the progress on that?

**Comment by IndrekV** [comment]
The server issues should be solved.Currently only latest stable versions of Toggl Desktops are working. 
Windows version 7.1.208
OSX version 7.1.201

If you have installed a dev version that is newer then these versions or have any other version you need to uninstall them and install the latest stable version to continue using Toggl Desktop.

You can get the latest stable versions from this link http://support.toggl.com/toggl-on-my-desktop/

**Comment by ohcibi** [comment]
Ok, the cask version seems not to be up to date.
