### ISSUE TITLE
OSX can't login with "cannot decrypt empty string" error

### ISSUE THREAD

**Issue by dandaka** [toggl/toggldesktop#1206]
Password is correct (tried on website).

Tried with Google — no chance. Saying "Login failed. Are you online?"

OSX Yosemite 10.10.2 (14C109)
Toggl Desktop 7.1.218

**Comment by IndrekV** [comment]
We had server issues and Toggl Desktop server access was blocked until we get these issues solved. Toggl Desktops will start to work normally in the next couple of hours. Until then I suggest you use the web version.

We post updates to the blog and our twitter account
http://blog.toggl.com/2015/03/information-on-current-server-issues/

**Comment by jakehilton** [comment]
I just tried with the OSX client and got the same error.. so I'd suggest this isn't fixed.

**Comment by IndrekV** [comment]
Please use the latest stable version. The version 7.1.218 is a dev version and not currently working. Please uninstall the dev version and install the latest stable which is 7.1.201. Get it from http://support.toggl.com/toggl-on-my-desktop/

**Comment by IndrekV** [comment]
If there are still some errors after install please follow instructions described here: http://support.toggl.com/fixing-toggl-desktop-upgrade-issues/

**Comment by jakehilton** [comment]
I've always been using the 7.1.201 and it hasn't worked for days. I've never installed the dev version. As per that document.. I don't see any errors with "SQL" in them.. so is that still applicable?

**Comment by jakehilton** [comment]
Stil seeing the "cannot decrypy empty string" error when I try to authenticate with it.

**Comment by IndrekV** [comment]
This guide clears all local data. The "cannot decrypt" error is because of offline login error. So yes this should also work for your situation.

**Comment by jakehilton** [comment]
Will that delete any non-synced time entries?

**Comment by IndrekV** [comment]
Sadly yes. Make a copy of the Kopsik directory just in case. Something is missing.

**Comment by jakehilton** [comment]
Now I get another error: "E-mail not found, cannot log in offline." I'm not offline.. so not sure what is up now.

**Comment by IndrekV** [comment]
Please write to support[at]toggl.com so we can look more into since this is another issue.

**Comment by jakehilton** [comment]
Will do. Thanks.
