### ISSUE TITLE
Unable to login after reinstall

### ISSUE THREAD

**Issue by woody-ru** [toggl/toggldesktop#1207]
Have an error while trying to login
SQL Statement invalid: SQL error or missing database: no such column: api_token

**Comment by kesy85** [comment]
+1

**Comment by Michal-Mikolas** [comment]
I have different error when try to login: 
"Cannot decrypy empty string"

**Comment by Michal-Mikolas** [comment]
And if I try "Login with Google account" -> browser open with google permission alert -> I click "Accept" -> page is redirected to "http://localhost:59793/authorize/?code=4/YmAAmRGa8r...EmwGmAI" 

Didn't you (app developer) compile the test environment for production?

**Comment by kesy85** [comment]
I've solved following this http://support.toggl.com/fixing-toggl-desktop-upgrade-issues/
