### ISSUE TITLE
SQL error on startup

### ISSUE THREAD

**Issue by goalgorilla** [toggl/toggldesktop#1216]
![screen shot 2015-03-10 at 15 13 17](https://cloud.githubusercontent.com/assets/557052/6576512/011c0d22-c738-11e4-90e3-2449e8f3f2d9.png)

First I got a message that the App was no longer supported. After closing and restarting the app I was unable to login. Got this error on top: "SQL Statement invalid: SQL error or missing database: no such column: api_token" 

I'm on OS X Yosemite using version 7.1.201

**Comment by tanel** [comment]
Were you using the "dev" channel previously?

Please follow the steps listed here: http://support.toggl.com/fixing-toggl-desktop-upgrade-issues/

Kind regards,
