### ISSUE TITLE
Unable to log in to Mac client

### ISSUE THREAD

**Issue by dougludlow** [toggl/toggldesktop#1217]
When I attempt to log in with my username and password, I'm getting the following error:

```
I/O error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
```
I uninstalled and reinstalled the client via `brew cask`, but get see the same issue. Is there a specific profile file I should try blowing away?

**Comment by ohcibi** [comment]
Currently there are issues with all desktop clients. See #1205

**Comment by IndrekV** [comment]
Please check that you have the latest version. The cask version seems not to be up to date.
You can get the latest stable versions from this link http://support.toggl.com/toggl-on-my-desktop/
