### ISSUE TITLE
Toggl Desktop blocks shutdown

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1220]
Somehow Toggl Desktop freezes and block the shutdown of osx
![image](https://cloud.githubusercontent.com/assets/842229/6615356/cba5dcfc-c8ab-11e4-8e30-fdd5ef9ac864.png)

More info 140554

Might be connected to #1219

**Comment by tanel** [comment]
same as #1219

**Comment by tanel** [comment]
should be better now
