### ISSUE TITLE
"Login with Google" link stopped working when updated to 7.1.224

### ISSUE THREAD

**Issue by effreyh** [toggl/toggldesktop#1223]

**Comment by karavinds** [comment]
I am experiencing the same issue. The application will do nothing when I click on Login with Google account.

**Comment by jimothyr** [comment]
same here... am trying the beta channel for fix

**Comment by IndrekV** [comment]
I've managed to reproduce this issue. Will look more into it.

**Comment by OlivierJaquemet** [comment]
Yup same here :( This is a major regression for a feature on the first window of the app, and unfortunately it completely prevents use of the Desktop app if you use google, in what is supposed to be a stable release :/ After the mail of the big boss yesterday, this is a disappointment, but times must be rough... Good luck with the bug chase.

**Comment by johnpbloch** [comment]
As a workaround, you can reset your password using the google account you want to log in with and then log in normally with email/password. This doesn't disable login-with-google, just adds a password to your account.

Obviously the workaround is less than ideal, but at least I can get back to tracking my time. :) Good luck with the bug.

**Comment by OlivierJaquemet** [comment]
Thank you for your suggestion @johnpbloch. However, as far as I could see in the web UI, changing a toggle account password requires the current password, and of course, having created my account from google I don't have any. 

There is still one obvious workaround : use the website...

**Comment by johnpbloch** [comment]
@OlivierJaquemet Right, I mean't use the "Forgot Password" reset. Imprecise wording on my part. :)

**Comment by OlivierJaquemet** [comment]
Thank you @johnpbloch ! Setting a password through the "forgot password" allows for a working desktop app afterward.

**Comment by tanel** [comment]
The installer was missing dependent assemblies list, in file TogglDesktop.exe.config

**Comment by brendanmatkin** [comment]
I'm having this problem in both the desktop and web version trying to set up a new account ("login with google"). 

I already have an account but I'm trying to make one with a different email.

**Comment by kolnogorov** [comment]
But is still here.
