### ISSUE TITLE
Empty window, cannot open preferences

### ISSUE THREAD

**Issue by mbrodala** [toggl/toggldesktop#1224]
With the latest version 7.1.224 the main window is empty except for a green background on the resize grip:

![toggle-window-empty](https://cloud.githubusercontent.com/assets/5037116/6618456/58167694-c8c3-11e4-875e-6716de7bec8f.png)

Also accessing the preferences does not work.

Is there an option to downgrade?

**Comment by IndrekV** [comment]
Please close all Toggl Desktop instances and remove all files in this directory

C:\Users\[user]\AppData\Local\Toggl\

After that it should work again. We are aware of this issue and are working on a fix.

**Comment by mbrodala** [comment]
No, that doesn't fix the issue. Removing the files only resets the window position to 0,0, the window is still empty and the preferences still inaccessible.

**Comment by IndrekV** [comment]
Are you sure you closed all Toggl Desktop instances. Check Task manager to be sure. If one old instance is running it can block the work of the new version

**Comment by oilvier** [comment]
Same problem here

**Comment by IndrekV** [comment]
Could you specify from which version you upgraded so I can replicate the situation as closely as I can.

**Comment by mbrodala** [comment]
Yes, I have made sure no remaining TogglDesktop instances where running by checking the task manager. Since I have always accepted all automatic updates, you can just start from the previous version. I do not know the exact version number since I've emptied the `AppData/Local/Toggl` folder as you suggested. ;-)

**Comment by oilvier** [comment]
Well, same here again.

**Comment by Rugsie** [comment]
Same issue here version 7.1.224 - just updated

**Comment by bfcerny** [comment]
Same here-

**Comment by kdelacroix** [comment]
Same issue here.  I've also tried ending all TogglDesktop processes in Task Manager, uninstalling TogglDesktop, removing C:\Users[user]\AppData\Local\Toggl  (C:\Users[user]\AppData\Local\TogglDesktop was removed during the uninstall), and re-installing.  No change in behavior.  Is there any way I can get to the previous version?

**Comment by SchoschiMan** [comment]
Same issue here after installing the update today.
Then I uninstalled the application, deleted all related directories and did a reboot of the computer. After this I downloaded the newest version and installed it. But again i get an empty window like shown at the beginning of this thread.
I use windows 8.1.

**Comment by 1971Vette** [comment]
Same issues here.
Updated from 7.1.208 to 7.1.224
Running Windows 8.1

**Comment by doodelidoo** [comment]
I have the same problem with an update done today. Could you provide us with an older version that is working. I have accidentally deleted the .msi file.

**Comment by tanel** [comment]
I can reproduce the issue on a clean Windows 7 machine.

**Comment by tanel** [comment]
The previous stable app is downloadable here: https://assets.toggl.com/installers//toggldesktop-7_1_208-2015-02-20-14-07-36.msi

**Comment by tanel** [comment]
Looks like a missing component; the app runs if the machine has Visual Studio etc tools installed.

**Comment by jcppkkk** [comment]
Got it.

You need to install [```Visual C++ Redistributable Packages for Visual Studio 2013 ```](http://www.microsoft.com/en-us/download/details.aspx?id=40784) **X86** version.
Yes, install **X86** version even if you are using x64 system.

here is my installed list.
![image](https://cloud.githubusercontent.com/assets/84070/6633126/6a0193dc-c97e-11e4-97df-ccfa0d118bfb.png)

However the ```login with google account``` still does not work, and i am waiting the password reset mail for about 1 hour now.

**Comment by mbrodala** [comment]
@tanel Thanks a lot, that works for now. :-)

**Comment by Malanius** [comment]
@jcppkkk Great. Many thanks - that solved it for me :+1:

**Comment by mbrodala** [comment]
@IndrekV Is there a better solution aside from what @jcppkkk suggests?

**Comment by IndrekV** [comment]
I think the best solution currently is to revert back to the previous version until we fix this.

As @tanel suggested the previous stable app is downloadable here: https://assets.toggl.com/installers//toggldesktop-7_1_208-2015-02-20-14-07-36.msi

**Comment by mbrodala** [comment]
Thanks for the feedback.
