### ISSUE TITLE
Got an error today...

### ISSUE THREAD

**Issue by th3m4ri0** [toggl/toggldesktop#1225]
So I tried to create a new entry in the Mac OS client, and the app would not stop bugging me with a 503 status.
Then I thought "Hey, I haven't got any client update for a long time !" so I head to the site, download the installer, overwrite the app...  
Wow ! I missed a lot of updates I think. You guys have redone the UI completely ! Some UX bugs I noticed long ago are now gone !
Good job.

**Comment by tanel** [comment]
Thanks for the feedback!
