### ISSUE TITLE
Opening the window on idle time popup button click

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1230]
-  keep the time   ( no need to bring up the window)
-  discard (no need to bring up the window)
-  Add idle time as a new entry ( Bring up the window to add details.)

**Comment by IndrekV** [comment]
Edit popup opening when selecting "Add idle time as a new entry" seems to be implemented, but not working properly. Needs to be double checked.

**Comment by tanel** [comment]
keep time opens on windows, should not

**Comment by tanel** [comment]
osx works
