### ISSUE TITLE
Option to pause/resume timer when computer is locked/unlocked

### ISSUE THREAD

**Issue by irhs** [toggl/toggldesktop#1240]
Having the option to pause the timer when the display turns off or when the computer is locked, and then resume the timer when the computer is unlocked might make it bit easier for people to accurately log their tasks when they take frequent breaks in between.

The timer gets resumed only if it was paused when the computer was locked.

**Comment by IndrekV** [comment]
We have idle detection for the same purpose. Idle is detected when computer is locked. When resuming to the computer the user is presented with options.

- Keep the time (Make it so as if I never was away and the timer just tracked)
- Discard (just stop the entry from the moment idle was detected)
- Add idle time as a new entry ( create a new time entry from the time detected as idle time)

For your scenario you should select "Discard" as this stops the timer at the moment idle was detected. After that you can start a new entry.

**Comment by irhs** [comment]
Thanks! The adjust the idle time in settings.

I was thinking of also automatically resuming the timer but I think it makes more sense to have the user start a new timer.
