### ISSUE TITLE
Desktop app prevents Mac from going to "sleep" and drains the battery

### ISSUE THREAD

**Issue by kyllikekimmel** [toggl/toggldesktop#1244]
I have been having an issue with my MacBook Pro not being able to go into
"sleep" mode. This causes a battery drain whenever I am transporting my
laptop. Sometimes in the morning, the laptop will be completely dead.

I have narrowed the issue down - whenever Toggl is running (Desktop App),
the laptop will not allow sleep mode - from both shutting the lid as well
as the sleep menu.

Desk #140965

**Comment by IndrekV** [comment]
Have not seen any other reports about this issue, will close.
