### ISSUE TITLE
Idle period never reports an idle time of more than 9min

### ISSUE THREAD

**Issue by triinjassov** [toggl/toggldesktop#1250]
I’ve been using toggl for a couple of months and works great mostly. However, I noticed recently that whenever I return to my computer after an idle period it never reports an idle time of more than 9min. This is annoying as it used to be very handy to just create a new task with the idle time and be correct. Whereas now I have to create a new task and then edit it with the approximate start time.

This is with desktop version 7.1.224 on OS X Yosemite 10.10.2"

User sent message to my personal e.mail. If you need his details, ask me.

**Comment by tanel** [comment]
works in master
