### ISSUE TITLE
Pressing "Click here to download update!" in non deb linux app downloads the latest deb

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1253]
Should download the latest tar.gz file

**Comment by tanel** [comment]
it will download deb if you have /opt/toggldesktop/platform set to deb.

the app itself does not know that it's deb or no deb.

uninstalling the deb should fix the issue.

maybe we should set the "deb" flag when building the app, to avoid confusion?

**Comment by IndrekV** [comment]
Yes flag would work. I think that it shouldn't download deb if I'm not downloading from inside the deb version.
