### ISSUE TITLE
Menubar icon menu commands (new,continue,stop) should not open the main window

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1257]

**Comment by tanel** [comment]
why?

**Comment by IndrekV** [comment]
Users use the menubar icon menu when the app is no visible. If app is visible it's more easy to use the start/stop, continue buttons inside the app. Currently user can't simply stop or start the timer from the icon menu without the toggl poping up.

**Comment by IndrekV** [comment]
wontfix
