### ISSUE TITLE
Add Color selection to project creation

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1274]

**Comment by amulware** [comment]
This needs library support if I am not mistaken.

**Comment by tanel** [comment]
Yes and we need to ask backend first as well.

**Comment by IndrekV** [comment]
Color should be sent in int format. Int refers to a certain color code
Example in.
https://github.com/toggl/toggl_api_docs/blob/master/chapters/projects.md#create-project

        "0":  "#4dc3ff",
        "1":  "#bc85e6",
        "2":  "#df7baa",
        "3":  "#f68d38",
        "4":  "#b27636",
        "5":  "#8ab734",
        "6":  "#14a88e",
        "7":  "#268bb5",
        "8":  "#6668b4",
        "9":  "#a4506c",
        "10": "#67412c",
        "11": "#3c6526",
        "12": "#094558",
        "13": "#bc2d07",
        "14": "#999999"

**Comment by tanel** [comment]
added to library

**Comment by amulware** [comment]
UI part is done and seems to mostly work. It does seem however that the library does not like the colour the UI tells it and changes it back to some other colour a few seconds later (maybe it receives a colour from the backend?)

@tanel: could you look into this?

**Comment by tanel** [comment]
ok will take a look asap!
