### ISSUE TITLE
Project field is not usable in the edit window (osx 7.1.224)

### ISSUE THREAD

**Issue by kyllikekimmel** [toggl/toggldesktop#1276]
User reports that they can't enter anything in the project window. 

![image](https://cloud.githubusercontent.com/assets/8287467/7004567/04dc0fb8-dc76-11e4-8072-823861f5cc48.png)

Desk #147470

**Comment by Dextro** [comment]
I can confirm this. Mac OS X version 10.10.3.

When you click on the 'Add new project' link, then everything rescales back to normal.

**Comment by IndrekV** [comment]
Unable to reproduce. This issue has not been reported on newer versions of MacOs.
