### ISSUE TITLE
Multi-line description field for time entries

### ISSUE THREAD

**Issue by mike-kelly** [toggl/toggldesktop#1277]
Enhancement request - I'm using Toggl to monitor personal learning and it would be very useful if the description field for time entries was multi-line, preferably with a gripper to expand the typing space. As well as creating the initial description for the entry I would like to be able to add a conclusion or summary at the end of the time period.
A multi-line entry field would make it possible to use the existing description field for this.

**Comment by IndrekV** [comment]
There is no multiline description in any of the Toggl applications. Adding this would mean that entries created with toggl desktop would seem strange in other applications. This will not be currently added. Thank you for your input.
