### ISSUE TITLE
create a release rollback script

### ISSUE THREAD

**Issue by tanel** [toggl/toggldesktop#1279]

**Comment by tanel** [comment]
take current, previous info from installer server, then tell the installer server that current = previous

**Comment by tanel** [comment]
needs backend support first. Perhaps implement it along with the new update server

**Comment by IndrekV** [comment]
Connected to #1524

**Comment by tanel** [comment]
we have a script to manually register whatever installer file as needed. seems to cover the rollback functionality; without any changes to Toggl backend (would like to avoid that).
