### ISSUE TITLE
Windows app crashing after upgrade

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1286]
System.ComponentModel.Win32Exception was unhandled
Message: An unhandled exception of type
'System.ComponentModel.Win32Exception' occurred in System.Windows.Forms.dll
Additional information: Error creating window handle.
More: 148393

**Comment by tanel** [comment]
most probably a) the app leaks window handles - check what new UI components have been added *or* b) user has simply too many time entries to render.

**Comment by tanel** [comment]
duplicate of #1139
