### ISSUE TITLE
Cannot select project with task (win7 toggl desktop)

### ISSUE THREAD

**Issue by Catmacey** [toggl/toggldesktop#1287]
In the time tracker panel I can only select projects that do not represent tasks such as;
ProjectX. ClientA
ProjectY. ClientB

I cannot select any projects that represent tasks within a project such as;
Task1. ProjectZ. ClientA

**Comment by IndrekV** [comment]
Please check that you have the latest version. This issue was fixed with version 7.2.36

**Comment by Catmacey** [comment]
Thank you. That worked. I was on version 7.2.35
Toggl updated already this morning so I assumed that it was at the latest version.
