### ISSUE TITLE
Window position and window size is lost after every update

### ISSUE THREAD

**Issue by tssajo** [toggl/toggldesktop#1291]
Platform: Windows 7

Maybe it is nitpicking, but every time I install a new version of TogglDesktop the previously used window position and window size is lost. This is quiet annoying since a new version of TogglDesktop seems to get released almost hourly, see https://github.com/toggl/toggldesktop/releases
Because of this (and the new bugs introduced in every new release), I am always hesitant to perform an update of TogglDesktop. But the program is bugging me with popups even when I click the Skip this update button... When I can no longer stand the constant naggings I give up and let the program update itself. But then I have to re-set the window position and window size again. Which the program then remebers until the next update which will almost certainly be released a few days later. Then the whole cycle starts over again... This is pretty annoying stuff.

Questions:

1. Can you make the update process of TogglDesktop on Windows not to lose the window position and size? It would be great!

2. Can you please make the Skip this update button actually work? It would be great too!

Thanks!

**Comment by IndrekV** [comment]
The releases shown in the https://github.com/toggl/toggldesktop/releases are development channel releases and should not bother users. We advise users not to have the `dev` channel selected in the about  view as we do create a lot of development releases that can be unstable at times. We create stable releases about once or twice a month. 

As for the `lost window position and size at update` issue, we will look into it.

**Comment by tanel** [comment]
we're keeping the window size and location in the local database now, and it will survive updates

**Comment by tssajo** [comment]
Thanks!
