### ISSUE TITLE
Look into the possibility of using tray icon in Xembed supported linux distros.

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1303]
Tray icon isn't supported only in Gnome 3 and Unity because they don't support Xembed. All other window managers and KDE support Xembed. 

Connected to #1272

**Comment by tanel** [comment]
fixed in 30d9688319bc1373568f49b853bd824d16f070c2

**Comment by buma** [comment]
Great that tray icon for Linux was added. My PR #1272 also added different icon based on tracking. If no tracking - grey icon otherwise red icon. I think this was also in previous versions and you can quickly see if tracking is in progress.

**Comment by tanel** [comment]
yeah there was an older commit with similar functionality, but with more menu items.

it lacks an inactive icon, yet.

**Comment by buma** [comment]
If I do a PR based on commited tray icon which changes icon based on tracking will it get merged?

**Comment by tanel** [comment]
yeah sure the issue with unity should be resolved now (checking for it).

and many thanks for help! :)

**Comment by buma** [comment]
Great. Then I'll do PR tomorrow. No problem.
