### ISSUE TITLE
Google login doesn't close the browser tab

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1304]
App logs in just fine, but the browser window stays open.

**Comment by tanel** [comment]
works fine with windows 7. reopen if you have more info on how to reproduce this issue

**Comment by IndrekV** [comment]
Reproducable in windows 8.1

**Comment by tanel** [comment]
whats the text in the browser tab that is kept open? some kind of error message?

**Comment by IndrekV** [comment]
Message in browser: `Received verification code: Closing ...`

Happens in latest Chrome 42.0.2311.90 m
In console it show warning `Scripts may close only the windows that were opened by it.` Might be something new that was implemented with a chrome update.

**Comment by tanel** [comment]
updated the packages; it could fix the issue
