### ISSUE TITLE
Windows application prevents windows shut down

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1311]
It seems that something is running in a background thread.

This could help:
http://stackoverflow.com/questions/2498432/c-sharp-windows-application-prevents-windows-from-shutting-down-logging-off

**Comment by tanel** [comment]
restart works on windows 7, without timeline

**Comment by tanel** [comment]
shutdown works on windows 7, without timeline

**Comment by tanel** [comment]
refuses to quit when at least one sub window has been opened (about, preferences etc).

**Comment by hairydogltd** [comment]
This problem is still causing me grief, to the extent that I'm considering abandoning Toggl.

**Comment by IndrekV** [comment]
@hairydogltd 
We have had reports that the updater has not worked properly for some users. This means that users have not gotten all the updates and fixes. To be sure you have all the updates please do the following:

- uninstall the application
- delete all the files from C:\Users\<username>\AppData\Local\TogglDesktop
- install the latest stable version

You can get the latest stable version from: http://support.toggl.com/toggl-on-my-desktop
