### ISSUE TITLE
Keyboard shortcuts for windows

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1314]
The idea is that user should be able to do everything with only keyboard

Similar to osx shortcuts:

`These are inside the cog menu and should already work`
**Ctrl instead of Cmd**

Cmd-N creates a new time entry and displays Toggl Desktop window
Cmd-D changes between timer and manual mode
Cmd-S stops a running time entry
Cmd-O continues a previous time entry
Cmd-T displays Toggl Desktop window
Cmd-E open running entry in edit popup

`Also there are context specific shortcuts to make moving around inside the app more easy:`

Switching between timer and Time entry listing
- [x] SHIFT+DOWN – Focuses the Time entry listing
- [x] ESC –
If the edit popup is opened it always closes the popup (event if listing is focused).
If edit popup is not opened and entries list is focused it will switch the focus to Timer.

Moving inside Time entries listing
- [x] UP/DOWN – switch between selected time entry
- [x] ENTER – open the edit view of selected time entry
- [x] SPACE –  continue the selected time entry
- [x] BACKSPACE – delete the selected time entry

**Comment by amulware** [comment]
Work started on `win-keyboard-list-navigation`. Mostly works right now, but the list navigation is a bit finicky, and the code for it rather ugly (especially the interaction between mouse and keyboard highlight). Will go over that again and see what can be done.
