### ISSUE TITLE
Start/stop hooks?

### ISSUE THREAD

**Issue by ezuk** [toggl/toggldesktop#1320]
It would be great if Toggl had an option for executing an arbitrary command (always the same command) when clicking Start, and another arbitrary command when clicking Stop.

I would use it to integrate with a local tool that records screenshots.

**Comment by tanel** [comment]
on what os would you use it?

**Comment by ezuk** [comment]
Windows.

**Comment by IndrekV** [comment]
We have decided not to implement this feature into Toggl Desktop. Thank you for your feedback.
