### ISSUE TITLE
when autocompleting task name, often project name is appended to task name rather than inserted into project field

### ISSUE THREAD

**Issue by triinjassov** [toggl/toggldesktop#1322]
linux_native_app/7.1.198
Version: 7.1.198

Content:
when autocompleting task name, often project name is appended to task name rather than inserted into project field

**Comment by dolugen** [comment]
Version: 7.4.7

This is a minor annoyance for me when using the app on Linux.

You end up manually removing the appended project name, and setting the project again.

**Comment by IndrekV** [comment]
Will be fixed with #2480
