### ISSUE TITLE
Unable to stop the timer => crash

### ISSUE THREAD

**Issue by petrhasalik** [toggl/toggldesktop#1323]
This is starting to make me crazy during the last few days. 

I am runing a timer and I decide to stop it, but the app wont let me and it does not respond. After a few seconds the app crashes. In some cases it does not even crash and I have to stop the timer manually in the web app and then I can watch how the desktop app crash. 

I have sent feedback directly from the app. I am not sure if you get logs this way.

It crashes few times per hour depending on how fast I switch between existing records, because I always continue with the existing timer.

Version 7.2.36 (stable)

**Comment by tanel** [comment]
which OS?

**Comment by petrhasalik** [comment]
Ah, sorry. I use Windows 8.1.

**Comment by petrhasalik** [comment]
This is starting to be really frustrating. It crashes multiple times per an hour. I am here in case that you will need some help.

**Comment by tanel** [comment]
looks like it's a known issue at the moment. the windows cannot render more than a couple hundred of time entries, before running out of window handles. we're working nonstop on replacing the windows app UI tech with WPF what will allow for more UI controls.

please use the web app until its fixed. we're super sorry.

**Comment by petrhasalik** [comment]
Thanks, but where I can track this when this is closed?

**Comment by tanel** [comment]
please keep an eye on #1139
