### ISSUE TITLE
Ugly UI and error

### ISSUE THREAD

**Issue by vistar** [toggl/toggldesktop#1330]
I bulid (make deps; make; make run;) application ArchLinux x86 and found it in path: /src/ui/linux/TogglDesktop/build/release/TogglDesktop

Run it, and seee ugly UI: http://i.imgur.com/qLDH4pOl.png and have this error on open UI.

What did I do wrong?

**Comment by tanel** [comment]
did you log into the app?

I fixed a similar issue a while ago.

**Comment by vistar** [comment]
Yes, sync is ok. Version 7.0.0 stable.

Now I rebuild, and not have error, but UI is ugly.

**Comment by tanel** [comment]
ok, the design will probably improve. if you have more specific feedback, we'd be thankful.
