### ISSUE TITLE
Controls are unrendered when un-minimising app

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1334]
When Toggl gets un-minimised while the timer is running, the window appears with most of the UI unrendered, and I end up having to click and drag around on the window to force it to refresh, which is a total attention-killer. The app used to not do this, until a recent update. Definitely detracts from the light-weighted-ness behind the product's philosophy

Windows 7 enterprise and Toggl desktop version 7.2.36

**Comment by IndrekV** [comment]
Also the new login design acts strangely. The controls seem to be on the left at first and then moved to the center.

**Comment by IndrekV** [comment]
@amulware Please try to replicate the situation described in the description. If you can't replicate then close the issue.

**Comment by amulware** [comment]
Cannot replicate either behaviour at the moment.
