### ISSUE TITLE
Linux install and integration

### ISSUE THREAD

**Issue by sasha-** [toggl/toggldesktop#1340]
I tried a few 7.2.x releases on KDE and I found these issues:
- Clicking close button brings up "are you sure.." dialogue. App closes regardless of the option selected at that point.
- 7.2 releases have system tray icon support but application cannot be closed to tray. It would be good if tray icon could be preference option until "close to tray" works so I can continue using ksystraycmd to "fake" that feature.
- Application is distributing its own QT libraries so it ignores system display settings for QT apps. I see that on ubuntu the only libraries needed should be  libbugsnag-qt   libPoco* (maybe?) and  libTogglDesktopLibrary. 
- TD has hardcoded colours and fonts, so, when running using native QT libraries,  it does not look good with  dark QT themes. It looks only good with default Fusion theme.

**Comment by s0undt3ch** [comment]
+1 for close to tray ...

**Comment by IndrekV** [comment]
I've created separate issues so we can look into this case by case.
