### ISSUE TITLE
App should try to use the system Qt libraries

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1343]
Application is distributing its own QT libraries so it ignores system display settings for QT apps. I see that on ubuntu the only libraries needed should be libbugsnag-qt libPoco* (maybe?) and libTogglDesktopLibrary.

Ref: #1340

**Comment by s0undt3ch** [comment]
Done?

**Comment by tanel** [comment]
yeah but not released. waiting for buildbot

**Comment by s0undt3ch** [comment]
Awesome! Thanks!
