### ISSUE TITLE
Set deadline for version 7.1.x deprecation.

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1345]
Two step deprecation:
* Gather information about how many users are using the 7.1.x version.
* Shows notice to users about upcoming deprecation.
* Notice that the version is deprecated and user should update

**Comment by tanel** [comment]
so, what will the actual deprecation deadline be?

the latest builds block user for inputting further data, upon receiving 418, so the upgrades should go faster / smoother this time.

but yes we should get some stats first.

**Comment by IndrekV** [comment]
#1318 should be done before this ticket.

**Comment by IndrekV** [comment]
Deprecation will occur when version 7.3 is in stable. Version 7.3 allows smooth update and should not pose any issues for users.

**Comment by IndrekV** [comment]
The date is 11th of November.
