### ISSUE TITLE
upload new builds to github releases in addition to Toggl download server

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1346]
Description how to create releases automatically
https://developer.github.com/v3/repos/releases/#create-a-release

Linking to releases
https://help.github.com/articles/linking-to-releases/

Use tags to separate different platforms.

**Comment by tanel** [comment]
where will we keep the buildbot builds? or will we not keep those any more at all? or just keep like 1 buildbot build around only?!?

**Comment by IndrekV** [comment]
I'm not sure if it's possible to use multiple channels in github releases.

We can do it so that we leave dev builds as they are and move stable and beta builds, that are important to our users, to github.

Important is that for our users downloading toggl desktop is not connected to toggl services being up or down.

**Comment by tanel** [comment]
i start by implementing parallel upload/release to github when doing releases from buildbots. if they seem to work, we'll register the Github download links instead of Toggl download links. i'll create a separate issue for this.

**Comment by tanel** [comment]
needed for #1503
