### ISSUE TITLE
window titles not visible in linux app under Qubes OS

### ISSUE THREAD

**Issue by tanel** [toggl/toggldesktop#1357]
more info in support case 160098

**Comment by v6ak** [comment]
What's the resolution (fixed/wontfix/…)?

**Comment by IndrekV** [comment]
As the user base for Qubes OS is really low among our users the answer is `wontfix`.

**Comment by v6ak** [comment]
When I was reporting this issue, I though this was a generic issue/feature. After realizing that this is somehow Qubes-specific, I tried to find the source of the issue. The `xprop` tool has found that many apps usually use both `WM_NAME` and `_NET_WM_NAME` for the title, while Toggl uses the latter only. Qubes seems to read only the `WM_NAME` property, not the `_NET_WM_NAME` one.

I'll report this to Qubes team.
