### ISSUE TITLE
Increase the numbers of beta users

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1358]
- [x] Invite beta testers in the 3 month plans blog post
- [ ]  Ask randomly users if they want to join beta action. Offer swag for active users.

**Comment by IndrekV** [comment]
Let's keep a flag that shows if the user has seen the suggestion. The aim is to actually in different times show every user at least once the opportunity to switch to the Beta channel.

**Comment by tanel** [comment]
we could add a flag to user record in desktop app local database?

**Comment by tanel** [comment]
need a mockup of the window that asks user if they want to join beta

**Comment by tanel** [comment]
wheres the mockup?

**Comment by IndrekV** [comment]
Let's keep it simple. No fancy hovering things, just a simple alert showing some text.
![screen shot 2015-06-15 at 10 49 17](https://cloud.githubusercontent.com/assets/842229/8155365/3c7be094-134c-11e5-8ad7-0e46d461a0d6.png)

**Comment by tanel** [comment]
me gusta
