### ISSUE TITLE
Create analytic functionality

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1359]
Measure:

- What preferences are ticked (users use)
- How many users use manual mode and how much
- How many users on each platform

Steps:
- Create backend
- Gather and Send data to backend

**Comment by tanel** [comment]
- preferences are only kept on local database, so we'd need to upload this somehow somewhere
- manual mode is also a local setting on the Desktop app
- how many users on each platform should already be available by doing a database query on server

**Comment by tanel** [comment]
we could post a snapshot of settings to backend each time user modifies those. they won't be sent to server, if user does not modify them at all, though.
