### ISSUE TITLE
Issues with Logging in with Google after "Clear cache"

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1361]
Windows version 7.2.36 and 7.2.70

User cleared cache and after that the Google Login gets 502 error.

There was some speculation about google services being down but the number of users with the same problem has increased so this might not be the case. 

Example case: 161663

**Comment by tanel** [comment]
can you reproduce the issue? i cannot with the windows app, master.

**Comment by amulware** [comment]
We have not been able to reproduce this so far. But we got what looks like the same thing from multiple people just within the last few days.

**Comment by IndrekV** [comment]
Let's open create a new issue when this comes up again. Closing for now.
