### ISSUE TITLE
Error: Insertion failed because database is full

### ISSUE THREAD

**Issue by vistar** [toggl/toggldesktop#1362]
On Stop.
And Stop not working - timer not stopped.

**Comment by tanel** [comment]
what app version are you using? the latest app versions should vacuum the database, so it should not be an issue.

it could be that the local database is just corrupt. please see this link http://support.toggl.com/fixing-toggl-desktop-upgrade-issues/ on how to remove the local database in this case.

**Comment by vistar** [comment]
Version is 7.0.0.

**Comment by tanel** [comment]
did you build the app yourself? we have not released such version ourselves.

did you try to remove the possibly corrupt data?

**Comment by vistar** [comment]
I build 2 weeks later.

I remove directory, but error is present.

**Comment by tanel** [comment]
hi, please try to update your sources and rebuild, including the dependencies (make deps).

has the app ever worked on your computer? 

before deleting the folder "/home/<your user name>/.local/share/Toggl Desktop", you need to quit the Toggl Desktop app, should it be running.

**Comment by vistar** [comment]
I rebuild tomorrow.

Yes, worked.

Yes - quit, delete directory, open toggl.

**Comment by vistar** [comment]
Partition do not have free space (many in reserved blocks). I reduce reserved blocks and all working, thanks!
