### ISSUE TITLE
Add tray icon to Ubuntu

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1363]
Qt 5.4 and higher should fix system tray icons (appindicators in Ubuntu Unity), for example in HipChat&#39;s Linux client

**Comment by sagikazarmark** [comment]
:+1:

**Comment by orschiro** [comment]
A tray icon would indeed be great. Then the main window doesn't have to stay in the way any longer. 

Thanks for working on this!

Robert
