### ISSUE TITLE
Click to go to URL

### ISSUE THREAD

**Issue by macdonaldster** [toggl/toggldesktop#1365]
I use the Chrome integration to being time tracking all the time (from Unfuddle tickets). 

I think a good feature for the desktop client would be the ability to click to visit the URL that spawned the time tracking, if present. 

I apologize if this is not the correct forum for this or if there is a way to do this that I have missed.

Thanks,

Scott 

PS> Awesome product, love it.

**Comment by IndrekV** [comment]
Currently we do not save this kind of information. This would be something that would make sense inside Toggl Button. So you could see what was the location you started the timer with Toggl Button. I'll create an issue for this to Toggl Button and we'll see if this is something that could be added.

This will probably not be added to other applications of Toggl.

Thank you for your feedback and thoughts.

**Comment by macdonaldster** [comment]
Thank you for your consideration.
