### ISSUE TITLE
Autocomplete:  the tags from the previous time entry are not added.

### ISSUE THREAD

**Issue by triinjassov** [toggl/toggldesktop#1367]
The desktop client has an autocomplete feature so you can easily &#34;continue&#34; a time entry by just entering the description and selecting it in the dropdown.

However, in doing so, the tags from the previous time entry are not added. You need to manually enter tags for the new time entry. This is different behavior from when you click on the &#34;play&#34; icon to continue a previous entry. In that case, the tags are added properly to the new entry.

I&#39;d consider this a bug, question is if you do or if it&#39;s by design for some non-obvious reason :)

**Comment by tanel** [comment]
implemented in tanel-1367
