### ISSUE TITLE
UI tests fail in windows buildbot

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1369]
Currently the app seems to not close after tests. Might be that it fails or freezes somewhere.

**Comment by tanel** [comment]
works for me: windows 7 virtual machine, master branch (916ebde25344bf54c633c3ab1ed5b0b404597a51), running "make uitest" from cygwin after rebuilding the whole solution.

note that uitests print out what they're doing at the moment; if a uitest gets stuck the last printout on the screen is a big hint

**Comment by IndrekV** [comment]
In buildbot:

![screen shot 2015-06-22 at 16 18 09](https://cloud.githubusercontent.com/assets/842229/8282602/8794bf52-18fa-11e5-8448-d7dddfe802fc.png)

**Comment by tanel** [comment]
ok looks like test session data is not cleared or similar. should also check that the environment is set to test. the issue is not connected to WPF.
