### ISSUE TITLE
Difficulties to stop timer and app crashing a lot

### ISSUE THREAD

**Issue by oilvier** [toggl/toggldesktop#1370]
Since a couple of days, I have difficulties to stop the timer, which results in the app crashing.

**Comment by amulware** [comment]
Hey oilvier,

Are you by any chance using the app on Windows?
If so, this is a known issue, that we are currently working on.

The current beta version already has a temporary fix (you can change in the about window of the program, then wait for a few minutes for it to download beta in the background, then restart the program), and we are busy working on a more permanent fix that will soon make it into the beta, and hopefully the stable build as well.

If you are not using Windows, can you give us more details?

**Comment by oilvier** [comment]
Yes, I'm on Windows 7 !
I'll try the beta then
