### ISSUE TITLE
[Windows] feature-wish: use command line options

### ISSUE THREAD

**Issue by steppenhahn** [toggl/toggldesktop#1373]
hi!
i use toggl on a regular basis and was wondering if it is possible to include the following feature in the windows desktop version:
- start tracking a certain project from command line.

example:
`TogglDesktop.exe -project "Projectname"`

which starts toggl and immediatley tracks a new entry for the project "Projectname".

This would be very useful to make it possible to start tracking a user session as soon as windows is started up - or to make desktop-shortcuts to start tracking certain projects.

**Comment by IndrekV** [comment]
We have decided not to implement this feature into Toggl Desktop. Thank you for your feedback.

**Comment by MarSoft** [comment]
Is there any kind of API for the running Toggl Desktop app?
Consider this situation: I am away from the internet, and I want to start tracking new task for some project. I can do that with Desktop app. But I would like to do that from command line (because command line is my main workspace).
I saw `toggl-cli` project but it didn't work on my machine. And I would like Toggl Desktop to cache my data.

**Comment by IndrekV** [comment]
@MarSoft There is no command line api for Toggl Desktop app. We do not have plans to add this functionality. There are some community created CLI-s in the [toggl api docs](https://github.com/toggl/toggl_api_docs)  repo, but I don't think that they support offline mode.

**Comment by MarSoft** [comment]
Maybe some other API, like DBus or whatever? I see it should be possible to programmatically stop tracking current task by sending `Ctrl+S` to the running TogglDesktop's window, and it should be possible to restart (continue) last task by sending `Ctrl+O`. But no way to start new task with certain task name, project and other attributes, right?..
My usecase is that I am using tiling WM, and use dmenu to start new task. For it to work properly I need first to obtain list of "suggestions" (i.e. latest used task names with their projects), and then to programmatically start new task with given name&project.
