### ISSUE TITLE
Clearing Cache freezes the app

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1376]

**Comment by tanel** [comment]
what version?

**Comment by amulware** [comment]
I was able to reproduce (though only in about one out of three cases) and track down the problem to [`WindowChangeRecorder::Shutdown()`](https://github.com/toggl/toggldesktop/blob/master/src/window_change_recorder.cc#L114).

Specifically, the method calls `Poco::Activity<toggl::WindowChangeRecorder>::wait()`, which never returns.

I propose using the second overload of `wait()` instead, which accepts a number of milliseconds after which it will throw an exception if it has not returned yet.

I do not know what interval length is appropriate though.

**Comment by amulware** [comment]
It seems that if `wait()` terminates, it usually does so in less than a millisecond, so I gave it a 5ms timeout.
