### ISSUE TITLE
Use staging api for development builds.

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1378]
When we run in development machine connect to staging api. Buildbot built versions always connect to production api.

**Comment by tanel** [comment]
we have these endpoints mentioned in const.h:

#define kAPIURL "https://www.toggl.com"
#define kTimelineUploadURL "https://timeline.toggl.com"
#define kWebSocketURL "https://stream.toggl.com"

do you want those to be something else when environment == "development"?

**Comment by tanel** [comment]
"https://www.toggl.com"

**Comment by IndrekV** [comment]
If app version is 7.0.0 (as it is when running app in development) we use staging urls.

Staging urls:
#define kAPIURL "https://next.toggl.com”
#define kTimelineUploadURL "https://next.toggl.com”
#define kWebSocketURL “https://fubar-ws.toggl.com”

**Comment by IndrekV** [comment]
If possible let's use wss protocol for websocket. Should be supported by backend already.
` wss://stream.toggl.com` etc

**Comment by tanel** [comment]
wss does not play (with the poco library), at least fro now

**Comment by tanel** [comment]
nevermind the wss comment; websocket in Toggl seems to be broken at the moment, does not work in Toggl web etc either
