### ISSUE TITLE
Full text search

### ISSUE THREAD

**Issue by dandaka** [toggl/toggldesktop#1383]
**Right now**

1. I have 10 clients (say "Client A", ...)
2. 10 similar projects (say "Website", "iOS app", ...)
3. Many similar tasks (say "Planning", "Organization", ...)

To find existing task I need to type something like

"Planning - Website. Client A" (with proper punctuation, which is nightmare)

So autosuggestion clearly is not working in case, where I don't have unique text IDs.

http://take.ms/bYjHG

**Should be**

Take Google as reference. When you type "Planning Client A" — it gives you all results with this keywords. And after that all other results (with smaller than 100% of match).

**Comment by amulware** [comment]
I can see where you are coming from. We had a quick chat about it in the team and will look into this when we find the time.

Since we are currently re-doing major parts of the windows UI, the changes are most likely going to happen there first, but hopefully we can bring them to the other platforms soon after.

**Comment by amulware** [comment]
There is a label for autocomplete. Huh. Also: Putting this on Windows todo for now. When it works there, we can discuss how to add the functionality to other platforms.

**Comment by amulware** [comment]
78c8454388940237f1c20d509523c5b378ff75c3 includes much better matching on Windows. It now splits the search string into individual words, and shows all options that include all those words in some form.

A possible next step could be to show options that contain only some of the words as well, or to allow for fuzzy matching. These are somewhat more complicated, and we will test how this new way is received first.

I'm closing this for now. Once we get more feedback on the current implementation we may want to implement it for OSX and Linux as well.
