### ISSUE TITLE
Updater not working

### ISSUE THREAD

**Issue by scrobbleme** [toggl/toggldesktop#1388]
Hi,

the updater isn't working anymore (I think). For me it doesn't work since the major update which brought retina support. Before this there where a lot of updates.

**Comment by IndrekV** [comment]
We currently have silent updater in place on windows. This means that updates are downloaded in the background with out bothering the user.

**Comment by scrobbleme** [comment]
Okay thanks. Beside this it would be nice to get a short information, that Toggle was updated. 
I still think it didn't worked as (I think) I had a quite old version installed, but will watch this ;)

**Comment by IndrekV** [comment]
I will create an issue for adding the update notification.

**Comment by IndrekV** [comment]
Silent update was added in version 7.1.224.
