### ISSUE TITLE
Convert Timer to WPF

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1392]
The design should remain the same. If no project is added the description text is vertically centered.
- [x] Description autocomplete
- [x] project-client label
- [x] tag and billable label
- [x] duration label
- [x] Start button
- [x] If project is added and entry not started there is an `x` that when clicked clears the selected project

**Comment by amulware** [comment]
All features are implemented. Testing and possible polish is still needed. Code currently on `win-wpf-timer`.

**Comment by IndrekV** [comment]
- [ ] Description placeholder not hidden when just hitting start
- [ ] Replace tag and billable icons with higher resolution icons
https://github.com/toggl/toggldesktop/blob/master/src/ui/osx/TogglDesktop/icon-billable%402x.png
https://github.com/toggl/toggldesktop/blob/master/src/ui/osx/TogglDesktop/icon-tags%402x.png
- [ ] Make keyboard shortcuts work ( shown in cog menu )

**Comment by amulware** [comment]
Shortcuts work for me. Will investigate this more as part of #1314.

Closing as wpf timer was merged into master.
