### ISSUE TITLE
Add timeline events display to osx

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1393]
First implementation should be a simple list showing the events. Also it should be possible to select event to create a time entry based on the timeframe.

**Comment by tanel** [comment]
perhaps we should somehow visually indicate which timeline events are already covered by time entries and which are not. just a thought

**Comment by IndrekV** [comment]
I agree. Something similar to the web app timeline that shows blue lines of time entries.

**Comment by tanel** [comment]
implemented in tanel-timeline branch
