### ISSUE TITLE
windows: "Start-end time :" label is too long on higher DPI

### ISSUE THREAD

**Issue by slav** [toggl/toggldesktop#1398]
Screenshot with the problem: ![togglhighdpi](https://cloud.githubusercontent.com/assets/350987/8396630/74c56c2e-1d7c-11e5-9827-8ae8963eb744.png)

On Windows 8.1. Turning on "Disable display scaling on high DPI settings" (as suggested in another ticket) has no effect.

That's the only label with the issue.

**Comment by amulware** [comment]
Thanks for reporting the problem!

We are currently doing a redesign of the edit window, which should make issues like this a thing of the past.

Closing this as it will be solved with the new design (see #1042).
