### ISSUE TITLE
"ManicTime" kill-feature

### ISSUE THREAD

**Issue by toby3d** [toggl/toggldesktop#1406]
It would be great to implement monitoring of open applications with the rendering of their activity on the timeline like [ManicTime](http://www.youtube.com/watch?v=OlfknjggACQ).

**Comment by tanel** [comment]
Hi, we already monitor open application when you enable Timeline Recording (then the data is shared with Toggl web too) or Autotracker (data is kept only on local computer) in the Toggl Desktop app Preferences.
