### ISSUE TITLE
When trying to log off/shut down, the desktop app indicates it's busy and has to be shut down manually (or forced). 

### ISSUE THREAD

**Issue by tiinakaarik** [toggl/toggldesktop#1409]
User agent: windows_native_app/7.2.172
See Desk #171137

**Comment by amulware** [comment]
fc3f45fa63282fabd2cb16ba300151015707bd84 fixed something that may have resulted in this behaviour.
Further testing is needed to see if there are other causes.

**Comment by tanel** [comment]
should work better now
