### ISSUE TITLE
"The workspace is suspended" error message with 2 active workspaces and 1 suspended one

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#1414]
osx_native_app/7.2.150
User reports seeing following message: “The workspace is suspended, please check your payments”. She has 3 workspaces: 2 of them active (986701, 964956), 1 indeed suspended (512340).  The message is displayed also after logging out/in. In h4xx the data seems to be syncing...
Asked the user to check what she sees in web, she replied: The problem only occurs when using the Desktop app. This does not occur when I use the browser version.
Desk case: #169371
![suspended-msg](https://cloud.githubusercontent.com/assets/12407134/8673861/bd804a9c-2a42-11e5-9374-020950881606.png)

**Comment by tanel** [comment]
The user tracked time to a suspended workspace. With each login/sync, the time entry was still being pushed to the server (which results in error, since workspace is suspended). Clearing cache will get rid of the issue, as it will delete the unsynced time entries.
