### ISSUE TITLE
Abort due to constraint violation

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1415]
![image](https://cloud.githubusercontent.com/assets/842229/8743013/cd20055e-2c73-11e5-9fcf-610d548d7759.png)

Seems to be happening in context.cc function  `StartTimelineEvent` Around Line 3380

**Comment by amulware** [comment]
This still seems to be happening, at least in the current windows beta (7.2.204). See #1375 and #1418.
