### ISSUE TITLE
Repaint issue

### ISSUE THREAD

**Issue by adrianhalid** [toggl/toggldesktop#1418]
Since upgrading about a month ago I am having repaint issues with the UI.

I have to move or resize the toggle window to get the fields to repaint. This has never been an issue previously.

Using Windows 8.1 64 bit.
TogglDesktop 7.2.182 - Release Channel "Stable".

Usually occurs when switching between fullscreen RDP and then back to my local desktop.

![capture](https://cloud.githubusercontent.com/assets/12272329/8790771/1e9f3494-2f95-11e5-804c-f327daa3f36a.PNG)

**Comment by amulware** [comment]
Hey, thanks for reporting this.

Could you try and switch to the current beta and see the problem still occurs?
The beta includes a fix that should prevent this issue.

You can switch by selecting the beta in the about window, waiting a few minutes for it to download in the background and then restarting the application.

Let us know if that helps!

**Comment by adrianhalid** [comment]
Still have the issue. Plus now I am also getting a Abort due to constraint violation.

![capture2](https://cloud.githubusercontent.com/assets/12272329/8794854/b2a437a4-2fca-11e5-88b7-dacd5486b8e6.PNG)

**Comment by amulware** [comment]
I think we found the problem with the redrawing. We will release a new beta build as soon as possible (probably in an hour or two) that should fix this for good.

We will also look into the constraint violation as well.

**Comment by adrianhalid** [comment]
Ok.. I will try it out tomorrow.

**Comment by adrianhalid** [comment]
BTW. How do you know that the Beta version has updated. Is there any indicator to let you know when to restart the application. Spotify does it nicely by a blue bar across the application with a "Restart" link to restart the application.

**Comment by amulware** [comment]
Unfortunately there is no way to see that right now.

It's definitely on the list for the near future though: #1391

**Comment by IndrekV** [comment]
Updates are quite small so usually a few minutes are enough to download them. We already have an issue for adding an `App update ready` notification.

**Comment by amulware** [comment]
@adrianhalid We just pushed that new beta build that should fix the redrawing problem. Closing this issue, but let us know how it goes!

**Comment by adrianhalid** [comment]
I am now using 7.2.205 beta but cant test the repaint issue as I can't use the app.

I am getting a Abort due to constraint violation message when I try to start a task.

![image](https://cloud.githubusercontent.com/assets/12272329/8814861/164afb00-3055-11e5-83a6-41a66e142e99.png)

**Comment by IndrekV** [comment]
@adrianhalid Just released a new Beta with `Abort due..` fix. Please clear cache from the cog wheel and update the app.

**Comment by adrianhalid** [comment]
Thanks. Just updated. So far looks good. I will test again tomorrow.
I must say you guys do an excellent job with turn around times. Well done!!

**Comment by adrianhalid** [comment]
Looks all good.
