### ISSUE TITLE
Convert preferences view to WPF

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1419]
Also tabs should be used in preferences view see issue #1374 

Add advanced `Reminder` preferences similar to osx
<img width="406" alt="screen shot 2015-07-22 at 10 04 57" src="https://cloud.githubusercontent.com/assets/842229/8819899/26ff5744-3059-11e5-98c9-f0fe385b3bf7.png">

**Comment by amulware** [comment]
Now merged into master.
