### ISSUE TITLE
Add UI to timeline listing

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1425]
Details will follow...

**Comment by tanel** [comment]
![timeline_mock_360](https://cloud.githubusercontent.com/assets/8346/8875289/6453829e-3218-11e5-8644-7cc93ed3cb15.png)
![timeline_mock_2_360](https://cloud.githubusercontent.com/assets/8346/8875290/645c424e-3218-11e5-8dd1-8ea9cd399f15.png)

**Comment by IndrekV** [comment]
### Opening and closing

* In the first implementation let's add an item to menubar icon menu with text `Show timeline data/Hide timeline data`. Also keyboard shortcut should be added to the menu item
* In future implementation some better way will be added ( handle to the bottom of the entries list to open and `x` somewhere to close it.

### Timeline View

#### Header

* Left/Right arrow changes the day.
* If the date is today, right arrow is not visible.

#### Content

* The circles next to time collapse the data for this time period.
* Blue vertical line shows tracked time entry ( When hovering should show time entry data: description and project)
* In the image Red circle shows selected time period start and Green shows selected time period end
This design will be changed to more subtle one. Two arrows and the space between selected arrows is darkened or marked some other way.

#### Footer

* Shows selected time period (From: start - stop)
* Description field - User can manually add description. Maybe it also makes sense to have autocomplete here
* Create button - Pressing create will create entry with inserted data ( start/stop time and description) and it will open the edit view with the entry for further changes.

#### Various

Also `collapse all/uncollapse all` button should be added to move around the timeline faster.
