### ISSUE TITLE
Reminder of running task

### ISSUE THREAD

**Issue by odinuv** [toggl/toggldesktop#1427]
Enhancement suggestion:
Similar to idle reminder it would be nice to have a reminder of running task, like:
"You are working on Foo for 20 minutes"
which would pop-up from (configurable) time to time. 
The use case is that people tend to forget things in the same way the forget to track tasks at all. They may forget changing the task they're working on. So when working on A, user actually does A and then B and C and only then realizes that he was tracking A.

**Comment by tanel** [comment]
In the OSX app, you can have the app to show you the project name in the status bar. Also the app icon shows the tracking status. 

I think we'd like to keep the popups to a minimum.
