### ISSUE TITLE
Add Autotracker UI to windows

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1428]
This is already added to osx and all backend lib functionality is present.
Adds new preferences tab called `Autotracker`

Autotracker's idea is that if user has entered terms, like in this case `Slack` the app reminds user to track. In this example case if user has no tracking time entry and focuses Slack then Toggl Desktop asks if the user wants to start tracking time for project `First project`.

**In AutoComplete preferences view user can:**
- [x] - enable/disable autotracker
- [x] - Add autotracker Term's.
* By typing in keyword or selecting keyword from recent timeline events
* Selecting project and pressing add
- [x] - Remove autotracker Term.
* Right click and select `delete` or with `x` icon like in edit view field clearing.
![screen shot 2015-07-24 at 12 27 15](https://cloud.githubusercontent.com/assets/842229/8871603/5876f032-31ff-11e5-8a9d-71d6b9e308d4.png)

**User notification:**
- [x] - User is shown notification if any term matches their focused window title
![screen shot 2015-07-24 at 12 43 18](https://cloud.githubusercontent.com/assets/842229/8871921/9a37332c-3201-11e5-82de-3588eccf177d.png)

For further details ask @tanel

**Comment by amulware** [comment]
This is mostly implemented on `win-autotracker-ui`.

Now only needs some testing, and probably polishing.
