### ISSUE TITLE
Assigning a project to a task erases its description

### ISSUE THREAD

**Issue by codeman38** [toggl/toggldesktop#1431]
In the latest beta version (7.2.214) of the Windows desktop client, changing the project for a task causes the task's description to be completely erased. This is definitely a regression compared to the older version-- it causes data to be lost when adding information to the task.

Steps to reproduce:
1. Open a previously created task for editing.
2. In the project dropdown, select "No project" to remove the project.
3. Observe that the description is still there.
4. In the project dropdown, select a project name.
5. Observe that the description is now completely empty.

**Comment by amulware** [comment]
I do not think that this should be happening. We'll make sure to investigate this soon.

Thanks for reporting the problem!

**Comment by amulware** [comment]
Fixed in 8b6f09e5b790fadec868d1dc93a0c194463001dd

This should make it into both the beta and probably stable build this week.
