### ISSUE TITLE
Dock icon is always red (running), even when timer is stopped

### ISSUE THREAD

**Issue by dandaka** [toggl/toggldesktop#1432]
Now

Dock icon is always red (OSX Mavericks)

Should be

Timer is running — dock icon is red
Timer is not running — dock icon is grey

**Comment by emersonf** [comment]
I'm seeing this today in a fresh install of TogglDesktop 7.3.319 on El Capitan from the App Store. Can someone look into it please?

**Comment by IndrekV** [comment]
This seems to be happening only with the AppStore version. I will investigate this.

**Comment by dandaka** [comment]
I'm using 7.3.325. Can't reproduce this bug right now. Maybe because I've switched from App Store version to a standalone.

**Comment by emersonf** [comment]
Just an update that as of 7.3.347 in the App Store version on El Capitan, the icon now shows red/grey correctly. It may also have been working earlier, but I'm sure it wasn't fixed more than a month or so ago.

**Comment by IndrekV** [comment]
Yes this was fixed in the latest AppStore version.
