### ISSUE TITLE
Window Desktop Can't Login With Google Account

### ISSUE THREAD

**Issue by sitawit** [toggl/toggldesktop#1433]
Version : TogglDesktopInstaller-7_2_172-2015-06-11-16-22-57

I can't login with Google Account and it doesn't show any error or message. When I pressed login with Google, nothing happened.

Can someone guide me how? I am able to use Google Account on web app perfectly. Thanks.

**Comment by tanel** [comment]
What Windows version are you using? Are you able to log into the Desktop app using regular Toggl username and password?

**Comment by sitawit** [comment]
Window 7 Enterprise. 

However, I don't know how to enable regular account because I'm always login using Google Account.

**Comment by amulware** [comment]
You can create a password for your google account email by using the password reset form: https://www.toggl.com/forgot-password  
(Don't worry, you can afterwards still login with Google.)

Could you try and see if the login works that way?

Oh, also: Did Google login work for you before with the Desktop App, or has it never worked there?

---

Either way, it would be great if you could also send us the programs logfile to support@toggl.com  
The log file can be found here:  
C:\Users\<your user name>\AppData\Local\TogglDesktop\toggldesktop.log

Please mention that the log file is for *Paul* :)

**Comment by sitawit** [comment]
@amulware Thanks. 

- Resetting password works very well. So right now I have toggl account which mean **I can use toggl desktop now**.
- Google login never once work in my PC. When I press the button (login with Google Account) nothing happens.
- Log is sent.

**Comment by amulware** [comment]
Good to hear that it works for now, and thanks for sending the file! We'll take a look at the log and see if we can figure out what the problem is/was.

**Comment by amulware** [comment]
Closing this for now, since we are continually unable to reproduce it.
The problem seems to crop of for only a few people, only sometimes, and seemingly at random.
