### ISSUE TITLE
OSX desktop app's TE details window is cut off

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#1434]
osx_native_app/7.2.150
I try to update the project and client fields, but now the desktop client looks like the attached screenshot OS X Yosemite. The Project field is cut off.
![screen shot 2015-07-28 at 18 24 46](https://cloud.githubusercontent.com/assets/12407134/8951864/3255d42a-35da-11e5-87c7-4baccbacc2ac.png)

Desk case #176583

**Comment by tanel** [comment]
cannot reproduce on OS X Yosemite (10.10.5)
