### ISSUE TITLE
Tags are reappearing after removal

### ISSUE THREAD

**Issue by gabrielpeter** [toggl/toggldesktop#1436]
Version: 7.2.219

Tags are sometimes reappearing after clicking the 'x' for removal, I haven't found the pattern yet.

Sidenote: New tags dropdown is less intuitive (before there was a checkboxlist and I just had to click, now I have to type)

**Comment by amulware** [comment]
I can see where you are coming from.
We'll see if we can add full mouse control back to the tag selection.

And of course we'll investigate the former issue.

Thanks for reporting!

**Comment by waterfowladdict** [comment]
I agree with gabrelpeter that the new tags dropdown is less intuitive. I did find a slight workaround for the time being:
1. Select inside the tag area. 2. Enter a space character. 3. Delete the space character. 4. Scroll to the desired tag.
It works but is not intuitive or user-friendly.
Thanks for looking into these issues.

**Comment by amulware** [comment]
When you have the tag area selected, you can also press the down key to open the popup menu. It will then show all tags.

I took a quick look, and from what I can tell it should help a lot if we add a down-arrow button to the box that lists the tags that opens the list of previous tags (just like the project selection thing). I'll also look into making the list stay open, in case one would one to select multiple tags with the mouse.

Do you think that would work for you?

**Comment by waterfowladdict** [comment]
If you were able to make the list stay open after selecting a down-arrow button that would work perfect for me. That's essentially how it was in the previous release I was running with the only difference being that in the previous release the tags list was always open/visible.

Thanks for the quick response!

**Comment by velis74** [comment]
Thanks @waterfowladdict and @amulware, I was just about to report that the new version doesn't even allow adding tags :)

**Comment by amulware** [comment]
Update: The behaviour as described above was implemented here: 9a92ad16a4aab89fedb45a6a5890eea6b35d9712

We are currently still fighting some stability issues, but once we have those sorted out this change should make it into both the beta and stable relatively quickly.

Thanks for your patience!
