### ISSUE TITLE
Clicking on the tray icon does not restore main app window (linux)

### ISSUE THREAD

**Issue by sasha-** [toggl/toggldesktop#1437]
Thank you for implementing "close to tray" option in 7.2.221. It works for closing the app to the tray and the icon changes based on a current activity as it should. 

Once app is closed to the tray it should be restored when clicking on the tray icon. This does not happen. 

"New" and "Continue" options do function and restore the main window when app is minimized to tray.

Selecting "About" or "Preferences", while app is closed to the tray, do bring up appropriate dialogues (but no main window). When closing these dialogues app exists completely. Opening and closing these dialogues while main window is shown does not exit the app. Even clicking "OK" on "Don't forget to track the time" dialogues while app is closed to the tray exits it completely. 

Is there some switch with which TogglDesktop can be invoked that would force main app window to be restored? This would make it easy to create a global shortcut for it. 

I just tried 7.2.223 and all of the above behaviours are unchanged.

**Comment by IndrekV** [comment]
We've added "show" item to the tray icon menu to bring the app to the from once it'd hidden

**Comment by sasha-** [comment]
Hello, Thanks for adding "show" option.

I do not think this issue should be closed just yet. Closing any of the dialogues from the app still exits it completely if the main window is not opened. That is not big deal with "preferences" and "about" dialogues, but it becomes major issue with time tracking reminders or update notifications. Once notification is closed  app will exit if the main window is not shown at a time.

**Comment by IndrekV** [comment]
Thank you for the details, we will investigate.
