### ISSUE TITLE
Cannot Uninstall Toggl Reminder

### ISSUE THREAD

**Issue by sententia** [toggl/toggldesktop#1438]
Hi,

I have uninstalled the togglDesktop app and empty the trashed. I've also gone into Application Support and removed files, however I'm still getting the reminder pop up!!

I've tried to install it again, then unchecked the reminder box. I've unticked all the boxes and still nothing. how do I turn off this notification?

It is the mac flavour

**Comment by tanel** [comment]
You have most probably the toggl chrome extension installed, thats giving you notifications - its not the Desktop app. If you still think it is please grab a screenshot.

**Comment by sententia** [comment]
I just face palmed myself!
