### ISSUE TITLE
Radiogroup instead of checkboxes in Proxy settings view

### ISSUE THREAD

**Issue by alari76** [toggl/toggldesktop#1439]
Shouldn't there be a radiogroup instead of checkboxes? (See attached image)
<img width="277" alt="screen shot 2015-08-03 at 10 31 23" src="https://cloud.githubusercontent.com/assets/5136955/9032804/18193d1e-39cb-11e5-96ed-c7ee27164fe8.png">

**Comment by amulware** [comment]
Adding windows label since it uses the same preferences layout.

**Comment by amulware** [comment]
Added in e76dd0668bd3848e5762d8e30d8b96f6e8a46060.
