### ISSUE TITLE
Better grouping of settings checkboxes

### ISSUE THREAD

**Issue by alari76** [toggl/toggldesktop#1440]
I'd propose to add separators to make the list a bit more readable. There are also a few changes to texts:

* Idle detection
* Record timeline

-- Separator --

* Show timer ON menu bar
* Show project ON menu bar
* SHOW dock icon
* On top of other windows

-- Separator --

* Focus app on global shortcut
* Open edit view when starting entry with shortcut

This is based on OSX version, should do something similar for Win version.

<img width="413" alt="screen shot 2015-08-03 at 10 43 00" src="https://cloud.githubusercontent.com/assets/5136955/9033093/0e1a51c0-39cd-11e5-9eab-dddf344c5cd2.png">

**Comment by amulware** [comment]
Windows has much fewer settings and does not need this right now.
