### ISSUE TITLE
Crash: terminating with uncaught exception of type Poco::NullPointerException: Null pointer

### ISSUE THREAD

**Issue by sinfante** [toggl/toggldesktop#1442]
Hi! I haven't been able to open Toggl since yesterday, and I have no idea what is the problem. The crash report doesn't say much besides:

Application Specific Information:
abort() called
terminating with uncaught exception of type Poco::NullPointerException: Null pointer

Tried reinstalling the app with no success. Couldn't replicate it on my other Mac.

The computer is a Mac Book Pro (latest version) with Mac OS X 10.10.4. The full crash report is here:

https://gist.github.com/sinfante/b6fedc67aa5008e0b3c2

**Comment by tanel** [comment]
cannot reproduce atm
