### ISSUE TITLE
Tag filtering is case sensitive

### ISSUE THREAD

**Issue by Iapmes** [toggl/toggldesktop#1452]
Destop for Windows, 7.2.219
Windows 8.1, Regional settings: Norwegian Bokmål

Filtering in the tags-picker is case-sensitive. (Should be case-insensitive.)

Kind regards
André

**Comment by Iapmes** [comment]
And I would suggest that using backspace (keyboard) to delete tags should be possible. Presently you would have to use the mouse to remove tags that makes fast editing of tags harder.

**Comment by Iapmes** [comment]
Actually a lot of issues related to editing tags (that should easily be discovered during testing). Like tags beeing deleted reappears:
Add tags "A", "B", "C". Then delete "C" then "B": "A" dissapears, then reappears, "B" is not deleted. Similar behavior if order of deletion is changed.

**Comment by amulware** [comment]
I think this should fix all the problems you mention (case sensitivity was addressed in a recent refactor as well).

Thanks for bringing this to our attention, and my apologies for the inconvenience.
