### ISSUE TITLE
Toggl Desktop Win 7.2.251 : Opens to an empty window, crashes as soon as you attempt to interact with it

### ISSUE THREAD

**Issue by killermouse0** [toggl/toggldesktop#1453]
There is no log in the file at the current time (last logs were 2+ hours ago)
Tried to clear cache => crashed
Uninstalled entirely + deleted any leftover files + Reinstalled
Still crashes

**Comment by killermouse0** [comment]
OK I think I figured it out. There was a time entry that was (for an unknown reason !) spanning from yesterday 9:17 am to today 9:20am, making the total of the hours clocked in the app around 35 or something. Corrected this in the website, restarted the app, and it seems fine now.

**Comment by killermouse0** [comment]
Oops, I see that when I reinstalled, I'm back to 7.2.219, so I'm not sure what factor caused or resolved the original issue.
Not quite sure if worth investigating.

**Comment by amulware** [comment]
As you noticed, the current dev build has some problems. We will make sure these are ironed out before releasing a new build to beta/stable.

I'm closing this for now.
