### ISSUE TITLE
Freezes

### ISSUE THREAD

**Issue by bluekheng** [toggl/toggldesktop#1457]
TogglDesktop 7.2.219 always freezes when attempting to stop timer or delete existing time entries.

**Comment by amulware** [comment]
Thanks for reporting the problem!

This is a known problem, and we have been working on sorting this out the last few days.

We have a new build you can try available here:
https://assets.toggl.com/installers//TogglDesktopInstaller-7_2_261-2015-08-11-23-59-06.exe

It would be great if you could let us know if this one works better.

(closing this as duplicate of #1444)
