### ISSUE TITLE
Windows 7 Unresponsive Desktop Icon

### ISSUE THREAD

**Issue by roessleinj** [toggl/toggldesktop#1460]
First off, LOVE the product, ridiculously helpful!  

I have been having issues with the Toggle desktop application on Windows 7, it would work fine for a few instances (open/change project close/etc.), but then would freeze up (and be stuck as the most forefront program, not close, etc.) until I went into the Windows Task Manager Processes menu to hard shut down.  Lately, when it opens, clicking on the desktop icon doesn't even open the dialog box..

Tried redownloading/installing, restarting my box, etc. to no avail, any tips you have would be greatly appreciated, will start using the web app, as I can't go another day without Toggl :)

![image](https://cloud.githubusercontent.com/assets/13771934/9236572/8b6130a2-40fa-11e5-9079-62a4c0b7d8a5.png)
^ button that pops up in toolbar after starting Toggl - that doesn't do anything anymore :( 

Cheers guys,
Jason

**Comment by amulware** [comment]
Thanks for reporting the problem!

These freezes are a known issue that we were only just able to fix. You can update to the new version right now by using the installer here: https://assets.toggl.com/installers//TogglDesktopInstaller-7_2_266-2015-08-12-15-54-12.exe

Sorry for the inconvenience, but great to hear you like Toggl (Desktop)! :)

**Comment by roessleinj** [comment]
Hmm, this seems to have solved the "icon doesn't do anything at all"
problem sometimes? But it still freezes up.  Let me know if there's any
other information I can provide to help isolate the problem. Webapp is
nice, feel free to shoot me an email if there is a new version released
that might improve things :)

Have a great weekend,
Jason
