### ISSUE TITLE
allow partial certificate chain for *.toggl.com

### ISSUE THREAD

**Issue by webervin** [toggl/toggldesktop#1463]
currently desktop uses http://curl.haxx.se/ca/cacert.pem but it would be better if you switch to http://curl.haxx.se/docs/mk-ca-bundle.html and extract all certificates.

Or alternatively - vendor full chain for toggl inside client, so it would not need  to be retransfered for every new connection again. 

main goal is to reduce traffic needed for handshake making connections faster

**Comment by tanel** [comment]
we could concat the whole chain as needed. where is it?

**Comment by webervin** [comment]
openssl s_client -showcerts -connect toggl.com:443 </dev/null

..but not throw away current root's - so that if we -republish cert with full, but different chain it will not break, it's good be able switch stuff without rollout of clients.
