### ISSUE TITLE
Cannot start app after upgrade to Windows 10

### ISSUE THREAD

**Issue by koubic8** [toggl/toggldesktop#1467]
I had Toggl desktop add in Windows 8 working pretty ok. Then I upgraded to Windows 10 and I cannot run the app. I run it, then Toggl icon appears in the right part of taskbar (next to the volume, wifi etc.). If I hover over the icon, then title "Toggl desktop" appears - seems working in the background. When I click it, nothing happens. Double click - nothing. After this, not even the title appears anymore when I hover over the icon.

I reinstalled Toggl desktop app and updated Adobe Air to the newest version with no improvement.

**Comment by amulware** [comment]
Hey!

Can you confirm if you are running the latest build? The easiest way would be to download and install the latest installer (released just today):
https://www.toggl.com/api/v8/installer?app=td&platform=windows&channel=stable

**Comment by koubic8** [comment]
Horray, it works, thanks! It took like 10 seconds for the window to appear but it's there and working so far.

**Comment by amulware** [comment]
Great to hear and thanks for letting us know!
