### ISSUE TITLE
List is hard to read in low contrast environments

### ISSUE THREAD

**Issue by Iapmes** [toggl/toggldesktop#1473]
Destop for Windows, 7.2.219
Windows 8.1, Regional settings: Norwegian Bokmål

The choise of font and background coloring makes the list really hard to read in low contrast environments. E.g. sunny environments, bad/low contrast monitors. Looks kinda cool but really impractical - and probably a nightmare for people with vision impairments.

Kind regards
André

**Comment by amulware** [comment]
Can you specify which part exactly is a problem for you? Maybe with a screenshot?

**Comment by Iapmes** [comment]
![image](https://cloud.githubusercontent.com/assets/8895860/9281140/5ba1e7e2-42c3-11e5-8fd0-ed9ca1b7e817.png)

Attached a screenshot of the desktop applications main window. Except from the selected entry, the rest of the list is hardly readable.

**Comment by amulware** [comment]
Ah, I understand. Thanks for the clarification!

This was indeed a bug in the last build. The highlight is only supposed to gray out the other entries when the edit window is open.

We released a new version just a few hours ago that fixes this.
If it does not update automatically for you (it should, maybe try restarting the application after waiting for a few minutes for the update to download), feel free to grab the latest build from the Toggl website.

Sorry about the inconvenience!
