### ISSUE TITLE
Cannot save reminder preferences

### ISSUE THREAD

**Issue by pitrsk** [toggl/toggldesktop#1479]
I can't save my preferences of reminder – especially start time, end time and days. Checkbox for activating reminder and time input works.

**Everything else is reset when the dialog is saved.**

- Windows 10.0.10240 PRO, 64-bit
- Toggl Desktop version is 7.2.281

**Comment by amulware** [comment]
Thanks for reporting the problem!
---
It looks like Toggl.SetSettings() has not been updated for the additional settings. A clear oversight on our part.

**Comment by pitrsk** [comment]
​​you're welcome. :)

**Comment by amulware** [comment]
Fixed with 2007c9997af315c8009b6c2001d3cfd80e176fa2.
