### ISSUE TITLE
Changing start time of running entry is not working.

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1480]
If you change the time and press `TAB` the duration in the timer is changed, but the one in the edit view is not. If you now close the edit view the old duration is saved and the change you applied is lost.

Everything works ok if you press `ENTER` after changing the start time.

**Comment by SteelsenS** [comment]
Similar behavior but when I press "enter" the modified time is not saved, it always reverts to the originally running entry.

To reproduce:
- Start running a time entry
- Click on top bar to open "edit"
- Change start time (e.g., I forgot to start the timer)
- At this point:
- Typing enter (no effect)
- Typing tab
 - Elapsed time changes in main window
 - Elapsed time does not change in edit window
 - Changed time main window remains correct as long as cursor is in elapsed time in edit window
 - Changing to next field causes main window to also revert to original time despite new start time remaining in edit window
 - Remaining in elapsed time in edit window and pressing either "back" or "exit" causes changed time to be lost. Reopening edit window shows original start time.

Version 7.2.266 (stable channel)
Windows 8.1 Enterprise x64

**Comment by IndrekV** [comment]
The Enter saving functionality was added in release version 7.2.281.

**Comment by SteelsenS** [comment]
My client updated some time overnight. I can confirm the enter saving functionality works as described.

**Comment by kadrihvl** [comment]
A user with windows_native_app/7.2.281 has reported (Desk case #185165):
I'm unable to update the start time on a running time entry. In the attached video, I'm attempting to change the start time from 12:57p to 11:30a. However, when I tab to the next fields, the time entry goes back to 12:57p.
