### ISSUE TITLE
toggl timer on desktop (app) not populating

### ISSUE THREAD

**Issue by mitchcan** [toggl/toggldesktop#1482]
A week ago my desktop app icon timer stopped populating. I've tried uninstalling and reinstalling the Windows Toggl software and this did not help.  I have been using the timer on the website account but this is very inconvenient.  Any help or assistance would be appreciated as I use this every day for work and have also recommended to many clients who are currently taking one of our courses.
I am running Windows 7 and the Toggl icon shows in my menu and in my programs and also on the lower right in the status bar but clicking it to launch it from any of these areas doesn't make the timer app appear.
Thanks, Michele

**Comment by amulware** [comment]
Hey Michele,

Thank you for reporting the problem! We indeed had some issues with Toggl Desktop on Windows the last few weeks.

Could you make sure that you have the newest version? You can download the installer here:
https://www.toggl.com/api/v8/installer?app=td&platform=windows&channel=stable

Let us know if this helps!

**Comment by mitchcan** [comment]
Hi Paul,

 

Thanks for your reply. Glad to know it wasn’t just me.

 

When I download the installer and then run it I get a number of error messages like these.  These are the same ones I got when I tried to install the app from the link on your website.

 

I’ll wait to hear back about next steps.

 

Thanks, Michele

**Comment by amulware** [comment]
Hey Michele

If I understand correctly, you tried to share an image? It does not seem to work when answering directly per mail. Can you make sure to get back to us on GitHub so we can take a look?

**Comment by mitchcan** [comment]
Will do.

 

M

**Comment by mitchcan** [comment]
Hi Paul,

Thanks for your reply. Glad to know it wasn’t just me.

When I download the installer and then run it I get a number of error messages like these.  These are the same ones I got when I tried to install the app from the link on your website.

I’ll wait to hear back about next steps.

Thanks, Michele

![toggl image](https://cloud.githubusercontent.com/assets/13835081/9356193/08e5250e-464d-11e5-896b-df8e89c7585b.png)

**Comment by amulware** [comment]
This may be caused by the application still running in the background.

Could you check if Toggl might still be running in the background with the task manager, and if so, killing any TogglDesktop processes there?

If that does not help, you could try deleting all files in C:\Users\Michele\AppData\Local\TogglDesktop\

**Comment by mitchcan** [comment]
That did it. I had to go and kill on process still running. The timer is now populating. Thanks for your help!

**Comment by amulware** [comment]
Great to hear that it works now, and thanks for your patience!
