### ISSUE TITLE
Pasting a value into description field doesn't always "stick" 

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#1486]
windows_native_app/7.2.28
The problem is that when I attempt to paste a value into the description field using TogglDesktop, the value does not "stick" the first time, it simply disappears after a second or two and I have to re-paste the value a second time, after which it "sticks".
I am currently running TogglDesktop 7.2.281 on Win7x64, but as I mentioned, this problem has existed in all previous versions of TogglDesktop for as long as I can remember.
Reported with Desk case #184864

**Comment by kadrihvl** [comment]
another user reported seeing the same with typing (clearing app's cache didn't help). Desk case #185075: 
The only issue I have with the latest version is that when I begin typing into the box to start tracking a time, it will clear the box and make me have to start typing again. By this I mean I will type the words "Check Jacksons Bac" then it will clear the box and I will have to type the full thing in again. It seems to be doing this on pretty much evert time tracking event and I'm not sure why.

**Comment by amulware** [comment]
This is most likely related to double updates from the library. Needs investigation.

**Comment by codeman38** [comment]
I'm experiencing this issue in the typing use case as well.

**Comment by killermouse0** [comment]
Same here. I have a feeling that this happens when the desktop app syncs while you're typing the description. Not 100% sure though.
