### ISSUE TITLE
Crash on Launch, 7.2.199 Mac OS X

### ISSUE THREAD

**Issue by emfabric** [toggl/toggldesktop#1488]
With the build downloaded from toggle.com (7.2.199), the app crashes immediately on launch (so quick it doesn't look like it's opening at all).

The crash log has this line, among others:

Application Specific Information:
abort() called
terminating with uncaught exception of type Poco::WriteFileException: Cannot write file

**Comment by tanel** [comment]
seems like to have no permissions to write to the app data folder:

~/Library/Application Support/Kopsik/production

(where ~ is your home directory, for example /Users/tanellebedev in my case)

Can you confirm that you have write permissions to that folder?

**Comment by emfabric** [comment]
I deleted that folder, and it is launching correctly now. Thank you.

The association between the Kopsik folder and TogglDeskop wasn't obvious to me.
