### ISSUE TITLE
Toggl Desktop prevents Windows to shut down.

### ISSUE THREAD

**Issue by sitawit** [toggl/toggldesktop#1489]
When shut down Windows without manually close Toggl Desktop, the app prevents Windows to shut down. Windows display a screen that says waiting for software to shut down but Toggl never shut itself down. 

I don't know the reason yet but it won't happens to most of Windows software. It could be just me. 

Windows Version: 7
Toggl Desktop: 7.2.266

It's not a big deal, however I feel like put it here because it might not be intentional.
Thanks.

**Comment by amulware** [comment]
Thanks for reporting the problem.

This is not intentional behaviour, and we will definitely look into it!

**Comment by IndrekV** [comment]
The latest version is 7.2.281. Please update to the latest version to see if this fixes your issue.

**Comment by sitawit** [comment]
Will do.

**Comment by pstephens** [comment]
I am running 7.2.281 and Windows still will not shut down without manually quitting Toggl desktop.

**Comment by sitawit** [comment]
The 7.2.281 version works well for me. It is now shut down smoothly. I'm not sure this will last, however  if I find the same issue again I will open another ticket.

**Comment by amulware** [comment]
I did some tests in the build we will be releasing next week, and it seems to work fine there.

I'm going to close this for now. If the problem persists in future versions, we will have to look into this more.

**Comment by JensGabe** [comment]
I'm having the same issue with version 7.2.313 on Win7Pro

**Comment by amulware** [comment]
Aaaaand open!

**Comment by JensGabe** [comment]
I cannot close it manually either (on the X button) or Close from the Windows menu (program icon).
Only Quit from the Settings menu (Cog wheel) works

**Comment by amulware** [comment]
There have been some major changes to the app which included a refactor of the way the app closes itself, and how it handles being force closed (for example during shutdown). Closing this again, until we get more reports in version 7.3.80 or higher.
