### ISSUE TITLE
Desktop app suddenly won't open anymore on windows 8.1, TogglDesktopInstaller-7_2_281-2015-08-14-12-29-02

### ISSUE THREAD

**Issue by neeltjes** [toggl/toggldesktop#1496]

**Comment by mginou** [comment]
I was having similar issues on Windows 7. I'm finally back up and running having completely removed Toggl, including manually purging directories under ...\AppData\Local and ...\AppData\Roaming.

Here's some official information on clearing out the local cache: http://support.toggl.com/clearing-the-local-data-from-toggl-desktop/

**Comment by amulware** [comment]
As @mginou suggests, could you try manually deleting all files in at least C:\Users\<username>\AppData\Local\TogglDesktop and see if that helps?

We have had some issues that may be related something going wrong with the installer lately that we are still looking into.

**Comment by neeltjes** [comment]
Thank you mginou and amulware. I manually deleted all toggl folders at the local app data folder. That helped. It now runs again.
