### ISSUE TITLE
Reminders don't persist using OSX Desktop Notifications set to Alerts

### ISSUE THREAD

**Issue by jb510** [toggl/toggldesktop#1499]
A bit confused as there is a ToggleDesktop setting in Preferences:Notifications even though the alerts don't look like they're using the OSX Desktop Notification API.  

Regardless, the reminder shows up to track time but it doesn't persist.  OSX Desktop Notifications are set to "Alert" (see screneshot) which should persist until dismissed unlike a Banner would would dismiss automatically.  The Reminder appears and then a minute later dismissed on it's own.  Other reminders set to "alert" like Slack persist like they should.

 https://cloudup.com/cQVgsKwojK3

**Comment by jb510** [comment]
Digging a little deeper.  The reason the alerts may have looked "wrong" was they may have actually been coming from the Chrome Extension, not TogglDesktop. I've disabled those, but now I'm not seeing any reminders...

**Comment by tanel** [comment]
the issue was about toggl button; the reminder logic has changed meanwhile as well
