### ISSUE TITLE
Several adjust start-time issues.

### ISSUE THREAD

**Issue by Iapmes** [toggl/toggldesktop#1500]
Behaviour for active tracked current event:

Issue 1:

1) Open details pane
2) Set focus to start time field
3) Edit (e.g. subtract one hour: 12:00 -> 11:00)
4) Tab - focus moves to the "time spanned" field (e.g. 53:05 min)
5) Tab again - focus moves to another field (date)
- The start time is reset back to 12:00

Workaround: Actively set focus to any other field.

Expected behaviour: When leaving the start time field, the new timespan should immediately be adjusted accordingly.

---
Issue 2:

1) Open details pane
2) Set focus to "time spanned" field, but make no changes
- The time tracking stops in the field, but continues in the main window
- Wait a couple of minutes
3) Set focus to another field.
- The timespan is reset to the time set in the field (also for the counter in the main window).

Workaround: none

Expected behaviour: When leaving the field and no changes have been actively done to the field, the time should not be reset to that value, but continue as in the main window. However it makes little sense to actually change the timespan for the current running event - you would most often change the starting time. So for the current event the field could be disabled. (This should then also resolve issue 1).

Kind regards
André

Destop for Windows, 7.2.281
Windows 8.1, Regional settings: Norwegian Bokmål

**Comment by amulware** [comment]
Hey André,

Thanks for reporting these issues!

We are aware of them and should have fixes for them in one of the upcoming builds.
Your suggestion to disable the duration field for running time entries is interesting.
We'll consider it and either way will make sure it works the expected way!

**Comment by amulware** [comment]
For completeness: The duration box is still editable. However, it will only cause a change to the time entry when the user actually edits it.
