### ISSUE TITLE
create test bots (trybots) 

### ISSUE THREAD

**Issue by tanel** [toggl/toggldesktop#1504]

**Comment by tanel** [comment]
buildbots should only build; for unit and ui testing we should have diff. machines without any dev stuff

**Comment by tanel** [comment]
if possible, lets use some cloud service for that. it does not need any access to our source code etc. only download the new build, run tests, run uitests, just run the app; report back the results or perhaps collect it in a waterfall, in buildbot view

**Comment by IndrekV** [comment]
We can also create Virtual machines in our Build machines and use them as Trybots
