### ISSUE TITLE
Add project form closed when selecting tag

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1505]
When inserting new project and after that select tag without pressing save on the project form the `Add project` form is closed.

**Comment by amulware** [comment]
Similar when checking the billable box, or applying any other change.

We probably need to somewhat rethink the way details are saved (mostly on un-focus, but it is complicated).
We also need to recheck how exactly the edit view updates when it receives data about the same time entry that is already being edited (this happens everytime a change is made and saved).
