### ISSUE TITLE
Converting the window to WPF

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1508]

**Comment by amulware** [comment]
For reference, all work on this is being done here: https://github.com/toggl/toggldesktop/tree/win-total-wpf-conversion

**Comment by amulware** [comment]
These issues should be resolved by the conversion:

**Comment by amulware** [comment]
These issues should be resolved by the conversion:

- #1465
- #1458
- other (minor) dpi scaling issues
- windows can be resized from all borders
- flickering and stuttering when resizing and maximising/restoring window should be greatly reduced

We should check all these things to make sure things didn't get worse.

**Comment by amulware** [comment]
Current status:

- all windows have been converted to WPF
- only a couple of small features are still missing, among them:
    - [ ] idle notifications are not triggered yet
    - [ ] balloon tooltips are not showing up
    - [ ] the error bar in the main window has not been added yet
    - [ ] global short cuts are not activated yet

Apart from that, there is still a lot of polish needed to make everything as smooth as before.
