### ISSUE TITLE
Auto-updater prompting to insert adminstrator password without indication that it's for Toggl Desktop

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1511]
OS X window saying “Autoupdate wants to make changes” and asks for password. There is noway to determine that the request was from Toggl Desktop.

More info: 193253

**Comment by tanel** [comment]
"Autoupdate" is the name of the executable that performs the actual update. It's part of the Sparkle framework. We could rename it to "TogglDesktopAutoupdate" or similar.
