### ISSUE TITLE
Cannot login into Toggl Desktop on windows behind a proxy

### ISSUE THREAD

**Issue by TumbleMagnet** [toggl/toggldesktop#1513]
I have not been able to log in since I installed the desktop. I always get the error message: "Login failed. Are you online?" 

I use the web site daily so the user/password I use are correct (tried several times).

Environment:
- Windows 7 Enterprise SP1 (32 bits)
- behind a proxy with authentication

I double checked the proxy settings with other programs to be sure they're correct.

Any clue what the issue might be?

**Comment by IndrekV** [comment]
Please contact support (support@toggl.com) and send your log files from C:\Users\<username>\AppData\Local\TogglDesktop

log file name is toggldesktop.log

**Comment by TumbleMagnet** [comment]
Forgot to mention that I tried both the stable version and 7.2.313.

**Comment by TumbleMagnet** [comment]
@IndrekV : thanks, I sent my log file.

Having a look into it, it seems that it cannot find www.toggl.com which would indicate that the call is not using the proxy despite what is configured.

**Comment by tanel** [comment]
What kind of proxy is that exactly?

**Comment by TumbleMagnet** [comment]
It is a corporate appliance: bluecoat ProxySG 9000-10

**Comment by tanel** [comment]
Do you know if its a HTTPS proxy? Do you know its host, port, credentials to configure the proxy manually? Our proxy support is not perfect at the moment; for example proxy auto config (PAC) does not work yet.

**Comment by TumbleMagnet** [comment]
It did try both the "auto" and the manual config and both did not work.

It is certainly an HTTP proxy and I am going through it at the moment to access Github in HTTPS from my browser.

**Comment by samcogan82** [comment]
I can confirm I am also seeing this issue when behind a HTTPS proxy, neither auto or manual configuration will allow it to work.

**Comment by tc0** [comment]
Same problem for me for version 7.3.199 behind corporate proxy. What I could find out:

* Using system proxy settings does not work at all. According Toggl's log files it does not use any proxy settings.
* Using manual settings, Toggl Desktop can establish the ssl connection (I have checked this with a local web proxy) and I can see the proxy settings in log file. But the sync is NOT successful. In log file I can see ":ui:E:Host not found: www.toggl.com". Same lines come up for stream.toggl.com and timeline.toggl.com.

**Workaround**: If I enter these 3 addresses to C:\Windows\System32\drivers\etc\hosts with any address, sync runs successful. It seems to me that the second host resolution is superfluous.

**Comment by IndrekV** [comment]
Thank you for the details. We will take another look at the proxy implementation.

**Comment by chipbite** [comment]
I am also most often behind a proxy. It works, but not consistently. Alot/most of the time the desktop client shows "Offline" in the status bar. Then, at some time, not sure when, upon repeated ctrl-r's, for instance, it connects and syncs. 

I will investigate further, and see if I can get any ideas.

**Comment by chipbite** [comment]
Same today. Laptop docked, on cabled LAN, behind proxy:
1. Initially says "Offline, no network"
2, Then manages to sync

3. I do changes to the web
4. Try to sync desktop client, and it takes a very long time to sync (2-4 minutes ?). Then it says "Offline, no network" again. And then a few moments later, that text is gone again.

The offline message goes on and off, basically, and sync is very slow.

**Comment by chipbite** [comment]
Hi again. I am not sure if the issue is exactly the same as the OP, but sync fails *almost* consistently (meaning in most cases).

If I persist, it may often sync, but it takes much time and ctrl-r's. Very odd.

Please let me know if there is anything i can do to assist if needed, send logfiles, or something.


As it is right now, the app is unusable to me, which is sad since I really appreciate some of the features.
Sticking with android app and web for now.

Thanks for a great service!

**Comment by chipbite** [comment]
I have sent my logfiles to the support mail as indicated above. :)

**Comment by aflcode** [comment]
Hi, my company uses PAC for internet access.  Any news when the proxy support will be enhanced?

**Comment by IndrekV** [comment]
Currently we have no clear plans about adding PAC support to the app.

**Comment by chipbite** [comment]
@tc0, ok, so it seems as if Toggl is having issues with the host lookup, but actual request is fine, once the host lookup is successful?

Will check my own log to confirm this. Odd behavior, indeed. I've almost given up on it, would be great to get it working again.

**Comment by tc0** [comment]
Same behavior after upgrade to  7.3.318 (see my post above). I have configured proxy settings manually including login and password for NTLM2 authentification. 
It works never if my hosts file is empty. 
Now I have to add desktop.toggl.com (with any IP) to my hosts file (probably an API change in Toggl Desktop compared to version 7.3.199). 
It works always, if desktop.toggl.com entry exists in my hosts file.

**Comment by chipbite** [comment]
Hi again, 
@tc0 - I tried to add desktop.toggl.com to my hosts file and it actually completes but it still takes some time, IMHO. Thanks for this tip!

With this workaround for proxy usage, I will start using toggl desktop again and see if it works.

**Comment by chipbite** [comment]
It takes several minutes for toggl desktop to complete a sync.

**Comment by IndrekV** [comment]
@chipbite  We have made some improvements to the local data in the latest beta version. It makes the app keep less unused data and should improve performance. To switch to beta. Change the channel from the About view.

**Comment by chipbite** [comment]
Hi @IndrekV ! 

Proxy is working better, but it is still very unreliable when commuting. Syncing is very slow, it says "3" (as in 3 items/entries to sync, I assume) but it takes a long time and the client often displays "offline" even though it is clearly not.

This is from today. Outlook connects, skype connects, but toggl desktop client struggles.

![image](https://cloud.githubusercontent.com/assets/559199/21174063/4bffdaf4-c1db-11e6-9277-0e4cede4408c.png)

Thanks for a great solution, all the same. I wish I could rely on the desktop more, it would be really good when commuting.

BR! /marcus

PS If you are interested, I can describe the usage scenario.
High level: Charlie Commuter connects using modem. Establishes VPN connection. Signs in on chat, triggers mail refresh and attempts to start toggl time entry. Charlie closes lid on laptop as he embarks on next travel leg (train, bus, etc). Modem closes connection, VPN may close or attempt retry. Toggl should preferably see this as idle. Charlie opens lid after sitting down. Re-establishes modem connection, VPN (either manually or automatic retry depending on company VPN policy). Mail & Chat client reconnect. Preferred/Expected would be for toggl to shoot up dialogue asking if to discard/keep/etc time and sync. Right now, this is not happening.

**Comment by etem** [comment]
Hello, 
Same issue with the proxy here. I can't login using google account either.

**Comment by MpDzik** [comment]
Hello,
I have the same issue with HTTP proxy. The log file contains an error message "Got networking error Host not found: desktop.toggl.com will attempt offline login".

**Comment by iyerusad** [comment]
Toggl Desktop (OSX) also appears to fail to connect behind SOCKS proxy.

**Comment by marianban** [comment]
I have same problem. Cannot login from behind company proxy. Tried both google/standard login and both failed. Here some log output:
`2017-10-25 11:53:44.528 [13372 4]:Analytics:E:SSL Exception: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
2017-10-25 11:53:44.544 [13372 4]:HTTPSClient:D:Sending request to https://ssl.google-analytics.com/collect?v=1&tid=UA-3215787-27&cid=29bf6705-d60b-451a-b500-d2f55b51197c&t=event&ec=settings&ea=settings/pomodoro_break-0 ..
2017-10-25 11:53:44.544 [13372 4]:Analytics:E:SSL Exception: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
2017-10-25 11:54:10.434 [13372 0]:context:D:SetWake
2017-10-25 11:54:10.434 [13372 0]:context:D:Next wake at 2017-10-25T11:54:12Z
2017-10-25 11:54:12.436 [13372 1]:context:D:onWake executing
2017-10-25 11:54:12.436 [13372 1]:context:D:Sync
2017-10-25 11:54:12.436 [13372 1]:context:D:Next sync at 2017-10-25T11:54:12Z
2017-10-25 11:54:12.436 [13372 1]:context:D:onSync postponed
2017-10-25 11:54:22.644 [13372 0]:TogglClient:D:Sending request to https://desktop.toggl.com/api/v8/me?app_name=windows_native_app&with_related_data=true ..
2017-10-25 11:54:22.725 [13372 0]:ServerStatus:D:UpdateStatus status_code=0
2017-10-25 11:54:22.725 [13372 0]:ui:E:SSL Exception: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
2017-10-25 11:54:22.725 [13372 0]:ui:D:DisplayOnlineState no network
2017-10-25 11:54:22.726 [13372 0]:context:D:Got networking error SSL Exception: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed will attempt offline login
2017-10-25 11:54:22.726 [13372 0]:context:D:User data not found in local database for marian.ban@gmail.com
2017-10-25 11:54:22.726 [13372 0]:ui:E:Login failed. Are you online?
2017-10-25 11:54:22.726 [13372 0]:ui:D:DisplayError err=Login failed. Are you online? actionable=Login failed. Are you online? is_user_error=1
2017-10-25 11:54:22.726 [13372 0]:toggl_api:D:Login failed. Are you online?`

**Comment by elestedt** [comment]
I have the same issue when I'm behind a corporate proxy, which I always am because of how IT has set it up.
As far as I can determine the problem is that it tries to resolve the name using DNS when a proxy is enabled - it should just send the request to the proxy and let it do the resolving.

**Comment by blitzkopf** [comment]
I finally figured this out, had been trying to get the app to work couple of times a year for the past 6 years. And newer really getting anywhere with it. But then it struck me today that "enterprise" proxy is actually intercepting HTTPS traffic and issuing a new certificate issued by it's own Root CA. This "local" root CA is unknown to Toggl, and it discards the connection as insecure.
So I Inserted the Enterprise Root CA into AppData\Local\TogglDesktop\cacert.pem, and got connected right away.

**Comment by DesHorsley** [comment]
Thanks @blitzkopf this worked for me, it would be great if Toggl added this to their documentation.

**Comment by IndrekV** [comment]
There is a page in wiki but I think adding this also to support page would make it easier to find. https://github.com/toggl/toggldesktop/wiki/Getting-Toggl-Desktop-to-work-with-local-proxy
