### ISSUE TITLE
shortcuts don't work in windows now

### ISSUE THREAD

**Issue by xypc** [toggl/toggldesktop#1516]
Hello! About a week ago I've noticed that keyboard shortcuts stopped working in toggl-app. I think that it's caused by one of last updates.I attach 3 screenshots with some words about how I try to use shortcuts, and what problems I have.
1. I open "Preferences" and press "Record shortcut"
![toggl_1](https://cloud.githubusercontent.com/assets/7665658/9761594/74d3a5f0-5706-11e5-996e-6493639cc76b.png)
2. Press my previous combination Alt+T
![toggl_2](https://cloud.githubusercontent.com/assets/7665658/9761600/77f91bd4-5706-11e5-997e-6a347e6a1171.png)
3. It seems that "Alt+System" isn't equal to "Alt+T" and it doesn't work.
![toggl_3](https://cloud.githubusercontent.com/assets/7665658/9761602/7a2b7ae6-5706-11e5-869d-e8f92843975a.png)

**Comment by amulware** [comment]
Hey @xypc, can you let me know what version of Toggl Desktop you are using? You can find that information in the about-window.

**Comment by xypc** [comment]
Hi! Here is the creenshot of "about" window=)

By the way, can you tell me what shoud I do and what shoud I know to join
your team or mb help you with some issues etc.?)

2015-09-11 12:03 GMT+03:00 Paul Scharf <notifications@github.com>:

**Comment by amulware** [comment]
You'll have to upload the screenshot directly on GitHub. It ignores email attachements.

Otherwise, if you like to help there are basically two options:
- fork the repo and create pull requests,
- or: http://jobs.toggl.com/

**Comment by xypc** [comment]
![toggl_ver](https://cloud.githubusercontent.com/assets/7665658/9816042/09e48f86-58a3-11e5-97f6-6c5df0c35ffe.png)

**Comment by amulware** [comment]
We recently released a new beta version which includes a number of bug fixes and improvements. Could you try and see if the problem still occurs with it?

To switch to beta:
1. select beta release channel in about window
2. give the app 5-10 minutes to download update in the background (there is no notification about this right now I'm afraid)
3. restart the app, and it will automatically install the update
4. check in the about window that it updated to version 7.2.313

I hope this helps!
If not, we will take a closer look.

**Comment by xypc** [comment]
I tried this, but it didn't help.

2015-09-14 13:24 GMT+03:00 Paul Scharf <notifications@github.com>:

**Comment by amulware** [comment]
I believe this commit fixes the bug you described.
There will probably be a new beta version including this fix next week.

Thanks for your patience!

**Comment by amulware** [comment]
Closing for now. We can reopen if the problem still exist with the next beta.

**Comment by xypc** [comment]
OK, thank you for feedback) I'll check this next week!

2015-09-16 10:52 GMT+03:00 Paul Scharf <notifications@github.com>:
