### ISSUE TITLE
libssl problem, fedora 22

### ISSUE THREAD

**Issue by sterndata** [toggl/toggldesktop#1517]
$ ./TogglDesktop 
./TogglDesktop: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

openssl-libs is installed

$ locate libssl.so

/usr/lib/.libssl.so.1.0.1k.hmac
/usr/lib/.libssl.so.10.hmac
/usr/lib/libssl.so.1.0.1k
/usr/lib/libssl.so.10
/usr/lib64/.libssl.so.1.0.1k.hmac
/usr/lib64/.libssl.so.10.hmac
/usr/lib64/libssl.so
/usr/lib64/libssl.so.1.0.1k
/usr/lib64/libssl.so.10

I found a copy of it in the tor browser package and copied it to ~/toggledesktop. It then bugged on libcrypto. I copied that from the tor browser, too. Now I get:

error while loading shared libraries: libdl.so.9b15f6a6

Giving up.

**Comment by tanel** [comment]
Hi, we've tested the precompiled Toggl Desktop for Linux on Ubuntu only. We recommend building from source on your platform.
