### ISSUE TITLE
Symbol lookup error (linux)

### ISSUE THREAD

**Issue by sasha-** [toggl/toggldesktop#1518]
toggldesktop_x86_64-7_2_325-2015-09-11-15-28-25.tar.gz does not start.

$ ./TogglDesktop
TogglDesktop: symbol lookup error: ./TogglDesktop: undefined symbol: _ZN9QMetaType22registerNormalizedTypeERK10QByteArrayPFvPvEPFS3_S3_PKvEi6QFlagsINS_8TypeFlagEEPK11QMetaObject

_ZN9QMetaType2 is referenced in libbugsnag-qt.so.1 and TogglDesktop

http://demangler.com/ translates this to:
QMetaType::registerNormalizedType(QByteArray const&, void (*)(void*), void* (*)(void*, void const*), int, QFlags<QMetaType::TypeFlag>, QMetaObject const*)

Is there missing #include <QMetaType> for libbugsnag-qt?

I will try building the app myself and se what happens.

I built it and it runs ok, but it does not sync any times.

**Comment by tanel** [comment]
the errors means that QT libs where not found. you have to add QT libs path to LD_LIBRARY_PATH for the app to work, as described here: https://github.com/toggl/toggldesktop/blob/master/src/ui/linux/README
