### ISSUE TITLE
should be possible to change start time when counter is running

### ISSUE THREAD

**Issue by rodrigo-campos** [toggl/toggldesktop#1522]
Should be possible to change start time when counter is running - as it is possible to do on Toggl website.

It was possible before, now it's not.

**Comment by amulware** [comment]
Thanks for reporting the issue.

Can you clarify, which operating system is this?
Also, in which way does it not work? Can you not edit the start time field at all, or does it reset after you change it?

**Comment by rodrigo-campos** [comment]
Well, nevermind.. it seems to be working correctly. Please close the issue.

Thanks.
