### ISSUE TITLE
Windows desktop app stops responding for 10-30sec when doing most tasks

### ISSUE THREAD

**Issue by ernasipi** [toggl/toggldesktop#1525]
New version (7.2.281) stops responding on most tasks, like starting new timer, editing existing/new task data, even when opening the about window to check version number. It mostly happens when starting to do something in app after some idle time or after working on a project for a while. Never had the issue with previous versions.

**Comment by IndrekV** [comment]
Please make sure you have the latest version of the app. We released a new version (7.2.313) just yesterday. Please upgrade if you have an older version. Please send feedback from the app if the issues re-appear with the latest version.

**Comment by ernasipi** [comment]
Back to normal after updating to 7.2.313

thx!
