### ISSUE TITLE
toggl timer on desktop (app) not populating

### ISSUE THREAD

**Issue by mitchcan** [toggl/toggldesktop#1527]
I restarted my computer tonight and my AVG detected a threat from my Toggle desktop. This threat was removed but then my desktop toggl was also gone.    I downloaded a new exe file and when I went to run it the same threat came up.

I had already uninstalled toggl desktop, made sure there were no processes still running in the task manager and also cleared all the files from apptdata/local/toggldesktop so I could start with the new exe install.

Any ideas?  Is this a problem you have been having from other users?  

I use this each day so I'd appreciate a solution, thanks, Michele

![toggle threat exe](https://cloud.githubusercontent.com/assets/13835081/10036376/cc784f0e-6174-11e5-8eca-9f7eec422273.png)

**Comment by IndrekV** [comment]
We have had few similar issues with Norton Security. The users have whitelisted the app or have contacted the AntiVirus software developer and have gotten instructions on how to whitelist the app.

**Comment by mitchcan** [comment]
How is it possible to be using this for months with no issue and then no change to versions and I restart my computer and it's all of a sudden got a virus detection from AVG?  Seems like you might be passing me off on this one.  I'll be in touch with AVG but would have appreciated more help on this if possible.

**Comment by IndrekV** [comment]
It seems that AVG has updated it's database and declared all Toggl products a threat. We got a similar report about our Android app.

**Comment by mitchcan** [comment]
I have successfully added the folder for Toggl desktop as an exception in AVG in advanced settings.  Thanks.
