### ISSUE TITLE
Create designed message boxes

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1529]
The native operating system Message Box does not fit with our overall design.

Message Box currently used:
- For delete confirmation and probably
- For successful feedback notification
- Clear cache confirmation
- Also inside Program.cs to show notification that an instance of Toggl Desktop is running
- Probably some other cases also.

**Comment by amulware** [comment]
I suggest following Google's material design principles, since we are already doing so in most things. Naturally, adapted to our own style.

I'll take a look at this and will show what I come up with!
