### ISSUE TITLE
Investigate windows issues

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1534]
- [x] Auto-complete sometimes works, sometimes does not.
- [x] Trying to edit time duration very fiddly, you cannot see a cursor sometimes and it clears what you are entering.
- [x] Same with the tasks description… start typing, it clears and then you have to start again.

Fields should never be changed when the user has focused them for editing.

If info needed contact: 199550

**Comment by IndrekV** [comment]
Should create ui test for extensive Autocomplete usage

**Comment by amulware** [comment]
These issues should be fixed now.
