### ISSUE TITLE
Design first user experience tutorial

### ISSUE THREAD

**Issue by amulware** [toggl/toggldesktop#1545]
The tutorial should at least teach the user to: start, stop, edit

**Comment by IndrekV** [comment]
First user experience is shown after first login.

overlay color: rgba(67,67,67,.7)
(opacity is 70%)

Green button color: #4bc800

Lets use similar style to the web app. In web app creates three mockup time entries and adds them to the list to show how they would look. Once user clicks ok, the list is cleared.

See screenshots for reference:

![start](https://cloud.githubusercontent.com/assets/842229/10631213/0ab9bc86-77e5-11e5-83fc-abb4b3ec0e95.png)

![edit](https://cloud.githubusercontent.com/assets/842229/10631214/0abab456-77e5-11e5-9f6a-317a13ef8873.png)


### Images
(Images are white so not visible on github)

left
![welcome-arrow-left](https://cloud.githubusercontent.com/assets/842229/10631378/49b2fc44-77e6-11e5-8b3a-39adfc4b2777.png)

right
![welcome-arrow-right](https://cloud.githubusercontent.com/assets/842229/10631377/49aa88de-77e6-11e5-91b5-c8da5d4b00de.png)

line
![line](https://cloud.githubusercontent.com/assets/842229/10631362/36ca33b8-77e6-11e5-81b0-a613f4bb07d0.png)

**Comment by IndrekV** [comment]
### First
### First
### First

**Comment by IndrekV** [comment]
### Intro view

Welcome to Toggl Desktop

Would you like us to show you around?

Green Button `TAKE TOUR`
(gray) link `no thanks`


### Second

- Overlay
- Dummy entries


Text : Your activity will appear here
Button: Ok, let's go!

(After button press the dummy entries disappear and so does the overlay)

### Third

Text pointing to description: Describe what you are doing?
Text pointing to start button: Start and stop your timer here


Could be that the second text is shown when user focuses description field.

### Four

Timer is running

Text pointing to running entry: Click here to edit the running entry

### Five

Text in the main window: When you are done editing close the edit view with ESC or x on the corner

### END

You're all done here now try editing the stopped entries and continue entry from the list.

**Comment by amulware** [comment]
All relevant ui is implemented, and the tutorial can be started from the context menu.

The only thing missing is the library telling the ui to show the welcome screen (which also starts the tutorial unless the user wants to skip it).
