### ISSUE TITLE
Updates to the time entry is not persistent during field update

### ISSUE THREAD

**Issue by nicklasgav** [toggl/toggldesktop#1546]
When changing one field of a running/stopped time entry and then continue to change other fields the syncing process will reset all information entered after the sync has begun. See attached image for example. Affects both current beta and dev (7.2.360) channel (windows). Also affects other fields than the description.

![bug](https://cloud.githubusercontent.com/assets/1453777/10164473/f748df9c-66b9-11e5-94c8-f5351ee0edff.gif)

**Comment by amulware** [comment]
Thanks for reporting the issue!

I am able to reproduce the problem.
We will take a closer look and should have this ironed out for the next beta release.
