### ISSUE TITLE
Hibernation causing black window

### ISSUE THREAD

**Issue by amulware** [toggl/toggldesktop#1548]
A user has reported that the app shows entirely black for them when waking Windows from hibernation and has to be quit using task manager.

**Comment by amulware** [comment]
Not able to reproduce. Reopen when there is more data.

**Comment by amulware** [comment]
More information: Occurs only on Windows 7, as far as we know. Needs testing there.

**Comment by kadrihvl** [comment]
Desk case #199992 if more info is needed.

**Comment by IndrekV** [comment]
Unable to reproduce with latest stable 7.3.27 on Win 7 machine

**Comment by Unit106** [comment]
Hi, I've got the same issue! I'm using the stable channel. It occurs with version 7.3.27 on Win7.

**Comment by amulware** [comment]
@Unit106 Could you see if the problem also still occurs on the current beta? (7.3.119) We made some changes that might solve this problem.
You can switch to beta in the about window of the app. (then give it a few minutes to download the update, then restart the app and it will install automatically)

**Comment by Unit106** [comment]
@amulware, I'm working now with version 7.3.119. In a few days I will report if my problem has been solved by this version.

**Comment by amulware** [comment]
Thanks a lot!

**Comment by Unit106** [comment]
Ok, the black screen is gone but now I got the message : 

![image](https://cloud.githubusercontent.com/assets/15779592/11087089/7ccdd550-8857-11e5-9201-289ccbb7ead9.png)

When I kill the task in the Windows Task Manager and restart Toggl this bar isn't visible anymore. So after a Windows 7 hibernation Toggle can't find the network connection.

**Comment by amulware** [comment]
Summon @tanel.

**Comment by tanel** [comment]
@Unit106 please send feedback regarding this issue from the Desktop app. Then we'll receive the log files from your app.

**Comment by Unit106** [comment]
@tanel Done!

**Comment by nickfmc** [comment]
Black screen on wake Also happens on Windows 10. Defiantly not only a Togle bug however. Seams to be a windows/graphics driver bug. mostly happens on apps built in a webframe.
