### ISSUE TITLE
missing xcb plugin on linux after installing 7.2.359

### ISSUE THREAD

**Issue by jgindin** [toggl/toggldesktop#1553]
Installation of the .deb works just fine, but then when running I get:

> $ /opt/toggldesktop/TogglDesktop
> QMetaType::registerTypedef: -- Type name 'QVector<' previously registered as typedef of 'QVector<AutocompleteView*>' [1036], now registering as typedef of 'QVector<GenericView*>' [1039].
> This application failed to start because it could not find or load the Qt platform plugin "xcb".
> 
> Available platform plugins are: xcb.
> 
> Reinstalling the application may fix this problem.

I've tried re-installing, but to no avail...

**Comment by IndrekV** [comment]
We are aware of this issue and are working on a fix. Please revert back to stable version until this gets sorted.

**Comment by jgindin** [comment]
The app still downloads 7.2.359... Is there an estimate on when the updated version with this fix will be published?

thanks!

**Comment by tanel** [comment]
Hi there! The dev build is available here: https://assets.toggl.com/installers//toggldesktop_x86_64-7_3_67-2015-10-21-14-36-51.tar.gz

Please let me know if it helped!

Also please note that you need to run TogglDesktop.sh now to have the necessary libs and plugins automatically loaded.

Kind regards,

**Comment by jgindin** [comment]
So far so good! The indicator is really nice to have!!!

**Comment by tanel** [comment]
Thx! Feel free to create new issues if you discover anything unusual.
