### ISSUE TITLE
Timeline keeps tracking "Windows Default Lock Screen" while being idle

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#1554]
Windows 10 user has reported following:
Previously, when I was away from my PC, nothing was logged in Timeline and I saw a gap between the blue bars in the "Timeline" plot, but now I see blue bars even when I'm away from the PC,
indicating that "Windows Default Lock Screen" was running.
Desk case #199401

**Comment by MarcusHallettUAH** [comment]
Any progress on this? The problem is persistent.

**Comment by IndrekV** [comment]
Sorry no progress on this yet. @MarcusHallettUAH Can you confirm that you also are experiencing the issue with Windows 10.

**Comment by MarcusHallettUAH** [comment]
@IndrekV I can confirm, as I stated in #1965

**Comment by intParse** [comment]
This is annoying. 
![screenshot 1](https://user-images.githubusercontent.com/4715375/27301007-6a4b2444-553a-11e7-81fd-27396c1c7de9.png)

**Comment by johnconsulta00** [comment]
@intParse For what OS version build of Windows 10 does this happen?

**Comment by svbeon** [comment]
This issue still exists 
Windows 10 Pro 1809 (17763.503)
toggl desktop 7.4.422
