### ISSUE TITLE
Timer design changes for compact mode

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1557]
- [x] Make the font smaller - the same size as the listing font.
- [ ] Duration and start/stop button fonts should have the same size as other text
- ~~[ ] Start button should be smaller in width. Maybe the width of two header icons instead of three.~~
- ~~[ ] Switch the locations of project and description field. Description is always on top.~~
- [x] Hide the 00:00 (duration) field altogether when the timer is not running

Make the timer responsive. Smaller width has smaller fonts.

**Comment by amulware** [comment]
Mostly implemented, any further details should be discussed, but are easily added/changed.
