### ISSUE TITLE
Show notification when new version is downloaded

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1560]
Currently in osx we show two messages:
`Downloading version ...`
and 
`Version downloaded, restart to upgrade`

We should add something similar to windows.

**Comment by amulware** [comment]
Should this be displayed in the same bar as the offline/sync notifications? If so, which has priority? If not, should there be another bar, or where else should the information be displayed?

**Comment by IndrekV** [comment]
In osx the messages are actually showed in About view. It's good for example when you change the channel and want to know if you are getting the update.

I think in the first step we should add the notifications to the About view.

**Comment by IndrekV** [comment]
lib should send notification to ui

**Comment by amulware** [comment]
Can you look into this @tanel, and let me know if there is an event we are missing, or add one otherwise?

**Comment by tanel** [comment]
will add event to library, with string parameter that tells the new version and download state (downloading, downloaded)?

**Comment by amulware** [comment]
Sounds great!
