### ISSUE TITLE
Add possibility to use continue with "Manual mode"

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1565]
Currently when in manual mode and clicking continue on some entry in the list this entry is started and the timer is switched back to timer mode.

Instead of this it would make sense to switch the continue also to Manual mode when timer is manual mode. This means that when you are in manual mode and click continue on one of the past entries it opens up the edit view as with the timer link click and it fills in all the data with the data from the continued time entry.

Same should go for the keyboard shortcuts.

**Comment by amulware** [comment]
Looks to me like this should be handled in the library when the `toggl_continue_latest` command is called (which it is in the cases described), and not in the ui.

**Comment by IndrekV** [comment]
It's not only about continuing the latest entry you can continue any entry in the list. But yes it should be handled in the lib.

**Comment by tanel** [comment]
so basically the continued entry will pop up in editor. will it be started (running) or not? if not, what will be its start and end time?

**Comment by IndrekV** [comment]
It will not be started.
Works as the regular manual mode.
Opens up edit view and fills in details like usual continue. Start ,duration and stop are not filled in. They are same as they are in the regular manual mode created entry.
