### ISSUE TITLE
Global shortcut using the Windows key

### ISSUE THREAD

**Issue by glen-84** [toggl/toggldesktop#1568]
This doesn't seem to be possible, is there a technical reason?

I'd like to use `Win+G`.

Also, would it not make sense to show Toggl even if it's minimized?

Thanks.

PS. Have you considered writing a desktop client using something like [Electron](http://electron.atom.io/)? It would be cool to be able to customize the UI and/or add plug-ins. =)

**Comment by IndrekV** [comment]
We'll investigate the possibility to use Windows key for shortcuts. 

As for Electron, please see my comment in Toggl Blog https://blog.toggl.com/2015/09/toggl-desktop-future/#comment-53618

**Comment by amulware** [comment]
In case anyone is interested: Turns out WPF does not include the windows key in Keyboard.Modifiers, which we used to detect modifiers held down when setting the shortcut. I changed it do detect each modifier key as it is pressed down in the first place, which works fine.

**Comment by glen-84** [comment]
@amulware Thanks! I switched to the dev channel, how do I check for updates?

PS. Closing the preferences window hides the main window (Win10).

**Comment by amulware** [comment]
It should download the update automatically in the background. There is currently no notification for this however. If you wait for maybe 5 to 10 minutes and then restart the app, it should install the update automatically.

Note that as a rule we do not recommend people using the dev channel. We sometimes break things, and there may be unfinished/unpolished features there as well. So: at your own risk. ;)

Thanks for the PS. We'll take a look at that.

**Comment by glen-84** [comment]
> It should download the update automatically in the background. There is currently no notification for this however. If you wait for maybe 5 to 10 minutes and then restart the app, it should install the update automatically.

I wasn't quitting the app properly (oops). It updated now. Thanks.

> Note that as a rule we do not recommend people using the dev channel. We sometimes break things, and there may be unfinished/unpolished features there as well. So: at your own risk. ;)

Ya, I am mentally prepared. =) It's just that I'm so used to hitting `Win + G` to show desktop gadgets (where I used to use a stopwatch gadget in Win7), and I was getting annoyed at it showing some Windows game bar thing in Win10.

It seems that I can't easily override existing Windows keys, but I'll try [this](http://superuser.com/a/704368/107130) FWIW.

Question: If I switch back to the stable channel, will it only update again when there is a stable release > the current dev release (7.3.10)?

> Thanks for the PS. We'll take a look at that.

This doesn't seem to happen with version 7.3.10.

**Comment by amulware** [comment]
Yes, if you switch back to stable or beta it will only update once there is a higher version number. Worst case you can always download the stable installer from the website though.

**Comment by glen-84** [comment]
Thanks. :+1:
