### ISSUE TITLE
Add compact mode setting

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1569]
Users can select between two design modes:
- Comfortable
- Compact (implemented with #1559 and #1557

**Comment by amulware** [comment]
This may be significant work. I will investigate how we can change the layout at runtime the easiest.

**Comment by amulware** [comment]
This is essentially implemented. Waiting for #1570 to add proper setting (currently makeshift checkbox on main form, see branch win-compact-mode).
