### ISSUE TITLE
Add compact mode setting to lib

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1570]
Depends on #1569

**Comment by IndrekV** [comment]
This needs some details. This is for windows app and depends if it is easy to switch between different designs on runtime. If it's not easy this won't be needed and we'll just change the windows design to be more compact.

**Comment by amulware** [comment]
Investigation shows that (in all likelihood) it will be relatively easy to change layout at runtime. Please add the setting!
