### ISSUE TITLE
Toggl Desktop is shown in timeline as "unknown"

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1573]
As per user feedback.

**Comment by tanel** [comment]
which platform?

**Comment by tanel** [comment]
@IndrekV do you know which OS, version etc this is happening?

**Comment by IndrekV** [comment]
User reported that on Windows. Only one user has reported so this might be a fluke.

**Comment by tanel** [comment]
i'm afraid its too few information to debug it further

**Comment by IndrekV** [comment]
It's settled then a fluke. If it comes up again we'll investigate.
