### ISSUE TITLE
Issue with saving the window size

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#1574]
windows_native_app/7.2.375
Using multiple monitors.
Window size is lost after I quit and restart TogglDesktop. Every time I start TogglDesktop the window size is the inconveniently narrow 300 x 473 px (see attached image), which makes it almost impossible to enter (and read) information about my current activity, since it only displays around eight characters. Therefore, I always start by resizing the window to a more relevant size, e.g. a width of at least 500 px. This setting, along with window position, remains while I close the TogglDesktop window and reopen the window by clicking TogglDesktop icon in the tray. However, as soon as I select 'Quit' and restart the program, the size returns to 300 x 473 px (as in the attached image). I don't know where this setting is saved. 
Issue reported with desk case #203259
![togglwindow_quit-restart](https://cloud.githubusercontent.com/assets/12407134/10337200/e1759518-6d06-11e5-82a1-0753b82ad1b8.png)

**Comment by kadrihvl** [comment]
Another user reported the same: desk case #203299.

**Comment by amulware** [comment]
Can not reproduce this at the moment.

**Comment by amulware** [comment]
The logs of the users experiencing the issue also do not contain any warning messages related to size not being saved/loaded. I added further debug output to the saving and loading of window size and location, in the hopes that the additional output will reveal something useful.

These changes will be part of the next beta.

**Comment by amulware** [comment]
User reports this is fixed in current beta.
