### ISSUE TITLE
Header Toggl icon should open up Toggl web app

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1580]
It should also log in the user. Similar functionality to `Reports` link should be used

**Comment by amulware** [comment]
The library api currently has an `OpenInBrowser()` call, which opens the reports.

Should clicking the icons send the user to the reports as well? In that case this is trivial.
If it should send the user to the timer or some other page, this has to be implemented in the library.

**Comment by IndrekV** [comment]
Let's use the same call and redirect user to reports if Toggl icon is clicked.
