### ISSUE TITLE
Preference to keep 'What are you doing' text after hitting stop

### ISSUE THREAD

**Issue by JohannesMP** [toggl/toggldesktop#1583]
By default the Toggl windows application will clear the current text entered in the "What are you doing" field when the user hits 'Stop'.

I personally often find myself hitting Stop when I'm going to the bathroom or focus my attention on something non work-related for a few minutes, only to then want to resume the previous task.

If possible I would like to have an option that keeps the last 'What are you doing' text in place, so I could hit 'Start' and 'Stop' multiple times in succession, without having to re-enter my task every time. Clicking in the 'What are you doing' field would clear it, allowing for quick and painless switching of tasks when necessary.

I understand that not all users would find this behavior intuitive, so having it as a preference would probably be the best.

Alternatively, It would be nice to have a 'Resume' icon (styled similar to a <a href=http://fortawesome.github.io/Font-Awesome/icon/refresh/>refresh icon</a>), that when pressed acted as if you had manually re-entered the most recent task name.

**Comment by IndrekV** [comment]
Hi, 

This exact behaviour can be done with continue keyboard shortcut. Pressing Ctrl+O will continue the latest entry. You can also trigger the same action from the cogwheel menu "continue" item.

**Comment by JohannesMP** [comment]
Probably a separate issue, but when using Ctrl+O on Windows 8.1, Several sections of the window fail to update:
<img src=http://i.imgur.com/SgKDEXI.gif>

Most notably:
- The timer visibly only partially updates (you see some cropping on the numbers)
- The 'What are you doing' text often does not correctly update until clicked or selected manually
- The 'Stop' button does not re-draw correctly and often remains visible as 'Start', despite the fact that the timer is currently running, until you mouse over it.
- Not visible, but the list of recent time slots will sometimes fail to update until moused over.
- For reference, the small red 'power' icon in the top-left corner seems to update consistently. keep an eye on it in my screencapture, compared to the rest of the elements.

**Comment by amulware** [comment]
Can you confirm that you are on the stable release channel? (you can find this in the about window.)

If so, this is probably a known issue and should be fixed with our next release. If you like to get that build early (i.e. right now) feel free to switch to the beta release channel.
If the beta holds up, it should make it to stable very soon though.
