### ISSUE TITLE
Syncing indicator changes

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1585]
- [x] Move syncing indicator to the window header.
- [ ] Add delay to syncing notification ( no need to show indicator if the sync takes less than 2 seconds )
- [x] Syncing indicator should be the same color as other icons in header
- [x] Un-synced entries are shown in the middle of the syncing indicator. 
- [x] clicking on the indicator triggers sync

<img width="425" alt="syncer" src="https://cloud.githubusercontent.com/assets/842229/10423947/a32220ee-70d3-11e5-8c55-f430d8404d2e.png">

**Comment by amulware** [comment]
As discussed, leaving the delay to be done in library, if possible.

**Comment by amulware** [comment]
If adding the delay in the library would be much effort, let me know and assign back to me. I'll then do it in the interface. That wouldn't be a big problem.

**Comment by amulware** [comment]
Note: I set the delay of the indicator showing up to 3 seconds, since it still showed up sometimes with 2 seconds delay for me. (on pretty fast internet)
