### ISSUE TITLE
Create analytics framework to have overview of the used features

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1589]
We can use GAnalytics for first implementation.

Things to measure:
 - [x] autocomplete usage 1496dcd43adc72c23b8e85d5bc5f9d09fe79a12f
 - [x] How many users are on beta channel ( should be calculated when checking the channel and latest beta version) 8f5fa8fb7df66fcf79397666c710582ee87af3c8
 - [x] Settings usage (Most popular settings (the input type settings)) 961a216f3bea472089e54d7936ac216ab94e1cbd
 - [x] What buttons are mostly pressed in idle detection 1cb0b38a9900ee3f35dc11aa3be54a21e0780a2c 8dc57924ccfde7df34c6e52ff55375edad38f664

**Comment by tanel** [comment]
we already have google analytics client code; see GoogleAnalyticsEvent for usage example.

**Comment by tanel** [comment]
but it has no API, its only internally used in the library. does it need an interface for UI?

**Comment by amulware** [comment]
We should make a list of what exactly we want to measure/record and then see if ui stuff is needed.

**Comment by IndrekV** [comment]
Things to measure:
* ~~autocomplete usage (already working)~~
* How many users are on beta channel ( should be calculated when checking the channel and latest beta version)
* How many users are on *latest* beta ( should be calculated when checking the channel and latest beta version. Gives us a hint, when something is up with beta)
* Settings usage
* Most popular settings (the input type settings)
* Manual mode settings users
* Keyboard shortcuts usage
* tray/cogwheel menu items usage
* Continue button usage
* How many projects/clients are created from the app
* How edit view is closed (ESC or x in the corner or some other way)
* How many time entries are deleted in the app ( is the bulk delete necessary )
* How many times the app is closed with sync not done
* How many times sync fails
* How many times Websocket disconnects
* What buttons are mostly pressed in notifications ( Autotracker, Tracking reminder, idle detection )
