### ISSUE TITLE
Fetching the windows title properly with word an Zotero

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1595]
This can cause issues with other applications as well and needs investigating. If this is something that can be changed close the issue.

User writes
>Looking more closely at this, I see that the problem is with toolbars added to Word by plugins or macros. We have a lot of such toolbars, and it looks like Word is presenting the name of one of the toolbars to Timeline instead of the name of the document. I don’t know how Timeline gets the window title, but I note that using the following Applescript to arbitrarily fetch the window title from the frontmost window, I get the window title of the document rather than the toolbar:
```
global frontApp, frontAppName, windowTitle

set windowTitle to ""
tell application "System Events"
set frontApp to first application process whose frontmost is true
set frontAppName to name of frontApp
tell process frontAppName
tell (1st window whose value of attribute "AXMain" is true)
set windowTitle to value of attribute "AXTitle"
end tell
end tell
end tell

return {frontAppName, windowTitle}
```

**Comment by kadrihvl** [comment]
Reported with desk case #205009.

**Comment by tanel** [comment]
We're not using Accessibility API-s or AppleScript to fetch the window attributes. Please take a look at https://github.com/toggl/toggldesktop/blob/master/src/get_focused_window_mac.cc

**Comment by tanel** [comment]
AFAIK its not possible with the current way we do things to get the accessible title. Please reopen this issue if you do find some way to do this. (I did not).
