### ISSUE TITLE
Clarify intended behaviour on START/STOP of edit popup

### ISSUE THREAD

**Issue by amulware** [toggl/toggldesktop#1604]
Currently, the library assumes that the edit popup stays open on start/stop.
If the popup is closed in the UI, this causes problems when the user tries to click the same time entry again (the library thinks that the entry is still being edited, so it tells the ui to close the popup instead of open it).

The ui could specifically tell the library that it closes the edit popup (`Toggl.ViewTimeEntryList()`), however this causes several duplicate updates of the time entry list which are bad for performance.

The entire thing makes it somewhat difficult to keep the different entry highlights correct under all circumstances as well.

What is the intended behaviour here?

**Comment by IndrekV** [comment]
@tanel

**Comment by tanel** [comment]
What should the behaviour be? Not sure what to do here.

**Comment by tanel** [comment]
did we agree on anything? can we write it down here please, i forgot it already

**Comment by amulware** [comment]
We said that the library should switch to the time entry view being active (which is equivalent to the edit popup being closed in the UI) whenever the timer is started/stopped. (Fun fact: If it then also sends the time-entry-list event with open==true, we can probably even remove the hard coded closing of the edit view on start/stop, woo!)
