### ISSUE TITLE
After hiding/minimizing Win app window it reappears as black

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#1607]
If you hide or minimize the app window, it appears completely black if you open it up again.
Reported by windows_native_app/7.3.27 and 7.3.38.
Reported by #206597, #207427 and #206960 - report back once the issue is resolved.

**Comment by amulware** [comment]
So far there does not seem to be any indication of what causes this.

**Comment by kadrihvl** [comment]
One comment from the user: 
The only way to get the small black screen to go away and be replace with the normal timer screen is to go to Windows Task Manager and shut down the Toggl app. Then it will pop-up properly.

**Comment by egoroof** [comment]
Confirm on 7.3.87 dev. win10.
How to reproduce:
1. click close icon so it goes to tray
2. run the app again via desktop link or link in Task Manager
3. we got it! the app is black
4. if you now click to icon in tray the app is rendered correctly

**Comment by amulware** [comment]
@egoroof: Thanks for the steps! I can reproduce it, so we should hopefully be able to fix this soon.
