### ISSUE TITLE
Small freeze when stopping timer

### ISSUE THREAD

**Issue by amulware** [toggl/toggldesktop#1609]
Performance of the windows app has improved a lot over the last few weeks.

One of the things that still causes a small (but noticeable) freeze is stopping the timer.

From my analysis, stopping the time entry causes the following chain of events to happen:

```
DisplayTimeEntryList
    OnTimeEntryList

DisplayTimeEntryAutocomplete
    OnTimeEntryAutocomplete

DisplayMinitimerAutocomplete
    OnMinitimerAutocomplete

    OnStoppedTimerState (appears BEFORE the ui:D:Display.. line for some reason)
DisplayTimerState

    OnDisplayUnsyncedItems (no ui:D:Display.. call or similar appears in log)
```

These all happen on the same thread that called the Stop() function originally.
Most of the parts take very little time (0-5ms each, with OnStoppedTimerState at 15ms).

The real performance problem seems to arise from the sync at the end of it in some fashion. There seems to be a 180ms delay between `DisplayTimerState` and `OnDisplayUnsyncedItems`.

Do we know what causes this delay?

Proposed solutions:

In the ui:
1. make the Stop() call async. Pretty straight forward, and might just work. Might also cause there to be visible lag between the click and the various updates of the ui (might still be better than freeze?).

In the lib:
2. return after OnStoppedTimerState and do whatever needs 180ms on another thread, and call the syncing from there.
3. get rid of whatever needs 180ms.

Thoughts?

**Comment by IndrekV** [comment]
Needs lib investigation @tanel

**Comment by IndrekV** [comment]
Seems we have rewrote the stop part and sync is always done in separate thread.
