### ISSUE TITLE
Add timeline graph

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1616]
For screenshot and description see issue #1425

**Comment by amulware** [comment]
Would be useful to have the appropriate API (and if needed documentation) in place, so that I know how the data is formatted. (@tanel)

**Comment by tanel** [comment]
The API is not final yet, experimenting with the OSX UI, then will add docs and export to C# etc.

**Comment by amulware** [comment]
On hold for the time being.
