### ISSUE TITLE
Improved help

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1618]
Suggest support articles when user types feedback. Search the typed words from the support articles. 

Articles are fetched from https://support.toggl.com/webapp-help/

Up to 4 articles should be shown under the textarea. Clicking on the article opens up browser with the link.

**Comment by amulware** [comment]
Will proceed with ui design, but full functioning depends on #1620.

**Comment by IndrekV** [comment]
Also the feedback should take account where the user came from. For example if user came from edit view. We assume that content connected to edit view is more relevant. Basically we need to know what was the last opened view before user opened feedback.

**Comment by IndrekV** [comment]
I think there should be a file as a fallback and also we should get the latest data from KB with some interval.

Interval should be something longer like once a week or once a month.

**Comment by IndrekV** [comment]
Actually I think it is possible to add an `updated_at` param into the json so we can check if anything has been updated or something. In first implementation let's make it work without this.

**Comment by amulware** [comment]
Removed assignment and labels, since this issue is pretty much in limbo for the time being.
