### ISSUE TITLE
Save help articles into local database.

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1620]
Should be saved once a month.

Articles are fetched from https://support.toggl.com/webapp-help/

The data structure has 3 fields:
```
category:string
name:string
url:string
```

**Comment by tanel** [comment]
do we need to show category somewhere too?

**Comment by IndrekV** [comment]
We don't need to show category but we use category string to try to match the terms. We mostly try to direct the user to information connected to desktop application. Actually we probably won't need all the articles. We can create our own link page with links that are connected to desktop.

Also there is a sitemap that returns json of all articles on knowledge base. https://support.toggl.com/sitemap/

**Comment by tanel** [comment]
We could add the same json file to the app for lookup (so its easy to replace). Thoughts?

Or generate a code file with the JSON data. Maybe its safer or something.

We should not save the help data into database I think, as it must survive clearing out local data etc.
