### ISSUE TITLE
(Ubuntu) Linux design integration

### ISSUE THREAD

**Issue by orschiro** [toggl/toggldesktop#1622]
Dear all, 

Toggl Desktop provides a very good experience on my Ubuntu 15.10. 

However, I was wondering if the design/theme of Toggl could integrate into the (Ubuntu) Linux look (using GTK or Qt?) to make it look like more native (thus coherent) app. 

Any thoughts on this?

Thankfully,

Robert

**Comment by tanel** [comment]
Do you have specific examples, screenshots etc to give us hints what could be improved?

Kind regards,

**Comment by orschiro** [comment]
Dear @tanel,

Thanks for your quick comment. Below some examples that look very sluggish:

![image](https://cloud.githubusercontent.com/assets/170947/10758965/d8ca16c4-7cb4-11e5-840c-36df2de676b4.png)

![nimbus-image-1445951734268](https://cloud.githubusercontent.com/assets/170947/10759013/3596627c-7cb5-11e5-93aa-1f39330047cd.png)
![nimbus-image-1445951646526](https://cloud.githubusercontent.com/assets/170947/10759014/35afa62e-7cb5-11e5-9e41-0551c5eb2c4a.png)

**Comment by orschiro** [comment]
Dear all, 

I would like to make any progress on this design integration problem.

What graphical toolkit does Toggl Desktop use?

Maybe the users at AskUbuntu have an idea how to integrate Toggl into Ubuntu and other distributions properly. :)

~Robert

**Comment by IndrekV** [comment]
The linux app UI is created with Qt 5.5

**Comment by orschiro** [comment]
Thanks for the information @IndrekV!

Let's follow-up here: https://askubuntu.com/questions/666089/how-to-integrate-qt-software-like-focuswriter-telegram-toggl-desktop-or-rstudi

**Comment by IndrekV** [comment]
We've decided to keep the linux design universal as there are many distros out there and supporting multiple designs in linux seems like an overkill.
