### ISSUE TITLE
Autotracker disables itself on restart

### ISSUE THREAD

**Issue by amulware** [toggl/toggldesktop#1629]
It seems to be saved properly, and also works when enabled. When restarting the app, it seems to be disabled (both in the settings and by not working).

Can you take a look, @tanel?

**Comment by kadrihvl** [comment]
Reported with desk case #209096

**Comment by tanel** [comment]
The "autotrack" settings value is not used in the Windows UI

**Comment by amulware** [comment]
Setting has been fixed, and it also still works after restarting the app for me.
