### ISSUE TITLE
updater doesn't work

### ISSUE THREAD

**Issue by egoroof** [toggl/toggldesktop#1630]
version 7.3.87 dev on win10
I see geen text "Downloading vesion 7.3.93" but don't see any network activity. Also at the bottom of app there is label "Offline, no network". I don't use proxy.
![2015-10-28 19 59 58](https://cloud.githubusercontent.com/assets/2605831/10787943/21a01cae-7daf-11e5-973c-60f8c1dcf915.png)
![2015-10-28 20 09 25](https://cloud.githubusercontent.com/assets/2605831/10788054/cae4ff00-7daf-11e5-9cb8-3cafb419c1f4.png)

**Comment by IndrekV** [comment]
We have currently some issues with updates on the dev channel. We're looking into this.
