### ISSUE TITLE
7.3.91: error while loading shared libraries: libTogglDesktopLibrary.so.1

### ISSUE THREAD

**Issue by orschiro** [toggl/toggldesktop#1632]
Dear all, 

I just updated to 7.3.91.deb. However, this one seems to miss a shared library:

```
/opt/toggldesktop/TogglDesktop
/opt/toggldesktop/TogglDesktop: error while loading shared libraries: libTogglDesktopLibrary.so.1: cannot open shared object file: No such file or director
```

**Comment by tanel** [comment]
Hi! you need to run the script (TogglDesktop.sh) else the library load paths are not set.

**Comment by orschiro** [comment]
Good catch!

But still there is a problem with the desktop entry:

![image](https://cloud.githubusercontent.com/assets/170947/10848344/cf474432-7f1b-11e5-8e96-a0ee33ad3988.png)
