### ISSUE TITLE
Reminder not working properly

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1635]
The reminder function doesn’t appear to be working. I have it ticked to remind me every 30 minutes Monday - Friday between 9am and 6pm. I have not had the timer running for a couple of hours and I have not received a reminder.

mac 7.2.302

case 209714

**Comment by fonorobert** [comment]
desk case 209714

**Comment by tanel** [comment]
works in master. maybe the time format is not correct, clearing out the time fields could help

**Comment by IndrekV** [comment]
Needs more testing, users says that this is happening on multiple macs

**Comment by tanel** [comment]
Can the user check Notification Center (right upper corner on OSX screen) if the notification is really not there? I cannot reproduce the issue still. So I cannot fix this :/ at the moment

**Comment by tanel** [comment]
Another user reported this. Seeing reminder notification only once; then it goes away forever. Asking for more info.

Case 203338, 212754
