### ISSUE TITLE
Send user settings with feedback

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1636]
It would make it easier to see how the user has configured their account. Could be in a json file or just in text inside the email content.

**Comment by tanel** [comment]
sounds like a plan. i guess i can attach it to the email content so backend would not need any changes?

**Comment by IndrekV** [comment]
do it.

**Comment by IndrekV** [comment]
Settings can be also sent with JSON file as the endpoint accepts multiple files.

**Comment by IndrekV** [comment]
Files limit for post is 1 or 2mb (not sure exactly) and we should avoid going over it.

**Comment by tanel** [comment]
very good! attaching JSON then
