### ISSUE TITLE
Adding obm details to created_with

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1637]
When we start obm experiments it should be possible to declare a constant that is added to the created_with

example version: `windows_native_app/7.3.200-obm-99`

This should be platform specific as we can run different experiments at the time on different platforms.

obm number is manually entered and commited.
Can be empty in which case the `-obm-{nr}` is not added to created_with

**Comment by IndrekV** [comment]
First experiment number is 74

**Comment by tanel** [comment]
"obm number is manually entered and commited." <- so its a int constant somewhere in the source code?

**Comment by IndrekV** [comment]
Yes, it should also be platform specific, as we can run different experiments on different platforms at the same time.

**Comment by tanel** [comment]
maybe it should be set from the UI via lib api right after initializing it

**Comment by tanel** [comment]
?

like set_user_agent_obm_number or something

**Comment by IndrekV** [comment]
yes. `set_user_agent_obm_number` It is received with /me req so it makes sense to handle it in lib.

**Comment by tanel** [comment]
oh ok. so its the same obm number received with /me request. 

so i just attach the number to created_with, should i receive if from the backend.

so its not a constant and not platform specific in our code

**Comment by tanel** [comment]
if the app receives 73, included from backend, then the how long will the obm number linger on in user agent string? until its 73, not included? or another experiment starts?

**Comment by IndrekV** [comment]
experiment usually ends with a new release that doesn't have the experiment functionality.

**Comment by tanel** [comment]
but the experiment number is coming from backend, its not in the code? 

i'm thinking about sending the largest OBM experiment number, that has user included and that user has seen via UI. does it sound ok

**Comment by IndrekV** [comment]
the structure is as follows:
`“obm”: {“included”: true/false, “nr": integer, “actions”: stringarray/hasopmitempty/canbemissing}`

if included is false then nothing should happen. Nothing get sent to UI.

The issue is that there can be an array of experiments:
```
“obm”: 
[
{“included”: true/false, “nr": integer, “actions”: stringarray/hasopmitempty/canbemissing},
{“included”: true/false, “nr": integer, “actions”: stringarray/hasopmitempty/canbemissing}
]
```
We use only one of these experiments as the other are for web or mobile etc. I think we should add a platform based constant of the experiment number.

if obm struct has the same number as our const and the included param is true, send info to UI

**Comment by tanel** [comment]
wow its pretty complicated.
