### ISSUE TITLE
TogglDesktop: error while loading shared libraries: libTogglDesktopLibrary.so.1

### ISSUE THREAD

**Issue by zuernBernhard** [toggl/toggldesktop#1638]
Current Version on Ubuntu 14.04.3 LTS amd64 doesn't start (after update):

TogglDesktop: error while loading shared libraries: libTogglDesktopLibrary.so.1

**Comment by tanel** [comment]
Try to start the app by running TogglDesktop.sh, it will set up the library paths.

**Comment by zuernBernhard** [comment]
Yes that worked, thanks alot!
