### ISSUE TITLE
Permissions issues in linux auto-update tarball (7.3.119)

### ISSUE THREAD

**Issue by jrfoell** [toggl/toggldesktop#1639]
There seems to be some overly restricted permissions issues in the new TogglDesktop for linux:

<pre>
toggldesktop$ ls -al
total 3908
drwx------  7 justin justin    4096 Nov  3 03:20 .
drwxr-xr-x  9 justin justin   24576 Nov  3 14:13 ..
-rw-------  1 justin justin  267595 Nov  3 03:20 cacert.pem
drwx------  2 justin justin    4096 Nov  3 03:20 iconengines
drwx------ 11 justin justin    4096 Nov  3 03:20 icons
drwx------  2 justin justin    4096 Nov  3 03:20 imageformats
drwx------  2 justin justin    4096 Nov  3 03:20 lib
drwx------  2 justin justin    4096 Nov  3 03:20 platforms
-rw-------  1 justin justin     561 Nov  3 03:20 README
-rwx------  1 justin justin 3668171 Nov  3 03:20 TogglDesktop
-rwx------  1 justin justin     228 Nov  3 03:20 TogglDesktop.sh
</pre>

I can run the new TogglDesktop as root, but not as myself:

<pre>
$ ./TogglDesktop.sh 
QMetaType::registerTypedef: -- Type name 'QVector<' previously registered as typedef of 'QVector<AutocompleteView*>' [1036], now registering as typedef of 'QVector<GenericView*>' [1039].
Application font:  "Roboto,12,-1,5,50,0,0,0,0,0"
Log path  "/home/justin/.local/share/Toggl/Toggl Desktop/toggldesktop.log"
Bugsnag notify message: "Access to file denied"  context: "main"
QEventLoop: Cannot be used without QApplication
Bugsnag payload  "{\n    \"apiKey\": \"2a46aa1157256f759053289f2d687c2f\",\n    \"events\": [\n        {\n            \"app\": {\n                \"releaseStage\": \"production\",\n                \"version\": \"7.3.119\"\n            },\n            \"context\": \"main\",\n            \"exceptions\": [\n                {\n                    \"errorClass\": \"std::exception\",\n                    \"message\": \"Access to file denied\",\n                    \"stacktrace\": [\n                        {\n                            \"columnNumber\": 0,\n                            \"file\": \"somefile\",\n                            \"inProject\": false,\n                            \"lineNumber\": 123,\n                            \"method\": \"somemethod\"\n                        }\n                    ]\n                }\n            ],\n            \"payloadVersion\": \"2\",\n            \"severity\": \"error\"\n        }\n    ],\n    \"notifier\": {\n        \"name\": \"Bugsnag QT\",\n        \"url\": \"https://github.com/tanel/bugsnag-qt\",\n        \"version\": \"1.0.0\"\n    }\n}\n"

$ sudo ./TogglDesktop.sh 
QMetaType::registerTypedef: -- Type name 'QVector<' previously registered as typedef of 'QVector<AutocompleteView*>' [1036], now registering as typedef of 'QVector<GenericView*>' [1039].
Application font:  "Roboto,12,-1,5,50,0,0,0,0,0"
Log path  "/home/justin/.local/share/Toggl/Toggl Desktop/toggldesktop.log"
DB path  "/home/justin/.local/share/Toggl/Toggl Desktop/toggldesktop.db"
no script to run
displayUpdate update_url= ""
</pre>

**Comment by IndrekV** [comment]
I'm not able to reproduce this. It seems strange that the app cannot access a file that is inside the user directory. I think it is probably caused by the file being used by another process at the time when app tries to access it.
