### ISSUE TITLE
First user experience updates OBM

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1641]
In our first obm test we'll us a very simplified tutorial that only has one single screen.

- Describe text should be move a little bit to the left
- Start tracking text should be moved a little bit down (this would improve the separation of the two)
- end tutorial link should be removed

~~Clicking the green buttons sends out CTA that is handled in the lib.~~

![image](https://cloud.githubusercontent.com/assets/842229/10939240/dc4655a6-8308-11e5-83b5-d5718e3455ec.png)

**Comment by IndrekV** [comment]
The tutorial will be show to users on first login based on if they are included in the experiment or not. The data about user inclusion is in a obm param in /me request answer.

**Comment by IndrekV** [comment]
As the green button is pressed by everyone that sees the tutorial page theres no point in measuring that.

**Comment by amulware** [comment]
Screen implemented. Now waiting for #1643
