### ISSUE TITLE
OBM library functionality

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1642]
Library should be able to send out CTA actions to the server. The flag that indicates if user is part of the experiment comes with /me request data. Exact details are described in backend repo obm doc.

obm actions endpoint:
POST `toggl.com/api/v9/obm/actions`
input is JSON:
``` 
 {"experiment_id": int, "key": string, "value": string}
```
All the values of this object come from UI

**Comment by tanel** [comment]
do the experiments need to be saved to local database? or can they be dropped when user is offline?

**Comment by tanel** [comment]
will save to db
