### ISSUE TITLE
Show tutorial on first login of user is included in expriment

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1643]
info comes with `/me` request in format. There is an obm field.

Details in the backend docs.

First user experiment number is 74

If user is included in experiment they should be show the start tutorial when they login to toggl desktop the first time. Lib should send notification to UI. Currently the experiment works in Windows.

**Comment by tanel** [comment]
“obm”: {“included”: true/false, “nr": integer, “actions”: stringarray/hasopmitempty/canbemissing}

will be included in backend response.

how will i pass it on to the ui?

thanks

**Comment by IndrekV** [comment]
Send it with login callback that makes the UI show listing view.

**Comment by amulware** [comment]
I think it would be good to add a `run_experiment(int, other params maybe)` call, which we can reuse for all experiments in the future.

**Comment by tanel** [comment]
can we use the already there promotion thing in the lib?

at the moment it has

#define kPromotionJoinBetaChannel 1

toggl_on_promotion event

with

const int64_t promotion_type

parameter.

I wonder if 1 is already used by the OBM backend.

**Comment by IndrekV** [comment]
experiment number is 74 this is something that comes from obm and is setup in backend

**Comment by tanel** [comment]
ok then we can use the promotion stuff, as number 1 is not taken.

**Comment by tanel** [comment]
do we need to pass the actions to UI as well? or what does it do.

**Comment by IndrekV** [comment]
Yes, in the future we'll need the actions as well with the first experiment we don't need them in UI.
