### ISSUE TITLE
Logout process halted by linux app

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1645]
> Under XFCE, logging out of the UI will close the Toggl (v7.3.119 stable) window if open, but halt the logout process. A second logout operation completes normally. I suspect that Toggl is responding to XFCE&#39;s query/quit message as if the user had said &#34;no, don&#39;t logout&#34; but then closing cleanly.

Recap: When logging out on linux the TogglDesktop seems to halt the logout process

If it's not reproducible with ubuntu we shall close this as XFCE is not officially supported.

Probably caused by the fact that we don't close app when you close the main window because of the tray icon.

http://stackoverflow.com/questions/25108520/how-to-quit-qapplication-gracefully-on-logout
https://trac.transmissionbt.com/attachment/ticket/5206/0001-fix-Qt-tray-icon-causes-logout-cancelled-by-transmis.patch

http://www.qtcentre.org/threads/33320-Break-system-shutdown-when-in-my-program-I-want-minimize-instead-close

case: 211183

**Comment by basilevs** [comment]
In fact, application fails to exit, next attempt to launch application fails.
