### ISSUE TITLE
Tray icon missing

### ISSUE THREAD

**Issue by 876974** [toggl/toggldesktop#1646]
http://screencloud.net/v/m2Vi
I installed the Toggl 7.3.119 offered to me in deb file, which I was given previously installed software version. After installation I found that the icon appeared in the tray, which has no icon. My system is Elementary OS Freya.
I would also like to have the option in the program to be able to disable the tray icon.

**Comment by IndrekV** [comment]
Hi,

We have not tested the app with elementary OS so we can not guarantee that it works properly. We will look into this issue and see if there is an easy fix.

**Comment by IndrekV** [comment]
Same issue is reported to appear in xfce.

**Comment by mbojan** [comment]
Indeed, the same thing in xubuntu 14.04 (xfce4). Please fix!

**Comment by miloskroulik** [comment]
Same problem on Cinnamon 2.8.

**Comment by zajc** [comment]
Same issue on Xubuntu 15.10.

**Comment by dsvenss** [comment]
I'm experiencing the same issue!
My environment is 
Xubuntu 14.04
Window manager: Xfwm4
Qt version:
QMake version 3.0
Using Qt version 5.6.0

**Comment by mbaniasad** [comment]
same issue
cinammon 2.8.6

**Comment by stiig** [comment]
Same issue on Xubuntu 16.04
If i'll run app as sudo, everything works perfectly

**Comment by IndrekV** [comment]
@876974 I've created a fix for Xubuntu and Cinnamon. To make it also work with Elementary OS I would need the output of `echo $XDG_CURRENT_DESKTOP` on Elementary OS.

**Comment by stiig** [comment]
This fix does not work, icon still missing
http://i.imgur.com/L9h8mYu.png

**Comment by 876974** [comment]
@IndrekV echo $XDG_CURRENT_DESKTOP
Pantheon

**Comment by tobias-kuendig** [comment]
Same here. The icon is missing on Pantheon. Using version `7.4.7`

```
➜  ~  echo $XDG_CURRENT_DESKTOP
Pantheon
➜  ~  lsb_release -a
No LSB modules are available.
Distributor ID:	elementary
Description:	elementary OS 0.4 Loki
Release:	0.4
Codename:	loki
```

**Comment by Rayal** [comment]
The icon is also missing on Cinnamon. This issue has not been fixed!

**Comment by Rayal** [comment]
Perhaps you would be inclined to add this fix to the "Stable" build and the .deb files? Because I personally had to change the TogglDesktop.sh file to get this working. Seeing as how this issue was fixed about a year ago, shouldn't it already be in the working version?

**Comment by IndrekV** [comment]
@Rayal I just checked and the tarball has the fixed .sh and so should .deb file.

What is the version of the app you are using and what are the contents of the TogglDesktop.sh ?

What did you add to get TogglDesktop.sh working?

**Comment by Rayal** [comment]
The Tray Icon only showed up when I added the line
`DBUS_SESSION_BUS_ADDRESS=""`
to line 17

[TogglDesktop.sh.txt](https://github.com/toggl/toggldesktop/files/1302674/TogglDesktop.sh.txt)

**Comment by IndrekV** [comment]
Thank you for the details @Rayal . We were using `dbus-launch` that seemed to work in our tests. I also added `DBUS_SESSION_BUS_ADDRESS` to the mix to make it work more reliably.

Thank you for your feedback.
