### ISSUE TITLE
Pomodoro feature in Toggl Desktop?

### ISSUE THREAD

**Issue by orschiro** [toggl/toggldesktop#1648]
Dear all, 

Coming from [this](https://twitter.com/toggl/status/663649897745379328?cn=cmVwbHk%3D&refsrc=email) conversation on Twitter, is it possible to add the recent [Pomodoro feature](https://blog.toggl.com/2015/11/toggl-button-gets-pomodoro-timer/) to Toggl desktop?

Thankfully, 

~ Robert

**Comment by IndrekV** [comment]
We have the next 3 month planning meeting at the end of the month and we'll discuss it with the team.

**Comment by orschiro** [comment]
Dear @IndrekV,

Great, thanks for sharing your feedback!

~ Robert
