### ISSUE TITLE
Project removed from entry when syncing

### ISSUE THREAD

**Issue by fonorobert** [toggl/toggldesktop#1649]
to reproduce:
- start a time entry / edit a recently created one 
- assign a project to it
- wait for the app to sync
- the project will be removed, time entry is synced to sever without project

happens on windows, mac and linux as well

**Comment by kadrihvl** [comment]
Some related cases #212199, #212213

**Comment by IndrekV** [comment]
Seems like a lib issue. The data coming back from time entry creation is overriding the new update data.

**Comment by rbosneag** [comment]
Same thing happening to me on a Mac. I keep updating the project for a task and in a few seconds it gets cleared. 

I wonder if the fix will be able to put back the projects for all tasks without project or we have to update them again manually.

**Comment by Marwzoor** [comment]
This started to happen yesterday. (I can confirm that this is a problem)

**Comment by dandaka** [comment]
Same here (OSX) 7.2.150
http://take.ms/fhx4w

**Comment by Marwzoor** [comment]
My previous toggles are reset of their project randomly, it's really annoying.

**Comment by dandaka** [comment]
Had to switch to web interface, can't use desktop app at all :-1:

**Comment by rbosneag** [comment]
Maybe this is API related? I have OSX version 7.2.302,@dandaka has 7.2.150 so it's not about the client.
We need a fix soon, if @Marwzoor is right we may loose past toggls as well and this would be really ugly.

**Comment by amulware** [comment]
Small update: We are busy looking into this problem (and it indeed looks backend/api related).
There is no indication that the issue will affect time entries in any way other than messing up projects right now, so hopefully the damage will be limited.

We hope we can fix this soon and are very sorry for the inconvenience.
Thanks for your patience!

**Comment by refiito** [comment]
websocket return was fubar, fixed and should be syncing fine now.

**Comment by rbosneag** [comment]
@refiito indeed it seems to be working fine now. I'll get back with feedback in a few hours if anything changes
