### ISSUE TITLE
Autocomplete adds project and client names to description field

### ISSUE THREAD

**Issue by codeman38** [toggl/toggldesktop#1652]
The current Windows beta version of Toggl (7.3.119) has a bug in the autocompletion of tasks: when you click on a previous entry in the autocomplete dropdown, the app adds the names of the project and client to the end of the description.

**Edit:** This bug is also present in the dev channel (7.3.145).

**Comment by amulware** [comment]
This was fixed earlier today. However the windows buildbot is not working right now. The next build should include the fix.
