### ISSUE TITLE
Name field doesn't support quick project selection

### ISSUE THREAD

**Issue by HansCronau** [toggl/toggldesktop#1655]
Expected based on web interface:
I can type the name of a project in the name field, for quick selection of a project or a previous entry.

Actual behaviour:
In the name field I can type the name of a previous entry, but not of a project.

System specs:
Toggl Desktop 7.3.157 (beta)
Windows 7 64bit

**Comment by amulware** [comment]
Can you clarify if you mean the "What are you doing?" field in the timer, or the description field in the edit-popup?

For the first, project completion should work fine.
The latter currently only completes projects that have time entries with non-empty description in the last 9 days or so.

**Comment by HansCronau** [comment]
I meant the second, the description field. The "What are you doing?" field indeed works fine, unless the user already pressed Start, in which case it opens the edit-popup when clicked.

**Comment by IndrekV** [comment]
In the edit view there is a separate field for projects that's why it does not autocomplete projects in the description field.

**Comment by HansCronau** [comment]
@IndrekV:
Thanks for your reply.
I am aware of the separate field. But so there is in the web interface, which still creates the expectation with the user for this to work.

Personally I've become very accustomed to this handy feature.
