### ISSUE TITLE
Huge lag when autocomplete is loading everytime I go to add a new time entry description.

### ISSUE THREAD

**Issue by cnaccio** [toggl/toggldesktop#1660]
On windows 10 64bit when starting to type the description for a new time entry I experience an annoying lag with the autocomplete. The only reason I'm leaving an issue is because I've noticed that I'm starting to subconsciously avoid starting a new time entry if I can help it. I find myself resuming an old time entry whenever possible. I've been using Toggle for a while now so I have quite a bit of history; maybe there's something I can do to clear the history/cache? Either way I love Toggle, and so it's def not a deal breaker, but thought I'd pass along the feedback. As a consultant this is the best time tracking tool I've ever used; it's freaking amazing.  Thanks guys; really appreciate all the hard work!

**Comment by cnaccio** [comment]
Actually I found the clear cache option in the tool menu. After clearing the cache, and then logging back in everything is super fast again! Now that I think about it... it has been quite a long time that I've been using toggle on this computer without ever clearing the cache. Anyhow at least you now know there's a potential lagging issue that can occur over time. For the record my machine is pretty powerful; 2014 intel i7 with 16gb ram, and a Samsung ssd for what that's worth. Thanks again!

**Comment by IndrekV** [comment]
Thank you for letting us know we'll investigate this. I would appreciate if you could send us feedback from the app, that way we'll get the log files and have more data to go on.

@paul let's generate a lot of data and see at what point the autocomplete starts to slow down.

**Comment by codeman38** [comment]
Something that may possibly be related to this bug: I noticed that before clearing the cache, there are several weeks' worth of entries retained in the user interface (can't remember how many specifically), but after clearing the cache, only the past week's worth of entries is retained.

Is the entry list being automatically pruned to the last _n_ days of entries (for some value of _n_) during normal use? If so, maybe this should be more aggressive (or at least configurable)?

**Comment by IndrekV** [comment]
The sync get's entries from last 9 days. This works the same in the web app's timer page. Currently the data is not removed from the desktop application and this is what is making the autocomplete slow. Over time the autocomplete collection always grows and at some point slows down the app. The solution would be to define a timeframe that the app keeps. And all older entries are removed from the app.

**Comment by amulware** [comment]
This will be resolved with #1790.
