### ISSUE TITLE
Dash turns into square in Windows app

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#1667]
windows_native_app/7.3.157
windows 10 pro x64
Suggested reinstall, but it doesn't help.
Reported with English and Czech language setting.
Desk case #214175 and #214318
![capture](https://cloud.githubusercontent.com/assets/12407134/11237651/e7f36a60-8de9-11e5-9378-6b9c75dbe33b.png)

**Comment by fonorobert** [comment]
also case #214487

**Comment by nickfmc** [comment]
Just confirming same issue with the same environment as @kadrihvl

**Comment by node13h** [comment]
Same issue, same environment

**Comment by amulware** [comment]
Thanks for reporting the problem, @nickfmc and @node13h.

We are still investigating the cause of this issue.
Can you let us know what language you have your Windows set to?

**Comment by nickfmc** [comment]
Canadian English

**Comment by amulware** [comment]
Thanks!

From what I can tell it does not seem language related. Something that I noticed however, is that the people that have sent us screenshots of this problem have a different font inside Toggl Desktop.

At this moment, I do not know why that font cannot display the dash, nor why it is being used in the first place (we specify Roboto for all text in the app).

**Comment by nickfmc** [comment]
Funny you say that, I've had some issues with the same font in another app. I'll test uninstalling roboto tomorrow and reinstalling. Think the typekit version of the font messed me up before if I remember correctly.

**Comment by amulware** [comment]
Thanks for checking that out for us!

The thing is that we actually supply Roboto with the app. Maybe it finds the installed font and prioritizes it though.

**Comment by wearymadness** [comment]
When you say supply, do you mean it copies this font to the Windows fonts folder? If that is the case then I don't have the Roboto font there.

I'm using Windows 10 Pro 64 bit

**Comment by amulware** [comment]
@wearymadness The font is embedded in the executable.

It (unfortunately) also works fine for any computers I have access to right now, several with Windows 10 Pro 64bit.

**Comment by nickfmc** [comment]
I removed the Roboto font from windows font directory, uninstalled the toggl app rebooted and reinstalled the toggl app, No luck.

I should mention that this issue only started for me after updating the windows 10 threshold2 update.  I was using it right before I updated and it was fine, the first reboot after the update I noticed the issue.

**Comment by BeheSQ** [comment]
Hello all, I do confirm that this issue started right after upgrade to Windows 10 1511 (build 10586.11). Also I do not have any Roboto installed, so Toggle is definitely using the embedded one.

**Comment by IndrekV** [comment]
Might be connected to this issue with Roboto font https://github.com/google/roboto/issues/37
Maybe we should update the font files @amulware

**Comment by dicetomato** [comment]
Same issue here. I'm using a Surface Pro 2, with 150% DPI.

**Comment by amulware** [comment]
Hey everyone, we just updated the Roboto font files in the hopes that this may help with the problem.

It would be great if you could try updating the app to the latest dev version and report if it helps.
You can do this by selecting the dev release channel in the program's About window. It should start downloading the update a few seconds later. Once it's done (it will say so in the same window) restarting the app will install the update.

Thank you all for your patience, and help!

**Comment by amulware** [comment]
Alright, another fix that seems to do the trick. (I was able to reproduce the bug after updating to the version of windows some of you mentioned above)
The fix is already in beta, so feel free to check out to the beta release channel!

**Comment by BeheSQ** [comment]
Indeed, fixed in 7.3.189. 

Thank you very muych!

**Comment by korg250** [comment]
I can also confirm that 7.3.189 fixed the issue. It also fixed the issue of not showing space between the time number and sec/min.

Thanks!

**Comment by nickfmc** [comment]
Fixed here!
