### ISSUE TITLE
Toggl Windows 7.3.157 not launching

### ISSUE THREAD

**Issue by oilvier** [toggl/toggldesktop#1668]
Hi,

My TogglDesktop is not launching anymore. When i double click on the icon nothing happens.
I've completely remove the app and download it again from the site and it's I have the same problem.

**Comment by IndrekV** [comment]
Please contact support@toggl.com and send log files. Log files are usually at `C:\Users\<username>\AppData\Local\TogglDesktop\toggldesktop.log`

**Comment by oilvier** [comment]
OK, thanks I'll do that
