### ISSUE TITLE
Two timers running at the same time

### ISSUE THREAD

**Issue by liisa105** [toggl/toggldesktop#1676]
1) 'Subscription' entry was running
2) Clicked 'continue' on a previous entry
3) Changed project and description in the window that popped open ('Planeerimine')
--> it looks as though 2 timers are running at the same time:

![image](https://cloud.githubusercontent.com/assets/7447267/11361940/50beda62-9299-11e5-9cc4-abf0a320d420.png)

About:
![image](https://cloud.githubusercontent.com/assets/7447267/11361972/849309d0-9299-11e5-9847-391df682b5f8.png)

**Comment by liisa105** [comment]
When I clicked 'Stop', it stopped both time entries with the time that had passed, as though the timers had indeed been running at the same time:
![image](https://cloud.githubusercontent.com/assets/7447267/11362146/919d2556-929a-11e5-8eee-69c61dbf1b50.png)

**Comment by berlic** [comment]
Faced the same issue with Mac App today – noticed that when it was showing more total hours than I was awake.
Seems like a bug in this workflow (but I cant reproduce it):
1) Working on project A
2) Click "new" and fill in new task and new project (project X)
3) Continue to work on project A

After this I had the following time records:
```
Project A    ***********************
Project X              ******
Project A                    *******
```
The first record for Project A hasn't stopped when Project X has been started and then stopped with second record for Project A.

Very weird. Forced to look all the way back for such glitches to be sure that my bills to clients are correct :sob:

**Comment by berlic** [comment]
Found another overlap (second record for task A overlaps first record for the same task):
![_ _2015-11-29_ _22_30_49](https://cloud.githubusercontent.com/assets/2950241/11459507/54c2fa40-96e9-11e5-8f1e-00bb46c8868f.png)

Suspect the issue with idle detection. Maybe "Keep idle and continue" has some problems?
