### ISSUE TITLE
"Invalid access: Can not convert empty value" after upgrading to El Capitan

### ISSUE THREAD

**Issue by cfenollosa** [toggl/toggldesktop#1678]
Hi,

After the upgrade, Toggl Desktop doesn't let me log in, the following message appears:

"Invalid access: Can not convert empty value."

The username/password are correct, as I can log into the website without any issues.

Thanks

**Comment by cfenollosa** [comment]
Deleting the app and related plists, and then reinstalling, does not help.

The message appears upon app startup, in a banner on the top of the window, and doesn't seem to be related to the actual login process.

**Comment by IndrekV** [comment]
It might be that the El Capitan upgrade messed up the local database. Please see this article on how to clear the local data and get a fresh start https://support.toggl.com/clearing-the-local-data-from-toggl-desktop/#mac

**Comment by cfenollosa** [comment]
Thank you, this actually worked:

```Open Terminal and type the following then hit Return: open ~/Library/Application\ Support/Kopsik
In the Finder window that opens up delete every file and folder from within the Kopsik directory.```
