### ISSUE TITLE
Blue project color shows as grey

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1679]
Blue Colour for Projects does not show for TogglDesktop. It is instead greyed out. Here I have ‘Web’ project in colour blue and it shows correctly on the website however within the application it is always greyed out.

**Comment by kadrihvl** [comment]
Has been reported also by a Windows user (windows_native_app/7.3.157-obm-73). Desk case #216524.

**Comment by IndrekV** [comment]
Will be fixed in backend. Issue was with websocket project data not including color param, if the value of color was 0 ( in our case light blue color code is 0 )
