### ISSUE TITLE
Investigate syncing issues (websocket and regular)

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1680]
Time entry still runs in the app although it has been stopped in the web app.

Reported on mac.

**Comment by IndrekV** [comment]
Connected to #1665

**Comment by IndrekV** [comment]
Log in 243148

**Comment by IndrekV** [comment]
We should add more verbose error messages for websocket disconnects.

**Comment by kadrihvl** [comment]
Reported also with #243338 (has logs if needed).

**Comment by IndrekV** [comment]
duplicate of #2051
