### ISSUE TITLE
Add simplified Pomodoro Timer

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1683]
The idea is to allow user to add notification when the pomodoro timer set time has ran out.

 - [x] Add setting checkbox `Enable Pomodoro Timer`
If checked (show/enable) another setting `Pomodoro timer interval`
 - [x] If Pomodoro is enabled the timer is started every time timer is started in the app.
 - [x] When Pomodoro timer has ended:
* show notification and button `stop`

**Comment by alexbaumgertner** [comment]
:+1: 
May be linked with https://github.com/toggl/toggldesktop/issues/1648

**Comment by wcjr** [comment]
looks like @tanel 's taking a stab at it in Feb.  Thanks you all!

**Comment by yangchenyun** [comment]
+1 for this feature, would replace my current pomodoro timer.

**Comment by mateialexandru** [comment]
+1

**Comment by mateialexandru** [comment]
This will help me stick to Toggle forever :D not to talk about having it also on Android :+1:

**Comment by IndrekV** [comment]
We have planned to start developing this in the end of January. Until then you could use Toggl Button Chrome extension as it already has Pomodoro timer feature. [Get Toggl Button!](https://chrome.google.com/webstore/detail/toggl-button/oejgccbfbmkkpaidnkphaiaecficdnfn?hl=en)

**Comment by mateialexandru** [comment]
I just read a nice blog post about Toggle Button, thank you for the feedback! Can't wait to have it on Android and desktop! :cool:  I can handle 3 more months  :)

**Comment by amulware** [comment]
Windows implementation is looking good now. (Still on `pomodoro`)

**Comment by IndrekV** [comment]
Version 2 updates are in issue #1789
