### ISSUE TITLE
Updater gives "Access denied" when starting app after update.

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1693]
When clicking `Restart App` in the about view. App quits, installs the update and tries to start the new app. This gives the error `Access denied` in a popup. Closing popup and opening the app manually works.

Maybe we should investigate why this happens and if we can somehow try to still open the app when this error occurs.

Happened when I updated from latest stable (7.3.157) to latest dev (7.3.184)

**Comment by amulware** [comment]
I cannot reproduce the problem. For me the app restarts fine.

However, I imagine that the problem may be related to the updater trying to update the app while it is still running.

**Comment by IndrekV** [comment]
In that case the error message should be more clear and actionable for the user.
"Unable to automatically start the app. Please start the app manually" or something similar.

Should probably be more compact.
Maybe `Start the updated app`

**Comment by amulware** [comment]
I agree that the message should be clearer. However, this case would also occur if the app did not manage to shut itself down properly. In which case starting the app again will not do anything.

Either way, we should take a closer look.

**Comment by IndrekV** [comment]
I've seen this issue multiple times and always the update is installed and manually starting the app has worked.

**Comment by amulware** [comment]
Are you sure the update is already installed when you see the notification? I suspect that it only installs the update when you then start the app manually.

**Comment by IndrekV** [comment]
I'm not sure so anyhow this text should cover it `"Unable to automatically start the app. Please start the app manually"`
