### ISSUE TITLE
Desktop app prevents Windows Taskbar from auto-hiding

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#1699]
Sometimes Toggl Desktop appears to keep Windows Taskbar from auto-hiding. 
The Windows taskbar can be set to'auto-hide' so it only appears when you move your mouse to the edge of the screen where the task bar is located. This maximizes screen real estate and cleans up the appearance of the desktop. The Taskbar will 
pop whenever there is a warning msg or pop-up from a running application (a task reminder from Outlook, for example). Toggl Desktop is triggering something to cause Windows to drop the taskbar. Stopping Toggl Desktop and restarting resolves the issue for a while. 
Windows 10, windows_native_app/7.3.157
Desk case with logs #217208.

**Comment by amulware** [comment]
Was able to reproduce this once, but not since then.
In that one case, the taskbar popped up with the autotracker notification, and did not return to normal afterwards. May be unrelated. Currently not occurring again under what seem to be the same conditions.
