### ISSUE TITLE
Crash/Segfault - Cannot run on Kubuntu 15.04 since after version 7.2.66

### ISSUE THREAD

**Issue by kingIZZZY** [toggl/toggldesktop#1704]
I have Kubuntu 15.04 x64
Neither the standalone tarball nor the .deb installation has ever worked without crash/segfault ever since the app started using a shell script to setup library path (version 7.2.66 still apparently works running the executable directly)

**shell output**:
bash> /opt/toggldesktop/TogglDesktop.sh 
QMetaType::registerTypedef: -- Type name 'QVector<' previously registered as typedef of 'QVector<AutocompleteView*>' [1036], now registering as typedef of 'QVector<GenericView*>' [1039].
Application font:  "Roboto,12,-1,5,50,0,0,0,0,0"
kf5.kiconthemes: "Theme tree: (Breeze)"
Log path  "/home/kingIZZZY/.local/share/Toggl/Toggl Desktop/toggldesktop.log"
DB path  "/home/kingIZZZY/.local/share/Toggl/Toggl Desktop/toggldesktop.db"
Segmentation fault (core dumped)

**/var/log/syslog entry**:
Nov 30 10:05:45 kingIZZZY-box kernel: [  860.681303] TogglDesktop[3539]: segfault at 0 ip           (null) sp 00007fffe2192aa8 error 14 in TogglDesktop[400000+364000]

**Comment by kingIZZZY** [comment]
So uh, nothing?

Can anyone at least tell me what additional things I can try or info I can gather that can help identify the problem here?

Is it perhaps a library/package I installed for the old Toggl which does not agree with the latest one? Do I need to install / uninstall anything? Can I generate a list of libraries I have so the offending one can be found? Other?

**Comment by IndrekV** [comment]
I've looked into it and couldn't reproduce it right now. It might be specific for your system.

Try running this command to see if it reveals more details:
`addr2line -e TogglDesktop`

Frequent segmentation faults can also refer to bad memory so checking with memtest would be necessary  http://www.memtest.org/

If you get the details then please send them to support@toggl.com and mention that they are for Indrek
that way I get them faster. It would be good if you could send the feedback from the app as that way additional details are send with the email.

**Comment by kingIZZZY** [comment]
Thanks for following up.
I replied through the app (the working version 7.2.66 one that is) that I tried the addr2line command you suggested but nothing happens, it just hangs indefinitely...

I also attached an image of as much info I could show about my setup; the working 7.2.66 app, the .deb package of the latest version with its details shown in QApt, the installation folder, and the command line with the above command.

What else can we try please?

**Comment by kingIZZZY** [comment]
Someone suggested I try showing you guys some `strace` output:

strace TogglDesktop: http://paste.ubuntu.com/13880949/
strace TogglDesktop.sh: http://paste.ubuntu.com/13880991/
Manually setup LD_LIBRARY_PATH, then strace TogglDesktop: http://paste.ubuntu.com/13881131/

**Comment by IndrekV** [comment]
Thank you for the details. On thing that could also cause strange behaviour is when local database has error in it. I would suggest you to remove local database and see if that helps.

Remove the Toggl Desktop directory 
`/home/<your user name>/.local/share/Toggl`

**Comment by tanel** [comment]
confirmed on Kubuntu. crashes while hooping up the app menus. looks like something Kubuntu specific.

**Comment by kingIZZZY** [comment]
Well whadyou know, after upgrading to Kubuntu 15.10 the latest TogglDesktop 7.3.119 installed from .deb seems to be working fine. Still might be worth looking into for others experiencing the issue though.

**Comment by tanel** [comment]
Thanks for reporting this! It might be some Qt and Kubuntu 15.04 specific issue then.

**Comment by tanel** [comment]
Issue is solved by upgrading Kubuntu. Will mark as closed at the moment and will advise users who experience the issue to upgrade.
