### ISSUE TITLE
Invalid access: Can not convert empty value.

### ISSUE THREAD

**Issue by Aproducktion** [toggl/toggldesktop#1712]
I am unable to login using TogglDestop OSX version 7.3.177. I get the error Invalid access: Can not convert empty value.
![screen shot 2015-12-01 at 9 53 45 am](https://cloud.githubusercontent.com/assets/1811675/11509178/7c53fb62-9811-11e5-81fd-7695ae791cb8.png)

**Comment by IndrekV** [comment]
This is already fixed in master with 98121dc5f4f1d9b7c0b701787f490a0c885755ba but not released. Clearing the local cache would be a temporary fix until this is released. We plan to release it to beta channel today.

**Comment by Aproducktion** [comment]
##### Thanks @IndrekV , that fixed it the issue :+1: 
-------
For anyone else having this issue follow this guide: [Clearing the local data from Toggl Desktop](https://support.toggl.com/tag/cache/)

**Comment by IndrekV** [comment]
This is also fixed in the latest stable windows release. (7.3.199)
