### ISSUE TITLE
Bulk edits load slow

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1715]
If time entries are changed in bulk ( removed or edited )  the items appear or are removed from the list one by one which is slow and seems really strange.

**Comment by tanel** [comment]
does the bulk editing happen on the web?

**Comment by IndrekV** [comment]
Yes, I deleted a punch of entries from the web timer view. I'm not sure but maybe websocket sends the info on by one and that is what is triggering this.

**Comment by tanel** [comment]
thx will check it out

**Comment by tanel** [comment]
confirmed as websocket action. not sure if we can improve it on our side
