### ISSUE TITLE
Highlight colour makes text unreadable with Windows Classic theme

### ISSUE THREAD

**Issue by fonorobert** [toggl/toggldesktop#1719]
If the Windows Classic theme is used in W7, the mouse-over blue bar in, for example, the Options (cogwheel) list will be so dark as to obscure the black text. A similar case is this Send Feedback form where the drop-down-list also has a near black-blue mouse-over color, hiding the text.

![toggl](https://cloud.githubusercontent.com/assets/6963710/11560981/54850fcc-99c4-11e5-944e-700f9af7db5f.png)

**Comment by amulware** [comment]
We may be able to override the system highlight colour to a lighter blue. If not, we may have to completely restyle these controls.

**Comment by amulware** [comment]
This fixes the combo boxes in the about window, and the send feedback window. The only issue remaining is the highlight in the context menu.
