### ISSUE TITLE
Linux app crashes if second screen is disconnected

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1721]
linux_native_app/7.3.119

> Every time I disconnect my laptop from a second monitor, the Toggl desktop app crashes. I’m running Ubuntu 15.10 with Unity.

**Comment by kadrihvl** [comment]
Logs in desk case #226794.

**Comment by MartinBriza** [comment]
Pretty old issue, most likely related to Qt, most likely fixed, too.
