### ISSUE TITLE
pasting text into os x "what are you working on?" box starts new time entry

### ISSUE THREAD

**Issue by cborgia** [toggl/toggldesktop#1724]
this was not the case before, and it's really annoying. everytime i paste text into a new (or already running) time entry, it stops the current time entry and starts a new one.

**Comment by danfbu** [comment]
This same problem happened to me on version 7.3.177, but doesn't anymore with version 7.3.197. I'm using OS X 10.11.1.

**Comment by IndrekV** [comment]
Duplicate of #1687
