### ISSUE TITLE
Menubar timer is not in line with other text on menubar

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1749]
It seems to be a bit lower than other text.

**Comment by Leland** [comment]
On High Sierra it's perfectly in line with the time

<img width="165" alt="screen shot 2018-01-31 at 12 23 07 pm" src="https://user-images.githubusercontent.com/714017/35637198-867c824a-0681-11e8-93f7-f912c3a0b71e.png">

Can probably be closed.

**Comment by IndrekV** [comment]
Jep, seems to be aligned just fine with the latest version.
