### ISSUE TITLE
Labels with the same name across projects/organisations do not show up

### ISSUE THREAD

**Issue by omnidan** [toggl/toggldesktop#1756]
I have two `Social Media` labels, one for private social media and one for work. On toggl.com they both show up, one under my private project, the other under my work project.

In the Toggl Desktop app (OS X) only one of them shows up in the search. Even in the full list, the label is missing from the second project (work) and only showing up in the first (private).

**Comment by amulware** [comment]
We had some fixes with regards to projects and clients of the same name. Labels may possibly still use the old (and wrong) comparison for equality.

**Comment by IndrekV** [comment]
@omnidan Please specify the issue. By labels do you mean tags or tasks? Also it would help if you could send us feedback from the app and mention that it's for Indrek. That way I can get more details and can investigate further.

**Comment by omnidan** [comment]
@IndrekV I mean the project field on a task: ![https://i.imgur.com/bHxd3fy.png](https://i.imgur.com/bHxd3fy.png)

I have multiple "project-groups"/teams (the ones in CAPS) with the same project names (e.g. "Social Media"), but only one of the projects shows up, the other teams project just doesn't show up. (it does on toggl.com, though)

I sent feedback from the app too :smiley: 

Let me know if you need anything else.

**Comment by kadrihvl** [comment]
Desk case with logs: #237140

**Comment by IndrekV** [comment]
@omnidan It seems that for some reason the list currently only accepts unique items and that is why it doesn't show multiple project with the same name. I will be working on a fix for this.

**Comment by IndrekV** [comment]
fixed with #1768
