### ISSUE TITLE
UI debug information not written to log when compiling in Release

### ISSUE THREAD

**Issue by amulware** [toggl/toggldesktop#1763]
When compiling the Windows application with the `Release` build configuration, none of the UI debug information is written to the log file, which makes debugging certain issues very difficult.

This used to be different, so something must have changed.

When compiling in the `Release_VS` build configuration, it works fine. I am at the moment not sure what makes the difference here.
As far as I can tell, the only thing that `Release_VS` changes is deactivating the updater, and effectively disabling bugsnag.

**Comment by IndrekV** [comment]
We should determine at what point this broke. Is it working on the latest stable.

**Comment by amulware** [comment]
For me it does NOT work on stable (7.3.199).

**Comment by amulware** [comment]
I did a search for the build which broke this, and it seems to be commit `6ea73bb`. Before that commit all the debug info shows up, afterwards it does not. I do not have any idea how that commit influences the logging. Will continue to investigate.
