### ISSUE TITLE
Allow day-collapsing with keyboard shortcut

### ISSUE THREAD

**Issue by amulware** [toggl/toggldesktop#1765]
Have to decide on shortcut/key and exact behaviour.

**Comment by IndrekV** [comment]
For me LEFT and RIGHT arrow make sense. For example pressing LEFT on any of the entries will collapse the day of this entry. The difficult part is how to open the day with a key. This would mean that the day is focusable.

One way would be to make day focusable when it is collapsed and not focusable when it's not collapsed.

**Comment by amulware** [comment]
Currently, keyboard navigation does not skip collapsed days, and instead expands days if the user navigates into them. It looks like we have to change that.

I think that making collapsed days focusable is a good solution.

I would also propose another shortcut: Ctrl/Shift + Left, to collapse all days, (and maybe also one to expand all).
That way the user can get a quick overview of the last week, etc.

**Comment by IndrekV** [comment]
yes, good idea about collapse/uncollapse all.
