### ISSUE TITLE
Project entry box frequently fails to autocomplete

### ISSUE THREAD

**Issue by Morgon** [toggl/toggldesktop#1766]
When attempting to apply a Project to a new task, very often (~80% of the time), it fails to autocomplete on the first try. In order to fix it for that particular task entry, I have to click the Project dropdown to get all of them to show, and then I can filter using autocomplete. 

OSX 10.11.2
TogglDesktop 7.3.197

**Comment by IndrekV** [comment]
Please try clearing the cache to see if helps. It might be that with time the autocomplete database has grown very big and this is causing issues. https://support.toggl.com/clearing-the-local-data-from-toggl-desktop/#mac

**Comment by Morgon** [comment]
Apologies for not following up. Clearing the cache did work mostly. It's more responsive overall, but still occasionally fails to autocomplete. Unfortunately, I haven't been able to work through any definitive steps to repeat it, so it will have to do for now.

Thank you
