### ISSUE TITLE
Check Autotracker on windows

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1772]
Users have reported that Autotracker does not work properly on Windows. Example was given with phrase `outlook`

We have to double check if it is somehow connected to the fact that autotracker uses data collected by timeline. So maybe it is dependent on timeline. If timeline is disabled the data is not collected and autocomplete may not work.

**Comment by amulware** [comment]
It works just fine for me in the latest beta (and with timeline disabled). If there are specific programs that do not work, that has to be investigated individually (and fixing it may be impossible/very difficult).
