### ISSUE TITLE
Time entry locking

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1774]
There are two settings:

- Locking enabled flag
- Date of locking

If the setting is enabled and date is set, it should not be possible to edit entries that have been stopped before the locking date. Maybe we should add lock icon to indicate this in the UI.

Also handle the case if the edits are made offline while actually the time entries are locked. In this case an error is received upon trying to sync.

This should work so only for regular users.

**Comment by amulware** [comment]
This data has to be gotten from: `v9/workspaces/<wid>/preferences` which will include `{"report_locked_at":01-01-0000}`  if the workspace has a lock date.

**Comment by amulware** [comment]
As far as I can tell, this is all implemented on `business`. Currently the code does NOT make a difference for admin users however. Are admins really supposed to be able to ignore these settings?

**Comment by IndrekV** [comment]
Yes, admins can edit everything all the time.

**Comment by amulware** [comment]
All done on `business`. Including windows ui. Only OSX ui is left, see #1775.
