### ISSUE TITLE
Starting time entry should not cause OnApp event

### ISSUE THREAD

**Issue by amulware** [toggl/toggldesktop#1782]
Needed for #1764

**Comment by IndrekV** [comment]
Seems to be windows specific issue.

**Comment by amulware** [comment]
It looks like the default setting for 'show window on shortcut' is set to TRUE, and that this is checked on every start.
We agreed to include a bool parameter in the Start/Continue(/Stop?) calls to specify (/override) whether the window should be/is allowed to be shown.

**Comment by amulware** [comment]
Api changes implemented on `win-mini-timer`.
