### ISSUE TITLE
Customize Toggl Desktop dmg file icon

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1787]
More info:

http://stackoverflow.com/questions/61635/beautifying-an-os-x-disk-image
https://iconfactory.com/home/show/1151

**Comment by NghiaTranUIT** [comment]
IMO, I prefer [create-dmg ](https://github.com/sindresorhus/create-dmg) since it's straightforward and active OSS 🥇

**Comment by NghiaTranUIT** [comment]
We could close this ticket, since it's done here https://github.com/toggl/toggldesktop-branding/pull/27
