### ISSUE TITLE
Can you compile linux 32bit app ?

### ISSUE THREAD

**Issue by palkoc** [toggl/toggldesktop#1788]
Can you please compile linux 32bit version as well?  The application behaviour is "strange" when I compile it from master on xubuntu (i686)...

Thnx

**Comment by IndrekV** [comment]
We have currently no plans to release 32bit versions of Toggl Desktop apps.

**Comment by IndrekV** [comment]
By default the app compiles to use the testing environment. See this article on how to make it compile for live servers https://github.com/toggl/toggldesktop/wiki/Building-Toggl-Desktop-from-source-for-usage-with-live-servers
