### ISSUE TITLE
Pomodoro timer v2

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1789]
Development in branch: `pomodorov2`

- [x] _[lib]_ Stop timer when Pomodoro time ends
- [x] _[osx]_ Notification actions are `Continue latest`, `Start new`
- [x] _[osx]_ Play sound when Pomodoro time ends (should be a system alert sound)
- [x] _[win]_ Notification actions are `Continue latest`, `Start new`
- [x] _[win]_ Play sound when Pomodoro time ends (should be a system alert sound)

**Comment by ducedo** [comment]
Really appreciate that you're adding Pomodoro support for OS X. I downloaded the latest release to test it and I'm not sure if this is the correct place but I've got a few ideas:

* Pomodoro should be counting down to 0 in the menu bar, not up.
* When it reaches 0, it should stop and not continue (settings?).
* An alarm should go off so you don't miss it when sitting next to the computer.
* The notification could be bigger and continue to show until you take action.

Now it mostly works as a silent popup every minute when going over the time. In my view, the Pomodoro technique is carved in stone. When it reaches (say) 25 minutes, then you should stand up and take your break before continuing. The app Tadam mostly works like I wish the Pomodoro in Toggl would work.

**Comment by IndrekV** [comment]
Started development in branch `pomodorov2`
