### ISSUE TITLE
Add "load more" functionality to lib

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1792]
Request needs two parameters:
```
*end_date -> should be the date of the oldest time entry currently available
*num_of_days -> 5
```
end date should be in format `2016-01-20T11:04:48+02:00`. Maybe also urlencoded, but we have to double check.

**Comment by amulware** [comment]
This is currently waiting for implementation of the required v9 api by the Toggl backend team.

**Comment by amulware** [comment]
Implemented on `load-more-button`.
