### ISSUE TITLE
SEGV on Ubuntu

### ISSUE THREAD

**Issue by ppslim** [toggl/toggldesktop#1793]
I have hit a SEGV whilst using Toggle Desktop on Ubuntu 14.04 LTS.

TogglDesktop crashed with SIGSEGV in getFocusedWindowInfo()

I have the full core if required.

[_opt_toggldesktop_TogglDesktop.1000.crash.txt](https://github.com/toggl/toggldesktop/files/97261/_opt_toggldesktop_TogglDesktop.1000.crash.txt)

**Comment by IndrekV** [comment]
What version of the app are you using? Did you compile the app itself or downloaded packaged app?

**Comment by ppslim** [comment]
I downloaded the deb from your website as available two days ago.

App reports 7.3.119

**Comment by IndrekV** [comment]
We've release a new stable version today. Please download the latest version to see if it has this issue fixed. If issue still appears try to remove local database files. More info in this article https://support.toggl.com/clearing-the-local-data-from-toggl-desktop/

**Comment by ppslim** [comment]
I have downloaded and I am presently testing.

**Note:** Your download page still reports the version is 7.3.119
