### ISSUE TITLE
Delete issue when 'On Top Of Other Windows' setting

### ISSUE THREAD

**Issue by chastings77** [toggl/toggldesktop#1796]
I am not able to delete an entry whenever I have the 'On top of other windows' setting checked.  It appears that the delete confirmation window is behind the main window so I am unable to confirm since the main window is always on top.  Not sure that it matters but my setup is with dual monitors and Toggl Desktop is in the top left corner of my left monitor when I delete.

**Comment by IndrekV** [comment]
What operating system are you using?

**Comment by chastings77** [comment]
Windows 7 ultimate
![image](https://cloud.githubusercontent.com/assets/779211/12481138/adc99968-c00c-11e5-9dd6-e610b3274ce5.png)
