### ISSUE TITLE
Timeline events showing up as "Unknown program" on web app timeline graph

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1801]
User is on Windows 7
More info: 245263

Notify user of discoveries.

**Comment by wefixitgr** [comment]
Hello, came here while googling for the same problem...
I've got the same problem too since forever!

I'm on _Windows 8 Pro_. While it shows correct window and title for most of my programs it always shows Chrome as unknown program and since I'm a web-dev myself its my most used window!

My mac plays very nice though and shows chrome usage correctly with tab titles and everything.
Let me know if you need any debug info...

**Comment by amulware** [comment]
Did some debugging, and looking from inside the app the data seems to be recorded fine.

For example, I get these entries (note how chrome seems to work fine):

```
file: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
title: Timeline events showing up as "Unknown program" on web app timeline graph · Issue #1801 · toggl/toggldesktop - Google Chrome

file: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
title: Timer • Toggl - Google Chrome

file: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe
title: TogglDesktop (Running) - Microsoft Visual Studio

file: C:\Program Files\Sublime Text 3\sublime_text.exe
title: C:\Users\amulware\AppData\Local\TogglDesktop\toggldesktop.log - Sublime Text
```

**Comment by amulware** [comment]
Fixed for unknown programs to not be included in timeline data anymore. Errors are logged to log file once per run. So far found no reliable way to reproduce this behaviour.

**Comment by wefixitgr** [comment]
I don't know if its related to this but I got a blank timeline today.
I have attached my log file, I'm on beta channel.

**Comment by amulware** [comment]
Thanks @wefixitgr! There are indeed some errors in the log related to the timeline. We don't have a solution right now, but hopefully this will help us figure out what is going on.

**Comment by wefixitgr** [comment]
No prob @amulware! I'm on the forsaken version of Win8 Pro on the problematic machine. :stuck_out_tongue_closed_eyes: 

Let me know if you need anything else in terms of logs, system info or whatever in order to help squash this bug!

**Comment by alapolloni** [comment]
FYI.  I'm also seeing the same thing if you need further log files/testing.
