### ISSUE TITLE
Pinning Ubuntu Desktop icon between stable releases

### ISSUE THREAD

**Issue by ppslim** [toggl/toggldesktop#1803]
Per #1793 I have switched from 7.3.119 to 7.3.247. I have downloaded and used the provided .deb

I have the icon for Toggle pinned to the launcher. After the upgrade, on clicking the icon it launched, but was not pinned to the same icon (thus the icon is duplicated on the launcher)

**Comment by MartinBriza** [comment]
With the current releases, the desktop file is located in a standard location and it does not change between releases. This issue is now resolved.
