### ISSUE TITLE
Crash after calling stop in the Toggl API

### ISSUE THREAD

**Issue by greenrd** [toggl/toggldesktop#1804]
I have written a little script which calls the Toggl REST API to stop the current interval and locks the screen. When I run my script, Toggl Desktop often crashes. 7.3.247 on Linux (Fedora).

**Comment by greenrd** [comment]
Oops, I'm terribly sorry, this wasn't a crash - I was killing it in my script! Sorry for the invalid bug report!

**Comment by greenrd** [comment]
Sorry - it actually does crash - I confused the crash and the killing in my script. So this is a bug.

**Comment by IndrekV** [comment]
I tried to replicate this multiple time but was not successful. I tested with stopping the timer with one of the other Toggl tools (Toggl Button and web app)
