### ISSUE TITLE
Workspace projects don't match the ones on toggl.com

### ISSUE THREAD

**Issue by orschiro** [toggl/toggldesktop#1805]
Dear all, 

I noticed that not all my workspace projects found under toggl.com are shown in the dropdown menu of Toggl Desktop (7.3.247). Do you have any idea why?

Thankfully,

~Robert

![nimbus-image-1453876289531](https://cloud.githubusercontent.com/assets/170947/12605750/051e6134-c4c8-11e5-9aeb-5e6df5d422d5.png)

**Comment by amulware** [comment]
Hey Robert,

First check: Are you sure you are logged in with the correct account?

If yes, have you tried a manual sync, restarting the app, or clearing the cache?

If projects are then still missing, is there any pattern to which projects it shows, and which it does not? Maybe specific clients are missing, or projects with tasks, or project that have 'duplicate' projects (same name) under a different client?

Depending on how much information you want to share here, you could always contact us at support@toggl.com.

**Comment by orschiro** [comment]
Daer @amulware,

Thank you for your response!

In fact, I have just overlooked the scrollbar at the right...

How silly. I am sorry for that.

~Robert
