### ISSUE TITLE
Check on default project colour

### ISSUE THREAD

**Issue by amulware** [toggl/toggldesktop#1806]
At least on windows, it currently seems to default to light blue. We should investigate what is going on, and make sure it behaves like it is supposed to (what is the proper behaviour?).

**Comment by kadrihvl** [comment]
Reported with desk case #246860.

**Comment by amulware** [comment]
Will solve issue by selecting a random colour when the user clicks the 'add project' button. They can still change it, but this way there will never be magically changing colours, and no light blue reign!
