### ISSUE TITLE
High CPU usage when switching user

### ISSUE THREAD

**Issue by amulware** [toggl/toggldesktop#1811]
On Windows 10 (possibly others too), when switching to a different user (without signing out) if Toggl Desktop is running, the app will start using 100% of available CPU (though only a single core it appears).

**Comment by amulware** [comment]
Interestingly, during this time, almost nothing happens in the log file.

This definitely needs some more detailed looking at.

**Comment by amulware** [comment]
Profiling shows that the windows message loop runs hot during the times in question (instead of running idle, like one would expect). It seems that something may cause the window to continuously redraw itself. Need to investigate what messages are being received.

**Comment by amulware** [comment]
I have confirmed that when being logged into another user, the application is spammed with the `WM_PAINT` message which indicates that the window should be redrawn.

**Comment by amulware** [comment]
The same behaviour occurs in a completely new WPF app with just a single empty window.

Most likely this is a bug in WPF. For now, a workaround is to minimize the app before switching users.

**Comment by amulware** [comment]
This problem has since been fixed by Microsoft. See here:

https://connect.microsoft.com/VisualStudio/feedback/details/2390593/wpf-apps-use-a-lot-of-cpu-time-when-logged-into-different-user

**Comment by IndrekV** [comment]
Jep Microsoft is to blame.
