### ISSUE TITLE
TogglDesktop.sh keeps calling itself if launched from a symbolic link

### ISSUE THREAD

**Issue by claudiodangelis** [toggl/toggldesktop#1814]
Values of the following two variables are not correctly expanded when the script is called by a symbolic link:

```
appname=`basename $0 | sed s,\.sh$,,`

dirname=`dirname $0`
```

For example, say we have a symbolic link called `/usr/bin/toggl`

`ln -s /path/to/TogglDesktop.sh /usr/bin/toggl`

If you run `toggl`, `appname` variable will be set to "toggl", resulting in recursive call and a consequent `fork: retry: No child processes` error.

Those variables should be declared with something like this in order to resolve the destination basename:

```
appname=`basename "$(test -L "$0" && readlink "$0" || echo "$0")" | sed s,\.sh$,,`
dirname=`dirname "$(test -L "$0" && readlink "$0" || echo "$0")"`
```

Ref: https://github.com/toggl/toggldesktop/blob/5964caf774c49355a00fca31e37ecdb516524710/src/ui/linux/TogglDesktop.sh#L2-L4

Claudio

**Comment by IndrekV** [comment]
Thank you for your contribution Claudio.
