### ISSUE TITLE
Two icons on Ubuntu 15.10

### ISSUE THREAD

**Issue by orschiro** [toggl/toggldesktop#1816]
Dear all, 

Can someone reproduce the problem of two icons being shown in the Unity launcher?

While the left icon doesn't launch, the right one does.

I installed `toggldesktop_7.3.247_amd64.deb`.

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/12719775/76544f7a-c8f7-11e5-95c3-dff880777511.png)

**Comment by orschiro** [comment]
After some more testing, I found that the duplicate icon is created by the Ubuntu launcher feature "Lock to launcher" which places the duplicate icon file in `~/.local/share/applications/toggl_desktop.desktop`.

![image](https://cloud.githubusercontent.com/assets/170947/14766311/81745d84-0a04-11e6-8fc6-cf4058bf5b44.png)

This file contains the following lines:

```
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Name=Toggl Desktop
Icon=toggldesktop
Path=/home/orschiro
Exec=/opt/toggldesktop/TogglDesktop
StartupNotify=false
StartupWMClass=Toggl Desktop
OnlyShowIn=Unity;
X-UnityGenerated=true
```

The line `Exec=/opt/toggldesktop/TogglDesktop` need to be changed to `Exec=/opt/toggldesktop/TogglDesktop.sh` in order to run properly.

Yet, the duplicate icon remains in Ubuntu Dash.

**Comment by IndrekV** [comment]
Hi, 

Thank you for testing. I've managed to reproduce this issue and will look more into this.

**Comment by orschiro** [comment]
Glad I could help, @IndrekV.

Hope we can find a solution to this!

~Robert

**Comment by MartinBriza** [comment]
This issue is now pretty old and I'm not sure what was the actual culprit, however with the way we do packaging and .desktop files at this moment, it should be fixed. If it happens again, please feel free to reopen this issue.
