### ISSUE TITLE
OBM experiment D98 - Two-step introduction 

### ISSUE THREAD

**Issue by kyllikekimmel** [toggl/toggldesktop#1819]
Experiment number in back end - 98. 

When a user in "included" group signs in for the first time, display a welcome slide: 

![desktop_1st_final](https://cloud.githubusercontent.com/assets/8287467/12784083/b5be065a-ca8d-11e5-824a-f8886a0fc4dc.png)

The user can close it from the X in the upper right corner. If they don't, it should be replaced with the next slide once the user has clicked "Start":

![desktop_1st_step2_final](https://cloud.githubusercontent.com/assets/8287467/12784197/5cdaa790-ca8e-11e5-96d9-842f2b918593.png)

Close the screen when: 
- the user clicks on the X in the corner, 
- the user opens the Edit window, or
- when they stop the timer, whichever comes first. 

Text for the first screen: 
Hey, welcome! 
Type in what you're working on, then start the timer.

Text for the second screen: 
To add a project or tags, click anywhere on the timer.

**Comment by kyllikekimmel** [comment]
Actually, correction - let's display the second screen even if the user has closed the first one. 

Additionally, track how many users see both screens as experiment_actions = "seen_1" and "seen_2".

**Comment by amulware** [comment]
We'll also send a "start" action, the first time the user starts a time entry through the app (this resets every app restart until #1817, but duplicates are discarded by backend).

**Comment by amulware** [comment]
Implemented on `win-new-experiments`.
