### ISSUE TITLE
OBM experiment D99 - A single welcome screen

### ISSUE THREAD

**Issue by kyllikekimmel** [toggl/toggldesktop#1820]
Experiment number in back end - 99.

When a user in "included" group signs in for the 1st time, display a welcoming screen: 

![desktop_3rd](https://cloud.githubusercontent.com/assets/8287467/12784336/3f2515a4-ca8f-11e5-8545-b8908ce95b21.png)

User can close it from the X in the upper right corner. Otherwise, close it once the user has stopped their first time entry. 

Text: 
Welcome!
First, describe what you're working on, then start your timer. 
PS - edit, or add projects and tags, by clicking the running timer

**Comment by kyllikekimmel** [comment]
Track how many users start the timer as experiment_actions = "start"

**Comment by amulware** [comment]
Implemented on `win-new-experiments`.
