### ISSUE TITLE
Ocassionally, selected project not saved for a given task

### ISSUE THREAD

**Issue by orschiro** [toggl/toggldesktop#1822]
Dear all,

I noticed the following problem:
1. Of a running task, select a project 
2. Click "Done"

Sometimes, the project field remains empty. 

I need to do steps 1 and 2 again.

Tested on Ubuntu 15.10 and Toggl 7.3.247.

Thankfully,

~Robert

**Comment by IndrekV** [comment]
will be fixed with new autocomplete component #2480
