### ISSUE TITLE
Selecting task from autocomplete adds project name to description

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1825]
User reports on linux 7.3.247:

> When I select the previously executed task by typing in the input field, then it adds the Project name at the end followed by hyphen(-). So, in the report, it shows as new task

**Comment by jayvdb** [comment]
I am also encountering this.

**Comment by jpbaril** [comment]
This is a duplicate of: https://github.com/toggl/toggldesktop/issues/1322

**Comment by IndrekV** [comment]
will be fixed with #2480
