### ISSUE TITLE
Improve windows edit view UX

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1826]
Use regular windows actions:
- double click selects word
- triple click the whole field

when you select (by pressing tab/enter) a suggested task, the cursor stays at the begining of the phrase should be at the end.

User suggest:

> I wish the edit window would work like Firefox URL field: typing some word would show suggestions that, as I navigate through them with the cursor, are already selected; hitting tab would select and move to the next field, while hitting backspace would edit the currenct selection from the last character

**Comment by skel35** [comment]
I believe auto-complete works as expected now, the cursor jumps to the end after an entry is selected.
So double-click/triple-click PR #3059 should close this one.
