### ISSUE TITLE
Latest version fails to run on Linux

### ISSUE THREAD

**Issue by luciash** [toggl/toggldesktop#1831]
Hi,
when I run `sh TogglDesktop.sh` on my Ubuntu 14.04 all I get is this in the Terminal:
`/home/luci/Apps/toggldesktop/./TogglDesktop: 1: /home/luci/Apps/toggldesktop/./TogglDesktop: Syntax error: ")" unexpected

`

**Comment by IndrekV** [comment]
I'm unable to reproduce this on the latest stable version (7.3.247)
Maybe you could try running `./TogglDesktop.sh` instead the `sh TogglDesktop.sh`

**Comment by luciash** [comment]
Same result :( I just downloaded the same version as you have via https://support.toggl.com/toggl-desktop-for-linux/
Any requirements I could be missing?

**Comment by luciash** [comment]
weird thing is, there is no ")" in the shell script file ???

**Comment by matiasmasca** [comment]
I have the same issue, when I try to run the file: TogglDesktop.sh
Error in termina:

> ".../Toggl/toggldesktop/./TogglDesktop: Syntax error: ")" unexpected"

My version of TogglDesktop.sh is:
#!/bin/sh
appname=`basename $0 | sed s,\.sh$,,`

dirname=`dirname $0`
tmp="${dirname#?}"

if [ "${dirname%$tmp}" != "/" ]; then
dirname=$PWD/$dirname
fi
LD_LIBRARY_PATH=$dirname/lib
export LD_LIBRARY_PATH
$dirname/$appname "$@" &

**Comment by IndrekV** [comment]
Linux version is compiled only for 64 bit so it won't work on 32bit.

**Comment by luciash** [comment]
Please suppport 32 bit too! Thanks

**Comment by IndrekV** [comment]
Currently there are not plans to add support for 32bit systems.
