### ISSUE TITLE
Taskbar icon to indicate timer state.

### ISSUE THREAD

**Issue by dotancohen** [toggl/toggldesktop#1837]
It would be nice if the desktop app's Taskbar Icon were to change state to indicate if a timer is running or not. Currently, it seems that Toggl does not set a Taskbar Icon. Testing in Ubuntu 15.10 with the default Unity desktop, the Taskbar Icon is always a grey icon with a question mark.

**Comment by IndrekV** [comment]
Did you test with .deb package or with tar.gz. Please add a screenshot to illustrate the issue.

**Comment by dotancohen** [comment]
I installed from the tarball:
toggldesktop_linux_x86_64-7_3_247.tar.gz

This is the taskbar icon that I see, in both the task running and paused states:
![workspace 1_003](https://cloud.githubusercontent.com/assets/246144/13072569/cd4c82aa-d4a2-11e5-8b9b-b71be474c10a.png)

**Comment by IndrekV** [comment]
I've tested both deb and tar.gz version and both showed the taskbar icon. The taskbar icon is currently always red and doesn't change color to indicate tracking/not tracking.

![screen shot 2016-02-16 at 11 56 23](https://cloud.githubusercontent.com/assets/842229/13072918/828d968a-d4a4-11e5-9f18-6edc4ee18e27.png)

**Comment by dotancohen** [comment]
Some more details, if it helps:
I simply extracted the tarball to `/opt/toggldesktop/` and then `/usr/bin/toggl` is a shell script which simply calls `/opt/toggldesktop/TogglDesktop.sh`.

I notice now that there is a Panel App that does show the proper state, so for me the issue is functionally resolved even if the Taskbar Icon does not show. However if you would like to troubleshoot in order to improve the app I have no problem testing, just tell me what you would like me to test.
