### ISSUE TITLE
It don't enters chars with tilde such as 'ã' or 'õ'

### ISSUE THREAD

**Issue by alexandre-mbm** [toggl/toggldesktop#1842]
I write in brazilian portuguese and I need do time entries names with tilde. All is working on my environment, but not on Toggl Desktop (only on it that does not work); I use Antergos with Fluxbox.

**Comment by alexandre-mbm** [comment]
No accents. None. Neither tilde or acute, for example.

**Comment by IndrekV** [comment]
I've managed to reproduce this issue. We'll look more into it.

**Comment by IndrekV** [comment]
I've taken another look at this issue. Sadly I cannot reproduce it anymore.

![tilde](https://cloud.githubusercontent.com/assets/842229/18776714/e19669d2-8173-11e6-9493-1681782d4d21.gif)
