### ISSUE TITLE
I can only install desktop app on my C drive's user folder?

### ISSUE THREAD

**Issue by G4MR** [toggl/toggldesktop#1844]
![wtf](http://i.imgur.com/kGA9hAR.png "wtf")

That actually doesn't make much sense to me why you would limit the installation location.

OS: Windows 10

**Comment by amulware** [comment]
Hey G4MR,

We only allow installation to the user directory because this allows the application to run properly without requiring admin rights.

Unfortunately, there is nothing that can be done to change this at the moment.

I hope this does not cause you too much inconvenience.

**Comment by G4MR** [comment]
It's 2016, there's literally no reason to not give me the option to install it anywhere else on my system.  Maybe give users a warning for those who don't know how to use a computer lol, but this is absolutely ridiculous.

**Comment by IndrekV** [comment]
Thank you for your feedback. We'll consider making it an option in the installer.
