### ISSUE TITLE
Mac desktop syncing issue

### ISSUE THREAD

**Issue by scorchio** [toggl/toggldesktop#1845]
I have an issue similar to #1400 using v7.3.297 on El Capitan. The changes I make in the web app are not reflected automatically in the desktop client unless I manually refresh.

The issue doesn't occur consistently; after a fresh start of the app, it disappears for a while.

**Comment by IndrekV** [comment]
This issue was caused by a hiccup in the backend system and should be solved now.

**Comment by joeydsmith** [comment]
This issue is not fixed!

**Comment by IndrekV** [comment]
@joeydsmith Is the issue appearing the same way as the original description.

Live update works ok for some time but then stops to sync. Pressing sync manually will sync ok.

**Comment by joeydsmith** [comment]
Pressing sync does not work. If I clear cache will I loose my time entries that haven't sync'd? Is there a way to export a CSV of time entries on the desktop app?

**Comment by IndrekV** [comment]
@joeydsmith .Clearing cache will delete all local data, so if it's not synced it will be lost. There is a way I can convert your local data to csv for easy import. Please contact support@toggl.com and mention that the info is for Indrek.

**Comment by josephfusco** [comment]
I have also been experiencing this recently. I will have a timer running but when starting up desktop it shows nothing.

**Comment by IndrekV** [comment]
With next version the app will do full sync on app start.
Also triggering full sync will be added with #1922
