### ISSUE TITLE
Timeline isn't tracked v7.3.307 Windows 10

### ISSUE THREAD

**Issue by xtoq** [toggl/toggldesktop#1848]
Steps to reproduce
-----

1. Track some time (at least 15 minutes).
2. Sync to the Toggl website.
3. Visit Toggl dashboard.
4. Click the gear icon below the "stop" button.
5. Ensure "Footer Chart" is set to timeline.

Expected outcome
-----

- Timeline should be populated with the programs/activities that you were doing during the tracking.

Actual outcome
-----

- Timeline is empty.

Additional information
-----

- v 7.3.307
- Windows 10 Professional 64 bit
- I do have the "Record Timeline" checked, and you actually can't uncheck it; when you uncheck "Record Timeline" in preferences and click save, when you go back into prefs "Record Timeline" is still checked.
- This started happening to me on 3/2/16 when I installed v 7.3.307.

**Comment by IndrekV** [comment]
Thank you for the detailed feedback. Could you please send us feedback from the app. That way we get debugging data and can investigate the issue further. Just mention the feedback is for Indrek.

**Comment by xtoq** [comment]
Done! I just put "Feedback for Indrek regarding GitHub issue #1848" in the field.

If you need more information please just ask!

**Comment by IndrekV** [comment]
This issue is solved in the latest beta 7.3.318 that will soon be released to stable.
