### ISSUE TITLE
App doesn't start in Windows 10

### ISSUE THREAD

**Issue by oilvier** [toggl/toggldesktop#1854]
Hi,

Since yestarday, when I try to launch Toggl nothing happens.
I tried to uninstall and reinstall and it's still the same problem.

**Comment by IndrekV** [comment]
Try clearing all local files manually. Local files are located in:
 `C:\Users\<username>\AppData\Local\TogglDesktop`

Just remove the whole folder and then reinstall. This should give you a clear start.

**Comment by oilvier** [comment]
Thanks, it worked !

**Comment by TeePaps** [comment]
This is an issue for me

**Comment by IndrekV** [comment]
@TeePaps please write to support@toggl.com and we'll investigate your situation.
