### ISSUE TITLE
Mac desktop autoupdate

### ISSUE THREAD

**Issue by verydull** [toggl/toggldesktop#1856]
The autoupdate feature of Toggl Desktop hasn't been properly working for "some time" now - at least several months, probably much longer.

Updates only seem to happen when I restart the MacBook Pro and although the old files get moved to the Trash okay, the new files don't install correctly - meaning I have to manually download and install the latest version. The old files in the Trash are a good reminder to do it though!

I'm currently on a MacBook Pro 15", late 2011, running 10.10.5; however this issue was also present on my old machine, a MacBook Pro 15", early 2008, last OS being 10.8.5. It might be helpful for you to know I didn't "migrate" files, apps and settings from one machine to the other; it was a fresh install.

**Comment by IndrekV** [comment]
We had an issue with autoupdater a while back. Could it be that you have this faulty version. The broken version was `7.3.177`. I'd advise you to download the latest version from https://support.toggl.com/toggl-on-my-desktop/ and install manually.

App update is executed when you restart the app. No system restart should be needed.

**Comment by verydull** [comment]
Thanks. I think that's the link I used yesterday; the version I have just now is 7.3.309. I'll delete it and reinstall a fresh copy, so I don't suppose we'll know if it's fixed or not until the next update is released. 

App restart makes sense -- it loads at system start, so that's probably why I just notice it then :)

**Comment by verydull** [comment]
Indrek

Interesting you should close this ticket today as, after an absence for a while, the problem has reoccurred this evening.

TogglDesktop 7.3.309 is the version which just tried to update itself from. Version 7.3.319 appears to be the latest available for manual download from your website.

Don’t know if AutoUpdate has missed a few versions, but I’ve restarted my machine several times recently, so there does still seem to be a problem.

Ideas?


Tim
—

**Comment by IndrekV** [comment]
I'd suggest trying the AppStore version if the one on the website is causing problems. We'll do some more tests to replicate the issue.

**Comment by IndrekV** [comment]
No reports about this issue happening anymore.
