### ISSUE TITLE
Project name already exists

### ISSUE THREAD

**Issue by webpepper** [toggl/toggldesktop#1858]
Toggl 7.3.309 on OSX 10.11.3 says that the project name already exists when I try to create a new project for a client. That project name already does exist for other clients, but it shouldn't matter.

I end up going to the web version of the app, creating projects there and then syncing everything. There's no reason why that shouldn't be doable inside of the desktop app, other than a bug somewhere.

I saw a couple of tickets like this that were closed, even though the bug still seems unresolved.

**Comment by IndrekV** [comment]
This is resolved by moving to api v9 that takes account the client id when submitting project data to server.

**Comment by vedr4n** [comment]
This issue might have resurfaced. Check Desk case #419594

**Comment by kadrihvl** [comment]
Logs with case #420607

**Comment by vedr4n** [comment]
Another case with logs - #420076

This one is for Windows.

**Comment by IndrekV** [comment]
This is fixed with d4ddc4c  #2108

Users has a duplicate project names and it failed to sync and caused also time entries to fail to sync.

**Comment by kadrihvl** [comment]
Same error, new logs: #421926

**Comment by IndrekV** [comment]
This will be solved with the syncing fix.
