### ISSUE TITLE
Minimize on Ctrl-F4 just like on [x] clicked (reporting again)

### ISSUE THREAD

**Issue by pdachtera** [toggl/toggldesktop#1859]
When toggl desktop window is closed with [x], it would minimize. That is correct.
But when closed with Ctrl-F4 (which should be the same as [x]), it would close the app altogether.

There was a tentative fix for that, but it doesn't work it seems:
https://github.com/toggl/toggldesktop/issues/1784

**Comment by amulware** [comment]
This definitely used to work when I implemented it in the mentioned issue, but in the current build it does not work for me either. Something must have broken it since then. Thanks for letting us know!

**Comment by amulware** [comment]
Small note: Ctrl+W _does_ work and minimizes the window. So using that shortcut is the current workaround.

**Comment by pdachtera** [comment]
Thank you for checking that! Ctrl-F4 has been kind of automatic for me :). That's the deal.

**Comment by skel35** [comment]
Done in 4996a38
