### ISSUE TITLE
Clicking on the right side of the description textbox does not put cursor in the end of text

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1862]
> When using the desktop-based app and entering text about a task, clicking in the text box to the right of the last entered character does not automatically set the cursor to the end of the string.

If I have set the cursor to the middle of the edit vide description field then clicking on the right side will not move it to the end. Event if another field is focused and I click on the right side of description field the field is focused but the cursor is still where I last had it (in the middle of the text for example)

**Comment by korg250** [comment]
Everything related with cursor position and text selection does not follow the default behaviour (like any other Windows program). Another examples:
- The cursor "remembers" its position for every single field, even if I close and open another task.
- Double click on a word, does not select the word, but the whole sentence. The same for time fields.

**Comment by JamieGruener** [comment]
Came here to open this very issue. Excited to see it's already been defined, saddened to see it's been open for 2+ years.

**Comment by IndrekV** [comment]
Closed with #2894 2894
