### ISSUE TITLE
Unable to login using Google on OSX.

### ISSUE THREAD

**Issue by rhaphazard** [toggl/toggldesktop#1863]
Running latest ver. of toggl on OSX 10.10.5
Opens the mini-browser window to login to Google but nothing happens after entering my information and authentication code.

Edit: If 2-factor authentication is in place, does Google require a one-time code?

**Comment by IndrekV** [comment]
Make sure you have enabled google login from the web app. It's in the "My Profile" page. You can enable it from cogwheel that's next to the"Done" button.
