### ISSUE TITLE
When selecting item from timer dropdown click is registered by the entry underneath

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1865]
If you select and item from timer autocomplete dropdown then the underlying entry captures the click after the dropdown is closed and opens up the edit view of the entry.

Case: `266850`

![win_click](https://cloud.githubusercontent.com/assets/842229/14079019/34eedd9c-f503-11e5-8ddf-f7e2a235187b.gif)

**Comment by vedr4n** [comment]
The bug has been reported by another user. Case #314777
