### ISSUE TITLE
New releases as .deb?

### ISSUE THREAD

**Issue by orschiro** [toggl/toggldesktop#1867]
Dear all, 

I am wondering whether we can soon expect new .deb releases?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/14142199/1a6588de-f67c-11e5-84fb-d07a2af4f557.png)

**Comment by IndrekV** [comment]
We are updating our linux building machine so it can take some time before new linux releases start building again.

**Comment by orschiro** [comment]
Alright, thanks for the update!

Warmly,

~Robert

**Comment by IndrekV** [comment]
New beta release is out as of 11th July.

**Comment by orschiro** [comment]
Thank you very much for the new release, @IndrekV!
