### ISSUE TITLE
Linux notification too intrusive - takes input focus

### ISSUE THREAD

**Issue by danfarrow** [toggl/toggldesktop#1876]
The "Don't forget to track your time!" notification is quite intrusive on Linux - it takes keyboard focus so if you're halfway through typing something it interrupts.

I suppose that it's fulfilling its purpose, but it would be more polite to use `notify-send` instead

**Comment by tobias-kuendig** [comment]
Are there any plans on implementing this feature?

**Comment by IndrekV** [comment]
We don't plan to change the logic of the tracking reminder. It is meant to get users attention and make user take action.

**Comment by LC43** [comment]
has anyone reconsider this? together with #2573 , the linux app is totally unusable for me.

i had to constantly exit the app.

**Comment by tobias-kuendig** [comment]
I don't get the reasoning behind this decision.

> We don't plan to change the logic of the tracking reminder. It is meant to get users attention and make user take action.

The default notification system that `notify-send` would use will get my attention 100x more than the focus stealing notification. What actually happens is that the notification steals my focus and I alt+tab back to the app I was using. This way the toggl notification stays open and won't come up again. A notification that would come up every 5 minutes whether I click it or not makes so much more sense.

On Windows and Mac the native notification system is used as well, why not on Linux?

**Comment by danfarrow** [comment]
> What actually happens is that the notification steals my focus and I alt+tab back to the app I was using. This way the toggl notification stays open and won't come up again.

I totally agree. I've stopped using Toggl on Linux for this reason.

**Comment by IndrekV** [comment]
Thank you all for the feedback. We've re-evaluated this and will look into the possibility to update our notifications to use `notify-send`

**Comment by IndrekV** [comment]
This will be solved with #2654
