### ISSUE TITLE
Keyboard shortcut for Linux to start/stop a running timer?

### ISSUE THREAD

**Issue by orschiro** [toggl/toggldesktop#1877]
Dear all,

Inspiration comes from:

> @IndrekV This just gave me an idea. How about adding a keyboard command? The command would stop the current entry and if there's no entry running it would continue the last entry. It could be something like: ctrl+shift+t

Source: https://github.com/toggl/toggl-button/issues/430#issuecomment-212450757

What do you think of this for the Desktop version?

Thankfully, 

Robert

**Comment by IndrekV** [comment]
Various keyboard shortcuts including stop timer are already present in Toggl Desktop.

The global shortcuts are best for starting and stopping timer at any moment.

See these articles for reference:
https://support.toggl.com/toggl-desktop-for-windows/#keyboard
https://support.toggl.com/toggl-desktop-for-mac-osx/#shortcuts

**Comment by orschiro** [comment]
Dear @IndrekV,

Are there any Linux equivalents?

Warmly,

~Robert

**Comment by IndrekV** [comment]
No keyboard shortcuts in linux for now.

**Comment by orschiro** [comment]
I edited my issue title to specify for Linux.

Can we re-open this issue?

~Robert

**Comment by IndrekV** [comment]
duplicate of #1785

**Comment by IndrekV** [comment]
@orschiro This has been implemented and will be available in the next release.

**Comment by orschiro** [comment]
Fantastic, thank you!

Any plans when the next Ubuntu Linux package will be released?

**Comment by IndrekV** [comment]
Beta version is planned to the end of this week on beginning of next. Few weeks after that it will be in stable channel.
