### ISSUE TITLE
OSX Errors encountered while syncing data

### ISSUE THREAD

**Issue by dandaka** [toggl/toggldesktop#1886]
> Errors encountered while syncing data: pq: function json_build_object(unknown, text, unknown, integer) does not exist.

http://take.ms/Kr7SB

**Comment by IndrekV** [comment]
I'm currently not able to reproduce this issue. Please send feedback from the app so we can investigate the logs. Mention that the logs are for Indrek.

**Comment by dandaka** [comment]
I've sent the feedback.

**Comment by IndrekV** [comment]
Thank you for the fast response. It seems that the issue was cause by some backend error we had. This has been fixed and should not happen anymore. If you still get this error try clearing cache as the faulty data might be still somewhere in the app.

**Comment by askdesigners** [comment]
I'm getting this error right now. No functionality seems effected, but it's annoying to have to dismiss the message every time I start it up.

`Errors encountered while syncing data: json: cannot unmarshal number 1.100075e+06 into type int64`

**Comment by IndrekV** [comment]
@askdesigners Please contact support so we can get your local data and investigate this. We would need your local database. Local database is a .db file. See this article (https://support.toggl.com/clearing-the-local-data-from-toggl-desktop/#manual) for the location of the local database. Mention that the feedback is for Indrek.

**Comment by kadrihvl** [comment]
Also reported with case #360639. Asked for the db file.

**Comment by kadrihvl** [comment]
Logs with case #359831

**Comment by kadrihvl** [comment]
.db file attached to #357315
