### ISSUE TITLE
Windows app queues a lot of notifications if user leaves the computer running for a long time.

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1889]
User reports:

> If I leave my computer running for the weekend, the Toggl Desktop tends to queue up Windows notifications. It is a bit annoying that every Monday a few hundred reminders pop-up after each other. As far as I remember, this did not use to work like this, it has only been doing it for a few weeks.

We should keep track if there are already notification s pending and not add new ones to the pool.

**Comment by kadrihvl** [comment]
Reported with desk case #280800 (logs available).

**Comment by dandaka** [comment]
OSX the same bug
![toggl](https://cloud.githubusercontent.com/assets/2384694/15815095/eefee314-2bca-11e6-9400-95e8ff6fdd23.jpg)

**Comment by ApocalypticFish** [comment]
case/532028 user is experiencing this issue also regardless of whether the reminders are set to between 9am - 5pm or not.

**Comment by jayvdb** [comment]
Probably similar issue to https://github.com/toggl/toggldesktop/issues/1799

**Comment by IndrekV** [comment]
Fixed with #2673
