### ISSUE TITLE
toggl desktop is logging user activity even when autotracking and timeline is switched off

### ISSUE THREAD

**Issue by hyperknot** [toggl/toggldesktop#1890]
I've opened a support ticket but I guess it's a better place here.

Toggl desktop (at least on OS X) is tracking user activity and outputting everything to tiggl_desktop.log in cleartext. (on OSX it's in `Library/Containers/com.toggl.toggldesktop.TogglDesktop/Data/Library/Application Support/Kopsik/production`). 

This includes everything which could possibly be displayed on a terminal window's title, or in any other program's tile, the including a users time-stamped browsing history. 

This is happening with **autotrack and timeline switched off**! This is a serious bug, it should never happen, this can possibly make toggl into a keylogger which also outputs whatever it captured into a cleartext log file visible to every other program.

toggl should never ever track anything happening on a user's computer without asking for the user's permission first, and even when the user enables tracking or timeline it should never store it in cleartext visible to every other program.

**Comment by IndrekV** [comment]
Thank you for notifying. We will fix this.

**Comment by IndrekV** [comment]
I've looked into this issue a bit and we removed the info from the log a while ago. You might have an outdated version. Please get the latest version of the app from our homepage https://support.toggl.com/toggl-on-my-desktop/

**Comment by hyperknot** [comment]
I am using the version from Mac App Store. If the latest version in MAS is so outdated and contains bad bugs like this, you should update it or at least display a big warning sign that the user should stop using the MAS version and download a dmg one from your homepage.

**Comment by IndrekV** [comment]
Thank you for your concern, we will address this situation.
