### ISSUE TITLE
Sometimes associated project is not saved

### ISSUE THREAD

**Issue by orschiro** [toggl/toggldesktop#1892]
Dear all, 

I am using the latest Toggl Desktop on Ubuntu 16.04.

Occasionally the associated project of an entry is not saved after hitting "Done".

If I repeat this one more time, then the project is correctly stored. 

Can anyone reproduce that?

Thankfully,

~Robert

**Comment by IndrekV** [comment]
Will be fixed with next release that has new autocomplete component.
