### ISSUE TITLE
Request: Preferences to start on system start-up?

### ISSUE THREAD

**Issue by orschiro** [toggl/toggldesktop#1895]
Dear all, 

Would it be possible to add a preference to the Preferences menu to start Toggl Desktop on system start-up?

Thankfully,

~Robert

**Comment by IndrekV** [comment]
We have decided not to add this functionality into the app. Users can define TogglDesktop as startup application in their operating system to achieve this behaviour. Here is a good guide on how to do it in Linux http://stackoverflow.com/a/7221787/1015296

**Comment by orschiro** [comment]
Dear @IndrekV,

I can understand that reasoning. 

For future reference in case someone is an Ubuntu user:

![image](https://cloud.githubusercontent.com/assets/170947/15065763/1a05c152-1363-11e6-823b-86edd885ca9b.png)
