### ISSUE TITLE
Integration possibilities with other Apps  on OSX

### ISSUE THREAD

**Issue by grantkemp** [toggl/toggldesktop#1896]
I would like to spin up from my app or others like Pomodone
1. Ability to add a task to Toggl
2. Ability to Start a timer from my app
3. Ability to close off a timer and get the resulting numbers

Currently my workflow involves spinning a task manually in Toggl - starting timer and then manually turning it off .  Would be great to spin up a service for above using SharedServices.

**Comment by IndrekV** [comment]
All of these scenarios could be simply solved with making requests to the API. Wouldn't that solution work for you. Here is a link to the api documentation: https://github.com/toggl/toggl_api_docs

**Comment by grantkemp** [comment]
would that trigger a Timer on the Toggl Mac app?

**Comment by grantkemp** [comment]
Also there doesn't seem to be a Swift Wrapper / SDK available

**Comment by IndrekV** [comment]
Toggl Desktop app uses socket connection to be connected to the server and will get update from the server in a few seconds.

We don't actually create wrappers ourselves so yes if community has not created one there is no wrapper.

There is an older project with objective-c but I'm not sure it works properly anymore. https://github.com/toggl/toggl-objective-c-samples

**Comment by grantkemp** [comment]
oh - so its basically a web app .. makes sense. 
I am not sure if I will have time to create a wrapper. Might wait around for someone else to build one as it its just a nice to have function. 

Probably best to close issue.

**Comment by chmac** [comment]
I'm looking for the same functionality. Interacting with the API is not quite the same. It doesn't work offline for one thing.

I'd like to see the timer started automatically whenever I switch branch in a specific git project. While I could push that to the API, it's not exactly the same as being able to control the timer that's running on my desktop.

@IndrekV Any plans to support this?

**Comment by grantkemp** [comment]
@chmac I would look at something like Githooks - or scripting something in command line to integrate that - you can probably do it yourself quite simply. ( and you need to remember to unbranch when you aren't working on it.  I built a custom mac app - which uses my jira status . That might be easier?

**Comment by chmac** [comment]
@grantkemp Agreed, git hooks was what I was thinking. My thought was to start / stop the timer based on the branch. Actually, probably just start the timer every time the branch changed.

**Comment by IndrekV** [comment]
There are currently no plans to add possibility to communicate with the app from scripts and such. Only way would be to use scripts to make API requests.
