### ISSUE TITLE
Enhanced search function?

### ISSUE THREAD

**Issue by orschiro** [toggl/toggldesktop#1904]
Dear all, 

Would it be possible to enhance the search function? 

Following example:

A previous entry (that I wish to continue with) is found if the keyword is at the beginning but not in the middle of the entry.

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/15289713/40bf615e-1b74-11e6-835a-e36a5dc9511f.png)

![image](https://cloud.githubusercontent.com/assets/170947/15289714/445e659e-1b74-11e6-8c54-c42bd7c41633.png)

**Comment by IndrekV** [comment]
Fixed with #2110
