### ISSUE TITLE
Limit amount of items loaded in main window

### ISSUE THREAD

**Issue by peterlozano** [toggl/toggldesktop#1907]
Toggle loads in the main windows time entries since around a year ago. Which for people who use it daily it can be a lot and severely impacts the performance of the app. Opening the app takes minutes, and doing any operation with time entries is painfully slow.

Adding a configurable limit of the number of entries that are loaded in the main window would make this less of a problem. The default limit should also lower, limiting the display to time entries for the last 30 days or so.

**Comment by timgaunt** [comment]
I agree totally, I've found Toggle is really dragging and I have to sign out/in to reduce the number of items in the autocomplete. Even limiting it to 30 days wouldn't be enough for me as I tend to create around 30 items a day. 

Ideally the main menu should only load in the last day or two (or 50 entries) and then more as you scroll down. Also the auto complete only really needs to look at recent items.

**Comment by IndrekV** [comment]
I agree with this. There is an issue #1790 to solve this issue. There is also "Load more" button at the bottom to make it easy to load more data if needed. 

Could you please elaborate what operating system you are using.

**Comment by peterlozano** [comment]
I'm using OSX Yosemite 10.10.5

Good to hear it is been taken care of.
