### ISSUE TITLE
Make sure mini-timer cannot go off screen

### ISSUE THREAD

**Issue by amulware** [toggl/toggldesktop#1908]
This sometimes happens when switching monitors, especially in multimonitor setups, with large coordinates. Not sure if there is an actual bug or it just comes down to configuration changes.

I propose performing a check whenever the mini timer is shown if it is on any of the monitors, and if not just positioning it on the primary screen. That way a user encountering this problem can 'find' the mini timer by disabling and reenabling it.

**Comment by IndrekV** [comment]
Current workaround is to clear local cache as the location of the window is saved to local database. 
https://support.toggl.com/clearing-the-local-data-from-toggl-desktop/

**Comment by Xx-Ness-xX** [comment]
Thanks, I will give it a try
