### ISSUE TITLE
Full screen and Split mode not working in secondary displays

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1912]
On secondary display the triangles are not shown and `+` sign is shown instead.

_Primary Screen_
<img width="139" alt="screen shot 2016-05-26 at 09 55 27" src="https://cloud.githubusercontent.com/assets/842229/15566174/063f93ee-2328-11e6-87fd-c4f963105de8.png">

_Secondary Screen(s)_
![screen shot 2016-05-26 at 09 55 17](https://cloud.githubusercontent.com/assets/842229/15566175/0644cda0-2328-11e6-9cd7-3e2df9304fcb.png)

http://www.laptopmag.com/articles/use-os-x-el-capitans-new-split-screen-mode

**Comment by VeljkoTN** [comment]
another case of an issue on secondary display: case/674020

"Toggl Desktop appears only as black box after switching displays (laptop screen / external screen while in dock station). Need to quit it and start again."

![toggl_black_box](https://user-images.githubusercontent.com/36152180/39988476-b67d0eba-5767-11e8-8d7a-8c313964b9b1.png)
![toggl_black_box_2](https://user-images.githubusercontent.com/36152180/39988477-b69fb438-5767-11e8-92f8-856523de099d.png)

Fresh instal with local data cleared manually did not help. 

Let me know if you need more info

**Comment by IndrekV** [comment]
@VeljkoTN The comment you added about Windows app is not connected to the original case as it is about mac. I looked into the issue you described and it seems to not be Toggl Desktop issue. It seems that with some settings and graphics cards many of the apps on windows go black. Here is a link for a case that has one possible solution. https://answers.microsoft.com/en-us/windows/forum/windows_10-start/dual-monitor-different-resolutions-black-program/58ec488a-b62d-4ce8-a058-5e01e2a54d9a

**Comment by IndrekV** [comment]
Also I'm not able to reproduce the original issue so closing this.

**Comment by VeljkoTN** [comment]
Thanks @IndrekV
