### ISSUE TITLE
Project selection disappears

### ISSUE THREAD

**Issue by dandaka** [toggl/toggldesktop#1921]
OSX
1. Type a task name
2. Type a project name, select from autosuggestion
3. Select another input with TAB
4. Project selection disappears

http://take.ms/XF8GN

![project-select](https://cloud.githubusercontent.com/assets/2384694/15852762/b95da0b4-2ca2-11e6-88a9-79c5d422def2.gif)

**Comment by IndrekV** [comment]
I'm able to reproduce this. I'll look more into this.

**Comment by dandaka** [comment]
Any ideas, when it will be fixed? Very annoying, I see it every time I use your app.

**Comment by IndrekV** [comment]
I tried to replicate it again but was not able. What do you press to select the item from projects dropdown? Do you use mouse ore keyboard?

**Comment by emersonf** [comment]
I just tried a ton of combinations and couldn't replicate it either. But
this happens to me multiple times a day, so I'll try to notice a pattern.

**Comment by dandaka** [comment]
I was not able to replicate on fresh start. In the end of working day I see this bug appearing again.

1. Press Play icon to start task track
2. Click on "(no description)"
3. Type existing task name
4. Select it from the dropdown
5. Project is appearing / disappearing, while jumping with TAB key

![screencast 2016-09-05 18-22-50](https://cloud.githubusercontent.com/assets/2384694/18253562/f63b6252-7395-11e6-9600-d8d5552dacf9.gif)

**Comment by dandaka** [comment]
I have restarted Toggl and issue disappeared. Looks like bug starts to appear after some time of working.

**Comment by dandaka** [comment]
Any news on this one? It is a pity to see important bugs open for so long. Hope you guys get more resources to make your product better for users.

**Comment by dandaka** [comment]
Any news on this one? Still there, still annoying. Experiencing this every day.

**Comment by thecjharries** [comment]
+1 Linux client, had to show my supervisor to make sure I wasn't going insane

**Comment by bkitko** [comment]
This has gotten worse since the update when projects got grouped under clients. I start typing a client or project name and click my selection from the suggestions, it disappears. I try typing it out manually and it disappears. The only fix I have found is quitting the app and restarting. Restarting fixes it maybe 1 out of 10 times, but only long enough for me to input one entry, then the bug pops back up.

**Comment by IndrekV** [comment]
@bkitko I've created a separate issue to investigate this. #2530

**Comment by IndrekV** [comment]
Because the new autocomplete component is totally different than the previous one. Previous was a combobox with autocomplete support but now we use textfield with custom dropdown. This old issue is referenced in new issue to see the details if needed.

**Comment by ivicaned** [comment]
I also have this issue on OSX since last update, I can't use autocomplete for project. The way around is to click on Project and select project, without filtering projects by names/clients.
