### ISSUE TITLE
Focus on main window from tray icon entry "Continue"

### ISSUE THREAD

**Issue by orschiro** [toggl/toggldesktop#1930]
Dear all, 

I would like to discuss the following "feature":

If I click on the Continue entry in the tray icon context menu on Ubuntu 16.04, it puts the focus to the Toggl main window. In my opinion this is not necessary as continue already assumes to continue with the last entries. There is no reason to show the main window. 

What do you think?

Thankfully,

~Robert

**Comment by IndrekV** [comment]
Thank you for the feedback. If we decide to implement it, we will probably add setting for this.

**Comment by orschiro** [comment]
Dear Indrek, 

You're welcome and I am glad to hear you might consider my request. 

Thank you!

~Robert

**Comment by IndrekV** [comment]
This issue can be solved with disabling preference `Focus app on shortcut`

**Comment by orschiro** [comment]
Thank you, @IndrekV!
