### ISSUE TITLE
Tracking reminder keeps sending notification even when lid is closed

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1931]
user reports:

> If I close the lid and the timer is not running, after I open my laptop, there are a lot of notifications about if I didn't forget to start the timer.

**Comment by fonorobert** [comment]
desk case: 303186

**Comment by jayvdb** [comment]
Closely related to https://github.com/toggl/toggldesktop/issues/1889

**Comment by IndrekV** [comment]
Fixed with #2673
