### ISSUE TITLE
Multi-line Notes field

### ISSUE THREAD

**Issue by peterlozano** [toggl/toggldesktop#1933]
It would be good to have a Notes field.

Many times I need to write some additional notes about the time entry which I find very inconvenient to have to write on the entry title/name.

An additional multi-line textarea field for notes would be awesome.

**Comment by IndrekV** [comment]
Toggl used to have nots field but it was not used by our users so we decided to remove it. I don't think it will be coming back. Sorry.

**Comment by peterlozano** [comment]
Oh, sad to hear. Thanks for the answer.

**Comment by yosimor** [comment]
**_Very_** sad to hear! And I'm quite surprised to hear that hordes of otherwise-happy Toggl users have not forcefully demanded this most basic and useful functionality! ;-)

**Comment by AdamBohil** [comment]
FWIW, also would like to see this. Would be very useful to me on the majority of my projects/tasks.

**Comment by yosimor** [comment]
With all due respect, how can such a basic "notes" feature ***not*** be considered to be "time-tracking"-related?!

Even without *any* connection to project management or planning, people purely interested in tracking how they spent their time will generally find it much more convenient to assign relatively **concise headlines** to each item, while still having a need to record some **detailed annotations**.

But of course, this is all just *my* humble opinion, and Toggl's management should make their business decisions according to their organization's goals and requirements!

**Comment by yosimor** [comment]
With all due respect, how can such a basic "notes" feature ***not*** be considered to be "time-tracking"-related?!

Even without *any* connection to project management or planning, people purely interested in tracking how they spent their time will generally find it much more convenient to assign relatively **concise headlines** to each item, while still having a need to record some **detailed annotations** on *what* exactly they did during this time.

But of course, this is all just *my* humble opinion, and Toggl's management should make their business decisions according to their organization's goals and requirements!

**Comment by AdamBohil** [comment]
Yeah, there seems to be some confusion here.  Not sure how a _notes_ field is a project management or planning feature.  Oh well - no matter.
