### ISSUE TITLE
Starting TE from autocomplete always starts the TE that has no project assigned

### ISSUE THREAD

**Issue by fonorobert** [toggl/toggldesktop#1934]
OSX 10.11.5, v7.3.319

steps to reproduce:
- have two time entries with same name, one with a project and one without
- in desktop app start typing the time entry's name in description field, autocomplete will offer both the one with project and the one without
- select the entry with the project, start the timer
- timer will start without a project

**Comment by IndrekV** [comment]
Works ok if selecting with keyboard and pressing Enter to select. Issue appears when selecting from autocomplete with mouse and then starting the timer.
