### ISSUE TITLE
Detected W32.Adware.Gen with webroot antivirus in toggldesktopupdater.exe

### ISSUE THREAD

**Issue by martonsz** [toggl/toggldesktop#1935]
Hi!

My antivirus detected **W32.Adware.Gen** in toggldesktopupdater.exe
- Toggle Desktop version 7.3.318
- Windows 10 Pro 64bit
- Antivirus: Webroot Secure Anywhere: Antivirus. Version: 9.0.10.10

![2016-06-22 13_47_01-program manager](https://cloud.githubusercontent.com/assets/2458236/16265584/6bfc78a6-3880-11e6-8dde-03301ba0e379.png)

**Comment by IndrekV** [comment]
This might be false positive as we have received similar reports before and contacting the antivirus software provider has resolve the problem.

**Comment by martonsz** [comment]
I have submitted a false positive report to Webroot.

![2016-06-22 14_10_47-webroot file submission](https://cloud.githubusercontent.com/assets/2458236/16266054/3521d9e0-3883-11e6-9f24-0837ff8f0b82.png)

**Comment by martonsz** [comment]
No reports about this since march 2016.. closing issue
