### ISSUE TITLE
Set Popup window Pointer to selected entry

### ISSUE THREAD

**Issue by BenRichter** [toggl/toggldesktop#1938]
If you have multiple times tracked on one project and you need to edit the entries, its hard to distinguish wich entry is currently selected. If you edit the currently running entry, the last selection wont turn off. So I often edited the wrong entries without knowing it...

It would be really helpful, if the **pointer left of the popup would point to the currently selected entry**.

![bildschirmfoto 2016-07-05 um 10 40 05](https://cloud.githubusercontent.com/assets/3908676/16578980/bc87e4dc-429d-11e6-9dbc-05b626f187b7.jpg)

**Comment by BenRichter** [comment]
Tags: OSX, Design, Enhancement

**Comment by Leland** [comment]
Oh man, would love to see this. Struggle often trying to figure out what entry is selected.

**Comment by IndrekV** [comment]
Fixed with #2707
