### ISSUE TITLE
7.3.325 beta failed to launch in Linux Mint 17.3

### ISSUE THREAD

**Issue by hugopeek** [toggl/toggldesktop#1946]
Got the following error:

/opt/toggldesktop/TogglDesktop: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /opt/toggldesktop/lib/libTogglDesktopLibrary.so.1)

Solved with:
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install libstdc++6
```

Thanks for adding Pomodoro support!

**Comment by IndrekV** [comment]
Thank you for your input Hugo.
