### ISSUE TITLE
Support multi user machines

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1953]
It seems that the permissions of the files inside TogglDesktop.app don't support multi user machines. The permissions should be 755 to allow multiple users to use the app.

We can add permission update to the build process.

We should also test if this creates any errors with local database and app usage

Some more info in case: 314724

**Comment by zdericnina** [comment]
One more user reported this issue:
User agent: osx_native_app/7.4.7
Version: 7.4.7
> Cannot open the app in a multi-user environment on macOS. Please check the following. 
> Procedure to confirm the issue: Use macOS. 
> 1. Create two user accounts. 
> 2. Install the app by the first user. 
> 3. Switch to the second user. 
> 4. Try to open the app. 
> Fails. 
> How to resolve the problem: 1. sudo chmod 755 /Applications/TogglDesktop.app 

Case: 430510

**Comment by IndrekV** [comment]
Will be fixed with next release.
