### ISSUE TITLE
Pomodoro timer conflicts when started from web and using desktop

### ISSUE THREAD

**Issue by unmultimedio** [toggl/toggldesktop#1955]
Steps to reproduce the bug:

- Having installed OSX Client and Web Chrome Toggl Button
- Login in both
- Activate Pomodoro, and set timer (e.g. 25min)
- Start a task in desktop app, stop it before 25 min (e.g. 23 min)
- Start another task via web app, it doesn't start the Pomodoro timer again _(as it should)_, but takes into account last task, so it will stop automatically around only 2 min of work.

**Comment by IndrekV** [comment]
What version are you using? This issue should be solved in latest beta (7.3.325).

**Comment by unmultimedio** [comment]
Oh ok, I'm on 7.3.319.
Downloading new version…

**Comment by unmultimedio** [comment]
Moved to the Beta channel, tested same steps, solved. Thanks!
