### ISSUE TITLE
Toggle Desktop stops every 25 minutes

### ISSUE THREAD

**Issue by cvoronin** [toggl/toggldesktop#1957]
Toggle Desktop (Win, 7.3.318) stops every 25 minutes and asks me if I want to continue or make a break.
I cannot find a way to disable it.
All check-boxes in General Tab are off:
https://www.dropbox.com/s/xq1z10bg6yygnm9/Ashampoo_Snap_2016.07.22_19h57m46s_003_.jpg?dl=0

Is there a way to disable it?

**Comment by IndrekV** [comment]
Please get the beta version (7.3.35) has it has fixes for pomodoro calculation issues. You can switch to beta channel from the about view. Also please check if you have pomodoro disabled in Toggl Button chrome extension if you are using Toggl Button.

**Comment by unmultimedio** [comment]
Check additionally if your chrome extension has the pomodoro option on, and its length. It could interfere with your desktop client.

**Comment by cvoronin** [comment]
@unmultimedio Thank you, I have forgot about chrome extension, pomodoro timer was enabled in extension.
