### ISSUE TITLE
Status offline, no network

### ISSUE THREAD

**Issue by zhigang1992** [toggl/toggldesktop#1960]
This is happening 50% of the time.

Connection to `stream.toggl.com` seems to be pending forever.

I had to reject `stream.toggl.com` for it to work.

Can you help?

**Comment by IndrekV** [comment]
stream.toggl.com is used for websocket access. Do you by any chance have any firewall or proxy setup that might block this connection.

**Comment by IndrekV** [comment]
Unable to produce this issue. Will close until new information comes up.
