### ISSUE TITLE
Unexpected error when start time is a future time (Windows)

### ISSUE THREAD

**Issue by retnek** [toggl/toggldesktop#1967]
The following error occurred when I adding a future time entry in start date (and I start recording):

![sync_error](https://cloud.githubusercontent.com/assets/1765261/17588451/50e3acc6-5fcf-11e6-896f-73ae34ce5a30.PNG)

Version: 7.3.318
Windows 10

**Comment by IndrekV** [comment]
It probably says that stop time is before start time and this is causing the issue. Toggl does not support future time entries and will not show them in the time entry list. The servers won't accept time entry with future dates. This is what this error is saying. Editing the date of this entry should fix the issue. Also hovering the error would show the full error text in tooltip.

**Comment by retnek** [comment]
There isn't any stop time. Just press "Start" and the start time is future time. I do understand that Toggl won't accept future dates.
