### ISSUE TITLE
Mac Desktop app often locks up

### ISSUE THREAD

**Issue by mhodge13** [toggl/toggldesktop#1968]
I have been having issues with the Mac Desktop app continually locks up.  Usually when adding a new timer or modifying the time on a previous timer.  The entire UI locks up for a couple of seconds before it allows to me do anything else with the app.  This is ongoing and does not seem to be related to any particular project I am working on.

This seems to have been an issue in the past but was resolved in a later version.  Is it possible that it has the same issue again?

Reference ticket: https://github.com/toggl/toggldesktop/issues/1483

Mac Version 10.10.5

Toggl Desktop 7.3.319

**Comment by IndrekV** [comment]
Please send feedback from the app when this happens. Mention that it's for Indrek. That way we get logs and can investigate. Alternatively clearing cache could help fix the issue. https://support.toggl.com/clearing-the-local-data-from-toggl-desktop/#mac

**Comment by dandaka** [comment]
I experience same behaviour. Will send report from app as well.

**Comment by mhodge13** [comment]
Clearing the Cache seemed to help and I have not had any timeouts since September 2nd.  It must have been an issue with my Cache that was causing the issue.

**Comment by dandaka** [comment]
Did that with little result. Also cache corruption was the case for #1921. Which brings an idea, that asking users to clear cache is only a workaround, not the solution.
