### ISSUE TITLE
7.3.247 failed launch ElementaryOS Loki

### ISSUE THREAD

**Issue by alvianx** [toggl/toggldesktop#1969]
```/opt/toggldesktop/TogglDesktop: error while loading shared libraries: libgstapp-0.10.so.0: cannot open shared object file: No such file or directory```

fixed by
```sudo apt-get install libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev```

**Comment by IndrekV** [comment]
The dev packages are actually not needed. It is enough if following packages are installed `libgstreamer0.10-0 libgstreamer-plugins-base0.10-0`
