### ISSUE TITLE
Deleting a time entry is much too easy

### ISSUE THREAD

**Issue by derhasi** [toggl/toggldesktop#1970]
Accidentaly deleting a time entry is much too easy, as the default Option in the confirmation modal is set to "Ok" instead of "Cancel".

![Screen](http://share.undpaul.de/bilder/jh/Monosnap_2016-08-18_13-07-41--uhmnt.png)

**Comment by IndrekV** [comment]
The button focused by default is "cancel". ESC is key for cancel button and RETURN is the button for ok.  I think it is very obvious and does not need to be more complicated. The popup itself acts as a filter to prevent unwanted delete operation.
