### ISSUE TITLE
Data that you are sending is not valid/acceptable after offline

### ISSUE THREAD

**Issue by schmidt9** [toggl/toggldesktop#1971]
Hello

I get following error 
Data that you are sending is not valid/acceptable. 
Sync worked earlier, but I started to get this error after I worked some time offline and then was going to sync results.

**Comment by IndrekV** [comment]
The time entry or entries created while offline have something wrong with their data. If it's only one it is easy to just edit start, stop and date fields and everything should be fine. If it's more then it is harder to find what exactly is causing this.

If you need help you can send feedback from the app and we can investigate the logs. Just mention that the feedback is for Indrek.

**Comment by schmidt9** [comment]
@IndrekV I sent you feedback from the app as you recommended, please check out.

**Comment by schmidt9** [comment]
I had to delete buggy database (backed it up) and start from very beginning, now it works, but if I restore old db, the error repeats as expected.

**Comment by IndrekV** [comment]
If the time entry is faulty it will not sync that time entry until it is fixed.

**Comment by schmidt9** [comment]
@IndrekV why could it be faulty, how can I prevent such cases in future? It is very frustrating, if I have to delete the whole database.

**Comment by IndrekV** [comment]
Usually in these cases the reason is start or end time. Start time is later than end time or something like that. Changing the times would fix the error.

**Comment by schmidt9** [comment]
Thanks, I will check your suggestion

**Comment by schmidt9** [comment]
@IndrekV  `select * from time_entries where start >= stop` on broken db gave me no results... What else could be faulty?

**Comment by IndrekV** [comment]
Please send feedback through the app and mention that it is for me. That way I get your data and can check our logs for the specifics of the error.

**Comment by schmidt9** [comment]
Did send it just now again (actually second time already), please check.

**Comment by Roman86** [comment]
could you highlight invalid entries in Toggl UI (time entry list)? I'm getting it pretty frequently (and right now), but can't find any invalid entries.

**Comment by IndrekV** [comment]
@Roman86 The version you had (7.3.16) was really old. We had some issues with the updater a while back. You might have had the broken version that failed to update.

**Comment by Roman86** [comment]
right, my mistake was that I thought it was updating automatically, but it was failing for a long time. I suppose there could be still many people in same situation. So, if you're getting the message "Data that you are sending is not valid/acceptable" - just make sure you're updated to the latest version. Re-check version after the update, and download manually if auto-update fails.

**Comment by Zenexer** [comment]
Can confirm that this issue appears when using an outdated version.  I had installed Toggl via Chocolatey, but for some reason [the package isn't properly syncing with the Chocolatey repos](https://github.com/ferventcoder/chocolatey-packages/issues/295).  As far as I can tell, it didn't prevent any time entries from being synchronized, and manually installing the latest version from the Toggl website resolved the error message.
