### ISSUE TITLE
Toggl lagging on MAC - long sync time - Toggl unusable during sync

### ISSUE THREAD

**Issue by exmaxx** [toggl/toggldesktop#1972]
I am experiencing **long sync times when updating task info or starting new task**.

An umbrella appears and I cannot interact with the app. It takes **about 30 seconds** (sometimes more) and it is really annoying. It started couple months ago when app got "locked" from time to time for couple of seconds but as time went it got much worse. Now it appears many times a day for longer times.

I am not sure if it is because I have more tasks logged or if it is something on my Mac. It doesn't depend on network connection quality - I experienced this on both slow and fast connections.

I am running OSX 10.11.6 (15G31).

**Comment by IndrekV** [comment]
Please try to clear the local cache. https://support.toggl.com/clearing-the-local-data-from-toggl-desktop/#mac

With the next release there will be automatic cache cleaner that will avoid these kinds of slowdowns in the future.

**Comment by exmaxx** [comment]
Thanks! That worked. The only small disadvantage is that you get logged off during the cache clearing.

And thanks that you are working on making this automated.
