### ISSUE TITLE
Linux app adding tags

### ISSUE THREAD

**Issue by mDfRg** [toggl/toggldesktop#1973]
Like the title says, it's annoying that native linux app doesn't provide an option to add tags to a task - only a checklist to choose from. Any plans to implement it?
BTW: great app!

**Comment by mDfRg** [comment]
Any news? Still waiting :)

**Comment by IndrekV** [comment]
This is currently not planned in the near future, but thank you for pumping this issue. If the stars are in your favour it might fit in our plans somewhere.
