### ISSUE TITLE
Can't go back with Shift-TAB

### ISSUE THREAD

**Issue by dandaka** [toggl/toggldesktop#1974]
**Right now**
1. Click TAB on fields in task details
2. Go until Add new project has focus
3. Press Shift-TAB
4. Focus stays the same place, not going backwards

![screencast 2016-09-05 09-27-39](https://cloud.githubusercontent.com/assets/2384694/18240294/1060eeb8-734b-11e6-9547-39dc0249e109.gif)

**Should be**

Focus goes backwards to Project name input

**Comment by Leland** [comment]
Can confirm this is still an issue as of 48b016e

Note that `Add new project` is no longer focusable, so really this issue is: "Can't shift-tab from Duration back to Project field"
