### ISSUE TITLE
Add autotracker to Linux app

### ISSUE THREAD

**Issue by zalloy** [toggl/toggldesktop#1987]
It would be really nice if the autotracker was a part of the Linux app. I switch tasks very frequently, and sometimes forget to switch the project/task that I am working on, so having the autotracker and being able to define keywords for different tasks (or even web URLs and/or window titles) would be very helpful for me, in keeping my time tracking accurate.

**Comment by IndrekV** [comment]
Hi,

Just to clarify the autotracker currently works as an intelligent tracking reminder. It notifies the user to start tracking when certain defined app is focused. It does so only when nothing is tracking . It does not start tracking by itself and it does not notify once tracking is in progress.

**Comment by zalloy** [comment]
Aw, man! I was actually kind of hoping that it would notify and ask me if I want to switch projects/tasks based on the assigned keywords even if there is already a timer running. Not necessary to auto switch. 

Most of my time tracking issues are a result of switching tasks and forgetting to also switch the timer to that project/task, so it would be helpful if Toggl could pop up a notification like "I see you're working on [task]. Would you like to track this time?" so that the user has the option of stopping the active timer and starting a new one for the new task or allowing the active timer to continue running.

**Comment by IndrekV** [comment]
I understand what you are saying. This kind of functionality could cause a lot of notifications if you switch between different tasks many times. That's why we made it just a helper to not forget to get your timer tracking. For detecting the time when you switched tasks, the timeline graph would work best.
