### ISSUE TITLE
Make the kept days number a setting

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1988]
Currently only last 9 days is kept on startup. This makes the autocomplete list of items also low.

Allow users to change this setting and keep up to 30 days of data in the app.

**Comment by IndrekV** [comment]
As a first test we should just increase the number of days kept. As the issue with big data was about keeping multiple months of data the performance should not be affected if we make the number of days kept to 30 days.

In this case `load more` could get a maximum of 1 month more.

**Comment by timgaunt** [comment]
I would suggest also limiting it to a number of results @IndrekV as I have a lot of entries per day (usually around 20 entries a day) so 30 day's worth may still be sluggish.

Do we know when this will be released?

**Comment by timgaunt** [comment]
@IndrekV do we have any idea when this will be released? The desktop app is almost unusable at the moment

**Comment by IndrekV** [comment]
Part with keeping 30 days by default is live. The part about limiting number of entries is not live and is not planned to be added in near future. I think the issue might not be with the number of entries but somewhere else.

@timgaunt Could you please send feedback from the app and mention it is for Indrek. I'd like to see log info of your app to see where it slows down.

**Comment by timgaunt** [comment]
Done.

--
Tim Gaunt
Managing Director | The Site Doctor | Reg'd in England & Wales: 6502026
M: 07715 110 656 | T: 0121 31 45 374
www.thesitedoctor.co.uk<http://www.thesitedoctor.co.uk> | @thesitedoc
