### ISSUE TITLE
Don't show entry delete confirmation if the entry has no data

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1989]
If entry has duration of under 15 seconds and no description and no project  don't ask for confirmation if user deletes it. No data is lost and this makes cleaning up a lot faster.

**Comment by Trost123** [comment]
Maybe it's a personal preference, but I'd find it useful if this worked for **any** entry with <15 seconds.
Sometimes I click "continue" on a wrong entry, and then you have to go through the whole: stop task>right click entry>click delete>confirm.
I mean, how big can a loss of 15 seconds task can be?

**Comment by IndrekV** [comment]
@Trost123 this kind of makes sense. I'll reopen this case and we'll take another look.
