### ISSUE TITLE
Toggle Desktop 7.3.326 don't start on macOS

### ISSUE THREAD

**Issue by vandesign** [toggl/toggldesktop#1990]
Work only old (7.3.319) version.

**Comment by IndrekV** [comment]
Please try to clear local cache. Sometimes the update of the app can cause local database corruption. See this article about clearing local data: https://support.toggl.com/clearing-the-local-data-from-toggl-desktop/#manual

**Comment by vandesign** [comment]
Thank you so much! That helped.
