### ISSUE TITLE
Sync switches input that user is editing

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1995]
What happens is:
- 1) I open up a stopped task and change certain information (say for instance the end time) 
- 2) I already click to start typing in the "What are you doing?" box and start typing. 
- 3) Toggl synchronizes with the server (I can see the "update" icon) 
- 4) When it finishes, it automatically highlights the Entry box input (the one that I was editing before) 

Since I was already typing in new information for my new entry, I end up editing the name of the older entry, which means I have to delete the mistake, click on the new entry again, start editing and hope that it doesn't go back to the old one again.

case: 354308

**Comment by skel35** [comment]
Fixed with #2898
