### ISSUE TITLE
Automatic tracking in Atom

### ISSUE THREAD

**Issue by bennyp123** [toggl/toggldesktop#1996]
Hey there fine folks at Toggl. 

Love Toggl, hate manually tracking. 

I found a [package](https://github.com/dan12mol/toggl) for atom which provides tracking commands through atom's command palette. Imagine if users could set a `toggleProject: String` key on their project settings, and whenever a file from that project was open in the editor, toggle would automatically track an entry for the toggle project with the name specified on that key. It should take the filename as default task description.

**Comment by IndrekV** [comment]
Hi, this doesn't seem to be directly connected to Toggl Desktop app. This is more of an addition to the Atom package that you mentioned.

Thank you for sharing your ideas.
