### ISSUE TITLE
Show correct daily total in brief view

### ISSUE THREAD

**Issue by atapin** [toggl/toggldesktop#1998]
In brief view, only the visible entry is considered in calculation of daily total, whereas it would be more useful to display correct daily total (~8 hrs instead of <1 hr on the screenshot).

![image](https://cloud.githubusercontent.com/assets/1181403/18905642/8abfa6d8-857d-11e6-8958-f50b5c5556da.png)

**Comment by atapin** [comment]
Probably, users would like to see a kind of collapsed entry with label "N entries" which would lazily load all daily entries on click.

**Comment by IndrekV** [comment]
Looking at the screenshot I don't see anything out of the order. Are you referring that there are more entries on the 19th and the Total time in the day header does not reflect time of the entries that are not loaded?

**Comment by atapin** [comment]
@IndrekV here in the list we can see kinda "archived" days from past. I have many daily entries (>10), totalling to approx. 8 hours each, while day header, as you've noticed, reflects only a single entry's time.

**Comment by IndrekV** [comment]
Hi, I've looked into the issue. All time entries tracked should be visible in the app. I can see that they are present servers side. The app calculates the total times from the visible entries.

If for some reason the time entries are not showing up please try to clear cache to clean up the app's data. See this article: https://support.toggl.com/clearing-the-local-data-from-toggl-desktop/#mac

**Comment by atapin** [comment]
@IndrekV if I click "Load more", the entries become visible. I'm just suggesting to show correct daily total. And for better UX, it would be probably better to fold past days' entries which would be loaded by click. 

Anyways, thanks for the great app - the best time logging tool on the planet, as for me.

**Comment by IndrekV** [comment]
Outdated issue. We have since then introduced `Grouped entries` that group together similar time entries.
