### ISSUE TITLE
Support dark theme on MacOS

### ISSUE THREAD

**Issue by atapin** [toggl/toggldesktop#2003]
On dark theme Toggl still shows light system menu bar.

This is how Toggl looks:

<img width="996" alt="screen shot 2016-10-04 at 19 51 09" src="https://cloud.githubusercontent.com/assets/1181403/19079247/6c836ef4-8a6c-11e6-86f5-683145f784fb.png">

Any other app:

<img width="972" alt="screen shot 2016-10-04 at 19 50 50" src="https://cloud.githubusercontent.com/assets/1181403/19079259/7807e6b0-8a6c-11e6-8926-789d51b8bf14.png">

**Comment by IndrekV** [comment]
Unable to reproduce on macOs 10.11.6 

I'm seeing dark menubar as expected

![screen shot 2016-10-05 at 10 54 09](https://cloud.githubusercontent.com/assets/842229/19105358/2eaf2dce-8aea-11e6-8a62-f16598ab0267.png)

**Comment by atapin** [comment]
@IndrekV yes, I confirm. Not reproducible after the app restart.
