### ISSUE TITLE
Selecting date in Australian timezone saves the date of the day before

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2012]
User reports:

> I selected 28 September 2016 in the date picker. This makes the date picker disappear, but then the date displayed in the date field is set to 27/09/2016.

case 358926

**Comment by epagnini** [comment]
Brazilian user reporting the same as well. 

case 441631

**Comment by vedr4n** [comment]
Another user from Brazil reporting the same problem.

Case: 444299

**Comment by nicktoggl** [comment]
popped up again /case/451058

**Comment by vedr4n** [comment]
Another example: 460573

**Comment by nicktoggl** [comment]
case/672501
