### ISSUE TITLE
On Windows 10 the reminder notification seem to be missing

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2013]
Log file shows that the notification is triggered. User says that notifications are not visible. 

case: 315169

**Comment by Meppyman** [comment]
I too am not getting reminders since installing Toggl (both the chrome extension and the desktop app). I used Toogl in the past and reminders appeared.. there must be a fix for this?

**Comment by IndrekV** [comment]
@Meppyman I'm not sure how this is happening. The reminders are triggered certain time after last entry is stopped or app was started. The fact that it does not work for both toggl button and desktop is really strange.

**Comment by Meppyman** [comment]
Even stranger is they started working properly a day or so after I posted here. I am going to go with Windows 10 notification bug  and leave it at that lol.
