### ISSUE TITLE
Webapp doesn't display clients created in desktop app

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#2015]
When I create a new client in the Windows desktop toggl. And create a new project with that new client. And sync it. And start and stop a timer that shows the new project-new client on it.
But the website shows the newproject but no new client. Even when I refresh the page.
The new project has no new client. It seems that the sync does not add the new client.
Logs: #361190

**Comment by maritoggl** [comment]
User reported the same issue - conversations/19341310307. Sent screenshots where client name is clearly visible in the app, but backoffice shows that client name has not been synced to our servers.

**Comment by IndrekV** [comment]
Fixed together with #2607
Available from version https://toggl.github.io/toggldesktop/#win/7.4.345
