### ISSUE TITLE
Unable to type in description after adding emoji 

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2020]
User reports that cursor is not shown after emoji has been added to the description.

case: 366468

Step to reproduce.
```
0. Create a new entry
1. Hit the shortcut to display the emoji (ctrl + cmd + space)
2. add an emoji
3. try to type - the cursor does not show
4. close the entry
5. reopen
6. try to type - same issue
7. Close the main window
8. reopen the main window (no need to quit)
9. reopen the entry
10. Now you can type !
```

**Comment by NghiaTranUIT** [comment]
I'm unable to replicate this Emoji issue anymore, in both Stable 7.4.2.5.3 and latest commit [#803d43a](https://github.com/toggl/toggldesktop/commit/803d43a723ca36d562970a9ad9991a5bc0b0ee4c) on Master.

I believe that it has been resolved after we revamped new AutoComplete as we discussed ⛑.
