### ISSUE TITLE
[MAC] Project/Company selection formatting is confusing

### ISSUE THREAD

**Issue by bilekt3** [toggl/toggldesktop#2031]
Project/Company selection is very confusing especially "." as separator between projects. Header with Workspace has no indentation and looks same as Project/Company item.

**Comment by simonschllng** [comment]
Even worse that it is not separated by workspace. It is really hard to find the right project. (Tag should not be macOs or at least add linux as well.)

**Comment by IndrekV** [comment]
This issue is solved in the new grouped and colorful autocomplete (already released on mac and windows, close to release on linux)
