### ISSUE TITLE
Add v9 preferences query

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2041]
This is currently needed to:
- Detect if user is on Snowball (for duration only disabling)
- Getting grouped mode info

Probably some other things too in the future.

**Comment by kadrihvl** [comment]
Another user affected by this: #382544

**Comment by refiito** [comment]
snowball flag is to be dropped within next few weeks (do not use this)
preferences has to be scoped per client, don't use me/preferences directly, ping backend for details (before implementation)

**Comment by IndrekV** [comment]
All traces of snowball flag and duration only mode setting has been removed with 21fac31b01bf5398bf6f835c54eebae860bfda06

Let's create a new issue when the new route for fetching grouped mode info is ready.
