### ISSUE TITLE
Large amount of data makes app unusable

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2042]
Login on windows only took 5 minutes.

User has more than 500 tasks in some projects. The rough amount of total tasks can be up to 10000

Details of broken account in: 369619

**Comment by IndrekV** [comment]
In macos after few minutes of logging in the app works as expected.

The issue is probably with autocomplete in windows. In windows we use WPF to generate nice structured autocomplete.

In macos we use native dropdown and generate the content in library.

**Comment by vedr4n** [comment]
Hey Indrek. Do you plan on including a fix for this in the beta that's coming next week?

**Comment by IndrekV** [comment]
@vedran This needs a bigger development so the answer is no.

**Comment by vedr4n** [comment]
Thanks for letting me know!

**Comment by IndrekV** [comment]
Connected to #2251
