### ISSUE TITLE
Pomodoro timer impossible to turn off

### ISSUE THREAD

**Issue by torbjornlarssen** [toggl/toggldesktop#2043]
Tried both 3.3.337 and latest dev version, but after having enabled Pomodoro-timer and used it for a day, I can't turn it off again. Still starts the break after 0.42h even if I set it to 55min before turning off the function alltogheter.

**Comment by IndrekV** [comment]
Please specify the os and double check if all pomodoro checkboxes are not ticked.

**Comment by torbjornlarssen** [comment]
Hey, i found the issue: Toggl on another computer in another place running with the option ticked. Case closed
