### ISSUE TITLE
toggl desktop writes *way* too much data to disk

### ISSUE THREAD

**Issue by vlsd** [toggl/toggldesktop#2049]
I was in the process of checking how much Spotify is writing to my SSD (following [this article](http://arstechnica.com/information-technology/2016/11/for-five-months-spotify-has-badly-abused-users-storage-drives/)). What I discovered was about Toggl Desktop: it wrote more then 500GB to my SSD in just 12 days. For comparison, during the same period of time, Spotify wrote around 200GB (still a lot), Dropbox wrote about 20GB and all my browsers combined wrote less than 20GB. 

The overall rate at which toggl writes to my disk comes out to be something around 45GB/day or close to 2GB per hour. Of course, my computer is not on 24 hours, so the actual rate is at least twice that.  

Here are some details on my system, in case it's important:
```
Hardware Overview:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,1
  Processor Name:	Intel Core i7
  Processor Speed:	2.8 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	16 GB

System Software Overview:
  System Version:	OS X 10.11.6 (15G1108)
  Kernel Version:	Darwin 15.6.0
  Boot Mode:	Normal
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	12 days 50 minutes

Toggl Desktop Details:
  Version: 7.3.337
  Record Timeline: Enabled
  Autotracker: Disabled
```
I'm also attaching a screenshot of the preferences pane, to save me from entering all that stuff manually.
<img width="449" alt="screen shot 2016-11-11 at 11 23 32 am" src="https://cloud.githubusercontent.com/assets/278058/20223934/7986411e-a801-11e6-8d4b-5bdb1ad531ee.png">

**Comment by maltehuebner** [comment]
I can confirm the desktop client to write around 2 gb per hour while I had id only in standby during the weekend:
![toggl](https://cloud.githubusercontent.com/assets/633959/20245849/58bd9a68-a9aa-11e6-8cf5-520083295d58.png)

I would love to see this fixed.

**Comment by IndrekV** [comment]
The data is written when timeline is enabled. Timeline tracks actions every second and saves data to local database. This is why the amount of data written is big. Disabling timeline will lower the written data amount greatly.

**Comment by vlsd** [comment]
@IndrekV even taking this into account, it seems like an extraordinary amount of data. For comparison: `iStat Menu` keeps track of all my system load (CPU, Memory, etc.) and samples every second as well, but only writes about 4MB per hour to disk. 

Even Spotify (which is getting slammed right now for writing too much stuff to disk) is writing at half the pace that Toggl Desktop is, and that is considered too much for an app that caches music.

If this about of disk writes is necessary for having Timeline working, then its usefulness is overshadowed by the drawbacks. However, others may disagree. At the very least the users should be warned that large amount of disk writes will happen if they turn "Record Timeline" on.

**Comment by IndrekV** [comment]
Thank you for your feedback. We will re-evaluate how we handle the timeline data and see how we can improve this.

**Comment by mhujer** [comment]
When I asked the support two weeks ago, Kadri suggested [clearing the app cache](https://support.toggl.com/clearing-the-local-data-from-toggl-desktop/#win) which helped for some time, but now the Toggl is writing like mad again...

![image](https://cloud.githubusercontent.com/assets/353372/20588339/a95b4fac-b214-11e6-8e67-f92376fe95b0.png)

**Comment by mhujer** [comment]
@IndrekV anything new?

![image](https://cloud.githubusercontent.com/assets/353372/20786492/b49bf334-b7a6-11e6-8f4f-0bc794d6220e.png)

**Comment by IndrekV** [comment]
Sorry nothing yet. We haven't managed to dive into this issue. We will do our best to start working on it as soon as possible.

**Comment by herent** [comment]
Another person here that can confirm that it's happening. I'm going to try disabling the "record timeline" feature, but feel it's worth mentioning that it didn't actually sync any of my unspecified time. From the description in the docs, it sounded like this was supposed to keep track of my time when I wasn't actively recording a task, but there's no data when I'm logged into the website. 

I actually wouldn't have minded the 220gb it apparently wrote since I last rebooted much  if it actually recorded that data and I could analyze my "slacking off" time better.

**Comment by IndrekV** [comment]
I've added timeline data cleanup. It seems that old timeline data was what was causing a lot of read and write actions. With this change unusable and synced timeline data is cleared on app start.

First version with the fix is https://github.com/toggl/toggldesktop/releases/download/v7.4.14/TogglDesktop-7_4_14.dmg
