### ISSUE TITLE
Google login error

### ISSUE THREAD

**Issue by Gelo3D** [toggl/toggldesktop#2050]
Whats wrong ? 

Login with google acc. 
If i choose google login option, app redirection to default browser for choose google acc. 
I choose google acc, login in, allow this aplication, in the end i have problem. 
But in verification site "Received verification code. You may now close this window." - is succes dialog. 

App version : 7.3.337

![Uploading google.png…]()

[Device][Test Platform]
Laptop Toshiba L50-B-125
PROCESSOR : INTEL i5-4200U 2x1,6 - 2,3 GHz
RAM : 4GB DDR3 1,6GHz
SSD : 120 GB SATA3 M2 Micro Data MD500
HDD : 750 GB SATA3 TOSHIBA MQ01ABD075
GRAPHIC : AMD RADEON R7 M260 +

**Comment by IndrekV** [comment]
Please make sure that Google login is enabled from Toggl Web app profile settings. See this article about info how to enable Google login for your account. https://support.toggl.com/google-sign-in/

**Comment by skel35** [comment]
Closing as an outdated issue and probably related to Google login in general
