### ISSUE TITLE
togglDesktop Linux : Search feature

### ISSUE THREAD

**Issue by dricoco** [toggl/toggldesktop#2052]
Hello,
The autocomplete in toggldestkop is working like this :
   - let's say you have a list of task like
           Server Maintenance Customer1
           Server Maintenance Customer2
           etc...
   - when you type in the "What are you doing ?" 
           If you type : Server you will see the list appear
           If you type : Customer1 nothing appears
     the search is not on %string% but ^string% only

Could you make it %string% ?

Thanks

**Comment by IndrekV** [comment]
Fixed with #2110
