### ISSUE TITLE
Feature request: Single track for multiple users

### ISSUE THREAD

**Issue by unmultimedio** [toggl/toggldesktop#2065]
There are lots of times where a group of people within a workspace are doing exactly the same activity (ie. a Team Meeting, a Client Presentation, …), during the same period of time.

Wouldn't it be awesome to use the **User Groups** _(are they available via API?)_ to be able to have just one person tracking the time, add the `user_group` exactly as it's added a `tag`, and have that entry added to everyone in the User Group?

I'd love to start hacking this feature, anyone interested in helping?

**Comment by IndrekV** [comment]
Starting timer for other users is only possible in Business plan when you are admin. Also it's possible when you know api tokens of all the users. The backend has not been developed with this kind of actions in mind.

I don't think that this would be a good fit with the desktop app.

Thank you for sharing your thoughts.

**Comment by unmultimedio** [comment]
What about having a boolean preference in each user desktop app, that says accepting to have actions tracked by someone else in the team, and a field below tags that fetch UserGroups, then a table that syncs it all?

Well, what I'm trying to say is that it's _technically_ possible to build the feature, but even if I manage to build it, it's not going to be pulled on the main repo since it goes against the Business plan?

**Comment by IndrekV** [comment]
Basically yes. The we don't plan to add this feature to the official app.
