### ISSUE TITLE
Focus jumps somewhere out

### ISSUE THREAD

**Issue by dandaka** [toggl/toggldesktop#2070]
Today I see a new bug in Toggl desktop app. Focus started to "jump" for different UI elements without any user input. I include one of instances. Sometimes it is hard to input any data, since active element is constantly changing. And it is not obvious, which one is active at the moment.

v 7.3.367

http://take.ms/nouoh

You can see, that text field is losing focus to some other UI element. No input from a user perspective.

**Upd.** Oh, super annoying! I can't input text in task description, focus jumps out somewhere. And for some reason app scrolls down. Feels like a wicked house.

**Comment by dandaka** [comment]
Had to switch to stable channel, impossible to use beta right now.

v 7.3.337, don't see this bug

**Comment by rxnlabs** [comment]
I'm having this same issue with v 7.3.367. It also causes the scrollbar to slide down to earlier tasks instead of staying at the top of window.

**Comment by oshev** [comment]
Me too. Sometimes because of these random jumps, I even delete random entries. :(

**Comment by praghavaji** [comment]
Me too. A simple and small bug but hugely irritating. I'm using a separate text editor to create task descriptions and cop and pasting them into the app.

Then I'm trying to set the project character by character, continually having to click back into the field because the app is jumping focus for what appears to be no reason at all.

**Comment by IndrekV** [comment]
I've been able to reproduce this and will work on a fix.

**Comment by kadrihvl** [comment]
Notify case #394475 once new release with the fix is out.

**Comment by jeremylinlin** [comment]
Very irritating bug to me too! I end up switching back to [this version](https://github.com/toggl/toggldesktop/releases/tag/v7.3.349). Hope this will get fixed soon :)

**Comment by IndrekV** [comment]
Thank you everybody for all the details. It took some time to work through all the changes but I found the bug that caused this flickering.

**Comment by praghavaji** [comment]
Nice, thanks @IndrekV ..

Does that mean there's a new beta version with the fix in?

**Comment by IndrekV** [comment]
I'm working on it. I'll push it out as soon as possible.

**Comment by oshev** [comment]
Thank you so much, Indrek! Very appreciated.
