### ISSUE TITLE
Project colors sync error between web app and desktop app

### ISSUE THREAD

**Issue by tatrosh** [toggl/toggldesktop#2071]
Project colors doesn't seem to sync correctly between web app and windows desktop app.

Here's what I did:

1. I created new projects from within the desktop app and set up different colors
2. I kept using toggl for some time
3. I added new project from within the desktop app - everything fine, colors still present and identical in both apps
4. I edited project names within the web application and here's the issue - naming was updated in both web application and desktop app, but **colors remained only in web application and all projects in desktop app are now blue**

I am not sure, if there's a way of solving this on client side (I didn't find the option to manage projects within desktop app), but it sure looks like a bug to me :)

Thanks, tatrosh

**Comment by IndrekV** [comment]
The colors issue is fixed in the latest beta version. If all goes well it will be also available in the stable  channel next week.
