### ISSUE TITLE
[macOS 10.12.1] Really really slow

### ISSUE THREAD

**Issue by vojtasvoboda** [toggl/toggldesktop#2074]
My Toggl Desktop is really slow. It is problem only by last month, before that it was Ok. That is the reason I found this GitHub repository.

There is the screenshot from my Activity monitor:

![toggl slow](https://cloud.githubusercontent.com/assets/374917/21241844/e3a808c2-c311-11e6-94d0-333eed00333b.png)

Clicking on the Toggl icon takes about 8 seconds to open Toggl window.

Anybody with the same problem? Is there some way how to restrict number of cached items? Because I can see whole month. But last week will be also fine for me (if it speed up the app).

TogglDesktop 7.3.337

**Comment by IndrekV** [comment]
Please send feedback from the app and mention it is for Indrek. That way we get logs and can see what is slowing things down.

**Comment by vojtasvoboda** [comment]
Feedback sent. It takes me about 3 minutes to send one small message:

![2016-12-16 11 43 57](https://cloud.githubusercontent.com/assets/374917/21260271/60c08384-c385-11e6-98ec-dfb7d922ab48.jpg)
