### ISSUE TITLE
Increase keyboard usability

### ISSUE THREAD

**Issue by ewirch** [toggl/toggldesktop#2078]
Change "Show/Hide Toggl" so it will bring up the window if it has no focus. Currently, when I leave the window open, continue to work and hit "Show/Hide Toggl", the window will minimize instead of popping up. I have to hit "Show/Hide Toggl" again. This is annoying and wastes time.

Editing a time entry is different depending on the context. When timer is focused I have to use CTRL-E to edit the time entry. In Time entries listing I can use ENTER. This could be unified: 
* ENTER starts Edit (either current or previous entry, depends on focus)
* SPACE Starts/Stops current or previous entry, depending on focus (this is familiar from players like Youtube).

CTRL-N starts a new entry with title "(no description)". I guess nobody is going to leave the entry like this. You have to press CTRL-E additionally to change the title. CTRL-N could automatically focus the description text box (having the default text already selected). This way I could start typing the new description immediately. Even when I want to keep "(no description)" I can siply leave the window.

CTRL-O (continue previous time entry) doesn't seem to work. Nothing happens independent of focus.

CTRL-V (start with text from clipboard) doesn't soom to work either.

SHIFT-DOWN is pretty uintuitive. It switche between three elements: Start/Stop button, time entry list, settings icon. When I used SHIFT-DOWN for the first time I got confused. Pressing SHIFT-DOWN for the second time (my intention was to move further down the list) removed the focus from the time entry list again. The focus moved to the settigs icon and the highlight of the icon is so subtile that it is hard to spot. So it took me some time to find out the rules. You have to press SHIFT-DOWN once and continue navigating using DOWN/UP. But you can't blindly press SHIFT-DOWN and then DOWN. When the settings icon is focused I have to press SHIFT-DOWN twice, bevor using arrow keys. When I was too quick (pressed SHIFT-DOWN, then DOWN when settings icon was focused first), I realize the time entry list is not focused, I can't fix my mistake by repeating SHIFT-DOWN, DOWN, because the additional DOWN did move the focus back to the sittngs icon, getting me back where I started. I can't use SHIFT-UP to get quickly from settings icon to time entries list, either because SHIFT-UP will only iterate Start/Stop buttor / settings icon.
My suggestion: ditch SHIFT. Use the arrow keys to navigate in the time entries list, when the to entry was reached, select the Start/Stop button. Stop the settings icon in praticipating in the arrow keys party. Settings will be used less frequently than the time entries list and the Start/Stop button. It's fine to use a shortcut to open settings: CTRL-S.

Summing up:
* Use UP/DOWN to navigate elements: Start/Stop button; entries in the time entries list.
* Make TAB switch from Start/Stop button to time entries list, and back on second press. ESC switches from time entries list to Start/Stop button.
* Make the settings icon harder to reach: CTRL-S It should not be reachable using arrow keys or TAB.
* ENTER will start edit mode of the current or a previous entry, depending on focus.
* Change "Show/Hide Toggl"'s function to "bring it up" when the window has no focus. When window is focused "Show/Hide Toggl" will minimize the window.
* CTRL-N stops current time entry, starts a new one and fuceses the description text box (text selected)
* typing lettern/numbers (when description text box is not focused) starts a search in the time entries list
* CTRL-O, CTRL-E, SHIFT-DOWN can be removed.

I understand that you can't simply change the keyboard scheme. Users which got used to the current scheme will get confused or maybe even dissatisfied. But you could add a "Use legacy keyboard scheme" setting.

**Comment by IndrekV** [comment]
I'm not sure what platform you are referring, but macos and windows both have keyboard shortcuts for moving around the app see our knowledge base articles.

Windows article: https://support.toggl.com/toggl-desktop-for-windows/#keyboard
MacOs article: https://support.toggl.com/toggl-desktop-for-mac-osx/#shortcuts

**Comment by ewirch** [comment]
I'm using the Windows client. I didn't know the existing shortcut list. I updated the issue.

**Comment by IndrekV** [comment]
Most of the descried shortcuts are present.

>After window open, the text field has the focus

In main window pressing `ESC` will focus description field.

>Starting to type immediately modifies the text

Currently typing in description field triggers autocomplete that suggest previous entries.

>Enter toggles Start/Stop

`Enter` Starts entry. `Ctrl+s` stops running entry

>Right focuses time input box

`Tab` changes focused field to duration and `Shift+Tab` back to description as is the default tabbing flow.

>Down selects the previous entry

Not implemented and we will not add it.

>Hitting Enter on a previous entry is like clicking the "Play" button

When in entries list `Spaces` starts the focused item.

>You can use Up/Down to navigate the previous list.

Moving around in entries list works with `UP` and `DOWN` keys. To focus entries list press`SHIFT+DOWN`.

>ESC gets you back from the previous list to the starting point

`ESC` jumps to the description field at the top

**Comment by ewirch** [comment]
It looks like our comments overlapped in time. You commented my original text while I updated the issue on 08:41 MEZ. Will you consider reevaluating the issue?

Here is some more input based on your comment:

> Enter Starts entry. Ctrl+s stops running entry

Yes, but I can't start the entry any more after stopping the timer. It looks like the focus is lost somehow.  Arrow keys won't get me anywhere. I even managed to crash the app by pressing combinations of arrows and ENTER. Created issue: https://github.com/toggl/toggldesktop/issues/2080 

> Currently typing in description field triggers autocomplete that suggest previous entries.

Autocomplete in edit pop up is nice, but it won't get you the tags and the project settings from the previous entries.

> Tab changes focused field to duration and Shift+Tab back to description as is the default tabbing flow.

Continue pressing TAB will iterate the small symbols in the window header: toggl icon, settings, minimize button, close button - which is inconvenient.

**Comment by ewirch** [comment]
No answer? You simply ignore my comment? That's rude.

**Comment by IndrekV** [comment]
Sorry for not answering. The issue got lost somewhere in my todo list.

- I've created separate issue for focus lost after entry stop #2091

- App crashing is a separate issue and not directly connected to keyboard shortcuts

- Autocomplete offers previous entries with all their data (description, project, tags)

- The Tab focusing on different element may be inconvenient but it is by design to allow users to focus all elements without the need to use the mouse

**Comment by ewirch** [comment]
I don't mean to annoy. I like Toggl Desktop and would love to improve my productivity using the tool.

I guess a lot of users will stick to the mouse after they tried some "usual" shortcuts and observed that they do not work. This is exactly what happened to me. I assumed Toggl Desktop simply does not support keyboard control. Which limits the usefulness of the tool.

Once you get used to the way of 'how' Toggle handles your input, you can do nearly everything using the keyboard. But it's not obvious at all and often more cumbersome than it could be. So please consider implementing my suggestions. I'm sure they will significantly improve usability of the desktop client.

**Comment by IndrekV** [comment]
Thank you for the feedback. We will test the two points and see how we can improve.

**Comment by ewirch** [comment]
The two points were meant to extend the big text in the issue description, not to replace it.

**Comment by skel35** [comment]
Some of the information mentioned in this issue is outdated, some we took into account to include into issues #3147, #3148.
