### ISSUE TITLE
Windows client crashes after a series of keybard events

### ISSUE THREAD

**Issue by ewirch** [toggl/toggldesktop#2080]
Version 7.3.337
How the crash was triggered: Press shortcut to bring window to front. Press CTRL-S to stop timer. Press arrow keys and ENTER in random order. Crash is reproducible.

Mini dump attached:
[TogglDesktop.zip](https://github.com/toggl/toggldesktop/files/665959/TogglDesktop.zip)

**Comment by IndrekV** [comment]
Connected to issue #2082

**Comment by IndrekV** [comment]
Probably fixed with new autocomplete component #2042
