### ISSUE TITLE
Group duration total ignoring the duration display format setting (available in the Profile)

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggldesktop#2083]
The duration display format setting available inside the Profile is ignored when displaying group totals in the desktop app. Group duration totals are always in the _X h XX min_ format despite being set to decimal (in the screenshot below).

I reproduced this in the macOS version but it's likely happening in others as well. 

![screen shot 2016-12-22 at 12 43 31](https://cloud.githubusercontent.com/assets/19473351/21424747/0c5712c6-c845-11e6-82ad-42613b876e02.png)

---
Desk case: 400908

**Comment by onelinkecm** [comment]
I was affected on 7.4.38 (New x64 install on Win 10). Reset profile> group setting on web and restart desktop app worked. anyway, cool timer.
