### ISSUE TITLE
Clicking the start/continue button on a time entry creates a new entry (!)

### ISSUE THREAD

**Issue by glen-84** [toggl/toggldesktop#2085]
Why is it doing this now??

I am on Windows 10, FWIW.

**Comment by IndrekV** [comment]
There is no duration mode as of releasing the new web app user interface. The update is that there is now feature called "Group similar time entries". You can turn it on from the web app profile view.

With start/continue there will always be a new entry. Similar entries are just grouped together.

The grouping is supported from Toggl Desktop 7.4.0

**Comment by glen-84** [comment]
@IndrekV I'm using Toggl Desktop 7.4.7 and the items are not being grouped (they are grouped in the web interface).

**Comment by IndrekV** [comment]
Please try logging out and back in. It seems that the setting info has not reached the app for some reason.

**Comment by glen-84** [comment]
Unfortunately that hasn't helped. 😞

**Comment by IndrekV** [comment]
A few more suggestions. 
- Delete local database (https://support.toggl.com/clearing-the-local-data-from-toggl-desktop/#win) This will give you a fresh start
- Quit desktop app. Re-enable the "Group similar entries setting" in web. This will trigger the settings update in the desktop app. Restart Toggl Desktop.

**Comment by glen-84** [comment]
I tried the 2nd suggestion and it worked!

Thanks Indrek.

**Comment by onelinkecm** [comment]
I was affected on 7.4.38 (New x64 install on Win 10). Reset profile> group setting worked. What kind of survey was made to determine which users affected? Maybe users who were affected gave up and uninstalled. That's what I did -- couldn't deal with 50 individual time entries per day. Luckily found the github project and decided to search issues and found nothing; luckily decided to search closed issues. maybe most users figure it out and don't say anything. anyway, cool timer.
