### ISSUE TITLE
Toggl Web App Unable to Sync

### ISSUE THREAD

**Issue by lepepe** [toggl/toggldesktop#2086]
### Unable to Sync Projects & Task with Asana.   
**OAuthError: updateToken: 400 Bad Request**   
![oauth-400-badrequest](https://cloud.githubusercontent.com/assets/12739553/21455741/cf70c6a2-c8f0-11e6-9447-903567b80d33.PNG)

**Comment by IndrekV** [comment]
Hi,

This is a repo for the desktop app. Fastest way to report this to the web team is to send feedback right from the web app. Just select the "Help" section and send your message through.
