### ISSUE TITLE
Freezing if reminder windows opened and user click Exit in the main window

### ISSUE THREAD

**Issue by pashagolub** [toggl/toggldesktop#2090]
When Pomodorro time is out, then reminder window shows up with "Continue" and "Start New" buttons. If user clicks on Exit in the Main window or MiniTimer window then whole application is freezing.

**Comment by IndrekV** [comment]
I'm unable to reproduce this issue on windows.

I tried both ways:
- Quitting from main window
- Quitting from minitimer

When pomodoro time end notification is shown.
