### ISSUE TITLE
A new time entry is created when clicking "Continue"

### ISSUE THREAD

**Issue by raahede** [toggl/toggldesktop#2092]
This bug essentially makes the app useless, as I'll have to add up time entries for all the times I've started/stopped or toggled between tasks.

![screen shot 2017-01-03 at 13 39 50](https://cloud.githubusercontent.com/assets/391833/21608011/207487d8-d1ba-11e6-9859-1041f20d8201.png)

![screen capture on 2017-01-03 at 13-37-12](https://cloud.githubusercontent.com/assets/391833/21608002/13c5ff3a-d1ba-11e6-9175-18c758bf5f9c.gif)

**Comment by vedr4n** [comment]
Hi there,

The reason the app started behaving this way is because we removed the "Save duration only" mode from Toggl. The mode was replaced with time entry grouping. You can read more about the feature here
https://support.toggl.com/grouped-mode/ 

You can turn this option on from your Profile (https://toggl.com/app/profile). Just tick the "Group similar time entries" option. 

The grouped mode make your Timer screen look similar to the way it looked with the old "Save duration only" mode.

**Comment by raahede** [comment]
@vedr4n I'm aware of the new grouping feature, and it works fine in the browser view (it was already checked in my profile settings). However, it doesn't work in the desktop app, which I almost only use. I've checked the version (screenshot above) and tried closing the app, logging out, everything I could think of, but no grouping...

![screen shot 2017-01-05 at 08 36 57](https://cloud.githubusercontent.com/assets/391833/21672333/2b37176c-d322-11e6-88be-fcb5c00d281d.png)

**Comment by vedr4n** [comment]
@raahede Try unsetting the grouping option inside the profile and save the changes. Then re-enable the option and save the changes again. 

You might need to restart the desktop app after that but the grouping should start working.

**Comment by vedr4n** [comment]
Ah, yes. When in doubt, restart :)

Atm we're not sure why some people need to reset the option in order to get grouping to work. Good news is that most desktop users aren't affected.

**Comment by raahede** [comment]
👍

**Comment by onelinkecm** [comment]
I was affected on 7.4.38 (New x64 install on Win 10). Reset profile> group setting worked. What kind of survey was made to determine which users affected? Maybe users who were affected gave up and uninstalled. That's what I did -- couldn't deal with 50 individual time entries per day. Luckily found the github project and decided to search issues and found nothing; luckily decided to search closed issues. maybe some|most users figure it out and don't say anything. anyway, cool timer.
