### ISSUE TITLE
Add option for global shortcut to start a new timer

### ISSUE THREAD

**Issue by twpol** [toggl/toggldesktop#2093]
As a user of Toggl Desktop, the most common action I am performing is the New (Control-N) item in the menu. I currently do this via the slightly cumbersome global shortcut to open the application (Control-Alt-T in my case), use the local New shortcut (Control-N), then the global shortcut again to close the application.

I would prefer to have a global shortcut that performs the menu's New option.

**Comment by IndrekV** [comment]
The reason why there is `Continue` global shortcut but not `New` one is that most of the time when creating a new entry you would need to enter details about the entry. I think that we won't add additional shortcut as you could also use global `Continue` shortcut and edit details later if you just want to start something new. Thank you for your feedback.
