### ISSUE TITLE
The "Today" total time is not including current running timer

### ISSUE THREAD

**Issue by raahede** [toggl/toggldesktop#2095]
This has been the case way back too, but was "fixed" at some point. When working a set time of hours a day, it's very useful to know how long you've been working without having to take the running timer into account. Not sure when this was changed. I can't seem to find it in the change log.

<img width="301" alt="screen shot 2017-01-05 at 08 41 37" src="https://cloud.githubusercontent.com/assets/391833/21672437/e8904b4e-d322-11e6-9219-9a327701385a.png">

**Comment by geissbock** [comment]
I commented https://github.com/toggl/toggldesktop/issues/2098#issuecomment-271285552 before seeing this (older) bug - sorry. Seems to be a change in the backend, not in the client(s).

**Comment by skrivanos** [comment]
+1
