### ISSUE TITLE
Timeline not working on OS Sierra

### ISSUE THREAD

**Issue by nschurmann** [toggl/toggldesktop#2096]
Timeline is not tracking the softwares or webpages that i'm visiting. Is there a permission or something needed?

![screen shot 2017-01-05 at 10 48 35 am](https://cloud.githubusercontent.com/assets/5099344/21682655/92080354-d334-11e6-9525-9e57c27ee01f.png)

**Comment by jfboismenu** [comment]
I've started using Toggl and Toggl Desktop about a month ago and it didn't work back then either.

**Comment by nschurmann** [comment]
I've contacted customer support and now it's working again! Seems that they don't have a monitoring system and relay on customers to discover the bugs.

**Comment by vinilavorato** [comment]
I also contacted their support and it's now working. Apparently they had to "manually enable Timeline rendering", whatever that means...

**Comment by jfboismenu** [comment]
@vinilavotaro How did you contact them? I sent them a message about my broken timeline through the Toggle Desktop support dialog. Never got a response back. This was at least two weeks ago.

**Comment by vinilavorato** [comment]
I also uset the support channel on toggl desktop, an they answered in about 2-3 days. Maybe you could try sending a new message?

**Comment by kadrihvl** [comment]
@jfboismenu Please send us a new note directly to support@toggl.com. We will check what happened to your initial note and if we need to enable the timeline for you from our side as well.

**Comment by sohpingting** [comment]
This is still not working.

**Comment by IndrekV** [comment]
Some steps to fix this:
- Make sure timeline recording is enabled in settings

**Comment by IndrekV** [comment]
Some steps to fix this:
- Make sure timeline recording is enabled in settings
- Disable/re-enable just in case
- start working and check online for the timeline graph (note that data is handled in 15 minute chunks so the first 15 minutes you will not see anything)
- If this fails contact support the best way is straight from the app as that way we get additional data about the app and can find the solution faster
