### ISSUE TITLE
Cursor Placement Issue On Windows Desktop

### ISSUE THREAD

**Issue by Michelle112** [toggl/toggldesktop#2097]
"When I need to correct the start time of an entry most of the time only the last digit is affected. Thus, I would like to put the cursor to the right of that last digit. - No text entry field has the cursor showing! - When I click into the blank space at the right of the text field that shows the start time, the cursor appears at the far left. - If I click again, the cursor stays where it is. - I have to move the mouse to within two pixels to the right of the last digit of the time stamp before clicking will move the cursor to the right of the last digit." User included a gif viewable here 410030.

**Comment by IndrekV** [comment]
I'm able to reproduce it. Will look for a fix.
