### ISSUE TITLE
The "Today" header is not counting the active timer

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggldesktop#2098]
This is the total I'm referring to

![screen shot 2017 01 06 at 12 47 11](https://cloud.githubusercontent.com/assets/19473351/21717004/7bb0fdba-d40e-11e6-8f2a-5c6bb40e25d6.png)

Earlier versions of the app (like v7.3.320) included the running timer inside that today total. The behavior was changed sometime between v7.3.320 and v7.3.374 (I'm not sure when).

**Comment by geissbock** [comment]
Actually, the web client started to behave exactly the same way some time ago, so this looks more like a change in the backend than in the client(s):

![image](https://cloud.githubusercontent.com/assets/1055277/21768247/ecb4bb3e-d678-11e6-95b2-4f5659608719.png)

**Comment by IndrekV** [comment]
closed with d4ddc4c
