### ISSUE TITLE
Issue with description in Linux app

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#2099]
User is reporting that the project and client name get added to the time entry description. Logs: 410034
linux_native_app/7.4.7

> Here are screen shots of "project. Client" being appended to the task name when it's selected from the task name dropdown menu. 
> I figured out another clue for replicating the bug. Typically, I press "Start" first, then I click on the time entry description. That takes me to the gray window with "Duration" "Start-end time" "Tags" etc. When I use that dropdown menu, I think that's where the project and client keep getting appended to the time entry description.
![image](https://cloud.githubusercontent.com/assets/12407134/21724971/16f0181c-d43f-11e6-9c98-9a52f3a17839.png)

**Comment by IndrekV** [comment]
duplicate of #1825
