### ISSUE TITLE
Issues when changing the Project from the detail window

### ISSUE THREAD

**Issue by zdericnina** [toggl/toggldesktop#2102]
osx_native_app/7.4.7
> 1. Open detail for item for project "*redacted*"
> 2) Change project to "*redacted*" and see
> project at left get updated.
> 3) Change back to original project (without closing detail window first)
> and see project at left NOT get updated. At this point there is no way to
> change the project back to "*redacted*".
> 
> Before that I had been using 7.3.347. The "Check for update" menu item was
> greyed out.
> 
> *Note that this/these bug extends to new projects*
> 
> 1) Start new tracking item and open detail:
> 2) Choose project, main list project is updated:
> 3) Click on description, and project drop down in detail tab goes blank:
> 4) Closing detail keeps the project in the main list, but step 3 is still
> disorienting.

I was able to replicate this issue.
Screenshots can be found in Case #413336

**Comment by nicktoggl** [comment]
project names redacted on user request

**Comment by IndrekV** [comment]
I'm able to reproduce this. Will look for a fix.
