### ISSUE TITLE
Toggl desktop use too much disk

### ISSUE THREAD

**Issue by khaninejad** [toggl/toggldesktop#2103]
Hi,

When I start Toggl desktop my disk usage goes to 100% and won't down again! so, I had to switch web version.

Regards
Payam

**Comment by IndrekV** [comment]
Please clear the cache of the app https://support.toggl.com/clearing-the-local-data-from-toggl-desktop/

There might be some old data that is causing the app to slow down. With next version there will be a cleanup function that will avoid this situation in the future.

**Comment by jayvdb** [comment]
With all the releases since then https://github.com/toggl/toggldesktop/releases (all marked as pre-releases?!) , has this been fixed?

**Comment by jayvdb** [comment]
I see there is a "Clear Cache" menu item in the app now, so it does seem this is resolved.

**Comment by IndrekV** [comment]
The clear cache button is there for a long time. The fix that I made for this issue was automatic data cleanup in the background.
