### ISSUE TITLE
Changing an entry to a suggestion doesn't carry over tags

### ISSUE THREAD

**Issue by tc-diederik** [toggl/toggldesktop#2107]
**[macOS] Editing an entry and choosing a suggestion (from the list based on previous entries) does not update the tags, unlike the description and project.**

When you start an old entry (whether by suggestion or by clicking the start button of an old entry), it creates a new entry with the same details (description, project, tags). This works fine. However, if you try to change an entry and choose one of the suggestions, it only carries over description and project, but not the tag.

That is assuming that tasks with the same description and project should have the same tags. We use tags to identify types of tasks, depending on the stage of a project; design, programming, presentation, etc. If I have an existing entry 'write code' for 'project foo' and change another entry to that, it should also change the tag to the corresponding tag.

**Reproduction**:
1. Start entry
2. Type something in the description
3. Choose one of the suggestions
4. Description and project change, but tag doesn't

_Why it matters?_
Using the hotkey functionality to start/stop tasks, when starting a new task, it starts the task and copies the previous task over. It also puts focus on the description field, so you can edit it straight away if you're not picking up where you left off on the previous task. This is great and handy. Select a suggestion, cool, oh wait... the tag didn't change.

Cheers. Sorry for the long wall of text.

**Comment by IndrekV** [comment]
I'm able to reproduce this. Seems to only happen when selecting from autocomplete. Will work on a fix.
