### ISSUE TITLE
Syncing issue with windows_native_app/7.4.7

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#2108]
Several users have reported syncing issues. Log file contains "Failed to get focused window info, error code: 4" error.
Cases with logs #415589, #415864

**Comment by nicktoggl** [comment]
416607 as well

**Comment by kadrihvl** [comment]
Logs with case #420076

**Comment by IndrekV** [comment]
```
"Failed to get focused window info, error code: 4" error.
```

This is a timeline error and not directly connected to syncing. 

The main syncing issues currently are that if either client sync or project sync fails the time entries are not synced. I'll fix it.
