### ISSUE TITLE
hide in tray on start

### ISSUE THREAD

**Issue by swalladge** [toggl/toggldesktop#2111]
I would like to be able to automatically run toggldesktop when my computer boots, so have it listed with other applications in my desktop configuration to autostart. The only problem is that it opens its main window when it starts.

There should be an option or command line argument that you can set so that when toggldesktop runs it doesn't open a window automatically but just shows the tray icon.

**Comment by IndrekV** [comment]
I would assume user would like to start using Toggl once it's started. This is why the app window is shown. I don't see a need to hide the window on app start.

**Comment by swalladge** [comment]
@IndrekV why would you assume that? Many applications offer a system tray icon (as does toggldesktop), to provide quick access and keyboard shortcuts. (For example from apps I use daily and can start automatically in the tray: nextcloud client, a clipboard manager, bluetooth settings, network manager applet, usb drive mounter, etc.) My current workflow with toggldesktop is:

1. start toggldesktop
2. close the window
3. press the keyboard shortcut I have set up to begin the timer (which opens the window so I can type in what I'm doing
4. close the window and start work
5. press the keyboard shortcut again once finished task, confirm it has stopped and do any tidy ups required, then close the window
6. repeate steps 3 to 5 throughout the day

If toggldesktop has a command line switch or setting to start only in the tray without opening a window, I can cut out steps 1 and 2, and have it start automatically when I log in without the window opening in my face.

**Comment by IndrekV** [comment]
Thank you for elaborating. I will look into the possibility of adding a command line switch. What platform are you using?

**Comment by swalladge** [comment]
Linux. Currently installed with https://aur.archlinux.org/packages/toggldesktop/ (archlinux package built from toggldesktop sources).

**Comment by StanLindsey** [comment]
Whilst we're on the subject, would it be possible to offer to option of not having it in the dock? Only in the system tray? (MacOs)

**Comment by IndrekV** [comment]
@StanLindsey There is actually a setting called `Show dock icon` in the macos app preferences.
<img width="279" alt="screen shot 2017-02-09 at 15 16 28" src="https://cloud.githubusercontent.com/assets/842229/22784942/c5e0c942-eeda-11e6-8b36-831444f3f2a9.png">

**Comment by IndrekV** [comment]
I've added "start in background" command line arguments to the latest beta [v.7.4.19](https://github.com/toggl/toggldesktop/releases/tag/v7.4.19)

use `-b, --background` command line arguments to start with the window hidden.
Example: `./TogglDesktop.sh -b`

**Comment by swalladge** [comment]
@IndrekV it isn't working for me...

This is with i3 desktop, toggldesktop v7.4.20

**Comment by StanLindsey** [comment]
Thanks @indrekV

**Comment by IndrekV** [comment]
I've reworked the background start issue. It is available in the latest beta. [v7.4.24](https://github.com/toggl/toggldesktop/releases/tag/v7.4.24)

**Comment by swalladge** [comment]
@IndrekV thanks, works perfectly now! 👍
