### ISSUE TITLE
Why are some of the entries are grey and some are black?

### ISSUE THREAD

**Issue by Trost123** [toggl/toggldesktop#2113]
http://prntscr.com/e2nev0
I see no relation to anything. What does this indicate?

**Comment by IndrekV** [comment]
If grouped mode (collapse similar entries) is turned on the group title is darker and the subitems are grey. In the screenshot it does not seem to be the case. Could you please elaborate how this situation happened. Are the grey items just single unique entries?

**Comment by ArniPL** [comment]
@IndrekV To reproduce, you need to have a few regular ungrouped entries and all have to be black. Then create another one with two sub-entries. Then expand that group and collapse it. Two of previously created black entries will turn gray. (Or three if you had three sub-entries and so on).

**Example:**

![](https://zippy.gfycat.com/FinishedSociableGlobefish.gif)

**Comment by IndrekV** [comment]
Thank you for the details. I'll try to replicate and work on a fix.
