### ISSUE TITLE
Total today time does not include duration of running task

### ISSUE THREAD

**Issue by janm6k** [toggl/toggldesktop#2114]
The duration of current running time is not added to the row with total time tracked today:

![image](https://cloud.githubusercontent.com/assets/203105/22468619/402bb4c8-e7c9-11e6-8755-6c0508fb9df4.png)

MacOS, Version 7.4.7. 

I was not completely sure if this was always missing and I have just never noticed it, but there is closed issue about this in 2014 (#915), so it seems that this have been working at some time.

**Comment by kadrihvl** [comment]
Hello! We have opened a ticket for this issue. If it's ok by you I will close this one and you can monitor the progress under https://github.com/toggl/toggldesktop/issues/2098.

**Comment by janm6k** [comment]
Oops, I tried searching before creating it, but I have used different words to search. Thanks for finding the existing issue!
