### ISSUE TITLE
Reminder notification behavior on macOS is very aggressive

### ISSUE THREAD

**Issue by NickAnderegg** [toggl/toggldesktop#2118]
I've noticed that the notifications to remind the user to track time are extremely aggressive. If I have a timer running for longer than the notification interval, I receive a reminder notification almost immediately after stopping the timer. It seems to be queueing up a notification to fire as soon as I stop tracking. A much more sensible behavior would be to schedule the tracking reminders to begin one reminder interval after the last timer stopped.

For example, if I have Toggl set to send me tracking reminders every 30 minutes, and I have a time running from 9:45 until 11:00, I shouldn't get a reminder again until 11:30.

macOS Sierra 10.12.3 (16D32)
TogglDesktop version 7.4.7
Release channel: Beta

**Comment by IndrekV** [comment]
We will try to replicate and fix this issue. The reminder interval should indeed reset when timer is stopped.

**Comment by IndrekV** [comment]
I've checked the code and tried to replicate the issue but have not been successful. When entry is stopped the reminder counter is reset and it shows the reminder at the correct time. Are you still experiencing the issue with the latest stable version (7.4.18)?

**Comment by basilevs** [comment]
I observe similar behaviour using Linux client 7.4.24.
Usually it reminder appears when I switch from one task to another using a link provided by browser plugin.
Test steps:
1. Start the timer for a task A from history.
2. Work for an interval longer than notification interval
3. Go to a web page and start another task using browser plugin

Expected:
No notifications, as task are switched without any intermediate period of inactivity (I never pressed Stop button).

Actual:
A reminder to track time appears immediately after a click on Start timer link in browser.

**Comment by IndrekV** [comment]
Thank you @basilevs for the scenario. I'm able to reproduce this and will work on a fix.
