### ISSUE TITLE
OSX High CPU usage

### ISSUE THREAD

**Issue by sl-fedegiust** [toggl/toggldesktop#2123]
Every now and then the CPU Usage gets around 50% for quite a while and makes the OS quite slow.
Also getting the beachball very often on OSX Sierra when starting a task on TogglDesktop

**Comment by IndrekV** [comment]
This should be improved in the latest beta. Could you please switch to beta channel from the about view and see if the update works better.

**Comment by dularion** [comment]
Seconded. Ill try the beta Channel and see if this fixes things

**Comment by sl-fedegiust** [comment]
I've changed the release channel to beta and works great now! Thanks @IndrekV

**Comment by IndrekV** [comment]
Thank you for getting back to me on that. Glad that it's better now. Thank you for reporting.
