### ISSUE TITLE
Timeline - Length of tracked activity/project displayed

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#2124]
Case 417339

Is there a limit of what can be displayed by timeline. This user would like to see the project totals for work in Adobe Premiere Pro but can only see directory paths, as seen in attached screenshot in case.

Thanks,

**Comment by IndrekV** [comment]
The display issue is connected to the way the web app handles showing timeline data in their UI. This is not directly connected to Toggl Desktop. We send data as we get it. We have a character limit, but it is a big one. Something like 200 characters or so. Anyhow contact web masters for an answer.
