### ISSUE TITLE
With decimal time format entry groups don't use decimal

### ISSUE THREAD

**Issue by fonorobert** [toggl/toggldesktop#2125]
When decimal time format is set in the web app Profile page, entries in the desktop app use that. Grouped entries however still use the X h Y m format.

![screen shot 2017-02-14 at 16 38 03](https://cloud.githubusercontent.com/assets/6963710/22933380/29018546-f2d4-11e6-9bed-0068a53825f2.png)

**Comment by IndrekV** [comment]
dupplicate of #2083 
This is fixed in latest beta. (v7.4.18)
