### ISSUE TITLE
Linux app doesn't pop up into focus

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#2130]
linux_native_app/7.4.7
logs: #427819

> When I use the shortcut to get to Toggl, the window doesn&#39;t pop up into focus, even with the preference set to do so. I have to manually switch to the Toggl window.  If I press the short cut 3 times, it appears in focus after the 3rd time (after appearing behind my windows after the first shortcut, disappearing after the second)

**Comment by IndrekV** [comment]
User reported. System update and restart fixed the issue.
