### ISSUE TITLE
Tracking reminders not appearing

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#2131]
windows_native_app/7.4.18 logs: #429759
User reports that although he has set up the reminders they are not appearing for him.

**Comment by jayvdb** [comment]
Which version of Windows?
c.f. https://github.com/toggl/toggldesktop/issues/2133

**Comment by IndrekV** [comment]
It's not said in details what exact version of Windows this is happening but I think this issue is a duplicate as I checked Win7 and could not replicate.
