### ISSUE TITLE
Reminder not working

### ISSUE THREAD

**Issue by Fajrfighter** [toggl/toggldesktop#2133]
I have set the desktop app to remind me every 10 min if I am not tracking time from 9:00 to 18:00 Monday-Friday. I have not received any reminder. 

Windows 10.

**Comment by chrisregner-com** [comment]
+1, doesn't remind me either on Windows 10.

**Comment by yunooo** [comment]
+1，Never reminded

**Comment by subinsahu** [comment]
Doesn't remind me on Windows 7.

**Comment by LiekeG** [comment]
+1, does not remind me. It used to work fine on my old laptop, also Windows 10, but then I switched to another one (Windows 10) and the newly installed Toggl desktop app reminders don't appear anymore even though the settings show they are turned on. Idle detection works fine, on the other hand.

**Comment by ricotheque** [comment]
Reminders not working for /conversation/17988814255

Windows 10, 7.4.231

**Comment by maritoggl** [comment]
+1 conversations/18627610175 (logs available)

**Comment by marcooosd** [comment]
Also have never received a reminder. Would love it if this feature could be fixed!

**Comment by nidarasheed** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/22667832385)
