### ISSUE TITLE
Debounce the keypresses during autosearch

### ISSUE THREAD

**Issue by timgaunt** [toggl/toggldesktop#2134]
I generally have a lot of entries so performance of the desktop app is slow unless I clear the cache and start again (not something I really want to do each day) but I know that's being sorted elsewhere. Another thing you could do to improve this is debounce the keypresses and cancel the previous search.

What I find is when typing the entry in, it triggers the search on the first keypress -but by the time it's got through the search for "E" I've typed "Emails", the search results for "E" return and reset my entry (which never actually appears as I type) which is frustrating as I can reduce the search parameters dramatically.

What we generally do with search fields is add a 50-100ms wait after a keypress before triggering the search (that's web so you'll probably want to test it so it doesn't feel sluggish) but the idea is you cancel the timeout between keypresses so you don't search until the user is done typing. 

That and cancel the previous search so it shows me the refined list straight away...

The debounce may need to be re-thought slightly considering it's a desktop app and needs to feel nippy but it may be worth searching on the 3rd cancellation (third letter).

May all be resolved when you limit the number of items in the cache I guess.

**Comment by IndrekV** [comment]
What operating system are you using?

**Comment by timgaunt** [comment]
I'm running Windows 10 on a Microsoft Surface with 16GB RAM :)

**Comment by w00kie86** [comment]
also happens on windows 7

**Comment by IndrekV** [comment]
Fixed with new autocomplete #2042
