### ISSUE TITLE
AppStore version outdated

### ISSUE THREAD

**Issue by 4brunu** [toggl/toggldesktop#2136]
Hi,

I use toggl for macOS, and I installed from the Mac AppStore, but the app is outdated, the last update was 2016-11-01, version [7.3.347](https://itunes.apple.com/pt/app/toggl-desktop/id957734279?mt=12).

But in your [change log page](https://toggl.github.io/toggldesktop/#mac), the last release was 2017-03-03, version [7.4.18](https://toggl.github.io/toggldesktop/#mac/7.4.18).

Could you please update the Mac AppStore version?
Because I'm having some syncing issue, that I think are solved in the last release.

Thanks

**Comment by IndrekV** [comment]
Thank you for your feedback. We know the AppStore is a bit behind. We've pushed a new version to the AppStore.
