### ISSUE TITLE
App won't launch after installing it with Enterprise installer

### ISSUE THREAD

**Issue by zdericnina** [toggl/toggldesktop#2138]
User needed a Toggl Desktop which would install in Program Files (or a different location) so all users on the Desktop could use it when logged in. We recommended Enterprise installer but after the installation, the app won't launch and it gives Appcrash errors:

> Problem signature:
> Problem Event Name: APPCRASH
> Application Name: TogglDesktop.exe
> Application Version: 7.4.18.0
> Application Timestamp: 589c712a
> Fault Module Name: MSVCR120.dll
> Fault Module Version: 12.0.21005.1
> Fault Module Timestamp: 524f7ce6
> Exception Code: 40000015
> Exception Offset: 000a7676
> OS Version: 6.1.7601.2.1.0.256.4
> Locale ID: 1061
> Additional Information 1: dd93
> Additional Information 2: dd93ef6d3211883182d4a88a8c8fe85f
> Additional Information 3: a482
> Additional Information 4: a4827a939525efa4460f70a46490d84c

Case #434827

**Comment by nicktoggl** [comment]
case/434134

**Comment by IndrekV** [comment]
will be fixed with #2955
