### ISSUE TITLE
Stretched editing window, Mac

### ISSUE THREAD

**Issue by wturrell** [toggl/toggldesktop#2140]
(This could well be a duplicate but I couldn't find one.)

Toggl renders editing windows incorrectly (content vertically stretched with uppermost inputs not visible.)  See attached screenshot.  Not sure of exact trigger, typically happens a few hours after app launched.  Closing and restarting app always fixes.  Not a new problem (i.e. have seen prior to 7.4.18)

Toggl Desktop 7.4.18
OS X 10.11.6 (El Capitan)

![toggl-desktop-display-bug](https://cloud.githubusercontent.com/assets/848021/23702277/73d1d970-03f2-11e7-96a5-3de12322e2e6.png)

**Comment by rmelgar** [comment]
I have the same problem

**Comment by IndrekV** [comment]
This issue is a difficult one. We've done some tests and have managed to see the issue only on 15 inch Macbook pro. The issue is not consistent and can not be replicated reliably to see what causes this. Any details you might have noticed that could cause this are welcome.

**Comment by rmelgar** [comment]
Well, I'm also using El Capitan, OS X 10.11.2. My Toggl version is 7.4.31. If I notice any actions that triggers this problem I'll let you know.

**Comment by wturrell** [comment]
Re: display - I mainly use a Mac Mini (2012) with an external Dell monitor (non-retina), 1920x1200.

**Comment by IndrekV** [comment]
This is a pretty old issue and we have totally reworked all the constraints that set this view into place. Since then we have not received any feedback about this issue appearing.
