### ISSUE TITLE
Laggy entries

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#2143]
case/438996 Video of problem in case,

"I have the Toggl desktop app installed on my work and home desktops. The app works great as long as I already have a task created from a previous time and I simply push the play button. The problem happens when I start a new empty task and try to type in a description. It allows me to type one or two letters and then it pauses for at least 20-30 seconds. Then it will let me type in two more letters. After about 40 seconds, it allows me to freely type in the full description."

"I unistalled the app and deleted the folder in the LocalApp Data. I 
reinstalled it and it still has the same problems."

"I cleared the cache and logged back into the desktop app and it took 
more than 40 seconds to allow me to type in a new task today. The delay 
is very annoying."

**Comment by IndrekV** [comment]
Connected to #2251

**Comment by IndrekV** [comment]
closed together with #2042 Will be released to beta next week
