### ISSUE TITLE
Autocomplete data from older entries should fill tags data

### ISSUE THREAD

**Issue by diegoquintanav** [toggl/toggldesktop#2144]
Whenever I write a new task that is the same as one I've used before, there is an autocomplete feature that works really nice. It fills Project, Description and Client data, but it won't fill the former used tags and they have to be input again, this leads to different groups of tags for the same entry because people forgets.

I don't know if autocompletion reuses the id of the entry (API responses hav several ids with the same name for different urls, so I guess I am talking about an entry id), but implementing autocomplete based on this parameter would be also a good idea.

This would be a nice feature to add since tags can be used for more complex classification schemes, thus making them easier to fill is always an improvement.

**Comment by IndrekV** [comment]
Could you please specify which platform you are using. This issue (#2107) was fixed for mac with the latest release (7.4.18)

**Comment by diegoquintanav** [comment]
Win7@x64, it seems that issue was fixed for MacOS only.

2017-03-16 4:06 GMT-03:00 Indrek V <notifications@github.com>:

**Comment by IndrekV** [comment]
Fixed in the latest beta release [7.4.31](https://github.com/toggl/toggldesktop/releases/tag/v7.4.31)

**Comment by diegoquintanav** [comment]
Thanks, I will check it out

2017-03-30 10:49 GMT-03:00 Indrek V <notifications@github.com>:
