### ISSUE TITLE
Timeline doesn't recognize Internet Explorer in Windows 7

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggldesktop#2145]
A user running Windows 7 can't see Internet Explorer inside his Timeline data. The entries are empty (with just the time). You can see the screenshots inside Desk case 439313. 

I ran some tests on Windows 10 and Timeline tracked IE correctly. Here's a screenshot from my test
![screen_shot_2017_03_14_at_14 58 41](https://cloud.githubusercontent.com/assets/19473351/23997115/56140a2a-0a50-11e7-8351-6e08485a964a.png)

---
Case 439313

**Comment by skel35** [comment]
Probably fixed with 64-bit release
