### ISSUE TITLE
Toggl Desktop on Mac cannot fetch projects with names starting with a digit

### ISSUE THREAD

**Issue by blaze182** [toggl/toggldesktop#2148]
Not sure if it's a client or backend api issue, but I cannot see any of the projects having a digit as a first symbol in their name.

Even if I assign this kind of project via Toggl Web, it still renders as empty in Toggl Desktop for Mac. Did full resync as well with no luck.

**Comment by IndrekV** [comment]
I've tested this and am not able to reproduce it. Could you please send feedback from the desktop app. That way we get logs and details about your account and can investigate this further.

**Comment by blaze182** [comment]
Hi @IndrekV, thank you for the reply,
I've just sent a feedback as you've asked

**Comment by blaze182** [comment]
Looks like running "Clear cache" in v.7.4.11 solved the issue for me. Thank you for the great product :)
