### ISSUE TITLE
Install (or symlink) the starter script under /usr/bin/

### ISSUE THREAD

**Issue by atleta** [toggl/toggldesktop#2150]
Hi,

Please install the starter script (and name it toggle or toggldesktop instead of camelcase + the .sh extension) into /usr/bin/ . Or place a symlink there pointing to the current script. To make it easy to start from the command line. (Yeah, I know, most of the time you'll just add it to the session, but still..)

**Comment by IndrekV** [comment]
Thank you for your suggestion currently the Deb package adds the app under /opt/toggldesktop and also creates `.desktop` shortcut. We'll look into this to see how we can improve.

**Comment by MartinBriza** [comment]
Improved along with the CMake changes.
