### ISSUE TITLE
Add keyboard shortcuts to cover all basic workflow tasks on linux

### ISSUE THREAD

**Issue by atleta** [toggl/toggldesktop#2151]
Hi,

Please make the app easier to use with the keyboard, as this would make it a LOT more convenient to use and give it an edge over the web UI. I've just submitted a feedback from the app asking for a global shortcut to open it, just to find it in the preferences 5 minutes later. Maybe it should show a popup on first start explaining how to set it (and that the feature is there). Still, a few things are missing to make it convenient for a developer (or anyone, mostly doing typing):
- after focusing the app, it should have the cursor in the 'what are you doing' field, so that I can just start typing what I am doing, instead of having to click-click-click between activating it with the keyboard shortcut and typing the text (with the keyboard)
- a shortcut to discard the currently running entry would be nice. Now it's pretty inconvenient and a lot of mousing (a new dialog opens, delete button at the bottom, new popup asks me if I'm sure).

**Comment by IndrekV** [comment]
Thank you for the suggestions. We will consider this when planning our next linux developments.

I totally agree with the first point. The focus should be in the description field when focusing the app.

The second point could be improved if we add a key shortcut that show the popup "Are you sure you want to discard running item?" right away avoiding the need to go to edit view and click delete icon in the bottom.
