### ISSUE TITLE
Make entering the project/client possible on the main view in linux

### ISSUE THREAD

**Issue by atleta** [toggl/toggldesktop#2152]
Hi,

Please make it possible to enter the project/client on the main view, as opposed to having to open a separate dialog (which needs mousing, where navigation inside the dialog also needs mousing). A better flow would be if after pressing enter in the 'what are are you doing' field, the focus would jump to the project field (to be added) and the next enter would start the timer. The project field could be initialized with the value from the last task, so that starting a new task on the same project would just need a second enter, as opposed to what the case is now:
- Click to fill in the task description, enter to start it
- click again to go to the task setting detail dialog
- click again to focus the project field (b/c by default no element is focused!)
- and then be able to type the project
- then click done again, because the dialog doesn't have a default button

Also, the combo box showing the projects could be a bit more intelligent (not sure how much extra work that is with Qt, but there could be 3rd party components doing this if needed): instead of a simple autocomplete, it should open the drop down at minimum, when starting to type and ideally show a filtered list of items to make choosing simpler. (Similar to how it works on the web, even if not looking that fancy.)

**Comment by IndrekV** [comment]
Currently starting a previous task can be done using the autocomplete feature of the timer description view.

Fair points you have there. The autocomplete element could be better to support more data not just a single line of text. We'll keep these ideas in mind when planning our next steps in linux. 

Thank you for your detailed description of the issues.

**Comment by MartinBriza** [comment]
While this is not possible from the main screen directly, improved keyboard support has been implemented and one can access the running task by just pressing ctrl+enter and then modifying the time entry "from inside".
Also, choosing a previously existing time entry now fills the project/task fields in the timer widget on the front screen.
