### ISSUE TITLE
Default button in the entry edit dialog on linux

### ISSUE THREAD

**Issue by atleta** [toggl/toggldesktop#2153]
Hi, 

Please make the done button the default, so that the dialog can be closed (and data saved) by hitting enter. Also, please add cancel button and make sure it's tied to the 'Esc' key as well. It comes in handy every once in a while :).

  Thanks,
     Laszlo

**Comment by sojusnik** [comment]
Imho, the focus should stay on the task field, but a shortcut for "done" like "ctrl+enter" would be very handy indeed! "Esc" or "Del" could be connected to "delete".
