### ISSUE TITLE
Use native notifications on Linux

### ISSUE THREAD

**Issue by sojusnik** [toggl/toggldesktop#2155]
Would be very convenient to have native notifications on Linux, f.i. on Ubuntu Gnome with [libnotify](https://developer.gnome.org/libnotify/), like shown [here](https://blogs.gnome.org/aday/files/2015/02/banner-screenshot-small.png).

Those notifications could show:

1. Start and end of a toggl respectively (with the name of the task, project and duration), when using shortcuts
2. End of a pomodoro (with an option to continue or to have a break)
3. End of a brake, when using the pomodoro timer
4. Idle detection message
5. Reminder to use toggl, if enabled in the options

**Comment by IndrekV** [comment]
Thank you for the suggestion. We'll consider this. We will test how different distros work with libnotify and if all is good I see no reason why not give it a go.

**Comment by jayvdb** [comment]
Probably would be good to solve https://github.com/toggl/toggldesktop/issues/1889 and https://github.com/toggl/toggldesktop/issues/1799 before switching to using native notifications on Linux.

**Comment by ivanfromtheroot** [comment]
+1 would be great!

**Comment by jazzdragon** [comment]
Any updates on this? I'm getting the toggl reminder in an alert box on the desktop, which I have to actively address when happens. I'd disable it, but it actually reminds me a lot to track my time...

**Comment by IndrekV** [comment]
Similar to #1876

**Comment by IndrekV** [comment]
Fixed with #2654
