### ISSUE TITLE
Windows sync issue 7.4.18

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#2156]
/case/447400 - 2nd occurrence in 2 months despite newest version, logs included

**Comment by IndrekV** [comment]
@nicktoggl This is caused by a large amount of unsynced entries. Current fix is to export data from local database and import csv. 

This fix is next on my list so in few weeks we should get this issue fixed.

**Comment by IndrekV** [comment]
This is fixed with converting to api v9 #2047

**Comment by IndrekV** [comment]
Updated version will be in beta today.

**Comment by IndrekV** [comment]
Beta release will be next week as some scenarios still need testing.
