### ISSUE TITLE
Timeline not working under Ubuntu

### ISSUE THREAD

**Issue by sojusnik** [toggl/toggldesktop#2157]
Although "record timeline" is enabled in the desktop client under Ubuntu Gnome 16.10, I can't see any websites and programs in the timeline overview, as described [here](https://support.toggl.com/timeline/).

Tried with Firefox 52.0.2 and Opera 44.0.2510.857. The toggle client has the version 7.4.24.

**Comment by IndrekV** [comment]
Timeline data is sent in 15 minute interval so the first data should appear online after first 15 minutes. If this is not the case and data is still not appearing, please send feedback from the app and mention that It is for Indrek. That way I'll see some additional logs and can look into it.

**Comment by nicktoggl** [comment]
@IndrekV /case/450751 logs

**Comment by IndrekV** [comment]
Logs show that timeline tracking and data sending to server works as expected. The issue is with settings in web app or with rendering the timeline graph.

**Comment by sojusnik** [comment]
I've tried again with Firefox 52.0.2 (64-Bit) even in safe mode (all add-ons are disabled) under Ubuntu Gnome 16.10, but can't see any details in the timeline, as depicted [here](https://support.toggl.com/timeline/). My timeline looks like [this](https://i.imgur.com/OQpXeKk.png).

Doesn't work under Opera 44.0.2510.857 too.

**Comment by sojusnik** [comment]
After some tweaking from a toggl developer, the timeline is now correctly depicted. Thanks!

**Comment by dreamy-sk** [comment]
Could you be a bit more specific about the "tweaking", please? I believe I am having similar problem under Debian 9.

**Comment by sojusnik** [comment]
@dreamy-sk for clarification: the tweaking part was done on toggl's side, not mines.

**Comment by dreamy-sk** [comment]
Oh, thanks; then I guess I should submit a new issue.
