### ISSUE TITLE
App creates numerous duplicate entries

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#2164]
windows_native_app/7.4.32 logs: 454346

> Since I downloaded release 7.4.32 some time entries are being duplicated. It seems to be an incorrect behaviour after idle detection, I guess (perhaps when I choose &#34;Discard time and continue&#34; it duplicates entry, but I&#39;m not 100% sure). I mean, &#34;duplication&#34; is not the right term, app creates a new entry running on the same time window.

Duplicates can be seen in h4x, check 13.04 entries. Has been reported by one other user, waiting for logs.

**Comment by rocketmonkeys** [comment]
This is happening to me as well.  7.4.32.0.  I'm not 100% sure the scenario, but at some point the app starts logging a duplicate time entry, once per second.

So if I had an entry "working on project" that was from 10:00am to 10:15am, I'll see that exact same entry be logged multiple times.  If I have the app open for 5 minutes, I'll get 300 duplicate entries (1 per second).

Right now I have 1600 entries I'm trying to clear out from the past half hour or so.

It *might* have something to do w/ the idle box... normally I press "continue" or whatever, and it goes away.  This bug might be caused after I hit that button, it goes into crazy mode.

I can't start the app - menu is grayed out, app is locked up (I assume from the # of entries).  Where are the debug logs stored?

**Comment by Michelle112** [comment]
Above user, rocketmonkeys, provided logs here 454456.

**Comment by vedr4n** [comment]
Issue appears to be caused by the 7.4.32 dev version. It's happening on both Windows and MacOS. 

Desk case: 454631

**Comment by vedr4n** [comment]
User in desk case 454766 confirmed that downgrading to 7.4.18 fixes the issue.

**Comment by IndrekV** [comment]
Issue is caused by time entry delete request failing
