### ISSUE TITLE
LocAppHost.exe showing up in Timeline data

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggldesktop#2166]
A user wrote the following

>Hi,
>
>I think it would make sense to ignore LocAppHost.exe on Windows when recording Timeline. This is the front-most process when the machine is in locked state. 
>
>As you can see some results are merged with results from my other machine, Mac. But the LocAppHost.exe still eats all the focus.

They included a video of the problem. You can see it in case 460567.

**Comment by fonorobert** [comment]
another report about this: case 557609

**Comment by skel35** [comment]
Fixed in #3056
