### ISSUE TITLE
Clicking on a time entry in the auto-complete box initiates an edit of another TE

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggldesktop#2169]
To reproduce:

1. Start typing in the "What are you doing" field
2. Click on one of the suggested entries
3. The app will insert the TE you clicked on in the timer and open the edit window for a TE that was underneath the option you clicked on. 

![test-win](https://cloud.githubusercontent.com/assets/19473351/25648684/e0a67152-2fce-11e7-8d94-90c13286fa6a.gif)

Reporting this felt like deja vu, but I just can't locate the previous issue.  

---
Case: 463472

**Comment by IndrekV** [comment]
Similar to #1865

**Comment by fonorobert** [comment]
seems to be the same issue reported in case 470244

**Comment by vedr4n** [comment]
Another affected user in case 526159.
