### ISSUE TITLE
Clicking entry in autocomplete creates new entry on Linux

### ISSUE THREAD

**Issue by fonorobert** [toggl/toggldesktop#2170]
Steps:

- type part of a description of a recent entry
- click the entry in the dropdown

expected:
description field gets copied, same project gets selected

what happens:
the project does get selected, description field will have both the original description and a copy of the project's name, resulting in a new entry that's not grouped with the original one (since description is not the same)

![image](https://cloud.githubusercontent.com/assets/6963710/25656205/2b217d34-2ff8-11e7-8271-7861f2c71543.png)

Issue is not present when using keyboard to select entry from the autocomplete.

reported from Kubuntu 16.10, confirmed both there and on vanilla Ubuntu 16.04

**Comment by IndrekV** [comment]
Similar to #1825

**Comment by fonorobert** [comment]
So similar it's the same :) closing
