### ISSUE TITLE
App window completely transparent

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggldesktop#2171]
A Windows user is reporting that the main app window is completely transparent. They already tried reinstalling and clearing the local db, nothing helped. 

![toggl desktop not working](https://cloud.githubusercontent.com/assets/19473351/25691468/95408c5c-309b-11e7-9a0f-20e1e4e86c80.jpg)

---
Case: 460087

**Comment by IndrekV** [comment]
Probably issue with config file corruption. 
Clearing everything from folder
```
C:\Users\[user]\AppData\Local\Toggl\
```

should do the trick. @vedr4n I answered the user.

**Comment by fonorobert** [comment]
@IndrekV user is reporting the issue is still present after clearing the local folder.

**Comment by kadrihvl** [comment]
User is still struggling with this issue - @IndrekV any other suggestions? Case #460087

**Comment by TheSoloJake** [comment]
Desk case/727074 is experiencing this issue, even after multiple uninstalls/cache clears/reinstalls of the latest stable version (.184). 

Windows version: 10, version 1803
Device: Surface Pro 3 (w/multiple displays, if that helps)

**Comment by IndrekV** [comment]
duplicate of #2208
See this comment for possible workaround
https://github.com/toggl/toggldesktop/issues/2208#issuecomment-404445700

**Comment by IndrekV** [comment]
closed together with #2208
