### ISSUE TITLE
Timeline not recording

### ISSUE THREAD

**Issue by gabrielcarioca** [toggl/toggldesktop#2180]
Well, I tried everything is written about starting the timeline recording. I activated it in the app preferences, I opened the timeline in the web (below the play button), I tried doing this in different orders, I tried logging out and in and my timeline shows nothing in the website, only the generic wave pattern it started with (nothing similar as the bars from the timeline in the support page). I can't see what was recorded or if it was actually recorded in the first place. I don't know if it is a problem with the web, the web, permission. I'm in Windows 10. Don't know if it is a problem (I tried only for some minutes with only one), but I'm using two monitors.

**Comment by TheSoloJake** [comment]
Hello @gabrielcarioca ! Please email us at support@toggl.com using your Toggl email address so we can help you out.

Thanks!

**Comment by gabrielcarioca** [comment]
In the end I only had to have asked the support to enable the feature on their end.
