### ISSUE TITLE
App crashing right on launch

### ISSUE THREAD

**Issue by fonorobert** [toggl/toggldesktop#2181]
User from Win 10 reports the app crashes immediately on launch. Tries reinstalling, clearing local data.
desk case 475853 has Windows Event Viewer logs.

**Comment by calraiden** [comment]
I have similar problem, after update Win 10, my toggl always crash after open.
I try debug in the Visual Studio, but only see the error: 

```
System.ComponentModel.Win32Exception was unhandled
Message: An unhandled exception of type 'System.ComponentModel.Win32Exception' occurred in WindowsBase.dll
Additional information: O identificador da janela é inválido
```

![image](https://user-images.githubusercontent.com/1984844/26927514-97fc3a42-4c28-11e7-906d-2b0293575a60.png)

![image](https://user-images.githubusercontent.com/1984844/26927521-a05aee4a-4c28-11e7-88b9-2ba4577af6de.png)

**Comment by IndrekV** [comment]
Closing as issue out of date and has not been reported recently.
