### ISSUE TITLE
Toggl Desktop starting on its own, not allowing user to select a Project or input description

### ISSUE THREAD

**Issue by zdericnina** [toggl/toggldesktop#2185]
> Using Toggl Desktop seems to start and stop projects, not always allowing me to select projects and not always saving description. It's starting and stopping time entries on its own, without the user doing anything in the desktop app or the web app. He is seeing these issues often, every 2nd-3rd entry. I can click on a project type using the dropdown however it doesn't save and blanks it all out and goes back to 'No Description' where I have to enter again.

He tried clearing out the local data and using both the latest beta and stable version, the result is the same.

Case #478178

**Comment by kadrihvl** [comment]
Similar case with logs: #479807

**Comment by zdericnina** [comment]
Similar case with logs: #480085

**Comment by TheSoloJake** [comment]
Similar case #480413

**Comment by nicktoggl** [comment]
case/481169

**Comment by nicktoggl** [comment]
case/480410

**Comment by nicktoggl** [comment]
case/481294

**Comment by nicktoggl** [comment]
/case/481189 with video

**Comment by nicktoggl** [comment]
/agent/case/481272

**Comment by ApocalypticFish** [comment]
agent/case/478105

**Comment by nicktoggl** [comment]
possibly similar? case/481276

**Comment by nicktoggl** [comment]
case/481314

**Comment by nicktoggl** [comment]
case/481322

**Comment by nicktoggl** [comment]
case/481336

**Comment by nicktoggl** [comment]
case/481334

**Comment by zdericnina** [comment]
Case/481348

**Comment by zdericnina** [comment]
Case/481354

**Comment by IndrekV** [comment]
I've created a fix for this issue. I would appreciate if someone could verify that the fix works properly. Get the latest version from:

Mac: [TogglDesktop-7_4_42.dmg](https://github.com/toggl/toggldesktop/releases/download/v7.4.42/TogglDesktop-7_4_42.dmg)
Windows: [TogglDesktopInstaller-7.4.42.exe](https://github.com/toggl/toggldesktop/releases/download/v7.4.42/TogglDesktopInstaller-7.4.42.exe)

**Comment by belazor** [comment]
@IndrekV no, this does not work (macOS). The Projects drop-down is not in sync with the website, and  anything you type in the Projects box does not reflect on the website.

Updating from 7.4.31 to 7.4.42 has made the desktop app 100% useless for tracking time.

**Comment by ApocalypticFish** [comment]
case/481786

**Comment by ApocalypticFish** [comment]
case/481786

**Comment by ApocalypticFish** [comment]
Still experiencing the same issue with Windows 7.4.42

Projects will be shown in the drop down, then will disappear several seconds later or on a second click of the dropdown window. 

Tags aren't showing at all.

**Comment by ApocalypticFish** [comment]
case/481793

Desktop has allowed user to create a time entry in a workspace he was removed from in 2015

**Comment by TheSoloJake** [comment]
case/482034

Issue persists "but not as often" in beta version. Case includes desktop logs

**Comment by TheSoloJake** [comment]
case/481729

Again, issue persists after installing beta version, but not as often. Case includes desktop logs

**Comment by TheSoloJake** [comment]
case/481823 having less problems, but still there. Case includes desktop logs

**Comment by ApocalypticFish** [comment]
case/482173 Client has downloaded latest Windows version from provided link but is still experiencing issues.

**Comment by ApocalypticFish** [comment]
/case/484252 Client has downloaded the latest version, has reported the issue happening less often but still happening.

**Comment by IndrekV** [comment]
There is new fixed version that seems to be saving correctly. It sometimes flickers and shows the old value, but actually it saves the new value just fine. I will look more into it.

You can get the fixed version from: 
Mac: [TogglDesktop-7_4_45.dmg](https://github.com/toggl/toggldesktop/releases/download/v7.4.45/TogglDesktop-7_4_45.dmg)

Windows:
[TogglDesktopInstaller-7.4.45.exe](https://github.com/toggl/toggldesktop/releases/download/v7.4.45/TogglDesktopInstaller-7.4.45.exe)

Linux:
[toggldesktop_linux_x86_64-7_4_45.tar.gz](https://github.com/toggl/toggldesktop/releases/download/v7.4.45/toggldesktop_linux_x86_64-7_4_45.tar.gz)

**Comment by ApocalypticFish** [comment]
Customer using Mac version 7_4_45 and is still reporting issues case/486048

**Comment by ApocalypticFish** [comment]
case/486556

**Comment by ApocalypticFish** [comment]
case/486953

**Comment by ApocalypticFish** [comment]
case/484329 description field on mac app blanking out whenever trying to write in it.

**Comment by ApocalypticFish** [comment]
case/486973

**Comment by ApocalypticFish** [comment]
case/486956 This user has reported that the updated version has resolved their issue.

**Comment by zdericnina** [comment]
Case/482240

User wrote in:
> I think the problem occurs when the user clicks out of a field with the mouse rather than pressing return. This happens with the version you sent me.

**Comment by zdericnina** [comment]
Case/486993

**Comment by ApocalypticFish** [comment]
case/487002 Includes logs from version 7.4.45
User needs to click stop button at least twice otherwise it will continue.

**Comment by IndrekV** [comment]
We've released a new beta version that addresses the flickering issue. Please get the latest beta (7.4.47) by switching to beta channel from the About view

**Comment by IndrekV** [comment]
7.4.47 seems to be working ok. Pushed 7.4.47 to stable.

**Comment by ApocalypticFish** [comment]
case/487484 Mac Version 7.4.47 Reporting project still disappearing from the main timer window and timer scrolling to the bottom of the list.

**Comment by ApocalypticFish** [comment]
case/487085 Mac 7.4.47 User wrote in: 
"Pressing command-N when Toggl is in focus creates
a new item but doesn't bring up a dialog box. Clicking on the new item
opens the dialog box, but hitting enter after entering information doesn't
close it. Have to use the mouse. Also inconvenient that autocomplete is not fully implemented. Starting to
type a project brings up a pick list, but does not fill in the closest
match so that you can just hit enter or tab to complete it. You have to
arrow down to the entry in the list to select it, even if it is the only
matching item."

**Comment by nicktoggl** [comment]
/case/487534 again only with Mac Desktop

**Comment by nicktoggl** [comment]
/case/487347 - Mac Desktop

**Comment by zdericnina** [comment]
Case/487844 Mac desktop
Case/487852 Mac desktop
Case/487856 Mac desktop

**Comment by IndrekV** [comment]
Seems to be fixed with current stable 7.4.52
