### ISSUE TITLE
Toggl Offline

### ISSUE THREAD

**Issue by HppyfaceKR** [toggl/toggldesktop#2189]
My toggl desktop app keeps saying it's offline and not updating the time accurately on the web tool. I do dock and un-dock my laptop all the time, so could that be the issue, or would a hard restart fix it?

**Comment by IndrekV** [comment]
Please try to send feedback from the app. That way we get logs and all the info about the app and can look more into it. Please mention that Indrek asked for the logs.

**Comment by HppyfaceKR** [comment]
Thank you!

Katie Nafius
512.634.3659

**Comment by IndrekV** [comment]
Probably long fixed with rewritten sync
