### ISSUE TITLE
Add Toggl to the Windows 10 App Store

### ISSUE THREAD

**Issue by JacobDB** [toggl/toggldesktop#2203]
Using [Desktop App Converter](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-run-desktop-app-converter), it should be relatively easy to package this up and serve it on the Windows 10 Store. This is great for discoverability and automatic updates. 

If you do add it to the store, I'd recommend you add nice "Windows 10-style" icons for the taskbar & start menu. I use a custom one currently, which I've attached below.

**Screenshot:**

![image](https://user-images.githubusercontent.com/1123997/27353643-5d332032-55ca-11e7-84b8-faaf8d7519b9.png)

**Icon (hard to see because it's white on white):**

![toggl](https://user-images.githubusercontent.com/1123997/27353661-752f6402-55ca-11e7-8c9e-d9a453c79a01.png)

For the start menu tile, I'd recommend using `#F30C16` as the background, the same red you use on your website :)

**Comment by IndrekV** [comment]
Thank you for the heads up. We'll look into this possibility.

**Comment by kristian-b** [comment]
Any news here? It would be great to have this app in the Microsoft Store.

**Comment by IndrekV** [comment]
This is not in our near future plans so there's no progress on this matter. We have not taken it off the table however so there's hope that this will be handled sometime in the future. I do thank you for showing your support on this issue.

**Comment by kristian-b** [comment]
Thank you very much for your reply.

To give you some background information why I asked: In our company we are deploying software via the [Microsoft Store for Business](https://businessstore.microsoft.com/de-de/store). That is a very easy solution to manage software for non-it-professionals. For that it would be great if toggle desktop would be available also.

You have placed toggle also in the Mac AppStore and in my understanding the limitations and requirements for an App are similar at Mac AppStore and Microsoft Store (no admin rights for the app, etc.). May be the Conversion via the [Desktop App Converter](https://developer.microsoft.com/en-us/windows/bridges/desktop) is a simple thing for this project?

**Comment by kristian-b** [comment]
Hello @IndrekV ,

may be it is also an option to publish the web app to the store as PWA?
https://blogs.windows.com/msedgedev/2018/02/06/welcoming-progressive-web-apps-edge-windows-10/

**Comment by IndrekV** [comment]
Thank you for the suggestion, but I don't think we'll go with the PWA solution. We'll evaluate if Windows Store is the way to go and go on from there with the Desktop App Converter if we decide to do it.

**Comment by ngodber** [comment]
Just like to add my voice to the chorus or alternatively some form of self-update functionality. But of those two windows store would seem the logical choice.

**Comment by IndrekV** [comment]
Windows app is now available in Microsoft Store https://www.microsoft.com/en-us/p/toggl-desktop/9nk3rf9nbjnp

**Comment by kristian-b** [comment]
Thank you very much. It works good!
