### ISSUE TITLE
Mac app crashing even after the newest update

### ISSUE THREAD

**Issue by zdericnina** [toggl/toggldesktop#2209]
> I&#39;m having difficulty using the desktop app on mac, every time I open the app it freezes and quits immediately.

User cleared out the cache manually, installed the new version and it still crashes. 

Case/492392

**Comment by IndrekV** [comment]
This crash is caused by large amount of account data. Will look for a fix.

**Comment by voipmeister** [comment]
+1 here, using 7.4.52 on macOS 10.12.6

Upon launch, the app crashes sometimes. Looks like it's minimized, but the main window can't be maximized.

Experiencing a lot of crashes on exit, the app almost always crashes and needs help via activity monitor > force quit (waiting doesn't help). Please note that the minor macOS version doesn't really matter, I had this before 10.12.6 as well.

Should you need additional info, please let me know.

**Comment by stranljip** [comment]
I also experience the problem, that I have to force quit the app regularly. I attach a file with the Apple diagnostic in the hope that it helps.
[toggl-crash-information.txt](https://github.com/toggl/toggldesktop/files/1288773/toggl-crash-information.txt)

**Comment by IndrekV** [comment]
Connected to #2251

**Comment by IndrekV** [comment]
Fixed with library data handling rewrite
