### ISSUE TITLE
Sometimes app doesn't quit properly. (Windows)

### ISSUE THREAD

**Issue by Trost123** [toggl/toggldesktop#2210]
It's not consistent, but sometimes when I exit Toggl Desktop, it disappears from system tray, but stays in processes.
What's more annoying is that I can't launch Toggl Desktop until I reboot or kill the process manually.
If I try to launch a new instance, while old one is running, sometimes I get an error (I didn't screenshot it, will add it if I encounter it again).

**Comment by nicktoggl** [comment]
Similar issue to #2201 but on Windows

**Comment by IndrekV** [comment]
Probably issue with the syncing activity. We will have to start syncing activity on demand and keep it closed when not needed.

**Comment by Trost123** [comment]
God, this is annoying. 😠 
Happens to me almost every day now. Plz look into it.

**Comment by IndrekV** [comment]
the issue 2201 is already fixed but not released. If testing goes well we'll push the new version to beta tomorrow. Thank you for your patience.

**Comment by Trost123** [comment]
Updated, now I get a crash instead of silent fail.
[Sceenshot.](http://prntscr.com/g7ymgd)
