### ISSUE TITLE
Missing project from the Desktop app on Macbook

### ISSUE THREAD

**Issue by zdericnina** [toggl/toggldesktop#2212]
User agent: osx_native_app/7.4.52
Version: 7.4.52
UpdateChannel: beta

> On the Mac Desktop app on my Macbook, one Project (Discipleship Book) just isn't showing up. I can't choose it, I can't see it — it's like it doesn't exist. The weird thing is that it works perfectly fine on the work iMac and on my iPhone SE. I've tried deleting the app, clearing all the Library files I could find (in the hidden library and the system library) and reinstalling it, but it didn't change anything. (the screenshot is of the Macbook on the left, and the iMac on the right) 

Screenshot in the case: #497345

**Comment by IndrekV** [comment]
Similar to #2219
