### ISSUE TITLE
Choice of development language

### ISSUE THREAD

**Issue by chriscz** [toggl/toggldesktop#2215]
Hey guys,

I don't want to start a language debate
But I am really curious why the toggle desktop client is developed in C++ and not in a language such as Java, golang or Python?

- Could it be due to the runtime requirements being less or simpler to install? 
- Are there any other languages you considered? If so why did you choose not to go with them.
- Experiences so far developing in C++?

**Comment by nicktoggl** [comment]
Hi Chris,

The person best able to answer these questions is currently on vacation so there may be a delay of a few weeks before he'll get back to you.
Hopefully he'll have some answers for you soon.

Thanks.

**Comment by IndrekV** [comment]
Hey @chriscz !

I'll gladly try to explain how we got to the decision we made.

The most important criteria when starting the Toggl Desktop 7 was that the app had to be native. The previous versions of Toggl Desktops were kind of hybrid with web technologies combined with native.

So it had to be native and it had to be cross platform. This meant we wanted to create as much sharable code as we can. In a sense we have 4 different parts in Toggl Desktop:
- Library (written in c++ and shared across all platforms)
- Windows UI, written with WPF (C#)
- Mac UI, written in Objective-C
- Linux UI, written with Qt (C++)

As for other languages. We didn't really consider any. We do love Golang in Toggl and use it in our API but at the time of starting Toggl Desktop there were not good examples of Golang being used in production desktop applications so we decided to go with C++.

As with all languages, C++ has it's pros and cons. The pros are that it is low level, powerful and it is fast. You can do complex things with large amounts of data really fast. The biggest con is that everything is done manually and sometimes doing simple things can be really complicated. Now when looking back at the decision I think we made the right one as the full package works well together and has allowed us to create a great product.

**Comment by chriscz** [comment]
Thank @IndrekV !
