### ISSUE TITLE
No icon in notification area

### ISSUE THREAD

**Issue by basilevs** [toggl/toggldesktop#2220]
Application does not show notification area icon if started with environment (or on environment restoration)

Test steps:
- install Xfce
- start TogglDesktop
- ensure its icon is shown in notification area
- relogin in Xfce

Expected: 
Notification are shows Toggl icon

Actual:
TogglDesktop is restarted (shows up in process list), but shows no icon

This is a regress in TogglDesktop for Linux 7.4.52, earlier versions were able to show icon on desktop environment restore.

Workaround:
restart TogglDesktop, it will show icon
```
killall TogglDesktop
/opt/toggldesktop/TogglDesktop.sh
```

I have not tested with other desktop environments, but they could be affected too.

UPDATE 1:
May be caused  by shutdown trouble. Application fails to quit when requested by either user or OS.

**Comment by basilevs** [comment]
Suddenly, can't reproduce anymore. Will reopen, when more information is available.

**Comment by basilevs** [comment]
This happens every time if Xfce is started long after logout (I login next day and see no icon, just process).

**Comment by IndrekV** [comment]
Seems to be duplicate of #1645

**Comment by basilevs** [comment]
Closed as duplicate
