### ISSUE TITLE
Toggl crash on logout

### ISSUE THREAD

**Issue by dshamim** [toggl/toggldesktop#2222]
clicking logout freezes toggl - windows 10 latest updates
it needs to be forced closed then restarted - at which point it has logged off

![2017-07-18_9-05-56](https://user-images.githubusercontent.com/5520081/28293633-74e8fd12-6b98-11e7-9284-8ba8beace773.png)
![2017-07-18_9-06-08](https://user-images.githubusercontent.com/5520081/28293632-74e71f92-6b98-11e7-9cee-666bddef9fd5.png)

NOTE: I do use multiple windows 10 virtual desktop -

**Comment by D3MZ** [comment]
Same issue on OSX
![](https://www.dropbox.com/s/r4suhfys72ajfbi/Screenshot%202017-08-09%2001.54.48.png?dl=1)
![](https://www.dropbox.com/s/xdrhkt9utc0nwyq/Screenshot%202017-08-09%2001.55.16.png?dl=1)

**Comment by IndrekV** [comment]
Can this be connected to the freeze issue with app quit. #2201 

If so please try the new beta version (7.4.58) as it has a fix for the quit freeze. I have not been able to replicate the logout freeze issue myself.
