### ISSUE TITLE
Automatically start toggl on login/boot

### ISSUE THREAD

**Issue by d53dave** [toggl/toggldesktop#2223]
Hello!

The toggl desktop app should really include a preference to "Start toggl at login", i.e. when I check this box, I can be sure that toggl automatically starts when I log in to my computer, i.e. after reboot.

That would be a great feature!

**Comment by IndrekV** [comment]
Hi!

Thank you for your feedback. We have decided not to add this feature as it is quite trivial to do from inside the operating system. 

Adding shortcut to the startup folder in Windows for example.

**Comment by iki** [comment]
Hi @IndrekV starting toggl desktop minimized on start is not trivial for many users, see 
https://github.com/toggl/toggldesktop/issues/542#issuecomment-368318041, and as you can see in #542 many would prefer to have it in app

**Comment by ideaalab** [comment]
Not trivial at all!
Having to do it manually its not as nice and easy as it would be to have a simple checkbox on the app itself.

**Comment by TomDobbelaere** [comment]
I second this, most windows applications have some 'start with windows' feature. They usually employ the registry or startup folder.

It's bad user experience if I have to find the windows startup folder, which isn't too easy to find, and drop Toggl in there, for it to then not even start minimized.

Slack has this option.
Discord has this option.
Steam has this option.

Now, those are all chat apps, I know, but in general you should think: is there a chance the user wants to see this every day?

If I use Toggl for my job, and I do, and it runs on my work laptop, then yes, I do want it to start every day and no I don't think it's cool to have to do it manually through 'Startup' folder.

**Comment by IndrekV** [comment]
Let's put it into the backlog and see what happens. Thank you for your detailed explanation.

**Comment by nibe** [comment]
Also consider the tracking reminder and autotracker. They don't help if you forget to start Toggl.

> It's bad user experience if I have to find the windows startup folder, which isn't too easy to find, and drop Toggl in there, **for it to then not even start minimized**.

This.

**Comment by klalinea** [comment]
Will it be available on MacOS too?

**Comment by dingvarson** [comment]
I believe for most users this would be essential. I  use both harvest (which automatically starts and reminds me) and Toggl. And I will use harvest for more clients simply because of that feature.  

If its trivial the add it.

**Comment by nonoesp** [comment]
👋🏻 Hi, everyone!

I've been missing this option as well on macOS (and I thought that was there before).

But it's easy to make apps start automatically on login/startup.

I made a 25-second video showing how. It works!

https://youtu.be/FyCtFNPIrBc

**Comment by mijewe** [comment]
+1 for this.

Probably the only app on my Mac that I do actually want to have this option!

**Comment by sagarvora** [comment]
Yeah, let's get this on Linux as well!

**Comment by evanlooij** [comment]
... what they said, an on Mac too

**Comment by djkgamc** [comment]
lol

**Comment by MohiuddinSumon** [comment]
We have to request for linux separately! well just add this kindly for linux as well.
