### ISSUE TITLE
Time tracking only updates on second attempt

### ISSUE THREAD

**Issue by naglalakk** [toggl/toggldesktop#2224]
Hi. I checked if I have the latest version and it seems that I do, version 7.4.11. I have to do everything two times for it to appear. For example I assign a project and a client. When I close the menu window it does not stick. I have to open the menu window again, select a project and a client again and then it works. This also happens with duration, time range etc. It's pretty annoying. Especially when you forget and you think you are tracking time but then you are not. 

Also the time suggestions are pretty bad. If I add time tracking and enter start time 8:00 PM and I want to end it at 9:30 PM it only works if duration is not set. Duration is always set if I have changed the time range before. So let's say I have a duration of two hours then it disregards my input in the time range and sets the time from 8:00 PM to 10:00 PM. I think time range fields should have priority.

**Comment by keldri** [comment]
I have this same issue and it's really frustrating, especially if trying to enter times from the day before. As mentioned above this happened with the latest update.

**Comment by IndrekV** [comment]
@naglalakk 
The latest update that addresses the saving issue is available on our website (7.4.52). The version on the AppStore is a bit behind. We'll try to get the AppStore version up to date. If you want the newest version that is updated faster I suggest you use the version from our website. It has automatic update and gets all the new stuff faster. https://support.toggl.com/toggl-on-my-desktop/

As for the second part:
>Also the time suggestions are pretty bad. If I add time tracking and enter start time 8:00 PM and I want to end it at 9:30 PM it only works if duration is not set. Duration is always set if I have changed the time range before. So let's say I have a duration of two hours then it disregards my input in the time range and sets the time from 8:00 PM to 10:00 PM. I think time range fields should have priority.

There is a setting that should make range field a priority 
( Change duration when changing start time ):

![change_duration](https://user-images.githubusercontent.com/842229/28943218-a07f0186-78a6-11e7-8077-472b36b74dfb.png)
