### ISSUE TITLE
Closing window through taskbar context menu closes the app completely.

### ISSUE THREAD

**Issue by Trost123** [toggl/toggldesktop#2225]
I have 7+ Taskbar Tweaker (Win7) and it allows me to close things in my taskbar by middle-clicking the entity on it.
The problem is: all apps that live in tray don't terminate when I close their window like this, but TogglDesktop does.
To replicate this error without that software - right click Toggl Desktop and choose "close window":
![image](https://user-images.githubusercontent.com/21346282/28371914-f884d8b2-6ca6-11e7-96d7-14da8a2b64b1.png)
Expected result: same if I'd click a cross icon in the window - Toggl is minimized to tray.
Actual result: Toggl quits.
Other software doesn't get killed if I do this. (such as: Spotify, Telegram, Workrave and more)

**Comment by IndrekV** [comment]
I'm able to replicate this issue. I will look more into it to find a fix.
Thank you for reporting this.
