### ISSUE TITLE
Autotracker not working

### ISSUE THREAD

**Issue by rifton007** [toggl/toggldesktop#2228]
I have a problem with autotraker function on Windows 7.
Toggl detect only Indesign but no the other applications.
Thank,

![image](https://user-images.githubusercontent.com/2601347/28729535-0f0d27b0-73cd-11e7-8aeb-61a6d4cf4357.png)

**Comment by IndrekV** [comment]
Do you by any chance use 64bit Windows?

**Comment by rifton007** [comment]
Yes, i work on Windows 64bits et ToggleDesktop 7.4.52.
Thanks,

**Comment by IndrekV** [comment]
Thank you for getting back to me. This seems to be connected to the timeline tracking issue #2139  with 64bit systems. We are aware what causes the issue and will look for a fix.

**Comment by PsychodelEKS** [comment]
Same here on win7 x64

**Comment by rifton007** [comment]
News for this problem ?
I also work with windows 7 x64.
I did remark that the autotracker detects just applications in 32bit.
In my case, I have two versions of Adobe Illustrator CS6. 
Autotracker detects Adobe Illustrator 32bit, but not 64bit version.

**Comment by IndrekV** [comment]
We'll trying to crate a 64bit version of the app. That seems to be the only way to make the Autotracker and Timeline work properly ob 64 bit machines.

**Comment by rifton007** [comment]
It's okay now for me.
Because I installed Windows 10 today and Autocracker works correctly with any applications.
Thanks for your support.

**Comment by maritoggl** [comment]
Seems there's another case related to the issue, #637396.

**Comment by maritoggl** [comment]
Another case related to the issue, case/650425

**Comment by VeljkoTN** [comment]
Case 695029

**Comment by konstantinosftw** [comment]
I have win 10/64 bit. Autotracker and Timeline stopped tracking Chrome pages since the 13th of June. It could be that my OS or Chrome got some updates then, because It was working properly before that.

**Comment by IndrekV** [comment]
Will be fixed with 64bit release.
