### ISSUE TITLE
Toggl 7.4.52 Mac OS: Frustrating list behaviour

### ISSUE THREAD

**Issue by jamescosford** [toggl/toggldesktop#2233]
When I start a new time entry by clicking "play" on al old entry, the window automatically scrolls 90% of the way to the bottom of the time-entry log...

**Comment by IndrekV** [comment]
same issue as #2217 

This is already fixed and will be available with next release. If all goes well and testing doesn't bring up any issues we will push new version to beta channel tomorrow.
