### ISSUE TITLE
Timeline recording doesn't work

### ISSUE THREAD

**Issue by nvarchar** [toggl/toggldesktop#2237]
I love Toggl and use it daily to track my projects. I'd also love to track my application usage, but I haven't been able to get timeline recording working. 

I've had "Record timeline" selected on both my Windows and MacOS desktop apps for the past month. I've restarted the app and machines multiple times, but haven't seen any timeline data show up on toggl.com/app/timer 

Regular project time recording has been working and syncing fine.

**Comment by TheSoloJake** [comment]
Hi! Can you email us at support(at)toggl(dot)com with the emailed associated with your Toggl account? We can finish the Timeline setup process there.

**Comment by nicktoggl** [comment]
Issue should now be fixed, responded in email :)
