### ISSUE TITLE
Project gets erased after quick adding  on MacOS

### ISSUE THREAD

**Issue by stephendiadamo** [toggl/toggldesktop#2239]
Whenever I use the "Add time entry" mode and select one of the auto completed task details, the project name appears, I press enter, and the project name disappears. 

1) <img width="413" alt="screen shot 2017-08-09 at 12 57 54 pm" src="https://user-images.githubusercontent.com/1194245/29118485-6e425438-7d02-11e7-9162-09973313c0b8.png">

2) <img width="372" alt="screen shot 2017-08-09 at 12 58 00 pm" src="https://user-images.githubusercontent.com/1194245/29118484-6e2afcf2-7d02-11e7-9d21-992a5817c3a8.png">

**Comment by IndrekV** [comment]
I haven't been able to replicate this issue. Could you verify that this only happens when adding entries manually and only when using ENTER to select dropdown item.

**Comment by stephendiadamo** [comment]
Here's the sequence I used step by step:
[Sheet](https://docs.google.com/presentation/d/1_4Ceu4ixq2B_d-zdFMP1ZddhVA7I2zmj09C9XqN9L4g/edit?usp=sharing)

**Comment by IndrekV** [comment]
Thank you for the details. It seems that the issue is connected to the problem described in issue #2244

**Comment by IndrekV** [comment]
This should be fixed with new autocomplete and background syncing.
