### ISSUE TITLE
Missing mini timer on orientation change

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#2240]
case/526540

"The mini timer is not working when I change my monitor orientation from a landscape view to a portrait view. I have not been able to get it back even when I switch the orientation back."

**Comment by bernhof** [comment]
I often change screen layouts during presentations or when plugging in and out of my dock, and the mini timer has now disappeared. I believe it's somewhere outside of the desktop bounds, but there's no way to trick it to come back. Image shows how the timer looks in the <kbd>Windows button</kbd>+<kbd>Tab</kbd> overview:

![image](https://user-images.githubusercontent.com/1303750/30684593-24c8f920-9eb2-11e7-9935-8847dbe60693.png)

**Comment by IndrekV** [comment]
@bernhof 
It seems that the minitimer is not able to reposition itself. We will look into it. Currently the way to fix it is to manually delete the local database file that holds the info about minitimer position. See this link for information. https://support.toggl.com/clearing-the-local-data-from-toggl-desktop/#manual

**Comment by IndrekV** [comment]
closed with 04cbbff74bbd4415e97d3a97c1469bad21601809

Now if the mini timer location is out of screen simply disabling and enabling minitimer will fix the position. Also Clearing cache will reset all window positions.
