### ISSUE TITLE
User Unable To Add Time/Edit Time Entry

### ISSUE THREAD

**Issue by Michelle112** [toggl/toggldesktop#2247]
"I am using TOGGL in manual mode, When I click on the + (plus symbol) to Add time entry, it just adds an entry, but doesn't open a pane to the right that allows me to enter my time. I am also unable to edit that entry." 

User says he upgraded to Beta hoping that might resolve it, it didn't. He has turned off manual mode, closed session and re-launched Toggl and enabled manual mode, and also cleared his cache. Currently on 7.4.58. 

Original Case: 531630
Case with logs: 532173

**Comment by aleksi-kallio** [comment]
Same problem here, after updating to 7.4.52 on macOS, I can't track new entries, there just is an empty entry created every time I click something that should start the tracking. I can edit the details of the entries but the time is always 0:00:00, and if I press the play button, it creates a new unnamed entry.

**Comment by IndrekV** [comment]
@aleksi-kallio are you in manual mode. In manual mode the timer is not started and pressing start will create entry with 0 duration. You can go back to timer mode by going to menubar menu and selecting "Use timer"

![screen shot 2017-09-15 at 00 08 45](https://user-images.githubusercontent.com/842229/30455839-1b7862aa-99aa-11e7-925d-a6618c0e510c.png)
