### ISSUE TITLE
Feature request: better idle time handling

### ISSUE THREAD

**Issue by klasyc** [toggl/toggldesktop#2253]
When the computer if left idle, it would be great to add an option to insert a task to the idle time and resume the last task before the idle time. Example use case: I am working on a project, then go for a lunch and after finishing my lunch I go on my previous work.

Current behavior: In idle time notification box I choose "Add idle time as a new time entry", then I have to write the task name and click "Continue" button of the previous task (and sometimes I forget to do this and the launch break is really long).

Preferred behavior: In the idle time notification box I would choose "Add time to a specified task" and then I would pick up the lunch task from the list of recent tasks. After this, the previous task would remain as the active task.

Also it would be nice to detect idle time whenever the user locks the screen.

And the last suggestion: When I shutdown my computer without stopping the current task, the task stays active until the next morning. Preferred behavior: stop the current task when the computer is shut down.

**Comment by IndrekV** [comment]
We have decided to keep the idle popup as minimal as possible, so we have no plans to add a dropdown to this view. 

As for the "Stop time when computer closes functionality" there is a separate issue for that and it is planned to be added some time in the future. (#1606)
