### ISSUE TITLE
Autotracker not working with all programs

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#2254]
windows_native_app/7.4.52

> Autotracker not working on all applications. MS office is the notable set of apps that aren&#39;t being tracked. Only Acrobat, webex and other small .exe are tracked. 

Logs: #534958

**Comment by rifton007** [comment]
i think that is same problem, look this #2138 and #2228.

**Comment by IndrekV** [comment]
Will be fixed with 64bit release.
