### ISSUE TITLE
App behaviour when user changes password

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#2255]
> I would like to inform you, that if a user on a free plan (like me), changes his password via the toggle website, he does not get logged out in the desktop application (mac os x), as one would expect. Even if app is restarted. But when a user logs out and logs in again, all (0 entries during my whole history) Toggl entries are gone, even on the website.

Case #542446

**Comment by IndrekV** [comment]
This is not a desktop app case exactly. It is a bizdev decision. With our current logic the only solution would be to reset API token when password is changed. This will logout any app that is logged in at the moment.
