### ISSUE TITLE
Pomodoro Occasionally Stops Outside of Set Limits

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggldesktop#2256]
User sets Pomodoro for a set time (ex. 50 minutes), and there are occasions where the Pomodoro finishes the timer but adds extra seconds on to the generated time entry.

Desk case 541506

**Comment by psabbate** [comment]
I'm facing this issue too. I have set the Pomodoro time in 30 mins and everyday I have to go to 5-6 entries and update the seconds to make the exact interval as 30.00 mins
