### ISSUE TITLE
Switching from Linux to Windows

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#2257]
> So you know, there is this weird bug when you switch from Linux to Windows, the clock goes back in time. So I set up a timer at 12 on Linux, switch to Windows, and it&#39;s written -2 hours worked.
> I know this is not a bug with Toggl itself, and the way you work with JavaScript Date objects forces you to face it, but yeah, just if you didn't know about it.
> I think it would probably be the same if someone was moving in another country and its timezone would change.

Case #546303
![capture](https://user-images.githubusercontent.com/12407134/30170464-dfc11714-93f7-11e7-9b83-8fc4b752b8c2.png)

**Comment by IndrekV** [comment]
This issue is not connected to desktop app. As the screenshot shows it has something to do how web app calculates time.
