### ISSUE TITLE
Linux app closes when trying to update

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#2265]
linux_native_app/7.4.52

> I'm on Kubuntu 16.04 64bit. If Toggl dos show me a new update is available and i press yes for auto update, Toggl closes without any message. 

When advising to run the app from terminal:

> Now i get this error about update and Toggl Crash. Terminal Log: http://paste.ubuntu.com/25528844/
> Toggl Log is attached.

Logs with case #495246

**Comment by VeljkoTN** [comment]
Just an update here, the same user reported the same issue again. 

Autoupdate crashed Toggl, but he can manually download and install the updated version without an issue.

**Comment by IndrekV** [comment]
There is no auto update in linux version of Toggl Desktop. When user clicks "update" button the download of the newest version is triggered. Then user has to manually install the new version. Auto update for linux is planned but there is no set date yet. In this case the trigger to download the new version with default browser probably fails and crashes the app.

**Comment by IndrekV** [comment]
Closed with #2611
