### ISSUE TITLE
Problems with identical project names in two workspaces

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggldesktop#2267]
**To reproduce:**
1. Create projects with identical names in two different workspaces (don't assign clients)
2. The desktop app only displays 1 project. The one from the WS with the lower alphabetical order

I can reproduce this problem on macOS. 

---
Case ID: 552325

**Comment by IndrekV** [comment]
This is a default behaviour of the autocomplete that it does not allow items with identical text value. There is an issue to create more custom autocomplete that would avoid this issue and also would have more possibilities to show project color and project and client name more clearly. 

It's all described in #1768 So I'll close this issue.
