### ISSUE TITLE
Cursor not appearing

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#2271]
osx_native_app/7.4.58

> Lots of times when I click in the time field to change the starting or ending time, I can't see a cursor. It's there, but I can't see it.

Logs: #550914

**Comment by kadrihvl** [comment]
Update from the user:

**Comment by kadrihvl** [comment]
> After removing Toggl, upgrading to macOS High Sierra and reinstalling
> Toggl, I can confirm that the cursor bug is still there. It's intermittent.
> I don't know what causes it, but I click in the time field and can't see my
> cursor. I close it and open the item again and this time it's fine.
>

**Comment by IndrekV** [comment]
Outdated issue.
