### ISSUE TITLE
ubuntu 17.10 unmet dependencies

### ISSUE THREAD

**Issue by msajadi832** [toggl/toggldesktop#2274]
when install:
`

    Reading package lists... Done
    Building dependency tree  
    Reading state information... Done
    You might want to run 'apt --fix-broken install' to correct these.
    The following packages have unmet dependencies:
     toggldesktop : Depends: libgstreamer-plugins-base0.10-0 but it is not installable
     Depends: libgstreamer0.10-0 but it is not installable
`

but in ubuntu 17.10 this packages exist:
libgstreamer-plugins-base1.0-0
libgstreamer1.0-0

**Comment by IndrekV** [comment]
Please check if this workaround works for you. https://github.com/toggl/toggldesktop/issues/1894#issuecomment-254427913

**Comment by IndrekV** [comment]
closed together with #1894
This will be properly fixed with next release. Version 7.4.274 or later.
