### ISSUE TITLE
Mac app does not start anymore

### ISSUE THREAD

**Issue by raphaelbrugier** [toggl/toggldesktop#2282]
Hi,

The application does not start anymore on my Mac.
I have tried to uninstall / reinstall from the AppleStore without success.

If I try to run it from the command line, I'm getting this error:
```
$open -a TogglDesktop
LSOpenURLsWithRole() failed for the application /Applications/TogglDesktop.app with error -10810.
```

Toggle app version: `7.4.58`
Mac OS x version:
```
Software:

    System Software Overview:

      System Version: OS X 10.11.3 (15D21)
      Kernel Version: Darwin 15.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 5 days 8:58
```

**Comment by IndrekV** [comment]
It seems that it can be an OS issue. Could you please try starting the app from the terminal with the full path:
```
/Applications/TogglDesktop.app/Contents/MacOS/TogglDesktop
```

Let me know if this also shows any errors.

**Comment by raphaelbrugier** [comment]
This returns the same error:
```

$open -a /Applications/TogglDesktop.app/Contents/MacOS/TogglDesktop
LSOpenURLsWithRole() failed for the application /Applications/TogglDesktop.app/Contents/MacOS/TogglDesktop with error -10810.
```

NB: you have put the wrong label on the issue: s/windows/mac/

**Comment by IndrekV** [comment]
I was actually thinking startign the app from terminal without the `open` command. Just typing in the line that I posted. If the command without open still gives an error it can be some strange permissions issue. Try fixing permissions with command:
```
chmod +x /Applications/TogglDesktop.app/Contents/MacOS/TogglDesktop
```

**Comment by raphaelbrugier** [comment]
Hi,

I've tried without `open` and changing the permissions but still the same issue.

```
$/Applications/TogglDesktop.app/Contents/MacOS/TogglDesktop
[1]    5821 killed     /Applications/TogglDesktop.app/Contents/MacOS/TogglDesktop

$chmod +x /Applications/TogglDesktop.app/Contents/MacOS/TogglDesktop

$/Applications/TogglDesktop.app/Contents/MacOS/TogglDesktop
[1]    5970 killed     /Applications/TogglDesktop.app/Contents/MacOS/TogglDesktop

$ls -l /Applications/TogglDesktop.app/Contents/MacOS/TogglDesktop
-rwxr-xr-x  1 root  wheel   1.1M Sep 12 18:48 /Applications/TogglDesktop.app/Contents/MacOS/TogglDesktop
```

**Comment by IndrekV** [comment]
I'm currently not able to replicate the issue. It will take time to get to the bottom of this. I would suggest you to try our website version of the app. Might be a specific issue with the AppStore version. https://support.toggl.com/toggl-on-my-desktop/

**Comment by raphaelbrugier** [comment]
Yes, the version from the website worked. Thanks for the help!

**Comment by IndrekV** [comment]
Closing this as I haven't been able to reproduce this after multiple tries on 2 different machines.
