### ISSUE TITLE
Mangled Login Screen

### ISSUE THREAD

**Issue by jackdeansmith** [toggl/toggldesktop#2292]
The Login Screen appears mangled on my machine after a fresh install. 

OS: macOS Sierra Version 10.12.6
<img width="671" alt="screen shot 2017-10-07 at 1 07 53 pm" src="https://user-images.githubusercontent.com/5905702/31310139-d357b4d0-ab60-11e7-9d47-e669d92f2d12.png">

<img width="542" alt="screen shot 2017-10-07 at 1 06 52 pm" src="https://user-images.githubusercontent.com/5905702/31310138-cf3f9c5a-ab60-11e7-9d2d-6ecfa822edea.png">

**Comment by szuke** [comment]
I just experienced the same thing. Unfortunately, it was my first impression.

**Comment by IndrekV** [comment]
Thank you for reporting this. We've found the issue and fixed it. Please uninstall the app and re-download and reinstall the latest stable. [MacOs stable](https://toggl.com/api/v8/installer?app=td&platform=darwin&channel=stable)

**Comment by jakepetroules** [comment]
The issue affects the current latest stable release (7.4.58), so if 7.4.58 is not meant to be the current stable release, please update the link accordingly.

**Comment by IndrekV** [comment]
@jakepetroules We had a faulty release of version 7.4.58. If the app updated while the faulty release was available the app is broken. We replaced the installer with a fixed one so re-downloading and reinstalling the version 7.4.58 will fix the issue.
