### ISSUE TITLE
verify ensure time entry duration / times

### ISSUE THREAD

**Issue by webervin** [toggl/toggldesktop#2295]
please validate/ensure following for data sent into API:
- [x] start time is not sub second precise (round/truncate it to seconds only part).
- [x]  stop time is not sub second precise (round/truncate it to seconds only part).
- [x] duration is non-decimal number of full seconds between start and stop for stopped time
entries.
- [x] duration field for running time entries encodes  same moment of time  as start field.

**Comment by IndrekV** [comment]
We use `time_t` that takes seconds precision. Also duration is set as "-start time" on timer start and stop time is calculated from duration seconds when timer stops.

When creating JSON for post we use `ISO8601_FORMAT` for start and stop fields.

Should be all good.
