### ISSUE TITLE
Check update says version 7.4.68 is now available, fails to download it, release seems half-done

### ISSUE THREAD

**Issue by gthb** [toggl/toggldesktop#2296]
Clicking “Check for update”, I get “TogglDesktop 7.4.68 is now available”. But when I click “Install Update”, I get “Update Error! An error occurred while downloading the update. Please try again later.” See screenshots below.

The download link on https://support.toggl.com/toggl-desktop-for-mac-osx/ resolves to [TogglDesktop-7_4_58.dmg](https://github.com/toggl/toggldesktop/releases/download/v7.4.58/TogglDesktop-7_4_58.dmg), and the changelog at https://toggl.github.io/toggldesktop/ also just shows 7.4.58 as the latest version. On the [releases list on Github](https://github.com/toggl/toggldesktop/releases) there is a v7.4.68, released three days ago, but it has no installer links, only source code downloads.

![image](https://user-images.githubusercontent.com/153580/31491526-31c2319c-af37-11e7-8fdc-0ce1fdc793c7.png)

![image](https://user-images.githubusercontent.com/153580/31491540-3c48f0a6-af37-11e7-92aa-b0e0e2caafa1.png)

**Comment by rogeriopradoj** [comment]
I think the @toggl-buildbot forget to build the macOS .dmg version:

7.4.68:

![releases_ _toggl_toggldesktop](https://user-images.githubusercontent.com/443391/31495177-ef9bdb56-af2c-11e7-9c24-55499a50b448.png)

7.4.58:

![releases_ _toggl_toggldesktop](https://user-images.githubusercontent.com/443391/31495193-056613c0-af2d-11e7-8e01-ac4864527b83.png)

**Comment by ApocalypticFish** [comment]
case/568518

**Comment by IndrekV** [comment]
Added the missing installer to the release
