### ISSUE TITLE
Preferences should be stored as preferences and not in a sqlite db

### ISSUE THREAD

**Issue by daften** [toggl/toggldesktop#2301]
The current setup leaves it very hard to adapt the settings through the command-line. When using the default preferences as it should be done on macOS, you can use defaults and/or plistbuddy to manipulate the settings from the command-line. This is needed e.g. for provisioning a machine with scripts.

**Comment by IndrekV** [comment]
Thank you for your feedback. As Toggl Desktop is built ground up as a cross platform app we tried to avoid duplicating functionality where possible. This is why we decided to keep all data and settings in Sqlite. If needed the sqlite command line tools can be used to modify the default settings. Note that database is created when app starts and no database is present.

Thank you for sharing your thought, but at the time we do not think it is necessary to start rebuilding the preferences system of Toggl Desktop.
