### ISSUE TITLE
Update error on OSX - false interpretation of read-only volume

### ISSUE THREAD

**Issue by Wildarts** [toggl/toggldesktop#2306]
After installing Toggl like every other app, it wrongly displays an error message when trying to update. Toggl is located in the apps folder, but for some reason doesn't recognize this. 

<img width="427" alt="nayttokuva 2017-10-23 kello 11 00 11" src="https://user-images.githubusercontent.com/7037621/31878117-9ec3ffe8-b7e1-11e7-999e-77a700000740.png">

**Comment by IndrekV** [comment]
We have not seen this kind of error before. Please try recopying the app to Applications from the .dmg. I think it's likely a one time issue.

**Comment by Wildarts** [comment]
Hi, I have uninstalled and installed the app multiple times, moved it from app folder to other folders and back again, but the problem persists.

**Comment by Wildarts** [comment]
Hi, I had this same problem with other apps as well, so I investigated a bit further. It seems to be a problem related to another app I'm using, Pathfinder. Installing Toggl from Finder resolved this issue immediately. 

https://discussions.apple.com/thread/7818490?start=0&tstart=0
