### ISSUE TITLE
Tasks missing in report . Windows 10 - Chrome

### ISSUE THREAD

**Issue by Arne-Olaf** [toggl/toggldesktop#2307]
Task names is missing when exporting reports to pdf. Same result in Edge.
![error pdf report](https://user-images.githubusercontent.com/30493506/31937863-0c5be62c-b8b6-11e7-9a22-79c6b56a706f.jpg)

**Comment by IndrekV** [comment]
This repo is for Toggl Desktop. The issue you are describing is connected to the Reports section in the Toggl.com web app. Please send feedback from the Web app or send email to support@toggl.com and our web team will look what's going on.

**Comment by Arne-Olaf** [comment]
Thanks. Wasn't sure where to report.
