### ISSUE TITLE
Windows Desktop app lag with mini timer

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#2310]
"In the Windows App (On Windows 10), when I click the Start/Stop button on the mini timer, sometimes it doesn&#39;t Start/Stop. Then, I have to try clicking it again before it finally takes effect. Some other times, clicking it does take effect, after a delay. If I had clicked it again in the interim (assuming it was one of those times it didn&#39;t take effect), it also registers the second click. This can lead to clicking start, waiting a moment, seeing no effect, trying to click start again, only to have an extremely brief task started then stopped...and the whole process can be repeated many times...leading to a bunch of very brief useless tasks being added to the log, and needing me to go back and clean them up. I am not sure but I suspect it might possibly be related to something like a difference between when I click on the actual letters of the text &#34;Start&#34; or &#34;Stop&#34; on the button, or when I click on the colored background of the button, not on the text. (But the button shade and mouse pointer change as if it would take effect either way). This issue has caused me some real frustration, so I hope you guys can find it. Thank you very much for your time and attention. I appreciate what you do."

**Comment by ricotheque** [comment]
case/637401

7.4.73 on Windows 10 Enterprise 64-Bit
"[On most text fields], Toggl Desktop shows the typed characters 1-2 seconds later"

User describes behavior as having happened for several months now, and he has tried different versions of the app. He has also sent a log through the feedback form, please see case.

**Comment by IndrekV** [comment]
Should be fixed with new superfast autocomplete. Ol autocomplete implementation was the reason the text fields lagged.
