### ISSUE TITLE
GitHub Desktop App doesn't open on Windows 8.1

### ISSUE THREAD

**Issue by RubenSousse** [toggl/toggldesktop#2313]
Hi everyone!! 

I'm using Windows 8.1 and recently installed a GitHub Desktop application (https://desktop.github.com/) on my computer. 
![image](https://user-images.githubusercontent.com/32354105/32170675-d1c93446-bd75-11e7-9ad7-cb06f1d049c3.png)

It was working completely fine since today: now when I try to execute, it doesn't even start, actually doesn't appear on the running tasks :/ 
I haven't changed anything in my computer that I remember :$

I've tried reinstalling it several times deleting the cache in AppData Local and Roaming, as advised in #1496. 
It worked once, but once I closed it, it never ran again... 

Thanks in advance!!

**Comment by IndrekV** [comment]
Hi @RubenSousse. I think you might have jumped into a wrong repo with this issue. The screenshot shows Github Desktop app. This repo is for Toggl Desktop app and has no connection to Github. 

I'm sad to hear you are having issues with Github Desktop app and I hope you get it sorted. On another note I've heard the Toggl Desktop app itself is pretty fabulous, so don't hesitate to dive in and check it out --> [Toggl Desktop for Windows](https://toggl.com/api/v8/installer?app=td&platform=windows&channel=stable)
