### ISSUE TITLE
Mac App keeps crashing and/or won't open upon reinstall

### ISSUE THREAD

**Issue by epagnini** [toggl/toggldesktop#2314]
Users are trying from App Store as well as Toggl 

> A few days ago Toggl app hanged and I had to force quit to close.
Since then, I had not reopened it until yesterday, but whenever I opened
it, it crashed right at the start. I was pressed at work so just moved on. Today I had some free time and decided to look into it, while running it
the app kept crashing. I tried downloading the latest version directly from the website to no
avail, I then tried to install TogglDesktop directly from the App Store,
still the same issue.

cases:
580512
580494
580497

**Comment by Michelle112** [comment]
580433
580435
580437
580469 - This user said they resolved the issue by downloading the previous stable version

**Comment by epagnini** [comment]
580532

**Comment by intes** [comment]
Process:               TogglDesktop [1218]
Path:                  /Applications/TogglDesktop.app/Contents/MacOS/TogglDesktop
Identifier:            com.toggl.toggldesktop.TogglDesktop
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           TogglDesktop [1218]
User ID:               501

Date/Time:             2017-11-03 20:22:08.371 +0300
OS Version:            Mac OS X 10.10.5 (14F2511)
Report Version:        11
Anonymous UUID:        D558F8F8-7DE9-4318-30C8-487D8104F244

Sleep/Wake UUID:       497C79E6-C8E5-4A66-858A-2B8767D30335

Time Awake Since Boot: 1700 seconds
Time Since Wake:       1300 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libPocoJSON.31.dylib
  Referenced from: /Applications/TogglDesktop.app/Contents/Frameworks/TogglDesktopLibrary.dylib
  Reason: no suitable image found.  Did find:
	/Applications/TogglDesktop.app/Contents/MacOS/../../Contents/Frameworks/libPocoJSON.31.dylib: code signature invalid for '/Applications/TogglDesktop.app/Contents/MacOS/../../Contents/Frameworks/libPocoJSON.31.dylib'

	/Applications/TogglDesktop.app/Contents/Frameworks/libPocoJSON.31.dylib: code signature invalid for '/Applications/TogglDesktop.app/Contents/Frameworks/libPocoJSON.31.dylib'

Binary Images:
    0x7fff5ff07000 -     0x7fff5ff3d92f  dyld (353.2.4) <3C068A0D-69D5-3AD6-86D9-6261D3B1564E> /usr/lib/dyld
    0x7fff817f5000 -     0x7fff819ef46f  libobjc.A.dylib (647) <759E155D-BC42-3D4E-869B-6F57D477177C> /usr/lib/libobjc.A.dylib
    0x7fff82fa4000 -     0x7fff832d5ff7  com.apple.Foundation (6.9 - 1154.20) <3D37F9B8-96CC-324B-9062-0A7E4ABCDC1F> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff83726000 -     0x7fff83abeff7  com.apple.CoreFoundation (6.9 - 1153.31) <4151A95B-66CA-3E6F-9FB2-DF1D8F3E606A> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff83db6000 -     0x7fff83e28fff  com.apple.framework.IOKit (2.0.2 - 1050.20.2) <09C0518C-90DF-3FC3-96D6-34D35F72C8EF> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff83ec5000 -     0x7fff83f19fff  libc++.1.dylib (120) <1B9530FD-989B-3174-BB1C-BDC159501710> /usr/lib/libc++.1.dylib
    0x7fff844c0000 -     0x7fff844c0fff  com.apple.ApplicationServices (48 - 48) <5BF7910B-C328-3BF8-BA4F-CE52B574CE01> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff857c0000 -     0x7fff86341ff7  com.apple.AppKit (6.9 - 1348.17) <E485D56D-3E72-34B7-99BB-BFDEE2D07BF5> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff8652c000 -     0x7fff8652cfff  com.apple.Cocoa (6.8 - 21) <EAC0EA1E-3C62-3B28-A941-5D8B1E085FF8> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff86ac8000 -     0x7fff86ac8fff  com.apple.CoreServices (62 - 62) <C69DA8A7-B536-34BF-A93F-1C170E2C6D58> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff86caf000 -     0x7fff86cb1fff  com.apple.ExceptionHandling (1.5 - 10) <C3A6EB3D-C0B3-371F-99D8-AF5495498091> /System/Library/Frameworks/ExceptionHandling.framework/Versions/A/ExceptionHandling
    0x7fff875c2000 -     0x7fff875c2fff  com.apple.Carbon (154 - 157) <9BF51672-1684-3FDE-A561-FC59A2864EF8> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff8a618000 -     0x7fff8a690ff7  com.apple.SystemConfiguration (1.14.4 - 1.14) <B835C014-901E-37B7-BD09-2EFF5FFEB910> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff8bb87000 -     0x7fff8bb88ff3  libSystem.B.dylib (1213) <4B24B5BE-45F2-355A-9A35-D438A516D140> /usr/lib/libSystem.B.dylib
    0x7fff8d19a000 -     0x7fff8d9fdffb  com.apple.CoreGraphics (1.600.0 - 790) <7BD274D8-73CC-32DE-BCA5-96C047A3B97B> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff8eeae000 -     0x7fff8eefdff7  libstdc++.6.dylib (104.1) <803F6AC8-87DC-3E24-9E80-729B551F6FFF> /usr/lib/libstdc++.6.dylib
    0x7fff8eefe000 -     0x7fff8f174fff  com.apple.security (7.0 - 57031.40.9) <8D9CB878-BB71-3CF1-88CE-9E6FAC4043ED> /System/Library/Frameworks/Security.framework/Versions/A/Security

**Comment by IndrekV** [comment]
Seems most of the issues are with MacOs 10.9.5 and some 10.10.* 
I'm able to replicate the issue.

**Comment by IndrekV** [comment]
I've reverted the latest stable version to previous version (7.4.58) until this is solved.

**Comment by IndrekV** [comment]
Same as #2315
