### ISSUE TITLE
User unable to reinstall - Mac

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#2319]
> I'm mac user, using Yosemite 10.10.5.
> Untill Toggle Desktop Version 7.4.58, Toggle worked. Since 7.4.71, Desktop Version doesn&#39;t start.
> I wanted to use the older version, but Toggle Desktop always starts to install the new one automatically.

We instructed to manually delete the app and shared the latest stable version link to reinstall but: 

> When I start Version 7.4.58, toggle automatically download the version 7.4.71, and after restart, it doesn't work again. 

Case: #581075.

**Comment by IndrekV** [comment]
I've removed the newer broken version from the automatic download list. Should be ok now.
