### ISSUE TITLE
Win app acting slow despite clearing cache

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#2323]
windows_native_app/7.4.73

> Toggl has become very slow and laggy. I have cleared the cache but it doesn't make much difference. Is it a known issue? Do I need to archive some old entries/projects?

Logs: #587741

**Comment by mavericknm** [comment]
Same. It's starting to feel almost as bad as using it from my browser. Changing time entries, editing entry names, or starting and stopping tasks takes half a second. Often going from editing one entry to another results in the wrong entry being edited because my inputs are too fast.

**Comment by IndrekV** [comment]
Probably connected to the amount of data that the account has. Connected to issue #2251

**Comment by IndrekV** [comment]
closed together with #2042 Will be released to beta next week
