### ISSUE TITLE
Windows App won't open

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#2324]
![desktop](https://user-images.githubusercontent.com/17441860/32818649-95d35c46-ca18-11e7-9887-fa8ca6ffc56e.png)
User has attempted several re-installs and gets same issue

Case 586135

**Comment by kadrihvl** [comment]
windows_native_app/7.4.73
The operating system is Windows 10; all of the latest Windows updates are in. Some screenshots and some more info of steps taken with the case.

**Comment by IndrekV** [comment]
The error message shown in the picture appears when the TogglDesktop app is updated in the background and the updater tries to restart the app. At this point manually starting the app should work. I would suggest checking if for some reason there is a TogglDesktop process running in the background that block starting of the app. Closing any TogglDesktop process from Task manager and then starting the app should fix this issue.

**Comment by kadrihvl** [comment]
Let the user know.
