### ISSUE TITLE
change Destination Folder on Windows

### ISSUE THREAD

**Issue by rubaboo** [toggl/toggldesktop#2331]
I have to install TogglDesktop elsewhere, not in my LOCALAPPDATA directory, but the path is greyed out and is unchangeable. I tried to install in the default location then move the folder, but the app would not start after the move. This is from the Event Log:

    Faulting application name: TogglDesktop.exe, version: 7.4.73.0, time stamp: 0x59f105b7
    Faulting module name: MSVCR120.dll, version: 12.0.21005.1, time stamp: 0x524f7ce6
    Exception code: 0x40000015

**Comment by rubaboo** [comment]
I was able to install it elsewhere by changing "Local AppData" value in the registry. That did not help, I am still unable to start the program. Same error in the Event Log. Tried with latest installer downloaded from here, same result.

    Faulting application name: TogglDesktop.exe, version: 7.4.84.0, time stamp: 0x5a0cb8d3
    Faulting module name: MSVCR120.dll, version: 12.0.21005.1, time stamp: 0x524f7ce6
    Exception code: 0x40000015

**Comment by rubaboo** [comment]
Tried a clean install on a different machine, same. Change "Local AppData", install, change "Local AppData" back, try to launch - same error as above.

**Comment by IndrekV** [comment]
Toggl desktop is meant to be in user directory and the reason is that the app would not need administrative privileges to run.

**Comment by rubaboo** [comment]
Is this a "won't fix", or can you enable the editing, so user can enter an arbitrary path? Running apps from user directory is forbidden in a corporate environment. Group policy. Can't override it even if I'm a local admin.

**Comment by rubaboo** [comment]
Having this group policy on is a common thing. Since viruses install themselves in user directory as well.

**Comment by IndrekV** [comment]
We have a separate Enterprise version that allows changing the install path. You can get it from [here](https://toggl.com/api/v8/installer?app=td&platform=windows_enterprise&channel=stable)

Let me know if this version works ok for you.

**Comment by rubaboo** [comment]
Will this installer let me stay on the basic plan (free)?

**Comment by IndrekV** [comment]
I'll do some tests to see if I can pinpoint what exactly causes this error.

**Comment by IndrekV** [comment]
will be fixed with #2955
