### ISSUE TITLE
Proper theming on Ubuntu 17.10

### ISSUE THREAD

**Issue by sojusnik** [toggl/toggldesktop#2333]
On Ubuntu 17.10 the latest version of Toggl (7.4.71) still looks out of place, even after applying [this](https://askubuntu.com/a/748186/79691) workaround, so that Qt5 apps should inherit the global GTK theme of Ubuntu.

Please have a look on that, since other Qt5 apps do apply the GTK theme, only Toggl doesn't.

**Comment by IndrekV** [comment]
Thank you for your feedback. We are planning to do a bigger upgrade to the linux app in the first quarter of 2018 and we'll look into this issue as well during this development.

**Comment by carlisgg** [comment]
can't wait to have the linux app updated!!!

**Comment by sojusnik** [comment]
@IndrekV Any updates on the linux update? :)

**Comment by MartinBriza** [comment]
We're updating the app now over the time. I have implemented better theming support in #2917 for the issue #2882.
