### ISSUE TITLE
eGambit flagging TogglDesktop as malware

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggldesktop#2336]
You can see it here
https://www.virustotal.com/#/file/cd81f6d6102f871e7d821509e323b6cd2bbe2d3a0bc0a78fb364aa00d1952256/detection

Here's the eGambit form for false positive issues
https://tehtris.com/egambit_fp.php

Let me know if you want me to fill out the form.

**Comment by IndrekV** [comment]
Jep, fill out a false positive report.

**Comment by vedr4n** [comment]
Filled a report.
