### ISSUE TITLE
Edit view layout issues in older MacOS

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#2342]
osx_native_app/7.4.84
User reports that he's not able to see date field when editing an entry. 
Case #625868

[Screen Shot 2018-01-10 at 09.37.32.PDF](https://github.com/toggl/toggldesktop/files/1619121/Screen.Shot.2018-01-10.at.09.37.32.PDF)

**Comment by IndrekV** [comment]
I looked more into it. This is not connected to duration only, as all of that code is removed. It is some other graphical issue.

**Comment by IndrekV** [comment]
In the screenshot, the "Tags:" label is also missing. I would need more details on the macos version and the computer.

**Comment by kadrihvl** [comment]
Will ask the user!

**Comment by maritoggl** [comment]
OS X Yosemite v10.10.5

**Comment by song4Him** [comment]
I'm on Yosemite too, and same problem here. Thankfully, I don't need those two options very much!

**Comment by kadrihvl** [comment]
@song4Him IF you do need to edit any of your entries, there is an alternative - you should be able to do so on Detailed Reports page in webapp. https://www.toggl.com/app/reports/detailed/

**Comment by song4Him** [comment]
@kadrihvl  I know, and I've done that before. I just haven't needed it so far, as I rarely have to add entries from a previous day, and the tags field is still available. I hadn't even noticed until this issue was brought up!
