### ISSUE TITLE
Auto-update on Linux

### ISSUE THREAD

**Issue by jlaw9** [toggl/toggldesktop#2344]
It would be great if the app could update itself instead of asking me to update it. It's a bit cumbersome to have to download and install updates on each of the desktops and laptop I use Toggl Desktop on

**Comment by IndrekV** [comment]
I agree. We have actually thought about it and it's in our todo list.

**Comment by kanemathers** [comment]
Ideally, Toggl would be packaged up properly and distributed via a repository so we could update it with the rest of our system.

If that's too much work, you could look into Flatpak?

**Comment by aiguofer** [comment]
+1 for flatpak (or rpms)

**Comment by IndrekV** [comment]
Will be solved with creating flatpak
