### ISSUE TITLE
Error when starting OSX app

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#2348]
When starting the application, user always gets error: "Max allowed duration per 1 time entry is 999 hours". I've been unable to spot this faulty entry in our database. User has tried: 
- Restarting the app
- Logging out/logging in again
- Uninstalling and reinstalling the app from the AppStore
- Uninstalling and reinstalling the app via Homebrew Cask
Logs with case #625814

**Comment by IndrekV** [comment]
One of the time entries has too big duration and backend rejects the sync. 
I didn't see in the case anywhere that the user actually cleared their cache. Uninstall and reinstall do not clear local data. I would suggest either clear cache from the app or manually clearing the local cache as described in.

Logs show the error, but sadly no more details about what are the exact details of the entry.
