### ISSUE TITLE
macOS: This version of the app is not supported anymore

### ISSUE THREAD

**Issue by remisdemis** [toggl/toggldesktop#2350]
Hey,

just restarted my toggldesktop app on macOS 10.13.2 and was greeted with:

This version of the app is not supported any more. Please visit Toggl website to download a supported app.

Reinstalling did not help.

Tried Versions:
- Link from the support page
- AppStore Version

Is this temporary?

**Comment by Lunariz** [comment]
Getting the same error on windows. Installing the latest windows version also had no effect.
In addition, syncing gave an error message along the lines of "Something went terribly wrong, we have been notified.."

**Comment by wisprp** [comment]
The same issue.
macOS Sierra
TogglDesktop: 7.4.58 (AppStore)

**Comment by IndrekV** [comment]
The issue was connected to server outage we had. https://blog.toggl.com/connectivity-issues-update-jan-16/

We'll try to improve the error message in case this kind thing ever happens again.
