### ISSUE TITLE
Version warning 

### ISSUE THREAD

**Issue by smpetrey** [toggl/toggldesktop#2351]
OS: MacOS 10.13.2
Toggl Version: 1.4.84
Release Channel Beta

Unsure what this was about, but I had a bizarre version warning that would not go away (closed the dialog, only to have it re-appear later) as seen below.
![screen shot 2018-01-16 at 2 06 10 pm](https://user-images.githubusercontent.com/6411509/35008277-ecf740f0-fac9-11e7-9d76-021208551c0c.png)

Steps to mitigate the issue:
- Closed the warning (reappeared)
- Quit the App (reappeared)
- Reinstalled the App from Toggl and App Store (reappeared)
- Signed out (reappeared)
- Attempted to sign back in (froze)

At this point I just uninstalled, and reinstalled Toggl and attempted signing in until it would let me sign-in. At which point the version warning messages stopped showing up... I wish this was a more useful issue, but it seemed pretty bizarre so I thought I'd file it in case this cropped up again.

**Comment by amelhorn** [comment]
I can confirm this has happened to me today also (first time I have seen this), and recurs consistently with using the application.

I assume something with the API is broken, causing calls from the desktop app to fail. None of my time from today has synced either.

**Comment by mhw** [comment]
I'm seeing this too. Possibly related to toggle connectivity issues? https://blog.toggl.com/connectivity-issues-update-jan-16/

**Comment by IndrekV** [comment]
The issue was connected to server outage we had. Should be solved now.

**Comment by smpetrey** [comment]
Might I suggest a more helpful warning message? If Toggl isn’t connected to the API due to a server outage, how about a warning such as:

“Looks like Toggl isn’t connected to our API at the moment. Your time logged will be synced momentarily.”

“This version of this app...” isn’t particularly helpful nor does the message match the end-user problem when a server outage occurs. Thoughts?
