### ISSUE TITLE
Start and end time should use profile settings time format (12h/24h)

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2355]
Currently duration uses the format but start and end times do not.

Other possibility is that the app uses system default setting.

**Comment by stoivo** [comment]
![2019-01-02_16 05 15_toggl desktop](https://user-images.githubusercontent.com/3492040/50597641-626b3b00-0ea8-11e9-87b8-4f633b6d9a49.png)
Is't this working? Or am I on the wrond site

**Comment by NghiaTranUIT** [comment]
Close ❌  because the start and end time are already respect the format from User Profile in toggl.com
