### ISSUE TITLE
Status menu on macOS High Sierra not dropping down on a full screen Desktop

### ISSUE THREAD

**Issue by ricotheque** [toggl/toggldesktop#2356]
On a full screen Desktop, the app's Status menu appears activated, but its dropdown remains hidden.

"In MacOS you can easily make apps full screen, and they move to a distinct desktop of their own. For example, at the moment I have these desktops open - a window Desktop with my calendar, then four full screen apps.

If I click the Toggle button in the top menu bar from the windowed Desktop (with my calendar visible on it), then I get the menu open as expected

However if I click the button from a full screen app desktop, then it doesn't work at all. I've clicked the Toggle button in the top menu which is why it shows as blue, but if a menu has appeared then its not visible from the full screen app and its not taking me to where it is visible."

(Screenshots at case/631058)

**Comment by NghiaTranUIT** [comment]
Unable to reproduce in macOS 10.14 🐞

After investing in the codebase, our logic to handle `NSStatusItem *statusItem` is look normal, nothing stranger. Additional, the logic to present/dismiss NSMenu is handled automatically from System.

My assumption is that some apps are trying to override their windowLevel, which is higher than our Status Menu ([NSStatusWindowLevel](https://developer.apple.com/documentation/appkit/nsstatuswindowlevel?language=objc)). As a result, the menu is below.

**Comment by IndrekV** [comment]
Unable to replicate.
