### ISSUE TITLE
User can't log in: "Out of range: value to small" error displayed

### ISSUE THREAD

**Issue by maritoggl** [toggl/toggldesktop#2367]
User 3536528 is failing to log in and is displayed "Out of range: value too small" error, while the e-mail address that they use is valid. User has also tried reinstalling the app with no luck. OpSys: Sierra 10.13.2.
![screen shot 2018-01-25 at 10 48 39](https://user-images.githubusercontent.com/35216651/35382251-459028c2-01c7-11e8-9dc4-91b8a20d3aa0.png)

**Comment by IndrekV** [comment]
Unable to replicate. Our logs show that this happened to a single use for a short time so it might be a temporary bug. Reopen this if it happens again and we'll look more into it.
