### ISSUE TITLE
OSX App stopped from reporting to web

### ISSUE THREAD

**Issue by dandaka** [toggl/toggldesktop#2371]
**Now**

1. Open OSX app (7.4.84)
2. Start logging time
3. Active entry is not synced with Toggl Web (looks like no time today was tracked). 30+ seconds waiting.
4. When you click Sync, entries are appearing on Toggl Web
5. When tracking items in Toggl Web, they are appearing in Toggl Desktop

**Should be**

Toggl Desktop is reporting data to Toggl Web properly

**Comment by dandaka** [comment]
**Update.** Now even manual sync is not working. "Account > Sync", no messages, no results :(

Once I was proud user of your app and invited many friends. But lack of support, years of waiting for bug fixes, failing performance forces to look for alternatives.

**Comment by IndrekV** [comment]
I just tried it out and was not able to reproduce this issue. 

![td_sync](https://user-images.githubusercontent.com/842229/35504394-9df14e8e-04eb-11e8-9af0-d617dfd228e7.gif)

The issue might be on the web apps side, as maybe it does not automatically refresh the data that is sent from servers.

If no errors and messages are shown the sync was successful.

**Comment by dandaka** [comment]
![toggl desktop 2018-01-29 12-00-09](https://user-images.githubusercontent.com/2384694/35504621-327b4e9c-04ec-11e8-96e3-6fc569d925a5.png)

![toggl 2018-01-29 12-00-45](https://user-images.githubusercontent.com/2384694/35504629-3841ec96-04ec-11e8-86ad-46aba9a216a7.png)

Can you forward this report to your "web app" side. Since I clearly experience a critical bug, which blocks work within app.

**Comment by IndrekV** [comment]
Please send feedback from the app so we get the app logs and your user info and can check what was synced and why it is not visible.

**Comment by IndrekV** [comment]
Mention that it's for Indrek so it comes straight to me.

**Comment by dandaka** [comment]
Done that

**Comment by dandaka** [comment]
Still not fixed.

**Comment by IndrekV** [comment]
Do you see your missing items in the web reports?

**Comment by dandaka** [comment]
I have stopped time entry on Toggl Desktop. Time is still running on Toogl Web.

**Comment by IndrekV** [comment]
Thank you for the details. I've emailed you for more data so I can replicate the issue.

**Comment by IndrekV** [comment]
I have failed to reproduce this issue after many attempts. I also investigated the logs and everything seems to be in order. No failures in syncing. 
Also we have not received no similar feedback from other users.
This might have been a one time edge case.
