### ISSUE TITLE
OSX dialog window lacks date and has broken icons

### ISSUE THREAD

**Issue by dandaka** [toggl/toggldesktop#2372]
It was possible to edit date of time entry.

Icons were not jumping around.

![monosnap 2018-01-29 11-54-42](https://user-images.githubusercontent.com/2384694/35504278-53f954c0-04eb-11e8-86a8-560afe47c4cc.png)

**Comment by IndrekV** [comment]
Already fixed, but not released. Will be released today or tomorrow to beta channel. Duplicate of #2342
