### ISSUE TITLE
Application Can't run after install new version

### ISSUE THREAD

**Issue by msajadi824** [toggl/toggldesktop#2377]
Application can't run after install v7.4.107 in windows. Show this error after run it via CMD:

```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'TogglDesktopDLL.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at TogglDesktop.Toggl.toggl_set_log_path(String path)
   at TogglDesktop.Toggl.InitialiseLog()
   at TogglDesktop.Program.Main()
```

**Comment by IndrekV** [comment]
The version you are referring has not been released yet and is only available in the development channel. We do not advise the users to use the dev channel as it can be broken at times.

I suggest you uninstall this version and get the latest stable version from https://support.toggl.com/toggl-on-my-desktop/

**Comment by IndrekV** [comment]
The were some issues creating installer some dll-s were missing.
