### ISSUE TITLE
Dark pane when editing project details on MacOS

### ISSUE THREAD

**Issue by marceliwac** [toggl/toggldesktop#2380]
This issue relates to #96 

Let me copy the text of my comment here:

> I realise this is a long-closed issue, but given the fact that I have the same problem Op had I'd consider reopening it. The background for adding project seems really dark especially if there is nothing bright below it. Maybe reducing the transparency of the task-edition pane / making the semitransparent colour brighter would help make it more readable?
>
> <img width="1440" alt="screen shot 2018-02-02 at 10 18 32" src="https://user-images.githubusercontent.com/17514757/35726112-00fa61e4-0804-11e8-8a2a-70004e640e3b.png">

**Comment by IndrekV** [comment]
Issue #96 is about overall background color as at that point the popup was not implemented yet. I'm glad you brought this issue to our attention again. I'll take another stab at it.

**Comment by IndrekV** [comment]
The solution was easier than I thought. Thank you for your input. It will be available in the next release cycle ( in a week or two )

**Comment by marceliwac** [comment]
Many thanks for handling that so promptly.
Thanks, great job!
