### ISSUE TITLE
Edit view changes size when opening "Add project" form

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2382]
Edit view is made much wider. May be because of some long text client,tag etc in one of the dropdowns.

May be connected to #1280

**Comment by MartinBriza** [comment]
What widget theme are you using when this happens? 
Which widget in the UI do you call "edit view"? 
For me, with the Breeze theme (in KDE Plasma Desktop), the whole window becomes a bit taller each time I click "Add new project".
