### ISSUE TITLE
Distribute Linux app with SnapCraft

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2385]
https://snapcraft.io/

**Comment by MartinBriza** [comment]
I have managed to get a Snap build on macOS (using `snapcraft` and `multipass` installed from `brew`). I didn't find a way to build Snaps with our current build infrastructure - our VMs don't get provided with VT-x (virtualization CPU instructions) and `snapcraft` refuses to run.
It could be worth investigating if we could build all of our packages inside `multipass` - it's a tool to orchestrate Ubuntu VMs and it runs just fine directly on macOS.

**Comment by IndrekV** [comment]
We're live! https://snapcraft.io/toggldesktop
