### ISSUE TITLE
Linux version 7.4.112 fails to start

### ISSUE THREAD

**Issue by ricotheque** [toggl/toggldesktop#2386]
case/638426 and case/638290

## Error message
When attempting to launch from command line this is encountered:

_$ ./TogglDesktop
./TogglDesktop: error while loading shared libraries:
libTogglDesktopLibrary.so.1: cannot open shared object file: No such
file or directory_

_$ ./TogglDesktop.sh
/opt/toggldesktop/./TogglDesktop: error while loading shared libraries:
libssl.so.1.1: cannot open shared object file: No such file or
directory_

## Potential cause
case/638426 theorizes:

_It looks like the build process for libPocoNetSSL.so.50 used libssl from 
the system library (that it was built on) instead of the libssl.so.1.0 
that is baked into the ToggleDesktop /opt/toggldesktop/lib_

_Perhaps due to work on #2279 and #2286_

_The result is that Toggl linux will not run on Ubuntu 16.04 which only 
has OpenSSL 1.0.  It looks like no released Ubuntu has OpenSSL 1.1 yet._

## Potential workaround
Downgrading to 7.4.71 has worked for case/638290, so this might be a feasible workaround for this issue at the moment.

**Comment by ricotheque** [comment]
Confirmed for case/638306 as well.

**Comment by elyssonmr** [comment]
I got the same problem :(

**Comment by IndrekV** [comment]
closed with eb0d5c4d558188734cd42b485dc3b244ba997312

I've released new beta version (7.4.118) with the fix.
[tar.gz](https://toggl.com/api/v8/installer?app=td&platform=linux&channel=beta)
[deb](https://toggl.com/api/v8/installer?app=td&platform=deb64&channel=beta)

**Comment by ricotheque** [comment]
Thanks for letting the users know about the fix, @IndrekV!
