### ISSUE TITLE
OSX stopped working (2nd time in 5 days)

### ISSUE THREAD

**Issue by edjere** [toggl/toggldesktop#2387]
Hi guys,
Are there any updates being made that may be affecting the app or is it something on my computer? My toggle desktop app stopped opening last week so I had to uninstall it and download it again to make it work.
I first tried the App Store version but that one did not work either.
Today, maybe 4 days since I reinstalled it I am having the same issue. Any idea what could be happening?

I know I can use the browser version in the meantime, but it is not as easy.

Thanks. 

By the way I am running macOS Sierra 10.12.6

**Comment by IndrekV** [comment]
What version of the app you are using. The version from our website is the most up to date version. Can this be connected to mac restarting as described in this issue #2141

**Comment by wuiidl** [comment]
I had the same problem. My mac console told me that toggl was looking for libcrypto1.1.dylib. That file was nowhere to be found.

macos 10.13.3
Below you can find the part of the crash report.
======
Dyld Error Message:
  Library not loaded: /usr/local/lib/libcrypto.1.1.dylib
  Referenced from: /Applications/TogglDesktop.app/Contents/Frameworks/TogglDesktopLibrary.dylib
  Reason: image not found

**Comment by IndrekV** [comment]
@wuiidl This issue should be fixed with the latest [beta version](https://toggl.com/api/v8/installer?app=td&platform=darwin&channel=beta)

**Comment by edjere** [comment]
@IndrekV I am using version 7.4.91. got it from here last week: https://support.toggl.com/toggl-desktop-for-mac-osx/

I don't think it is related to the issue #2141. I had this problem without even reseting, just closing the app. And also, I don't get any pop-ups or messages. It just does not open.

How stable is the beta version? Should I try this?

Thanks!

**Comment by edjere** [comment]
Running the beta version now. Seems to be working at the moment.

**Comment by IndrekV** [comment]
I tested the version 7.4.91 and it was indeed broken. The latest beta has the fix so it should be ok now.
