### ISSUE TITLE
Mac touch bar support

### ISSUE THREAD

**Issue by DustinJSilk** [toggl/toggldesktop#2388]
**This is a feature request.**

**The Issue**
The one thing I wish Toggl would make is a time line view. Similar to how music production software or any other time tracking tools work. Drag, stretch, copy, paste.

Because only some of our agencies employees use the live tracking. The rest prefer to do it at the end of the day / week. And its incredibly difficult to do currently - grouping tasks, AM / PM switching, ordering of tasks, reading times and trying to find the gaps. Ugh, it sucks and takes so damn long.

Ive asked Toggl support if they'll ever add a timeline view. They said no. They're all about live tracking.

**The Resolution**
Fine! The only way to really make live tracking work for me (and im sure a few others) is to have the tracker buttons display on Macs Touch Bar. That way its always accessible. And maybe i'll learn to love Toggl.

Please. Please make this happen.

**Comment by IndrekV** [comment]
The mac touch bar always shows functions from the application that is in focus. That means that it's not possible to always show Toggl connected button on the touch bar.

To improve your live tracking I suggest you take a look at all our tracking helper features.
- Tracking reminders
- Autotracker
- Idle detection
See more info: https://support.toggl.com/toggl-desktop-for-mac-osx

**Comment by yivo** [comment]
Please, see https://github.com/stevenleeg/harvest-touchbar. It is possible to do.

**Comment by trilliput** [comment]
Here is one more example https://github.com/azirbel/touch-bar-timer

**Comment by IndrekV** [comment]
Thank you for the tip @trilliput
This example looks very promising. I'll push this feature up on our list.

**Comment by rijk** [comment]
This might be of interest too: https://pock.pigigaldi.com/lack/

**Comment by franzwilhelm** [comment]
I'm on the case creating this! Already did a simple version for i3wm for my linux pc (https://github.com/franzwilhelm/dotfiles/blob/master/i3/scripts/toggl), but now I'm working on a much cooler version for the touch bar :D

**Comment by dianetoggl** [comment]
[User request](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3540765/conversations/24215718451)

**Comment by IndrekV** [comment]
The main functionality for Touchbar is finished. It will be available soon. This is what it looks like

<img width="1090" alt="Screenshot 2019-11-04 at 12 34 11" src="https://user-images.githubusercontent.com/842229/68098370-a6cbcb00-feff-11e9-87cf-74d214a2d66d.png">

You'll see the 5 recent unique time entries and the start button on the right.
Also, there will be a global Toggl button in the touch bar so you can always start or stop timer no matter what app is in focus.
