### ISSUE TITLE
Manual entry appeared as partial time

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#2389]
Case:640216 User iD:2091747

User inputted a manual time entry but the following occurred

"If you can see my account, the entry I'm referring to is on Thursday, Feb 1
at 7:00 PM. I manually entered that entry starting at 7:00 and ending at
9:30 PM. I would have expected Toggle to display 2:30:00 for the duration
but it displays 2:29:08."

editing the entry in web corrected the length of time to display 2:30:00.

Screenshots included in case

**Comment by IndrekV** [comment]
Issue is not connected to desktop app. The screenshots of manual entry are from webapp.
