### ISSUE TITLE
App closes right after log in on Mac

### ISSUE THREAD

**Issue by aguerilla** [toggl/toggldesktop#2390]
Downloaded multiple previous versions of app and restarted but none of the versions going back to 7_4_52 have worked.

I've also tried the app via the website instead of Apple store with no luck.

No luck with restarts either.
[Report.txt](https://github.com/toggl/toggldesktop/files/1704062/Report.txt)

**Comment by IndrekV** [comment]
Please write to support@toggl.com and let us know what email you are using for your account so we can try to replicate this issue. Also mention that the data is for Indrek so it is forwarded to me.

**Comment by IndrekV** [comment]
Same issue `case/640839`

**Comment by IndrekV** [comment]
@aguerilla I've made some changes and built a new version. I would appreciate if you could test it out and let me know if these changes fixed the issue.

[version 7.4.120](https://github.com/toggl/toggldesktop/releases/download/v7.4.120/TogglDesktop-7_4_120.dmg)

**Comment by aguerilla** [comment]
I've tried this new version and the old one.  The app is saying I no longer
have access to my workspace and I need to log in.  When I click on login to
toggl it opens a chrome page which is already logged in but the app does
not work.

**Comment by IndrekV** [comment]
Thank you for the feedback. This helped me reproduce the issue reliably and fix it. As a last request can you confirm that this issue is fixed in the latest build [74.121](https://github.com/toggl/toggldesktop/releases/download/v7.4.121/TogglDesktop-7_4_121.dmg)

**Comment by IndrekV** [comment]
Lates build [7.4.122](https://github.com/toggl/toggldesktop/releases/download/v7.4.122/TogglDesktop-7_4_122.dmg)

**Comment by aguerilla** [comment]
.122 Works - thank you!
