### ISSUE TITLE
macOS 7.4.84 freezes when shutting down

### ISSUE THREAD

**Issue by maritoggl** [toggl/toggldesktop#2392]
The toggle desktop app for OSX freezes about 50% of the time when trying shut it down (forced shutdown of the app required). Version of app: 7.4.84 System: macOS High Sierra 10.13.3 My general way of using it is; - launching the app at the start of the, around 9.30 AM - leaving it running all day, changing the timer whenever I switch between projects or take a break - stop the last timer at the end of the around 7PM - press CMD-q to shut down —&gt; freezes 

case/641381

**Comment by IndrekV** [comment]
Fixed with b4ed9b4fbf3f36a561014dfc884a69b63e9f0e24
