### ISSUE TITLE
Timeline not working on arch linux

### ISSUE THREAD

**Issue by twistedjoe** [toggl/toggldesktop#2394]
Hi,
The timeline is not working for me on arch linux.  It just show a wavy line like this : https://i.imgur.com/jefkuZs.png

I see that some people could not make it work before the support activated something for them. 
Could it be the same issue?

**Comment by IndrekV** [comment]
I will do some tests to see if I can replicate. The timeline data is sent in 15 minute chunks so the first data should be available after 15 minutes of timeline tracking.

**Comment by twistedjoe** [comment]
Yeah, I read about the 15 minutes. So I waited, but still no result hours later :confused: 

Will contact support too (like it was suggested in the other similar issues)

**Comment by TheSoloJake** [comment]
Hello Joe! I've enabled Timeline on our end; just reload the desktop app and you should be good to go! Let us know if everything starts working OK for you 👍

**Comment by twistedjoe** [comment]
It works! Thanks!
