### ISSUE TITLE
Clicking notifications on Mac should show Toggl

### ISSUE THREAD

**Issue by GreenGremlin** [toggl/toggldesktop#2395]
Clicking notifications on a Mac currently does nothing, but it should show the Toggl window.

**Comment by IndrekV** [comment]
Please share which notification you mean. Tracking reminder or something else.

**Comment by GreenGremlin** [comment]
Yes, I was referring to the tracking reminder. I did just notice the "Track" button does what I'm looking for, but it would be nice if clicking the alert itself took the user to the app.
