### ISSUE TITLE
Total Daily Time Going Over 24 Hours

### ISSUE THREAD

**Issue by ohare93** [toggl/toggldesktop#2397]
In the Toggl Desktop client I constantly get days where my total time is 29 or 31 hours, seemingly because of when I start my sleep timer. I always have a timer running, and only every one, so my total time should be as close to 24 hours as possible.

Instead I get this:
![image](https://user-images.githubusercontent.com/1471350/36303749-1c27d008-1305-11e8-9bc7-640b951849bc.png)

Which seems to be because I started sleeping at 12:00AM (midnight) and then slept again at 10:30PM, and it is counting both instances of 8hours as being entirely part of that day.
![image](https://user-images.githubusercontent.com/1471350/36303828-64038156-1305-11e8-8953-47c3bac2c2e1.png)

And this then takes time away from the next day too.

**Comment by IndrekV** [comment]
Day Total time is calculated by time entry start time. The entry belongs to the day it is started. We do not do split calculations and account part of the entry to one day and another part to another day. This is done so across all our apps.

**Comment by ohare93** [comment]
>This is working as intended, it's a feature not a bug

This may be your intended result, but it is not a user's expected outcome. No one expects to get 34 hours tracked in one day and 16 hours in the next. Will you consider adding this as an option, at least?
