### ISSUE TITLE
Unable to redisplay app after minimizing on multi-monitor setup.

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/toggldesktop#2399]
Mac Version 7.4.122

I have the app minimised (Mac OSX). I click the icon in the Dock and I get
the usual animation to show the window coming up out of the Dock to return
to show normally. However the app does not display. The animation ends and
I have no visible UI. If I right-click the Dock icon -> Show All Windows I
get "No Available Windows" on both my external monitors and my laptop
display. Only way out of it is to exit the app (right-click on the Dock
icon and select Quit) and restart.

**Comment by lizaPlotnikova** [comment]
Hey! Client's asking what the progress on this is. Any updates?

**Comment by VeljkoTN** [comment]
case/645998

Client reached out again, if possible please prioritize, thank you!

**Comment by IndrekV** [comment]
Closed together with #2232
