### ISSUE TITLE
Autotracker not working

### ISSUE THREAD

**Issue by crysiss** [toggl/toggldesktop#2402]
I'm on os X 10.11.6 with Toggl 7.4.129 and autotracking doesn't start at all after adding keywords and projects to be tracked.

**Comment by IndrekV** [comment]
I'm unable to replicate the issue. For me it shows the popup as expected.

Autotracker works when the timer is not running and you open up an app that has a keyword in the description. At that moment the app shows a notification to start tracking and you can click on it to start tracking the project specified.

**Comment by crysiss** [comment]
I'm unable to replicate your solution with Toggl launching on startup and fullscreen apps. Actually, just tried closing the apps and starting them again, not in fullscreen—no effect.

**Comment by IndrekV** [comment]
Please send feedback from the app and mention that it's for Indrek. That way I get log files and can look into it.

**Comment by IndrekV** [comment]
Did not receive info. Closing as we have not had any other similar feedback.
