### ISSUE TITLE
Toggl mini-timer should be opened in the active viewport (Windows)

### ISSUE THREAD

**Issue by phoogkamer** [toggl/toggldesktop#2403]
Usually I work with a multi-monitor set up, but there are times when I just work on my laptop without those external screens. When that happens my mini-timer is not in the active viewport. Disabling and re-enabling the mini-timer doesn't help. This happens even if my laptop has cold booted. 
Generally when this happens with other apps you can hit alt+space to maximize (this gets it on your active viewport), but the mini-timer can't be maximized (of course). You can only move the mini-timer, but it's often very hard to locate it like this.

**Comment by Aprinceinside** [comment]
I have the same problem and I am still looking for a solution
