### ISSUE TITLE
Provide Preferences Option to Start on Machine Startup

### ISSUE THREAD

**Issue by DarwinJS** [toggl/toggldesktop#2407]
I know there is a closed issue on this topic with a work around of "add it to your startup folder" - however, given that I am trusting Toggl Desktop to help me with remembering to track my time - not having this as a built-in configuration seems like a glaring omission toward the intent of Toggl Desktop (given how many very detailed settings it has for auto-tracking).  Most other programs I have seen that support this do indeed simply add a shortcut to "Startup" for which ever users configure it in the programs UI.

Also for non-technical folks it is a non-trivial experience to find exactly where the EXE is and then also find exactly where their personal startup folder is and right-drag and drop to indicate shortcut creation rather than a file copy.

Since it is not even installed in one of the Program Files folders - it is even more challenging.

**Comment by IndrekV** [comment]
Fixed with #3075

Will be available with next release.
