### ISSUE TITLE
Pomodoro timer starting incorrectly

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#2408]
Video of behaviour included in case/657585

"When I start task by toggl desktop app(mac), task stops automatically in few seconds and starts pomodoro break. I need help. mac version: 10.13.1 toggl desktop: 7.4.129 "

**Comment by IndrekV** [comment]
Issue was caused by windows app that the user also had open on another machine. The windows app had pomodoro enabled.
