### ISSUE TITLE
Linux crashing

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#2410]
Crash dump - case/658128

Toggle 7.4.122
Linux Mint 18.3 XFCE (Ubuntu 16.04)

coredumpctl info TogglDesktop | cat
PID: 14483 (TogglDesktop)
UID: 1000 (rich)
GID: 1000 (rich)
Signal: 11 (SEGV)
Timestamp: Thu 2018-03-15 15:47:15 EDT (15min ago)
Command Line: /opt/toggldesktop/TogglDesktop
Executable: /opt/toggldesktop/TogglDesktop
Control Group: /
Slice: -.slice
Boot ID: dcb27f61afae494e8998c7a5f267a6e3
Machine ID: 0a2058fc54c649ada1c67c1b7f870152
Hostname: twd-lmxfce-201801
Coredump: /var/lib/systemd/coredump/core.TogglDesktop.1000.dcb27f61afae494e8998c7a5f267a6e3.14483.1521143235000000000000.xz
Message: Process 14483 (TogglDesktop) of user 1000 dumped core.

Stack trace of thread 14515:
#0 0x00007f5da6f8c84e __memcpy_sse2_unaligned (libc.so.6)
#1 0x00007f5daa0021a8 n/a (libTogglDesktopLibrary.so.1)
#2 0x00007f5daa002311 _Z20getFocusedWindowInfoPSsS_Pb (libTogglDesktopLibrary.so.1)
#3 0x00007f5daa062bc7 _ZN5toggl20WindowChangeRecorder20inspectFocusedWindowEv (libTogglDesktopLibrary.so.1)
#4 0x00007f5daa06479d _ZN5toggl20WindowChangeRecorder10recordLoopEv (libTogglDesktopLibrary.so.1)
#5 0x00007f5da9fb15d3 _ZN4Poco8ActivityIN5toggl20WindowChangeRecorderEE3runEv (libTogglDesktopLibrary.so.1)
#6 0x00007f5da5ab0667 _ZN4Poco12PooledThread3runEv (libPocoFoundation.so.50)
#7 0x00007f5da5aac6e6 _ZN4Poco10ThreadImpl13runnableEntryEPv (libPocoFoundation.so.50)
#8 0x00007f5da577c6ba start_thread (libpthread.so.0)
#9 0x00007f5da6ff441d __clone (libc.so.6)

Stack trace of thread 14489:
#0 0x00007f5da5782709 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
#1 0x00007f5da5a4513e _ZN4Poco9EventImpl8waitImplEl (libPocoFoundation.so.50)
#2 0x00007f5da5a7c0d9 _ZN4Poco22TimedNotificationQueue4waitEl (libPocoFoundation.so.50)
#3 0x00007f5da5a7d33e _ZN4Poco22TimedNotificationQueue23waitDequeueNotificationEv (libPocoFoundation.so.50)
#4 0x00007f5da5dd7c18 _ZN4Poco4Util5Timer3runEv (libPocoUtil.so.50)
#5 0x00007f5da5aac6e6 _ZN4Poco10ThreadImpl13runnableEntryEPv (libPocoFoundation.so.50)
#6 0x00007f5da577c6ba start_thread (libpthread.so.0)
#7 0x00007f5da6ff441d __clone (libc.so.6)

Stack trace of thread 14483:
#0 0x00007f5da6fe874d poll (libc.so.6)
#1 0x00007f5da055a38c n/a (libglib-2.0.so.0)
#2 0x00007f5da055a49c g_main_context_iteration (libglib-2.0.so.0)
#3 0x00007f5da7b36a87 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4 0x00007f5da7adf212 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5 0x00007f5da7ae6d3d _ZN16QCoreApplication4execEv (libQt5Core.so.5)
#6 0x0000000000412f87 main (TogglDesktop)
#7 0x00007f5da6f0d830 __libc_start_main (libc.so.6)
#8 0x0000000000413af9 n/a (TogglDesktop)

Stack trace of thread 14493:
#0 0x00007f5da5782360 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1 0x00007f5da40a2cb0 n/a (libQt5WebKit.so.5)
#2 0x00007f5da40a2cd9 n/a (libQt5WebKit.so.5)
#3 0x00007f5da577c6ba start_thread (libpthread.so.0)
#4 0x00007f5da6ff441d __clone (libc.so.6)

Stack trace of thread 14490:
#0 0x00007f5da6fb930d __nanosleep (libc.so.6)
#1 0x00007f5da5aad00e _ZN4Poco10ThreadImpl9sleepImplEl (libPocoFoundation.so.50)
#2 0x00007f5da9fa9392 _ZN5toggl7Context17uiUpdaterActivityEv (libTogglDesktopLibrary.so.1)
#3 0x00007f5da9fb1873 _ZN4Poco8ActivityIN5toggl7ContextEE3runEv (libTogglDesktopLibrary.so.1)
#4 0x00007f5da5ab0667 _ZN4Poco12PooledThread3runEv (libPocoFoundation.so.50)
#5 0x00007f5da5aac6e6 _ZN4Poco10ThreadImpl13runnableEntryEPv (libPocoFoundation.so.50)
#6 0x00007f5da577c6ba start_thread (libpthread.so.0)
#7 0x00007f5da6ff441d __clone (libc.so.6)

Stack trace of thread 14492:
#0 0x00007f5da5782360 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1 0x00007f5da5a44f43 _ZN4Poco9EventImpl8waitImplEv (libPocoFoundation.so.50)
#2 0x00007f5da5ab0702 _ZN4Poco12PooledThread3runEv (libPocoFoundation.so.50)
#3 0x00007f5da5aac6e6 _ZN4Poco10ThreadImpl13runnableEntryEPv (libPocoFoundation.so.50)
#4 0x00007f5da577c6ba start_thread (libpthread.so.0)
#5 0x00007f5da6ff441d __clone (libc.so.6)

Stack trace of thread 14491:
#0 0x00007f5da6fb930d __nanosleep (libc.so.6)
#1 0x00007f5da5aad00e _ZN4Poco10ThreadImpl9sleepImplEl (libPocoFoundation.so.50)
#2 0x00007f5da9f99f58 _ZN5toggl7Context16reminderActivityEv (libTogglDesktopLibrary.so.1)
#3 0x00007f5da9fb1873 _ZN4Poco8ActivityIN5toggl7ContextEE3runEv (libTogglDesktopLibrary.so.1)
#4 0x00007f5da5ab0667 _ZN4Poco12PooledThread3runEv (libPocoFoundation.so.50)
#5 0x00007f5da5aac6e6 _ZN4Poco10ThreadImpl13runnableEntryEPv (libPocoFoundation.so.50)
#6 0x00007f5da577c6ba start_thread (libpthread.so.0)
#7 0x00007f5da6ff441d __clone (libc.so.6)

Stack trace of thr

**Comment by nicktoggl** [comment]
further correspondence including a txt file with the full log (hopefully!) case/658128

**Comment by nicktoggl** [comment]
another dump sent in by user at case/658128

**Comment by nicktoggl** [comment]
Not sure if similar issue so I've added to this case, but another user had this as their crash dump (case 669951)

User agent: linux_native_app/7.4.122
Version: 7.4.122
UpdateChannel: stable

Content:
TogglDesktop[9372]: segfault at 7f9aec025006 ip 00007f9b6bae584e sp 00007f9b09fe85e8 error 4 in libc-2.23.so[7f9b6ba46000&#43;1c0000]

**Comment by MartinBriza** [comment]
I couldn't reproduce this on my system so I went ahead and guessed what could be the problem in this case, there was an unchecked `malloc` call right before memcpy and memcpy figures in the first backtrace.

There is unfortunately not enough information to be sure.

PR inbound soon.
