### ISSUE TITLE
Mac OS: Menu Bar Toggl Drop-down Menu Not Showing When Another App Is Full Screen

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggldesktop#2413]
When you go full screen on any app on a Mac (for example chrome) the top menu bar disappears (gets retracted upwards). 

If you move your mouse to the top of the screen the top menu bar will slide in from the top, at that point, if you click on the little Toggl icon - the drop-down menu will not show as it would if your currently active app wasn't in full-screen mode (in this case Chrome). 

We managed to reproduce the issue, here's a quick video: https://www.dropbox.com/s/jcuflh71qyfljol/Grab.mov?dl=0

case/659617

Let me know if there is anything else I can provide you with here.

**Comment by IndrekV** [comment]
I have not been able to reproduce this issue. It can be connected to some specific system preferences. I've tried changing dock design and "automatically show hide dock and menubar" setting but I am not able to reproduce the issue.

**Comment by TheSoloJake** [comment]
May have possibly been due to either an app or system update; I can no longer replicate myself (Macbook Air Early 2016, latest stable app version)
