### ISSUE TITLE
Show new TOS agree info in app

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2421]
Once new TOS is live users will have to agree to it to continue using the app. We should show popup with the info and block all actions in app if the TOS is not agreed by user.

We need to specify how we detect if tos is not already agreed by user.

**Comment by fonorobert** [comment]
from BE:

> endpoint to accept ToS - `v9/me/accept_tos`
> just a post, no content
> responses:
> 200 - OK - everything got saved
> 400 - user has already accepted the ToS - "You already accepted" or something similar should be shown
> 500 - internal error, something went bonkers
> 
> to trigger the dialog:
> `v9/me/preferences` will have a `ToSAcceptNeeded` field, show screen if its present and true
