### ISSUE TITLE
Mini Timer Goes Behind Taskbar In Win

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggldesktop#2424]
A user reported that (CASE #670463) the Mini Timer does not stay on top of the taskbar in Windows if the taskbar is clicked. 

I guess it's convenient for them to keep the timer there when something else is in full screen, but clicking on the taskbar will put the timer behind it, I did reproduce the issue (if this is an actual issue) in case it's something we can change in future: https://screencast-o-matic.com/watch/cFfhQNDd2D

**Comment by skel35** [comment]
Duplicate of #2045
