### ISSUE TITLE
Windows 10 users reporting a lag / freeze with autocomplete

### ISSUE THREAD

**Issue by maritoggl** [toggl/toggldesktop#2425]
A few Windows 10 users have reported a lag or the app freezing when creating time entries. Have not seen reports of the same issues with other Windows versions so far. 

_It is running frustratingly slowly. When I start to type in what I am doing it is clearly trying to search an ever expanding database of previous narratives I have already put in. This means everything gets stuck. It used to be for a couple of seconds but now it&#39;s 10 seconds and getting longer._
case/672684 (with logs)

_I recently started using Toggl on a new Windows 10 computer and I've been having many issues with the desktop app locking up the entire machine, which eventually forces me to hard reset. This has happened multiple time now and usually occurs when I'm selecting a project for a time entry._
case/672446

**Comment by TheSoloJake** [comment]
Case/672446 has now included log files via case/672696

**Comment by vedr4n** [comment]
@IndrekV Is Windows version 7.4.138 coming with revamped autocomplete? In other words, is it coming with similar tweaks such as version 7.4.137 for macOS?

**Comment by IndrekV** [comment]
@vedr4n 
The next windows stable release will have updated autocomplete that is fast like crazy. It's not ready in the version 7.4.138. Visually it will not differ but the engine behind it will be new. It's not ready yet, so it will take some more time to put all this new power working with the UI.

**Comment by maritoggl** [comment]
Freezing reported also in case/678384

**Comment by IndrekV** [comment]
Connected to #2042 
New fast autocomplete that fixes this issue was released with version 7.4.184
