### ISSUE TITLE
App freezes for 3 seconds when user start/continue tracking

### ISSUE THREAD

**Issue by dandaka** [toggl/toggldesktop#2428]
**Now**

App ofter freezes for 1-3 seconds, when users selects a project from autocomplete.
OSX 10.11.6 (15G20015)
Toggl 7.4.129 stable channel

**How to recreate**

1. Start a new time entry (timer is ticking)
2. Open edit of entry with shortcut
3. Enter task name
4. Enter project name
5. Select project from autocomplete
6. Timer stops ticking, app is frozen for 1-3 seconds
7. Timer continues with visible delay, jumps from for example 1:03 min → 1:06 min
8. App unfreezes

**Should be** 

Application doesn't freeze

**Comment by dandaka** [comment]
@IndrekV Works significantly better. Still lags persists.

For example, I press Start tracking (big green Play-like button). I see 0:00 → 0:02 with a lag. Does it wait for a web service to answer?

**Comment by markkorput** [comment]
Same, in fact almost every action in the app seems to cause a short timeout in the UI.

The improved design of the autocomplete is great! If I can add a suggestion; sort the description autocomplete suggestions in a way that suggestions for the  selected project are shown first.

**Comment by dandaka** [comment]
Another case.

1) Find a task you want to continue tracking
2) Press Play next to it (which I read as "Continue")
3) App freezes
4) Tracking starts from 0:02, which I read "it took 2 seconds for an app to fulfil the request"

**Comment by IndrekV** [comment]
I've released another beta version (7.4.140) that does all the timer actions async and without slowing down UI. Can you confirm that this fixes the freeze issue for you @dandaka @markkorput

**Comment by dandaka** [comment]
Works like a charm! I'm closing this for now.

**Comment by dandaka** [comment]
While problem now is 50% better, still a very noticeable lag persists.

1) When TAB-jumping from a task name to a project name, I can see 500-1000ms delay. It gets better when I use app a lot, and worse when it is idle from user input.

2) When Entering from filled task form and closing the edit window. Animation for close action "waits" for something for 500-1000ms.

**Comment by IndrekV** [comment]
I haven't been able to replicate this. I will try with a different account with more data to see if it is connected to the amount of data on the user account. Thank you for bumping this up.
