### ISSUE TITLE
Selecting project from list in mac yields random result

### ISSUE THREAD

**Issue by arnorb** [toggl/toggldesktop#2435]
After typing into the autosuggest field and then selecting the desired from the list below gives me some other project, even from another client.

**Comment by arnorb** [comment]
I should note that i've been on the beta releases by mistake.

**Comment by IndrekV** [comment]
I'm unable to replicate this issue.

Please share more details so we can replicate the issue.
Do you use the main view timer autocomplete or the project specific autocomplete in edit popup?
Do you select item with keyboard or with mouse click?

**Comment by IndrekV** [comment]
After some more testing I was able to reproduce the issue. It seems to happen when selecting with mouse and it pressing mouse button longer. Will work on a fix.
