### ISSUE TITLE
[BUG] Finish time moves when editing start time

### ISSUE THREAD

**Issue by Plorenzo** [toggl/toggldesktop#2437]
This is so annoying. 

Every time I want to edit the start time of a finished entry on the app, the finish time moves, so the total time stays the same, even though want I was trying to do is expand the entry.

EXAMPLE:
I start to work, after 10 minutes I remember to start the tracker, so i do it. After one hour I stop the timer, so the entry will be something like:

`Start-end time: 10:10 - 11:10` Total time: 1 hour

So I will go to the app to edit the entry to take into account the missing time, so I will edit like so: 

`Start-end time: 10:00 - 11:10` Total time 1:10 hours

Now if you close the little editing pop-up and you open it again, this is the result !!

`Start-end time: 10:10 - 11:00` Total time 1 hour **?!?!**

Version: 7.4.129
Macos: 10.13.4

**Comment by IndrekV** [comment]
There is a setting for this in preferences called "Change duration when changing start time" that defines if finish time or duration is updated when user edits the start time. It's the last in the list of settings. In your case it should be ticked.

<img width="562" alt="screen shot 2018-04-26 at 13 34 57" src="https://user-images.githubusercontent.com/842229/39303515-bee6e5c2-4956-11e8-8663-7199332695be.png">

Thank you, come again!
