### ISSUE TITLE
Clicking on autocomplete suggestions populates with wrong text

### ISSUE THREAD

**Issue by Leland** [toggl/toggldesktop#2448]
Clicking an autocomplete suggestion instead populates with a previous title. This is true for running timers, and past time entries as well.

Note that moving down the list with the arrow keys and pressing <kbd>Enter</kbd> does select the correct entry.

This is on Toggl App v7.4.156, and macOS 10.13.4

![screen recording 2018-05-14 at 12 51 pm](https://user-images.githubusercontent.com/714017/40011358-9ba3f7e4-5775-11e8-9f11-cb6da77a3d68.gif)

**Comment by IndrekV** [comment]
Thank you for reporting. I'm able to replicate the issue and will be working on a fix.

**Comment by IndrekV** [comment]
@Leland I've released a new beta version 7.4.159 with the fix. Thank again for your prompt feedback.
