### ISSUE TITLE
Toggl crashes when submitting a feedback

### ISSUE THREAD

**Issue by korg250** [toggl/toggldesktop#2449]
Hi.
I using Toggl desktop for Windows and updated today to beta version 7.4.155. When I try to submit a feedback, Toggl crashes:

![toggl](https://user-images.githubusercontent.com/1518676/40031845-f32c9730-57c7-11e8-9005-21465c0bc0e7.png)

I'm on Windows 10 version 1709, build 16299.431.

Thank you.

**Comment by ApocalypticFish** [comment]
Can confirm this 
![image](https://user-images.githubusercontent.com/18132080/40031938-2e22ae7e-5831-11e8-8468-b7453d25ab16.png)

**Comment by IndrekV** [comment]
This will be released to beta in an hour or so. Thank you for reporting.

**Comment by IndrekV** [comment]
New beta 7.4.157 with the fix is out!
