### ISSUE TITLE
Windows Desktop App Crashes On Left Arrow Key

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggldesktop#2453]
A user reported [case/695230] that the app crashes after they type in a description and use the left arrow key to move the cursor in the description field. 

The issue is there with running and stopped entries, I've managed to reproduce it: https://screencast-o-matic.com/watch/cFhFXqbgdZ

> Toggl Desktop crashes when I use the arrow keys to navigate in the description field. For instance, if I place the cursor at the end of "testing toggl char bug" and press the left arrow key, the program crashes. Right now I can reproduce it with any length of text, with both active and stopped time entries. I was on the beta release channel when I encountered this, and subsequently switched to stable, but that didn&#39;t seem to have any effect whatsoever.

User agent: windows_native_app/7.4.157-obm-87-obm-98-obm-99-obm-101
Version: [Latest Beta, released at (15-05-2018)] 7.4.157
UpdateChannel: stable

**Comment by nicktoggl** [comment]
another case case/695246

**Comment by IndrekV** [comment]
I'm able to replicate this. It happens when pressing left while autocomplete dropdown is opened.
