### ISSUE TITLE
Windows Desktop App Editing Time Entry - Date Issue

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggldesktop#2455]
A user has reported that when they edit time entries through the desktop app and change the date on an entry, the entry takes on the date of the day before the actual date. 

When the issue was reported the user was on Win 7, in the process of our correspondence they upgraded the laptop and the OS to Win 10, they have a fresh install and the same thing happens. 

We've checked with the user if their Toggl timezone setting matches their device timezone - the user confirms that it does. 

Backoffice shows that the users' latest known location was "Dallas, Texas, US" and that their time zone is "Australia/Adelaide" - I've asked about this, the user travelled to Dallas earlier this year but is now in Australia, not sure if this can be the cause of the issue (latest known location not updating in our system to his current location when he traveled back to Australia). 

Case: 672501

I've asked the user to select a different timezone, save the change, then change back to the correct timezone and save again to see if that will somehow affect things, but no result. 

Version: [Latest Stable, released at (05-03-2018)]  7.4.122

Let me know if you need anything else.

**Comment by Rodolfobm** [comment]
Probably his timezone changes isn't what's causing this. I'm facing the same issue.
OS: win10
Toogl version 7.4.184 stable
Timezone: UTC -3 Brazil
