### ISSUE TITLE
Notifying the user on the iPhone when a pomodoro break has ended

### ISSUE THREAD

**Issue by McLovin92** [toggl/toggldesktop#2456]
Whenever a pomodoro break has been completed, the desktop version reminds you to start a new task.

However, the Toggl app on the iPhone keeps on recording the time after the 5 minutes have been over.

Is it possible to let the iPhone app also remind you through a notification and/or a sound to get back to work after a pomodoro break has been finished?

**Comment by IndrekV** [comment]
As far as I know our mobile apps do not support pomodoro at the moment. The pomodoro features is local and app based (it's present in Toggl Desktop and Toggl Button browser extension) and our servers and other apps know nothing about the status of the pomodoro.  This kind of cross-app notification functionality is not present and we currently have no plans to look more into it.

Sadly this means I have to say no to this request. Thank you come again!
