### ISSUE TITLE
Random scrolling in time entry list

### ISSUE THREAD

**Issue by szpasztor** [toggl/toggldesktop#2463]
Steps to reproduce:
- open macOS desktop app
- start a time entry (click on 'play' button of one of the previous entries)
- click on the running entry's title on the top so the detail page pops up 
- close the detail page

At this point, the entries list immediately scrolls from the top (today's entries) back quite a bit. For me it scrolled back from May 29 to May 15. I have roughly 5-10 entries per day. 

macOS 10.13.4
toggl 7.4.129

**Comment by maritoggl** [comment]
case/743286

**Comment by gee-forr** [comment]
Same. :( On v7.4.232, macOS
