### ISSUE TITLE
Pressing esc still commits timer title changes

### ISSUE THREAD

**Issue by Leland** [toggl/toggldesktop#2470]
## Expected behavior

If you're editing a Toggl entry's title, pressing <kbd>Esc</kbd> closes the window and cancels the edit.

## Actual behavior

When editing a Toggl entry's title, pressing <kbd>Esc</kbd> closes the window but commits the edit.

macOS 10.13.4
Toggl 7.4.159

**Comment by IndrekV** [comment]
Saving updates instantly is a general functionality for macOS. The Undo functionality that will be available with the next release will allow to take back unwanted changes (#2695).

**Comment by donquixote** [comment]
I agree with @Leland. It is far too easy to accidentally mess up a time entry, e.g. with a scroll wheel motion. See also #3386
