### ISSUE TITLE
Autocomplete is forcing entries based on history

### ISSUE THREAD

**Issue by mutchlerzd** [toggl/toggldesktop#2476]
Windows 10, Toggl 7.4.176, Cache has been cleared, issue persists.

Just today, I have lost the ability to create new entries in my timer if the new entry finds any partial string match to my history.

Example: 
Historical Entry: Project 12345

I can create a new entry such as "Test 123", but if I try to create something like "Project 99999", after I click start it forces the entry to match the historical "Project 12345"

I have tried this with all entries that are prompted by my recent history in the desktop app, all are experiencing the same problems.

**Comment by ricotheque** [comment]
Thanks for reporting this! What you've described is similar to #2473, which already has a fix pending for the 7.4.180 update: https://github.com/toggl/toggldesktop/commit/a3a5dce859f687485d5d9952851578d17adb590c
