### ISSUE TITLE
Autotracker Issue Windows 7.4.176 Stable

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggldesktop#2478]
Case 718315

A user reported that when they select a project to go with a term in the Autotracker settings nothing happens. 

The project color turns to gray when selected and after adding the term and the project and saving the change - nothing shows up in the list below. 

I was able to reproduce the issue: https://screencast-o-matic.com/watch/cF1ilabWgd

**Comment by IndrekV** [comment]
I released a new stable (7.4.184) a few seconds ago that fixes this issue.
