### ISSUE TITLE
Idle detection notification scaling issue on a Surface Book 2 Windows

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggldesktop#2479]
Case 718426

> Due to display peculiarities, when I unlock my Surface Book 2, a lot of things on the screen change size. With Toggle, this causes a problem because when the idle time detection dialog displays, sometimes it gets sized so small that only the title bar is visible, and I can&#39;t interact with it or resize it. Could you verify whether that dialog has a minimum size set? If not, could you set one? If it already has one, then it may take more investigation to figure out why it shrinks to title-bar size. It might also be helpful to make that dialog resizable, so that at least if it shrinks too small to work with, I can manually resize it.

**Comment by skel35** [comment]
#3009 same issue
