### ISSUE TITLE
First autocomplete item always used even if not selected

### ISSUE THREAD

**Issue by timgaunt** [toggl/toggldesktop#2481]
I'm finding that the first item from the autocomplete suggestions is set as the timesheet item regardless of whether I've selected it or not -which is getting increasingly frustrating as you need to hit ESC to cancel it rather than TAB to move to the project selector.

This is on Windows Build 7.4.176

**Comment by IndrekV** [comment]
this is fixed in the latest release (7.4.184). Please update to get the fix.
