### ISSUE TITLE
Tasks are no longer grouped by project

### ISSUE THREAD

**Issue by acoulton** [toggl/toggldesktop#2484]
In 7.4.184 (possibly since 7.4.176) on Windows, the list of tasks is no longer grouped by project. Instead, there are two separate sections in the list, with all the tasks listed at the bottom alphabetically. This makes it very hard to select the right task if - as we do - you have similarly named tasks on multiple projects ("Support", "New features" etc) especially because in the default layout the dropdown is too narrow to see much of the project except the colour dot and the first couple of characters.

I think maybe this is related to the fix for #2454 to group projects by client : that doesn't really bother us, but having the projects and tasks now separated out instead of grouped together is a major annoyance.

**Comment by IndrekV** [comment]
Thank you or your feedback. We did a total rewrite of the autocomplete part to make it faster with larger amounts of data. We're working on bringing back the logic that was there before (like tasks grouped by projects in project autocomplete)

**Comment by acoulton** [comment]
@IndrekV OK, thanks for the response. Personally, I wasn't having problems with the speed of the autocomplete (and we have a reasonable list of projects and tasks) but I am now annoyed multiple times a day that it takes me longer to find and select the right task, and we're having to spend more time as a team reviewing and fixing our time logs for the cases where we've accidentally picked a task with the right name but on the wrong project... So would really appreciate if you could bring back the removed functionality, which we relied on, sooner rather than later.

**Comment by ricotheque** [comment]
For my reference:

/case/736059
/case/718588

**Comment by TheSoloJake** [comment]
@ricotheque case/718588 would like to know when deployed to beta, so just adding my name to this and placing the case in question in Pending

**Comment by IndrekV** [comment]
will be available form version 7.4.231 (currently in beta)
