### ISSUE TITLE
Mac crash 7.4.170

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#2488]
"Toggl Desktop doesn't work anymore.
(Quits each time I enter a word in the case "what are you working on")"

Screenshots of crash dump included in case/720269

**Comment by IndrekV** [comment]
I was unable to replicate the issue with similar data that user has.
Might be connected to the Mac version. User has Mac OS X 10.9.5.

**Comment by nicktoggl** [comment]
Potential second case at /case/721837

log files included, will ask if they can update OSX

**Comment by nicktoggl** [comment]
/case/722770

**Comment by IndrekV** [comment]
Tried replicating on macOs 10.10 with no success.

**Comment by ricotheque** [comment]
Hi @IndrekV to clarify: the desktop app won't work on macOS 10.9.5 and earlier?

**Comment by IndrekV** [comment]
I haven't been able to reproduce the issue with later systems and macOs 10.9.5 is so old that it is impossible for me to get a machine running it. It's almost 5 years old and the latest update for the system was 4 years ago. I think there isn't sadly anything we can do about it. We just need to update the wording on our page that describes what operating systems we support.

**Comment by IndrekV** [comment]
I think I actually found a way to test it. But we will need to start dropping support for old systems.

**Comment by IndrekV** [comment]
No Update on the solution yet. I've narrowed the issue down to some part of the autocomplete dropdown positioning logic, but have not found a fix yet.

**Comment by IndrekV** [comment]
Found the cause. We were using methods that were not supported in the older versions of macos. Will see if I can work around this.

**Comment by bobleponge22** [comment]
Same issue for me.  
I'm running 10.9.5. 
I've been using the app since april 2015 with no problem.  Have been running 7.4.170 probably since it was updated.
I confirm that since few weeks I'm experiencing the same issue.

I haven't updated or installed any software on my mac since in the past weeks.

**Comment by IndrekV** [comment]
There are still some issue, but I'm hopeful I can fix them and create a new version that works ok on mac 10.9

**Comment by bobleponge22** [comment]
Thanks for the update. 
Still crahsed with the 7.4.194, though. Anytime you type anything in the description or project text boxes. 
Crash log attached.

**Comment by IndrekV** [comment]
I just created a new development version. Could someone test it out to see if we'e managed to fix this thing. https://github.com/toggl/toggldesktop/releases/download/v7.4.203/TogglDesktop-7_4_203.dmg

**Comment by bobleponge22** [comment]
Yes!
Autocomplete is back with 7_4_203.
No more crash :)
