### ISSUE TITLE
Windows 7.4.184 - Entries not created as billable even if connected to a billable project

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggldesktop#2491]
Case 722463

A user reported and I was able to reproduce that, unlike the web app, the desktop app will not mark an entry as billable if it's created within a billable project:

> If a project is set to "Billable" and I create a new entry, the entry won't be set as "Billable" automatically.

![image](https://user-images.githubusercontent.com/36152180/41401376-fdb38b72-6fbf-11e8-806e-f16dba84cfed.png)

**Comment by maritoggl** [comment]
+ case/725973

**Comment by ricotheque** [comment]
For my reference:
/case/725761

**Comment by TheSoloJake** [comment]
Also case/725843
