### ISSUE TITLE
Windows 7.4.184 sometimes crashing when choosing a project

### ISSUE THREAD

**Issue by maritoggl** [toggl/toggldesktop#2495]
User reported that the Windows app (7.4.184) sometimes crashes when choosing a project. 

> After last update. It keeps crashing when i try to choose project. Hangs for a few secs, and then closes down completly. No errors shown or nothing.

case/723669 - logs included

**Comment by maritoggl** [comment]
conversation/17441911664 referring to the same problem. Logs included.

**Comment by TheSoloJake** [comment]
User from @maritoggl conversation has responded with further steps on how they recreate the bug

**Comment by IndrekV** [comment]
Probably duplicate of #2486 
Ask the user to try latest beta.
