### ISSUE TITLE
Clear notification after certain time

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2498]
if computer stays open for a long time then a list of notifications is visible in the action center/notification center.

We should clear notifications after let's say 5 minutes to avoid the long list of notification that user has to manually clear.

One other idea is to clear all older notifications when user acts on some part of the app (starts tracking )

**Mac**

https://developer.apple.com/documentation/foundation/nsnotificationcenter/1407263-removeobserver

**Win**

https://stackoverflow.com/questions/44544624/remove-toastnotification-from-actioncenter

**Comment by NghiaTranUIT** [comment]
IMO, regarding macOS, `NSNotificationCenter` doesn't nothing with User Notification (like the Reminder Notification). It seems to be a mistake.

We should check out the `NSUserNotificationCenter`, especially [removeAllDeliveredNotifications()](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649502-removealldeliverednotifications) and [removeAllPendingNotificationRequests()](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649509-removeallpendingnotificationrequ)

**Comment by IndrekV** [comment]
jep it was my mistake. `NSNotificationCenter` is for app-wide notification not system-wide. You are on the correct path with this.

**Comment by NghiaTranUIT** [comment]
Regarding windows version and from my understanding, our WPF app is using [wpf-notifyicon ](http://www.hardcodet.net/wpf-notifyicon) to handle all out-going notifications.
https://github.com/toggl/toggldesktop/blob/4bdd1c2664db25af0bf9e5b7bd3f9d6ce27c57d1/src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/PomodoroNotification.xaml.cs#L6
Looking forward to see how we do on Windows side ⚒
