### ISSUE TITLE
Clarify os support for mac

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2502]
We should support only 3 of the latest os releases to avoid issues with old operating systems not supporting our latest developments.

- [x] Update knowledgebase info
- [x] Detect os version and notify user

At first show that os version is not supported and will be blocked on 1st of Jan 2019

If the date has passed block the app and show overlay with info that OS is not supported and user should update operating system or use web app.

update only when a new release is supported (if not supported stay on an old version and notify the user that the app may become unusable and is not supported)

**Comment by ricotheque** [comment]
I've updated the following, changing the text from _10.8 Mountain Lion_ to _10.11 El Capitan_:

https://support.toggl.com/toggl-on-my-desktop/
https://support.toggl.com/toggl-desktop-for-mac-osx/
