### ISSUE TITLE
UX inconsistency between MacOS app and Web timer time format

### ISSUE THREAD

**Issue by ivan-zakharchuk** [toggl/toggldesktop#2503]
I can observe very annoying UX inconsistency in project activity timer displaying in the web (browser Tab show time format like hh:mm:ss) and MacOS app shows it on menu bar like (hh:mm) that look like glitchy for me.
Please let me know if there are any known obstacles to make it work the same on OSX as on the web, so I might try to create a PR for that.

**Comment by IndrekV** [comment]
The main reason for that format is to keep it simple and similar to regular clock show on the menubar. The main aim of the time and project name in the menubar is to allow the user to see what they are working on at a glance. I think adding the seconds there won't make much of a difference. It will just make something always tick and update on your menubar.
