### ISSUE TITLE
Request: Today's Total Time on icon or mouseover.

### ISSUE THREAD

**Issue by marcooosd** [toggl/toggldesktop#2504]
I'd love to be able to quickly see today's total time at a glance on the Windows desktop.

This could be either:

• On the taskbar icon (notification tray) itself.
• By mousing over the taskbar icon.
• On a persistent gadget like the 'mini timer'.

On Mac you've been able to do this since 2012: https://toggl.com/blog/menu-bar-icon-for-mac-users/

Like many people I use Toggl for productivity, and set a daily total time as a goal. Having the total time easily visible would be a great motivator!

**Comment by IndrekV** [comment]
Whoa what a blast from the past! The screens shot is a cool reminder of a Toggl Desktop from a few versions ago. I'll add the today total time to the menubar icon tooltip.

**Comment by marcooosd** [comment]
Thanks @IndrekV ! <3

**Comment by IndrekV** [comment]
Will be available in next beta. Hopefully released tomorrow.

**Comment by marcooosd** [comment]
Hey @IndrekV any news on this?

**Comment by IndrekV** [comment]
Thank you for picking up this issue once again. It seems that I mistakenly implemented this to mac app instead of the windows one.

**Comment by IndrekV** [comment]
I added the tooltip to the tray icon for windows this time. Will be available with next release. Probably in a week if testing doesn't find anything. Thank you again for pushing this.

**Comment by marcooosd** [comment]
Thanks very much @IndrekV!

**Comment by benchilds** [comment]
Is this still outstanding on Mac? Just wondering whether to report a bug or whether it's never been completed? Currently mine always reads `Total today: 0h 0min`.
