### ISSUE TITLE
Crashes and now cannot start - .NET framework version complaint

### ISSUE THREAD

**Issue by chipbite** [toggl/toggldesktop#2509]
Returning to toggl desktop after a few years...  things have gotten more unstable, it seems. Alot of crashes and hangs, and now I cannot start the application.

It complains about .NET framework version. 
My gut feeling is that this is wrong, why would this be a problem all of a sudden, it is still the same...

Here is a shot of the complaint dialogue asking for .net version 4.0:
![image](https://user-images.githubusercontent.com/559199/42087987-37ace236-7b98-11e8-8cbc-53e9dc157d77.png)

I have these installed:
`C:\Users\mawid6>dir /b /ad /o-n %systemroot%\Microsoft.NET\Framework\v?.*
v4.0.30319
v3.5
v3.0
v2.0.50727
v1.1.4322
v1.0.3705
`
I have tried:
* Removing and reinstalling toggl (TogglDesktopInstaller-7.4.184.exe)

Any tips?

(But on the other hand, the android app is atleast as unstable. 
It seems all of toggl solution is rather shaky... )

BR! /marcus

**Comment by IndrekV** [comment]
We have not had similar feedback from other users so it must be something with your system. I would advise trying to update or reintsall the .net v4.0 framework to see if this helps.

**Comment by chipbite** [comment]
OK. I will check to see if I can do that. Thanks.

**Comment by chipbite** [comment]
Update: Yup, was problem with my machine. Corp IT updates screwed up .net fwk and several other applications stopped working. Fixed now. 

Really sorry for the noise.
