### ISSUE TITLE
[macOS] Console and Preferences windows cannot be dismissed with keyboard

### ISSUE THREAD

**Issue by brodkewitz** [toggl/toggldesktop#2511]
The Console and Preferences windows don't respond to key commands to close them. ⌘W closes the Main Window regardless of which window has focus. Esc doesn't work either, as it traditionally would.

Console and Preferences appear to handle all other keyboard input for navigation, including ⌘` to switch focus between Console, Preferences, and Main Window.

**Comment by Leland** [comment]
Yep, can confirm. This one's pretty annoying
