### ISSUE TITLE
Win Desktop App 7.4.184 - projects without client issue

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggldesktop#2516]
Case: 738766

> When using Desktop app and having 2 Workspaces, projects from both are now appearing in the same list, while before were separated with a clear label of a Workspace the projects is located. It is kind of confusing, are you planning to fix it? Thanks!

![image](https://user-images.githubusercontent.com/36152180/42557930-0e011ce8-84f0-11e8-9436-3012991dd3f3.png)

**Comment by joseltorres** [comment]
+1
