### ISSUE TITLE
Latest version of toggledesktop stops suggest clients/projects when user start writing it into field

### ISSUE THREAD

**Issue by masak2009** [toggl/toggldesktop#2518]
Older version of toggldesktop suggest clients/projects from dropdown list when user start writing into field. Latest version has broken these feature. Some times it works but sometimes it not works. I can not recognize when it broken.

It's important to fix this, because when suggest not works then it's hard to use toggledesktop to track tasks for different projects each few minutes. :-/ 

TogglDesktop 7.4.170 on MacOS 10.11.6

**Comment by IndrekV** [comment]
We've done a bunch of updates for autocomplete since the stable release. I suggest you try the latest beta as it has probably the fix in it already. To get the latest beta just open "About" view and then change "channel" to beta. App will trigger automatic update.
