### ISSUE TITLE
Forcing the Timer to stop when Pomodoro mode is on creates Entry with mismatched Duration and Stop Time

### ISSUE THREAD

**Issue by ricotheque** [toggl/toggldesktop#2529]
On Toggl Desktop (say its 7:!6PM)
1) Turn on the Pomodoro Timer and set it to 30 minutes
2) Start the Timer, and name the Entry (for easy reference later)
3) Open the running Entry, and set the Start Time to 1 hour earlier (6:16PM)
4) See the Timer stop + a new entry created with a 30-minute Duration, but Start and Stop Times are still 6:16PM and 7:16PM (or one hour apart)

Desktop app shows wrong Stop Time:

![image](https://user-images.githubusercontent.com/5687885/43394790-7f9d6788-942e-11e8-88cf-20fd5f9c7baf.png)

Web app shows wrong Stop Time:

![image](https://user-images.githubusercontent.com/5687885/43394769-72d4f1b0-942e-11e8-90ec-e81b6dc688a2.png)

Replicated on macOS 7.4.221 and 7.4.170, reported by user on Windows 7.4.184

(/conversations/17742327971)

**Comment by TheSoloJake** [comment]
User reporting this on version 7.4.129
