### ISSUE TITLE
Project select not attaching when selecting from new grouped autocomplete

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2530]
User feedback from #1921

>This has gotten worse since the update when projects got grouped under clients. I start typing a client or project name and click my selection from the suggestions, it disappears. I try typing it out manually and it disappears. The only fix I have found is quitting the app and restarting. Restarting fixes it maybe 1 out of 10 times, but only long enough for me to input one entry, then the bug pops back up.

**Comment by ivicaned** [comment]
I also have this issue on OSX since last update, I can't use autocomplete for project. The way around is to click on Project and select project, without filtering projects by names/clients.

**Comment by IndrekV** [comment]
@ivicaned We released a new stable version yesterday (7.4.232). Please check if you have updated and let us know if the issue still appears in the newest version.

**Comment by ivicaned** [comment]
It happen in newest version, actually I noticed this issue yesterday, after Toggl is updated to newest version. In previous version I did not have this issue.

**Comment by IndrekV** [comment]
@ivicaned I think I found the cause and created a fix. Would you be up to testing if the issue is solved in this version https://github.com/toggl/toggldesktop/releases/download/v7.4.243/TogglDesktop-7_4_243.dmg
