### ISSUE TITLE
Extra "Projects -> No Project" header appearing on Project dropdown list

### ISSUE THREAD

**Issue by ricotheque** [toggl/toggldesktop#2545]
I see multiple instances of PROJECTS -> No Project appearing breaking the Project dropdown list's outline structure:

![image](https://user-images.githubusercontent.com/5687885/44438671-bc9eea00-a5f2-11e8-9af0-15a7800c0ccd.png)

![image](https://user-images.githubusercontent.com/5687885/44438707-eb1cc500-a5f2-11e8-817d-e0fb3d08c329.png)

Experienced on my 7.4.231 Windows desktop app, Upgrading to 7.4.237 had no effect unfortunately.

also reported by:
/conversation/18108296729
/conversation/18108443148

**Comment by IndrekV** [comment]
Closed with 083405a019160bb5f56f0e392df07ecea1d900db
