### ISSUE TITLE
User unable to select Projects from dropdown list

### ISSUE THREAD

**Issue by ricotheque** [toggl/toggldesktop#2546]
As shown in a video sent in by the user at /conversation/18111894727, they're unable to select a Project from the dropdown autocomplete list after typing out text.

Experienced on El Capitan (10.11.6), on macOS 7.4.232 (stable)

**Comment by IndrekV** [comment]
@ricotheque 
Probably same as #2541
See my comment:
>I've created a fixed version. If any of the users are up to it they could verify if the version fixed the issue for them https://github.com/toggl/toggldesktop/releases/download/v7.4.243/TogglDesktop-7_4_243.dmg
