### ISSUE TITLE
Toggl feature request: Default project dropdown in mini timer

### ISSUE THREAD

**Issue by pixellos** [toggl/toggldesktop#2547]
Now either we have to access options and change it every time we want to work on other client's context or click on started task and change it manually.

**Comment by IndrekV** [comment]
Thank you for the feature request, but I think adding this dropdown would only clutter the mini timer. The scenario you are describing where you need to switch to another client or project can easily be achieved either by continuing an older entry in the entries list or by starting to type the project name in mini timer description field that then autocompletes and shows the possible matches.
