### ISSUE TITLE
Request: Provide option to show today's total time as the main time display in task bar

### ISSUE THREAD

**Issue by QuestofIranon** [toggl/toggldesktop#2556]
Similar to #2504 

I think it'd be great to have an option to invert the displayed time so that it shows today's current time in the task bar/ mac menu bar and the current session time on mouse over. 

As another person who sets daily time as a goal, I think this would be largely helpful.

**Comment by IndrekV** [comment]
**On mac:**
Today's total is visible when hovering on the menubar icon
Current timer can be enabled in menubar with setting `Show timer on menu bar`

**On Windows**
Today's total is visible when hovering on the tray icon (added with #2504)
Current timer is not visible in a way that it is on mac, but you can use minitimer for smaller window that shows currently running timer.
