### ISSUE TITLE
Development builds deb releases

### ISSUE THREAD

**Issue by furai** [toggl/toggldesktop#2558]
Hello,

I'm wondering why aren't there latest deb files in the latest releases. Is there some problem with building the app? Or was it not done because it's not stable enough? 
I've installed the latest available which was something like .184 but I'm willing to try newer builds if possible.

I've started compiling it but I don't have time for it right now so I left it alone. Is there anything I can help with? 

Cheers,
Furai

**Comment by IndrekV** [comment]
Hey, thanks for showing interest in linux app. We don't keep the deb building in the regular dev build loop. We only create deb package when we do a release. Either a beta or stable release.

**Comment by furai** [comment]
Is that a manual process?
