### ISSUE TITLE
#2480: Line Edit appears unfocused when autocomplete is open

### ISSUE THREAD

**Issue by MartinBriza** [toggl/toggldesktop#2571]
This is annoying because it appears as if you could not enter more characters

![screenshot_20180906_121747](https://user-images.githubusercontent.com/3977440/45151537-e51c0c00-b1ce-11e8-9b02-1208d438d741.png)

versus

![screenshot_20180906_121726](https://user-images.githubusercontent.com/3977440/45151546-e9482980-b1ce-11e8-883c-6fa617b7ab1c.png)

Part of #2480

**Comment by IndrekV** [comment]
I agree.
