### ISSUE TITLE
Reminders appearing despite running Timer

### ISSUE THREAD

**Issue by ricotheque** [toggl/toggldesktop#2576]
User is reporting on /conversation/18393912060 that despite having a running timer, his reminders still appear.

In this specific case, it appeared even though they were two hours into tracking their current Entry.

Happened on 2.4.237 and 2.4.252

Microsoft Windows 10 Pro

Version 10.0.15063 Build 15063

**Comment by IndrekV** [comment]
My first hunch was that the running time entry data is incorrect and reminder check thinks nothing is tracking. I've tested out all the possible reasons and looked through the code to see if I can find possible reasons for this, but sadly I haven't been able to replicate this issue and find any logic that would make this happen.

**Comment by jlsjonas** [comment]
Could it be related to the toggle-button having the above issue? https://github.com/toggl/toggl-button/issues/723 could be related

**Comment by IndrekV** [comment]
Yes this is a Toggl Button issue. Toggl Button does not update properly and shows the reminder as it does not know the latest status of the timer.
