### ISSUE TITLE
Tags do not get applied when time entry autocomplete is used in time entry edit view

### ISSUE THREAD

**Issue by maritoggl** [toggl/toggldesktop#2577]
Steps to reproduce: 
1. Have record some time entry present where name, project and tags filled 
2. Start tracking the new blank task 
3. Click on the currently running task -&gt; detailed window opens 
4. Start entering the name of previously tracked time entry which has the tag filled (see step 1) 

Expected result: The tag value gets populated from the existing record 
Actual result: The tag value does not get populated. Initially also project does not get populated, but by closing and reopening the window, project is displayed. 
Screen recording: check conversations/18427063491

PS. Issue is not present when using autocomplete right when starting a time entry - in such case tags get applied properly. Problem is only with autocomplete in time entry edit view.

**Comment by IndrekV** [comment]
Seems user uses keyboard to select item in edit view.

**Comment by IndrekV** [comment]
Fixed together with #2428
