### ISSUE TITLE
Reminder to track time does not disappear (Windows 10)

### ISSUE THREAD

**Issue by maritoggl** [toggl/toggldesktop#2578]
Windows 10 When user starts his machine from sleep mode, reminder notification appears on start screen and after he logs in to system the reminder is still showing and never disappears. 

User can't do anything with it. Even when he kills toggl process, the notification is still there. The only solution is to reboot a system. This does not happen all the time, but once every 1-2 weeks. 

![untitled](https://user-images.githubusercontent.com/35216651/45422200-2feac780-b698-11e8-8e53-d9ed1f16e2b5.png)

Logs in [conversations/18466381583](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2100822/conversations/18466381583)

**Comment by skel35** [comment]
Won't be happening anymore with custom UI for notifications implemented in #3065.
