### ISSUE TITLE
Not syncing on Fedora Linux

### ISSUE THREAD

**Issue by stfl** [toggl/toggldesktop#2579]
Hi. I built the latest source myself. I logged into my account through Google account.
First login, I didn't see any tracked work. After reboot I see the previously tracked work but not the current on.
If I start a new timer through the website it's not visible in the App. Neither the other way around.
It also does not sync newly finished tracked items. neither way..

Seams like the entire sync is broken?!

Any log I can provide?

**Comment by stfl** [comment]
I also sent a bug report through the app now..

**Comment by IndrekV** [comment]
The self-built version is connected to testing server. See this article on how to make it work with live servers. https://github.com/toggl/toggldesktop/wiki/Building-Toggl-Desktop-from-source-for-usage-with-live-servers

**Comment by stfl** [comment]
Thanks. That finally works
