### ISSUE TITLE
Reminders not popping up - Windows Desktop app 

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#2583]
"The reminder feature doesn't seem to work. It is enabled but I am not getting reminders.

I have tried clearing the cache and re-installing. "

conversations/18611274344

**Comment by maritoggl** [comment]
conversation/19164560998

**Comment by maritoggl** [comment]
[conversations/19999363216](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/19999363216)

**Comment by maritoggl** [comment]
Reported also via [conversations/20128183131](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/20128183131)

**Comment by skel35** [comment]
Logs show that C++ lib calls are done properly, so the problem should be somewhere within `ShowBalloonTipWithLargeIcon()`. We use an outdated version of `Hardcodet.NotifyIcon.Wpf`, so updating this NuGet package might help.

**Comment by lise-toggl** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/22616252662)

**Comment by zdericnina** [comment]
logs sent for Lisa's case above: [case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/22649429797)

**Comment by lise-toggl** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/22812290808)
