### ISSUE TITLE
Linux desktop app crashes

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#2584]
Linux 7.4.184 Beta

When I click on 'Add new project' - 'Add new client' - Fill new client name - click on 'Add' button ToggleDesktop crashed

More information on bug, with video and log log at conversations/18549944315

**Comment by MartinBriza** [comment]
I can't reproduce this. Is there anything specific that triggers this?

**Comment by IndrekV** [comment]
Unable to reproduce this. Closing.
