### ISSUE TITLE
TE description drop-down matching suggestions list reloading issue

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggldesktop#2589]
User: 1464634
User agent: windows_native_app/7.4.252-obm-87-obm-98-obm-99-obm-101
Version: 7.4.252 
UpdateChannel: stable
Intercom conversation: conversations/18940031416

The user reported that when they first start typing an entry description the list of drop-down suggestions is accurate at first, but then after a couple of seconds the list is not filtered and all time entries show up as suggestions.

I was not able to reproduce this, clearing local data and a fresh install of the latest stable version did not help

**Comment by skel35** [comment]
Duplicates #2839

**Comment by skel35** [comment]
Fixed by #2960
