### ISSUE TITLE
Option to Bypass macOS Do Not Disturb

### ISSUE THREAD

**Issue by ambroselittle** [toggl/toggldesktop#2605]
I want to use Mac's Do Not Disturb while doing my Pomodoro timer, but if I do that, I don't get Toggl's notifications that my timer is up. Too bad it doesn't seem Mac let's me set app exceptions. 

So this is a request, assuming it's possible, to have on option in Toggl bypass the regular macOS notification mechanism when DnD is on. Meaning do it's own form of alerts that don't rely on that.

**Comment by IndrekV** [comment]
Thank you for your feedback. This is not an easy task to solve as "Do Not Disturb" is created for a reason and being as we use the system notifications supporting this would mean a rewrite of the notifications part. Sadly this is a no for this feature request.
