### ISSUE TITLE
New Client Name Not Attaching to Projects

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggldesktop#2607]
conversations/19341310307

Users in this case primarily create projects and clients in the Windows app. When creating "NEW PROJECT/NEW CLIENT" in the Windows app, only "NEW PROJECT"(sans NEW CLIENT) appear in the webapp when the entries are synced. 

The case conversation listed above also includes notes linking to four other cases that contain log files from 4 affected users in this case. All 4 use .252 (3 stable, one beta)

**Comment by maritoggl** [comment]
Seems the same as https://github.com/toggl/toggldesktop/issues/2015

**Comment by TheSoloJake** [comment]
@IndrekV I believe that we are getting reports of this happening in .252 

[Conversation link](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/19757287886)

**Comment by TheSoloJake** [comment]
User asking for an update?

**Comment by IndrekV** [comment]
This fix is available in the latest beta released just yesterday https://toggl.github.io/toggldesktop/#win/7.4.345
