### ISSUE TITLE
We need screenshots of the application to display in app stores

### ISSUE THREAD

**Issue by MartinBriza** [toggl/toggldesktop#2617]
Sort of related to #1688

These screenshots should be 16:9, without wasted space around the window. They can be hosted anywhere, even here on github, and provided in the form of a link. From what I remember, they are fetched once by the metadata provider, like GNOME Software, and then distributed separately, so it won't create unnecessary traffic on our side.

**Comment by IndrekV** [comment]
Let's host them in our github page or just post pictures here in comments and we can reference them from here. I'm not 100% that the images added to issue comments will stay available forever so I'd go with adding them to the `gh-pages` branch and our toggldesktop github page.

**Comment by IndrekV** [comment]
Latest release to use to take screenshots https://github.com/toggl/toggldesktop/releases/tag/v7.4.348

**Comment by IndrekV** [comment]
Examples of screenshots:

https://flathub.org/repo/screenshots/com.spotify.Client-stable/752x423/com.spotify.Client-d37432933a34a6f8d324025c2ed042c3.png

https://raw.githubusercontent.com/hughsie/fedora-appstream/master/screenshots-extra/tomboy/a.png

**Comment by IndrekV** [comment]
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots

**Comment by IndrekV** [comment]
Here are the screenshots
![linux_ui2](https://user-images.githubusercontent.com/842229/52778574-fb1bdb80-304e-11e9-83f0-f33f48c925c5.png)
![linux_ui1](https://user-images.githubusercontent.com/842229/52779144-4387c900-3050-11e9-9d78-3d1f2c9d3a5c.png)

**Comment by IndrekV** [comment]
Here are the screenshots:
![linux_ui1](https://user-images.githubusercontent.com/842229/52779506-fd7f3500-3050-11e9-80b4-abc5a6950d1a.png)
![linux_ui2](https://user-images.githubusercontent.com/842229/52779522-040dac80-3051-11e9-938b-730ec3c291ac.png)

**Comment by IndrekV** [comment]
Screenshot links in github pages:
https://toggl.github.io/toggldesktop/assets/images/linux_ui_main.png
https://toggl.github.io/toggldesktop/assets/images/linux_ui_edit.png
