### ISSUE TITLE
We need application metadata for Linux app stores

### ISSUE THREAD

**Issue by MartinBriza** [toggl/toggldesktop#2618]
For the .desktop file and .appdata.xml, we need these things:

- Summary (several words about the application)
- Description (a few sentences about the application)
- Tags (a bunch of separate keywords to make searching for and categorizing the app easier) - I have "toggl", "time", "tracking" and "productivity" so far

Not absolutely crucial at this moment, but we should translate the Summary and Description, too.

**Comment by IndrekV** [comment]
We can probably use Appstore data for reference.

**Comment by MartinBriza** [comment]
All this data will be contained in https://github.com/toggl/toggldesktop/blob/master/src/ui/linux/TogglDesktop/dist/toggldesktop.appdata.xml

A summary similar to this is also in https://github.com/toggl/toggldesktop/blob/master/src/ui/linux/TogglDesktop/dist/toggldesktop.desktop which is the desktop file we used to ship in the past
