### ISSUE TITLE
applet in gnome panel missing

### ISSUE THREAD

**Issue by landsman** [toggl/toggldesktop#2638]
App working fine, it's integrated to OS as a regular program but I don't have applet in panel for quick access as on screenshot bottom (image from google).

![image](https://user-images.githubusercontent.com/3184228/48773829-c8b94700-ecc8-11e8-9c1b-efc0ca7ab272.png)

Ubuntu 18.04.1 LTS
Gnome: 3.28.2
64-bit
Installed from: https://support.toggl.com/toggl-desktop-for-linux/

Where can be the problem?
Is this function only for Unity? :(

**Comment by MartinBriza** [comment]
Hi, I'm actually working on fixing this right now! The progress will be tracked in #2155.

**Comment by landsman** [comment]
I don't think so that this issue is relative to this issue.
It's only about notifications. No word about applet / panel.
