### ISSUE TITLE
Connection Issue on Mac App

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggldesktop#2639]
User reports that starting up the Mac TogglDesktop app shows a no connection issue; restarting the computer itself sometimes works in clearing the problem and allowing the connection, but only temporary. 

Case https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/19636502261 includes log files

**Comment by vedr4n** [comment]
[Test](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/18664975792)

**Comment by tsugua** [comment]
I'm finding the same issue. I'm not sure what is causing it. The app seems to run fine all day and then the next day I'm seeing the no network icon. Maybe a sleep thing? Are you leaving open a persistent TCP connection and it is not reconnecting to the servers? (I actually lost a day and a half worth of data because of this bug, I didn't realize my desktop app wasn't syncing and I opened the iPhone app and made a change and because of this change the data from the Mac app was thrown away when it did finally connect.)

**Comment by TheSoloJake** [comment]
Also this case https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/19718020084 

Includes log files

**Comment by tsugua** [comment]
I don't have access to those links. I'd be happy to try some tests on my system when it happens again, however I'm not really sure what to look for. Do you think it's a TCP or HTTP socket getting stuck open and not self-healing when the connection is lost?

**Comment by TheSoloJake** [comment]
Also https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/19720992160

**Comment by TheSoloJake** [comment]
No worries about the links @tsugua ; they are for our team's reference as they work on the issue. If they do have any possible tests to ask you about, they'll be in touch!

**Comment by maritoggl** [comment]
https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/19809429936

**Comment by TheSoloJake** [comment]
https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/19850760212

**Comment by TheSoloJake** [comment]
https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/19738774677

**Comment by TheSoloJake** [comment]
https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/19869181668

**Comment by TheSoloJake** [comment]
https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/19858443428

**Comment by TheSoloJake** [comment]
https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/19958057310

**Comment by maritoggl** [comment]
https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/19988073630

**Comment by IndrekV** [comment]
I think I've gotten to the bottom of this @mari @TheSoloJake @Michelle112 

We'll review the changes and will push this fix to beta today if all seems good.
