### ISSUE TITLE
Modernize Objc codebase

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl/toggldesktop#2642]
## ⚒ Description
Our Objc codebase's style and structure seems to be out of date and there are bunch of smell code, which can slow us down when developing for long journey.

There are many best practice, which we can acquire easily to upgrade our codebase to new level.

This[ article from Ash Furrow ](https://ashfurrow.com/blog/structuring-modern-objective-c/) is one of the best resource, which explain carefully what the problem is and how we tackle it.

## ⭐️ Why do you want this?
We all want our codebase looks shiny and high quality, right? It's time to clean it up 🐞

## 🎩 Acceptance Criteria
1. Limit the accessibility of model's properties.
Examples:
+ There are a lot of public properties and they are writeable:
https://github.com/toggl/toggldesktop/blob/803d43a723ca36d562970a9ad9991a5bc0b0ee4c/src/ui/osx/TogglDesktop/TimeEntryViewItem.h#L15-L19
=> Use Read-only Properties in Headers

2. Should declare `nonatomic`
https://github.com/toggl/toggldesktop/blob/803d43a723ca36d562970a9ad9991a5bc0b0ee4c/src/ui/osx/TogglDesktop/TimeEntryViewItem.h#L29-L32
=> `atomic` leads to slow down the compile time and it doesn't provide full safe-thread ability.

3. `String` should be `copy` than `strong`
https://github.com/toggl/toggldesktop/blob/803d43a723ca36d562970a9ad9991a5bc0b0ee4c/src/ui/osx/TogglDesktop/TimeEntryViewItem.h#L58
=> `strong` mean the string is passed by reference. From my understand, it's the potential error, which leads to untraceable bugs.
=> `copy` is best practice in modern objc codebase, since it's copy value and `immutable`.

4. Fix warnings on Project and 3rd-parties projects

5. Don’t #import in Header Files Unnecessarily
There are a lot of benefits, such as faster compile time and avoid circular `#import` statement.
Ex: https://github.com/toggl/toggldesktop/blob/803d43a723ca36d562970a9ad9991a5bc0b0ee4c/src/ui/osx/TogglDesktop/TimeEntryListViewController.h#L10-L13

6. Move `#import "toggl_api.h"` to `precompiled header`.
https://github.com/toggl/toggldesktop/blob/803d43a723ca36d562970a9ad9991a5bc0b0ee4c/src/ui/osx/TogglDesktop/TimeEntryListViewController.h#L10

**Comment by IndrekV** [comment]
I'll add the Apple doc here also for reference https://developer.apple.com/library/archive/releasenotes/ObjectiveC/ModernizationObjC/AdoptingModernObjective-C/AdoptingModernObjective-C.html
