### ISSUE TITLE
Adding undo function to text fields

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2643]
Fields in edit view should have undo history per time entry. When pressing cmd+z it should revert to the previous value.

When a new entry is loaded into the edit view the Undo history list should be cleared.

Example of expected behavior:
- Open entry details
- Type in "Test" to the description field
- Move to the next field (description is saved)
- Move back to the description field
- Change text to "Undo" and press cmd+z
- The text should revert to "Test"

**Comment by NghiaTranUIT** [comment]
Block 🚫 by #2669

**Comment by NghiaTranUIT** [comment]
Close due to #2695
