### ISSUE TITLE
Acquire Diff Algorithm for TimeEntryListViewController's TableView

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl/toggldesktop#2651]
Regarding #2061 and #2643 

From my understand after playing-around the both tickets, I realize the root of problems.

In order to avoid the connection break between Popup and the entry when the list loads.

I think that we should consider about Diff algorithm in to our `timeEntriesTableView`

## Current Problem
1. Every-time we close the Edit Popup, this entry will save. Consequently, the `timeEntriesTableView` is reloaded completely with new list of entires (same GUID, but different instances)

## Drawback
It leads to visible consequences
1. Undo feature (#2643) is more difficult to implement because those instances are changed every-time
2. Popup feature (#2061) is hard to implement

## How Diff works
1. We shouldn't reload entirely the table.
2. We only update or add or remove a specific row, which changed from new DataSource.
3. ```By using Diff algorithm, the complex calculation is done automatically, no error-prone and super efficient.```

## Benefits
1. The instances of EntryTime from Entry List are same
2. Undo feature is now feasible, because this instance is alive and it's able to keep old value.
3. Popup feature is possible, because the table doesn't reload entire view, so the connection is maintained.

## Ref
- https://github.com/onmyway133/DeepDiff
- https://github.com/jflinter/Dwifft
- We might implement the lightweight Diff version (https://nghiatran.me/diff-in-real-world-ios-part-2/)

## Time Complexity
- `Wagner–Fischer` algorithm has O(mn) complexity, so it should be used for collection with < 100 items.
- `Heckel algorithm ` is O(n) 💯
- `LCS` is O(mn)

**Comment by NghiaTranUIT** [comment]
After preliminary investigation about "How to integrate Swift Diff library to out Objc codebase", I recognize that there are certain problems we're going to facing.

I will explain the problem and suggest certain possible solution (with pros and cons). Then we can make wise decision in order to acquire diff algorithm.

## Diff libraries
There are certain kinds of diff library, which implement different diff algorith out there.
Here are the noticeable one I can find.
1. [DeepDiff](https://github.com/onmyway133/DeepDiff) (Swift)
Overall, It's pretty neat, well-organized and efficient in term of time-complexity. It implements `Heckel algorithm`, so the result is incredible ([Benchmarks](Heckel algorithm)). The core diff functionality is same [IGListKit](https://github.com/Instagram/IGListKit) from Instagram does

2. [Dwifft](https://github.com/jflinter/Dwifft) (Swift)
Basically, it implement [LCS](https://en.wikipedia.org/wiki/Longest_common_subsequence_problem) algorithm, so the result is worse compared to DeepDiff.

## Problems
- Majority of diff libraries are dedicatedly written for Swift.
- Lack of native objc support.
- Don't use `@objc` annotation and subclassing from NSObject.

As a result, it's impossible to integrate directly to our Objc codebase.

## Solution 1: Fork 🍴
1. Fork diff library to our Toggl Organization
2. Support @objc annotation and subclass NSObject if possible
3. Integrate back to our objc codebase

### Pros
- Integrate **directly** to our codebase (don't' need to introduce any middleware)
- Re-use most of stable work from community.
- Don't re-invent the wheel.

### Cons
- Maintenance cost is bigger since we have to maintain our fork repository whenever the original repo has an update
- More work to support @objc

## Solution 2: Minimal diff version 🔨
1. We inspired from one of Diff library, then implementing all logic in Objective-C
2. Integrate directly to our codebase

### Pros
- Support fully to our requirement.
- Able to integrate directly.

### Cons
- Huge ownership of new-diff-lib (maintenance, fix bug, new features, ...)
- Re-invent the wheel

## Solution 3: Re-use and middleware
Basically, It's possible to integrate entire 3rd-party library (Swift) to our source code. Then introducing the middleware (swift) to call and handle all logic.

1. Add library project directly to our project
2. Make it as a dependency (like CrashReporter)
3. Write Swift middleware class and handle all diff logic here (Because Middleware class is writen by Swift, so it's able to call 3rd-library directly)
4. Adopt @objc and NSClass for our middleware, so it's possible to call our class from Objc codebase.

### Pros
- Integrate **indirectly** to our codebase
- Re-use most of stable work from community.
- Don't re-invent the wheel.

### Cons
- Have to take ownership on our middleware class.

## My thought 
I prefer the last solution (Re-use and middleware), because it's simple and reasonable in term of efficiency and Maintenance cost.

I also select [DeepDiff](https://github.com/onmyway133/DeepDiff#among-different-frameworks) as the potential candidate ⛑ 

How do you guys think? Feels free to open the discussion, then we make final decision to tackle this problem 💯

**Comment by IndrekV** [comment]
I checked into the DeepDiff and it is using CollectionView as the main object. We actually don't use CollectionView at all. We use NSTableView that we add rows of data. Would using DeepDiff mean that we'd have to convert our logic to NSCollectionView.

**Comment by NghiaTranUIT** [comment]
The selling-point of DeepDiff is a decoupling [logic](https://github.com/onmyway133/DeepDiff/tree/master/Sources/Shared). It provides us an ability to reuse it in macOS.

Thus, we have to implement simple logic for our NSTableView by using NSTableView's Batching Update, and inspire from the [UITableView's implementation](https://github.com/onmyway133/DeepDiff/blob/master/Sources/iOS/UITableView%2BExtensions.swift)

It's just 80 line of code for NSTableView's logic. For that reason, it's reasonable.

**Comment by khoi** [comment]
it sounds to me like you're looking for a **fast**, **battle-tested**, **Objective-C** diffing library. 

Based on those points, I nominate Instagram's IGListKit for a couple of reasons:

- written in Objective-C
- battle-tested
- well maintained
- has `Diffing` [subspec](https://github.com/Instagram/IGListKit/blob/master/IGListKit.podspec) if you're only interested in the diffing logic

IMHO, although the idea of diffing's trivial, finding the sweet spot for both execution and memory used is very difficult. I would prefer to delegate that task to a well-established team (Instagram) rather than someone's side project. Just my 2 cents
