### ISSUE TITLE
[Proposal] Rebase and merge

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl/toggldesktop#2655]
Regarding our Github flow, I realize that we're going to confront certain adversities ahead.

## Problem
1. Our Desktop team is expanding bigger soon.
2. There are many big PRs, which are bundled by many commits
3. The history of master branch isn't well-organize because all PR's commits are merged directly into Master.
<img width="585" alt="screen shot 2018-11-25 at 12 06 56" src="https://user-images.githubusercontent.com/5878421/48975755-acdbe980-f0aa-11e8-92cb-4cae8b8e2094.png">
4. Supper difficult to revert the big PR from master.

## Suggestion

**Shall we force squashing PR when merging to master? Like Toggl Mobile Team does?**

<img width="328" alt="screen shot 2018-11-25 at 11 55 42" src="https://user-images.githubusercontent.com/5878421/48975675-10651780-f0a9-11e8-8fcd-260ec5da46bf.png">

In my perspective, I totally thumb up the rule "Single Commit Rule' due to many following benefits, which we can consider by following criteria.

## Pros:
1. Easy to revert a PR (1 commmit) if needed
2. The squared commit is more meaningful, when it includes the number of PR.

<img width="373" alt="screen shot 2018-11-25 at 12 03 46" src="https://user-images.githubusercontent.com/5878421/48975727-2fb07480-f0aa-11e8-8a0a-8a2f2b4ad9e1.png">

3. Avoid conflict issue with rebase
4. Makes contribution process easy.
5. Keeps history of PR changes. => The history of master tree is linear, each commit is each PR.

<img width="409" alt="screen shot 2018-11-25 at 12 05 06" src="https://user-images.githubusercontent.com/5878421/48975731-5e2e4f80-f0aa-11e8-88c1-55e990b9b22b.png">

6. We don't need to use the bad -f (forced) option for amended commit

## Cons:
1. If Github changes or removes this feature, we have to go back to our traditional approach.

=========
How do you guys think? Feel free to open a conversation 👨‍💻

**Comment by IndrekV** [comment]
Thank you for bringing up this discussion.

My thoughts on this:

- Pull request merges should always be done with rebase to keep all commits about the PR in one list for easy bisect and revert if needed.
- For smaller pull requests (up to 3,4 commits) it is ok to use squash and only have a single commit
- For bigger pull requests let's keep all the commits for easier bisecting if needed. (it's easier to find the breaking commit if the commits are small). A good example of a big PR is the currently ongoing Linux autocomplete #2566. It would be a giant commit if squashed together.

Waiting for comments from @MartinBriza and then will add this info to the Team guideline

**Comment by MartinBriza** [comment]
Not a strong opinion from my side, I'm fine with whatever decision is taken in the end, but there is some stuff to consider:

From my point of view, the merges are a bit better separated if you do a regular merge commit because then the git history will look like this: 
![screenshot_20181126_091101](https://user-images.githubusercontent.com/3977440/49000874-3945e500-f15b-11e8-977b-b86fe8be0657.png)
Notice how the PRs on a completely separate branch. It's pretty clear what commit belonged to which branch in the past. As per the reverting stuff: while I haven't reverted a PR merge before, I'm fairly sure it's not a problem.

On the other hand, I agree in this case it wasn't really necessary, both PRs are very short and clear so I agree rebasing them on to the main branch (and probably even squashing the two-commit one) would have been cleaner and clearer. So I definitely don't have a problem with that approach, too.

**Comment by IndrekV** [comment]
Thank you for the feedback.  I agree that with merging it gives a good overview from which branch the commits came from. Tig does a very good job displaying this.

From this info let's agree:
- Small PR-s will be merged with rebase and possibly by squashing if commits are small
- Big PR-s will be merged regularly with merge commit. That will give a better overview of the commits coming from the other branch. Merging should always be done in your separate branch. 
Example:
```
git checkout your-branch
git merge master
git checkout master
git merge your-branch
```

Added info to Team Guidelines.

**Comment by amulware** [comment]
Note: you can enforce the merging you describe by enabling branch protection (in the repo settings) and only allowing up-to-date PRs to be merged into master.

Here is a screenshot of the settings for the mobile app's main branch (we do essentially the same: prefer small PRs and squashing, but bigger features get merged regularly).

<img width="738" alt="screenshot 2018-11-26 at 09 16 45" src="https://user-images.githubusercontent.com/3987892/49004488-43b4ae80-f15c-11e8-8910-48c18b756a8e.png">
