### ISSUE TITLE
Dropdown should compress from the right/end of text

### ISSUE THREAD

**Issue by danielcarr** [toggl/toggldesktop#2661]
### 💻 Environment
Platform: Linux (openSUSE Leap 15.0 Mate Desktop)

### 📒 Description
The text in the "What are you doing?" drop down box is anchored at the end, so when it is too long, the beginning of the text is pushed out and only the end of the task name is visible.
![long-name-task](https://user-images.githubusercontent.com/3668187/49287727-3b83a880-f4a7-11e8-9ad4-e0462496a9db.png)
I think the opposite should happen, with the text fixed at the start and ellipsized from the end (or in the middle — as is the case with inactive drop-down entries).
![toggle-dropdown](https://user-images.githubusercontent.com/3668187/49287917-dd0afa00-f4a7-11e8-9263-e71512a955a4.png)

**Comment by MartinBriza** [comment]
Oh god, this seemed like an easy issue to fix but now after I've spent the entire day trying to do this properly, I have to say this will remain in the bottom of the list of issues I'm going to fix for this milestone.
Why oh why does Qt not allow elliding text everywhere...

**Comment by IndrekV** [comment]
This is how I handled it in `timeentrycell` 4f3049b4ff66df718c076c868ad18d925817f72f

One way it can be done is that we have another so called display element in timer. So when editing we show the combobox and when timer is started w hide the combobox and show QLaber with the inserted text that is modified to display correctly.

This might be unneeded step if you can use similar logic like in the commit I added without messing up the time entry description when saving entry.
