### ISSUE TITLE
The entries list is disappeared suddenly

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl/toggldesktop#2667]
### 💻 Environment
Platform: macOS
OS Version: macOS 10.14
Toggl Version: lasted commit (#4bdd1c2) on Master

### 🐞 Actual behavior
Sometime, after the app has been opened, the app presents the entry list in 0.5 second, then it disappeared and show "Load More" Button.

### 💯 Expected behavior
+ It should show "Load More" button if all entries are old.

### 🔨 Steps to reproduce
1. Login and close the app completely 
2. Open app
3. Sometime, the app show the list of entry and suddenly show "Load More" button

### 📦 Additional info
Rate: 1/5 (20%) 
Gif:
![2018-12-03 19 39 01](https://user-images.githubusercontent.com/5878421/49374606-74847d00-f734-11e8-9916-a3c0b8e733df.gif)

**Comment by NghiaTranUIT** [comment]
This one can fix the scroller bar issue (
https://github.com/toggl/toggldesktop/commit/478fb5270bb5fc5fa65a9e8c95a2ef9d060aa648)

**Comment by NghiaTranUIT** [comment]
From what I experience when working on the Time Entry Editor view:
- We deliberately load entire Time Entry list at the first time in order to get those data (tags and build the auto-complete list) -> If not, we couldn't get the Tag & AutoCompleteData.

@IndrekV is it our intention?

**Comment by IndrekV** [comment]
The reloading fills the list with items from the last 9 days. All older ones are removed. This seems like the app deletes stuff. Showing items and then removing them is bad. The correct solution would be to not show older items at all and only show the listing once the first load is finished. In the example it should show `load more` button from the beginning.
