### ISSUE TITLE
Strange Auto-Scroll Bug on .253

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggldesktop#2671]
### 💻 Environment

Platform: MacOS 
OS Version: 10.10.5
Toggl Version: 7.4.253

### 🐞 Actual behavior
User scrolls down list of time entries, then leaves app window open and works in other window (ie, browser window). After a short time, the time entry list "jumps" up to newer entries. 

### 💯 Expected behavior
Normally, one would scroll down and the list would remain in the same spot. 

### 🔨 Steps to reproduce
1. Scroll down part-way on the time entry list
2. Wait for the jumping action to happen

### 📦 Additional info
N/A

**Comment by NghiaTranUIT** [comment]
I suppose that after leaving for a short-time, the entries list is reloaded, which results in the unexpected "Jump" 💥

Ideally, we have to keep the current position regardless of any sync or reload.

**Comment by TheSoloJake** [comment]
I would suppose that too, but the video that the user attached to the conversation shows the "jump" occurring on a random level; it doesn't jump to the top of the time entry list. 

If you'd like to see the video and do not have access to Intercom, please PM me in Slack and I'll give you access
