### ISSUE TITLE
Toggl Windows App Issue on Multiple Monitor Setup

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggldesktop#2681]
### 💻 Environment

Platform: Windows
OS Version: N/A
Toggl Version: 7.4.252

### 🐞 Actual behavior
If you have left the program on your secondary screen when turning off the computer and restart without secondary screen it is still on the secondary screen even though you can't see it. I can only see the visual effect of the window maximising and minimising to a screen which is not there. 

You can see the client flashing by the roboform popup in the lower right hand corner (and that pop up in unrelated). Please note, no other screen is connected. This effectively makes the desktop client unavailable for me until I connect to two screens and bring it back to the primary screen.

### 💯 Expected behavior
App should recognize active display set and should accommodate view to active display(s). 

### 🔨 Steps to reproduce
See "Actual Behaviour" for information 

### 📦 Additional info
https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/19951536312 

(Case link includes screenshot for reference)

**Comment by skel35** [comment]
The problem happens because `Utils.visibleOnAnyScreen()` method does not account for DPI of the monitor. We account for DPI in some other places, but not separately per monitor.
To make it work correctly we need to implement per-monitor DPI awareness, see #2066.

**Comment by skel35** [comment]
[Case link](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3155115/conversations/23167788321)
