### ISSUE TITLE
Idle detection time calculation issue when locking/unlocking machine

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2683]
### 💻 Environment
Platform: Linux

### 🐞 Actual behavior
We should check if this happens also in Linux app

### 💯 Expected behavior
Lock an unlock should trigger idle/not idle event and calculate idle time correctly.

### 🔨 Steps to reproduce
- Checkout master branch
- Open Toggl, override Idle time to 1 min (easy to catch the bug 🐞)
- Start any task
- Lock your computer 
- => At this time, tracking idle time should trigger
- Wait 2 min and open the lid, but don't log in to the machine yet.
- Close the lid again, or just waiting until the machine sleeps/locks automatically
- Open the lid, and actually log-in to Desktop.
- Toggl presents your idle time, but it's lesser than the expected total time.
- User reports time idle time is incorrect.

### 📦 Additional info
Connected to PR #2673

**Comment by MartinBriza** [comment]
This should be fixed by #2654 - there is a completely different mechanism to detect if (and how long) the user has been idle.

**Comment by IndrekV** [comment]
I tested it in Linux (KDE Plasma) and it seems to not be working properly.

It acted exactly as described in "Steps to reproduce" section. It detected the idle from the moment user opens the lid and does not log in, not the moment user suspends the first time.
