### ISSUE TITLE
Investigate adding Toggl Desktop to Chocolatey

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2684]
### 💻 Environment
Platform: Windows

### 📒 Description
Chocolatey seems to be the most popular one for windows. https://chocolatey.org/

Also we should look into some other package managers:  https://www.slant.co/topics/1843/~best-windows-package-managers

Should be worked on together with #2203 
Connected to #2289

**Comment by skel35** [comment]
https://chocolatey.org/packages/toggl/
