### ISSUE TITLE
Changing network connection means desktop app cannot connect without restart

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#2685]
Platform: Mac
OS Version: 10.14.1
Toggl Version: 7.4.321

### 🐞 Actual behaviour
From user
"I'm using toggl desktop 7.4.321 on mac 10.14.1 and everytime I change my network connection (e.g. some VPN or similar) toggl goes offline - that's ok. But it never connects back, it always stays offline even when manually pushing Sync;. The only option to get it back online and sync data is to restart the app."

case conversations/19987577219

**Comment by IndrekV** [comment]
Probably connected to #2639
