### ISSUE TITLE
Fix lib warnings

### ISSUE THREAD

**Issue by MartinBriza** [toggl/toggldesktop#2701]
### 💻 Environment
Platform: macOS/Windows/Linux

### 📒 Description
There's a lot of warnings coming from the library, especially unused variables and wrong initialization order in the classes which makes catching real issues pretty hard.

**Comment by IndrekV** [comment]
Ideas about how to suppress "unused parameter" warnings https://stackoverflow.com/questions/3599160/how-to-suppress-unused-parameter-warnings-in-c

**Comment by MartinBriza** [comment]
Yes, you can do this or omit the argument name from method definition
