### ISSUE TITLE
AutoTracker Not Tracking in Windows

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggldesktop#2712]
### 💻 Environment

Platform: Windows 
OS Version: Unknown
Toggl Version: 7.4.252

### 🐞 Actual behavior
Autotracker function not detecting user actions, even after all proper setup steps have been followed

### 💯 Expected behavior
Autotracker "sees" user activity that fits trigger words and asks to track time

### 🔨 Steps to reproduce

1. Set up Autotracker
2. Attempt to use

### 📦 Additional info
[User case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/19983618454)

**Comment by skel35** [comment]
Probably fixed with 64-bit release
