### ISSUE TITLE
Linux archive build broken: "cannot open libPocoXML.so.50"

### ISSUE THREAD

**Issue by danielcarr** [toggl/toggldesktop#2718]
### 💻 Environment
Platform: Linux
OS Version: openSuse Leap 15.0
Toggl Version: 7.4.328

### 🐞 Actual behavior
Opening toggl graphically fails silently, running from the command line throws the error message `TogglDesktop: error while loading shared libraries: libPocoXML.so.50: cannot open shared object file: No such file or directory`.

### 💯 Expected behavior
Toggl Desktop should start up normally, with new and improved features that I've been looking forward to.

### 🔨 Steps to reproduce

1. With toggldesktop v7.4.318 installed in `/opt/toggldesktop/`
2. Download [toggldesktop v7.4.328 Linux archive](https://github.com/toggl/toggldesktop/releases/download/v7.4.328/toggldesktop_linux_x86_64-7_4_328.tar.gz) to `~/Downloads`
3. Run `tar vxzf Downloads/toggldesktop_linux_x86_64-7_4_328.tar.gz -C /opt/`
4. Run `/opt/toggldesktop/TogglDesktop.sh`

### 📦 Additional info
- Error message `...TogglDesktop: error while loading shared libraries: libPocoXML.so.50: cannot open shared object file: No such file or directory`
- The application works again if I reinstall v7.4.318.
- The problem is present whether I've installed the new version into a a new directory or when the archive was extracted over an existing installation.
- It also makes no difference whether I run `TogglDesktop.sh` first or just run `TogglDesktop` directly.
- I have tried copying `lib/libPocoXML.so.50` from v7.4.318 to v7.4.328. The library files are different (based on byte size and running `cmp`), but that doesn't help.
- I have noticed that there are five libraries in v7.4.318 that were last modified in February that have been removed in v7.4.328:
  * `libicudata.so.54`
  * `libicui18n.so.54`
  * `libicuuc.so.54`
  * `libQt5WebKit.so.5`
  * `libQt5WebKitWidgets.so.5`.

  Adding these libraries doesn't make a difference, but I'm thinking maybe the library was built against these older versions.
- I can't see how it would make a difference, but I also noticed that the libraries in the new version are readable to all users, whereas v7.4.318 libraries were only readable to root (with the exception of the five libraries listed above).

**Comment by MartinBriza** [comment]
Hey Daniel, 
I'm sorry for the issues you had with this build, however this was just a development release and these can be unstable. Thank you for pointing out this issue to us, we're already working on fixing it for the following releases.
