### ISSUE TITLE
Hotkey doesn't close Windows pomodoro notification

### ISSUE THREAD

**Issue by BrendanMartin** [toggl/toggldesktop#2729]
Platform: Windows
OS Version: 10.017
Toggl Version: 7.4.252

### 🐞 Actual behavior
I have hotkeys mapped to start/stop the pomodoro timer. When the timer hits 25 mins, the popup notification in the bottom right corner of Windows shows up. When I use my hotkey to restart the timer, the notification does not disappear.

### 💯 Expected behavior
 I'm expecting that when the pomodoro notification pops up in the bottom right corner I should be able to hit my hotkey to start the timer again (which works) and close that notification at the same time. Instead, I have to double-click on the notification to make it disappear.

### 🔨 Steps to reproduce
1. Map hotkey to start/stop timer 
2.  Start timer, wait for 25 min notification popup
3. Press hotkeys to start timer again
4. Popup doesn't disappear, need to double-click it

**Comment by NghiaTranUIT** [comment]
It's a good point. We guarantee to take it into account 💯
