### ISSUE TITLE
Width changed when list view changes to empty view or the other way around

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2732]
### 💻 Environment
Platform: Linux

### 🐞 Actual behavior
Width changes to bigger size. Happens when creating first time entry ( empty view changes to listing view) or when deleting the last item in the list (list view changes to empty view)

### 💯 Expected behavior
View width should not change.

### 🔨 Steps to reproduce
Scenario 1:
1. Make app window width small
2. Delete last entry in the list
3. Window width is resized

Scenario 2:
1. Make app window width small
2. Make sure no items are in the list
3. Start the timer and stop it a few seconds later
4. Window width is resized

### 📦 Additional info

Gif shows what happens when the last item in the list is removed

![linux_width_resize](https://user-images.githubusercontent.com/842229/50518457-640abc80-0abe-11e9-90b7-780f0ffc44c3.gif)

**Comment by MartinBriza** [comment]
This doesn't happen to me. I tried it with very long tag names but the window size still stays the same.

Does this happen before or after merging the stackedwidget PR?

**Comment by IndrekV** [comment]
Yes this happens every time and after the stackedwidget PR. I don't understand what tag names are you referring to. Tag names or the data of the entries are not relevant to this issue. In the GIF there is no data in the time entry what so ever. As long as the width is small and I switch from empty view to list view or the other way around it happens to me every time.

**Comment by MartinBriza** [comment]
There has to be some UI element that's messing with the width of the windows, however I don't see anything special in your setup, except that you have a LOT of Tags in the list so I thought that could be why this happens. 
Otherwise, without any data, the size of the window doesn't change for me, hence I assume it's related to the Tags field anyway. There seems to be nothing special about your setup in the gif.

**Comment by IndrekV** [comment]
Scenario 2 is not connected to edit view at all. Can it be that this issue is similar to the issue with edit view changing width? Should we also have similar method to `void TimeEntryEditorWidget::aboutToDisplayTimeEntryList()` here

**Comment by MartinBriza** [comment]
That doesn't happen to me either so I really don't know. However I'd say this is still a layout issue - some widget is expanding when it should rather keep its width (and change only based on user input).

**Comment by IndrekV** [comment]
![linux_resize](https://user-images.githubusercontent.com/842229/50887132-0732ce80-13fb-11e9-8632-8257cb717856.gif)

**Comment by IndrekV** [comment]
That's extra strange. @NghiaTranUIT Are you able to replicate this?

**Comment by NghiaTranUIT** [comment]
Let me take a look on it 👍

**Comment by MartinBriza** [comment]
![qwmgkhshfi](https://user-images.githubusercontent.com/3977440/50887382-4eb55c80-13f3-11e9-8669-1db456befd1c.gif)

**Comment by IndrekV** [comment]
@MartinBriza Delete all items in list before creating new one. It happens when you go from empty  view to a listing view.

**Comment by MartinBriza** [comment]
![9w2uwxap51](https://user-images.githubusercontent.com/3977440/50887547-bf5c7900-13f3-11e9-8cde-00d1d25983ed.gif)

**Comment by NghiaTranUIT** [comment]
I'm unable to replicate it with empty entry list or existing entries.

I checked out latest master (before Poco library was merge), and my workspace is Ubuntu 18.04.1 LTS

**Comment by IndrekV** [comment]
I'm also unable to replicate it in fresh clone so seems all good. Thank you, everybody, for testing and wasting your time on this.
