### ISSUE TITLE
Unable to run Toggle Desktop Mac at the first time

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl/toggldesktop#2738]
### 💻 Environment
Platform: macOS
OS Version: macOS 10.14 
Toggl Version: master

### 🐞 Actual behavior
- Unable to run app
- TogglDesktopLibrary script was failed
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: './src/ui/osx/TogglDesktop/build/Release/TogglDesktop.app/Contents/MacOS/TogglDesktop': No such file or directory
```
- TogglDesktop Crashlytic's script was failed
```
can't open file: /Users/martinbriza/toggldesktop/src/ui/osx/TogglDesktop/build/Release/TogglDesktop.app/Contents/MacOS/TogglDesktop (No such file or directory)
```
- Crash on launch
```
dyld: Library not loaded: /usr/local/lib/libPocoData.50.dylib
  Referenced from: /Users/nghiatran/Library/Developer/Xcode/DerivedData/TogglDesktop-crbgfktryatxznfuieitjreuwxyo/Build/Products/Debug/TogglDesktopLibrary.dylib
  Reason: image not found
```

### 💯 Expected behavior
- Able to run `make deps`, `make` without any problems in fresh machine.

### 🔨 Steps to reproduce

1. Remove all Cache in `/Users/nghiatran/Library/Developer/Xcode/DerivedData`
2. Remove all libPoco in `/usr/local/lib/`. Ex: /usr/local/lib/libPocoData.50.dylib
2. Clone this repo
3. Run `make deps`, `make`
4. 💥

**Comment by IndrekV** [comment]
Crash on launch with Poco libraries not loaded is fixed with dc7ce8ae2e531bda2dc7fff455b201e19e9f6439
