### ISSUE TITLE
Hover in tray icon could show more information

### ISSUE THREAD

**Issue by t3mujin** [toggl/toggldesktop#2739]
### 💻 Environment

Platform: Windows

### 📒 Description
![toggl](https://user-images.githubusercontent.com/331767/50682489-e804fd00-1006-11e9-80e2-99f958bab3cb.png)

The hover of the tray icon in Windows could also show more information, besides the elapsed time. It could show the task/client/project

### ⭐️ Why do you want this?
I often have to quickly check what project timer is running, when I need that I have to open the application (I find the mini timer too intrusive and never got used to work with it).

**Comment by IndrekV** [comment]
Currently the tray tooltip shows `description- running time | Total time for today`

We'll add project name to the tooltip.

Tip how to add is in this commit e592c0ccdd55a38e28427e34e8d9e8c6b4c74df9
