### ISSUE TITLE
Timeline setting gets disabled when opening preferences view the second time

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2749]
### 💻 Environment

Platform: Linux
Toggl Version: Master

### 🐞 Actual behavior
When opening preferences the second time after enabling timeline recording the timeline setting is disabled

### 💯 Expected behavior
Timeline setting is not disabled if user has enabled it.

### 🔨 Steps to reproduce
As shown in gif

1. Open preferences
2. Enable `Record timeline`
3. Close preferences
4. Start timer
5. Stop timer
6. Open preferences
7. Timeline setting is now disabled.

### 📦 Additional info
![linux_timeline reset](https://user-images.githubusercontent.com/842229/50894618-559c9900-140c-11e9-82f1-b4f6b258cf14.gif)

**Comment by MartinBriza** [comment]
This issue doesn't happen on my machine. I tried in in Ubuntu and Fedora without a change to the behavior.

**Comment by MartinBriza** [comment]
Considering some of the field names have changed, I assume this is happening to you because your build tree is not clean (probably leftowers from QMake again).

**Comment by IndrekV** [comment]
Unable to reproduce anymore.
