### ISSUE TITLE
Invalid or corrupted package

### ISSUE THREAD

**Issue by 4ice** [toggl/toggldesktop#2764]
### 💻 Environment

Platform: Linux 
OS Version: 4.20.3-arch1-1-ARCH 
Toggl Version: 7.4.122 (Latest stable tarball as of now)

### 🐞 Actual behavior

1. I download the tarball from here: https://www.toggl.com/api/v8/installer?app=td&platform=linux&channel=stable
2. I run `sudo pacman -U toggldesktop_linux_x86_64-7_4_122.tar.gz`
3. I get the error message:
```
error: missing package metadata in toggldesktop_linux_x86_64-7_4_122.tar.gz
error: 'toggldesktop_linux_x86_64-7_4_122.tar.gz': invalid or corrupted package
```

### 💯 Expected behavior

The package should install.

### 🔨 Steps to reproduce

1. Download the tarball.
2. Install it with pacman

### 📦 Additional info

![image](https://user-images.githubusercontent.com/6935261/51547211-18052a80-1e66-11e9-819c-1f0ff4f4d613.png)

**Comment by MartinBriza** [comment]
The file you have downloaded is not an Arch Linux package. In fact, we don't provide an Arch Linux package. To be able to use the Toggl Desktop application in your distribution, you need to decompress this file, enter the folder and run the `TogglDesktop.sh` executable. You can do this using these (or very similar) commands:
```
cd ~/Downloads
tar xvf toggldesktop_linux_x86_64-7_4_122.tar.gz
cd toggldesktop
./TogglDesktop.sh
```
