### ISSUE TITLE
Execute Toggl APIs on main thread

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl/toggldesktop#2765]
Technically ,TogglDesktop is usually **frozen** during bad connection.

After investigation, it reveals that there are few APIs which are executed on Main Thread.

### 💻 Environment
Platform:  All platform macOS/Windows/Linux 
Toggl Version: Latest commit on Master

### 🐞 Actual behavior
- There are certain APIs, which are executed on Main Thread.
- Cause frozen app during bad network connection.

### 💯 Expected behavior
- Should be executed in background thread.
- Main thread should set free.

### 🔨 Steps to reproduce

1. Download [Network Conditioner](https://developer.apple.com/download/more/?q=Additional%20Tools)
2. Set **3G** profile
3. Open app and do actions, which execute the following APIs

- Login
- List Country in Sign up menu
- Sign up
- Report (/api/v8/desktop_login_tokens)

4. App is frozen in short time during requesting data from server.

### 📦 Additional info
For instance, Login API is running on Main Thread.
<img width="883" alt="screen shot 2019-01-23 at 11 47 33" src="https://user-images.githubusercontent.com/5878421/51588223-0713f200-1f16-11e9-978c-af18652fd026.png">

**Comment by MartinBriza** [comment]
Executing stuff on the main thread is not a problem per se. It's also possible to do async networking in the same thread without blocking. I haven't looked into the code yet but it feels to me like using threads could add a lot of complexity to our code and a possibility of creating race conditions between them.
It would be worth investigating if we can achieve the same functionality with using non-blocking networking functions (using the `poll` function, most likely) instead.

**Comment by NghiaTranUIT** [comment]
Sure, I would like to open discussion to compare which reasonable solution for this issue 👍 

In the mean time, I will do a research about `poll` function

**Comment by MartinBriza** [comment]
Hm, here's some info on this topic:
https://stackoverflow.com/questions/26410594/poco-c-websockets-how-to-use-in-non-blocking-manner
(here it's called `select` instead of `poll`)
However it seems we'll be stuck with threads anyway

**Comment by NghiaTranUIT** [comment]
I'm not sure why `Socket::select` could be related to this issue 🤔 , since we execute the RESTful APIs by using `Poco::Net::HTTPSClientSession`

https://github.com/toggl/toggldesktop/blob/bd10d54e113e784a74d1f83a1b03e7d20703ff13/src/https_client.cc#L343-L344

**Comment by MartinBriza** [comment]
This depends on how it's implemented in POCO and I don't know the things are in there.

I have just assumed it _could_ be possible because HTTP requests are done through a network socket. Sockets can be `poll`ed/`select`ed, hence why assumed it could be possible. However, the implementation of HTTP Client in POCO could prohibit this (or just make it much harder than using threads)

**Comment by IndrekV** [comment]
onTimelineUpdateServerSettings

**Comment by IndrekV** [comment]
Also we should address these methods that currently use task to delay the action but still execute on the main thread 
```
TimelineUpdateServerSettings()
SetWake()
fetchUpdates()
```
With these the solution is simple. Similar to `trigger_sync_` param we create a flag that when is true will execute the method. It's simple as these methods do not return anything.

With this list it's a bit more difficult:
- Login
- List Country in Sign up menu
- Sign up
- Report (/api/v8/desktop_login_tokens)

We need to change te logic. The method does not return anything and triggers the action once the request is made. Be it showing an error about login or triggering the browser opening with Reports.

**Comment by NghiaTranUIT** [comment]
Regarding the following funcs
```
TimelineUpdateServerSettings()
SetWake()
fetchUpdates()
```
From my experiment, those func are already executed in background and it doesn't block the Main Thread.

### Additions
#### TimelineUpdateServerSettings()
<img width="794" alt="screen shot 2019-02-01 at 15 23 42" src="https://user-images.githubusercontent.com/5878421/52113111-02002280-263b-11e9-90e7-068bb5722e32.png">
#### fetchUpdates()
<img width="994" alt="screen shot 2019-02-01 at 15 34 28" src="https://user-images.githubusercontent.com/5878421/52113112-02002280-263b-11e9-81eb-1f864e4ed91d.png">
#### SetWake()
<img width="959" alt="screen shot 2019-02-01 at 15 32 27" src="https://user-images.githubusercontent.com/5878421/52113113-02002280-263b-11e9-8d96-84242b540721.png">
