### ISSUE TITLE
"Notifications are not available" even though notifications are working

### ISSUE THREAD

**Issue by danielcarr** [toggl/toggldesktop#2818]
### 💻 Environment

Platform: Linux
OS Version: openSUSE Leap 15.0, Mate DE
Toggl Version: 7.4.354

### 🐞 Actual behavior
The reminder tab of the preferences window doesn't allow me to change my reminder settings and shows a warning that notifications are unavailable, even though notifications are actually working. (Notifications are displayed, for other applications as well as the Toggl app. I haven't tested, but it does seem like the timing might be a bit off, so it *might* be that the notification close signal isn't working).

### 💯 Expected behavior
Since notifications are working, I should be able to change the settings of how often they are displayed, even if other behaviour is unavailable (for which there might still be a warning).

### 🔨 Steps to reproduce

1. Open Preferences -> Reminders and see that notifications are not available
2. Wait a few minutes and see a reminder notification pop up

### 📦 Additional info
The output when launching from the command line is as follows:
```
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
Log path  "/home/daniel/.local/share/Toggl/Toggl Desktop/toggldesktop.log"
DB path  "/home/daniel/.local/share/Toggl/Toggl Desktop/toggldesktop.db"
QDBusMessage(type=MethodReturn, service=":1.6", signature="h", contents=([Unix FD: valid]) ) ""
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
QObject::connect: No such signal org::freedesktop::Notifications::NotificationClosed(uint,uint)]
QStackedWidget::setCurrentWidget: widget 0xffffff00ffffff not contained in stack
QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name org.freedesktop.ScreenSaver was not provided by any .service files")
```
Note: `QObject::connect: No such signal org::freedesktop::Notifications::NotificationClosed(uint,uint)` which is presumably related to [this line](https://github.com/toggl/toggldesktop/blob/edad5b1e669b7e314a8c2ebaa22f2017b676f624/src/ui/linux/TogglDesktop/systemtray.cpp#L25).

**Comment by MartinBriza** [comment]
First let me thank you for opening so many very helpful bug reports! I have noticed your name appearing on a quite o bit of them and all were legitimate and well described!
Now to this issue, hmm, I didn't expect some environment would implement notifications but not all signals from the spec. I'll have to resort to introspecting the DBus interface instead, probably. Can you please share the Mate version you're on? I'm specifically asking for the notification daemon version to know how far off would I be on Fedora (if at all).

**Comment by danielcarr** [comment]
Thanks. As a developer myself, I know how important a good bug report is, and the issues are minor enough that I want to make your part easier. I've been thinking of contributing directly, but I haven't yet managed to get my environment set up right (and I'm a complete novice to C++).

The `mate-notification-daemon` version is  1.20.0 (package `1.20.0-lp150.1.1`). It looks like that's the latest official release, but it was quite a while back, and they have tagged [later releases](https://github.com/mate-desktop/mate-notification-daemon/releases).

I don't know much about DBus, but it looks like they added these signals in v1.20.1 in May/June ([here](https://github.com/mate-desktop/mate-notification-daemon/commit/f26d490bfe55fe508b46819c41c8557ab3085bb1) or [here](https://github.com/mate-desktop/mate-notification-daemon/commit/960df18a456f5171a2f5e052278df64d6c663989#diff-0f7cd0fd88567efb065693fbfc082ab9)), so this probably isn't very important.

**Comment by MartinBriza** [comment]
If you need any help with setting up the environment, don't hesitate to ask me here or over my email (m@rtinbriza.cz) or Telegram ( https://t.me/martinbriza ) or... um, something else, i should put this info on my personal website, I'll let you know eventually.

Anyway, as per this issue, thanks for the additional info, I'll take a look at it. It may get fixed for you in the future with the newer version but Mate not implementing these signals could also mean some other deamon doesn't have them too, so I'll fix this to work properly everywhere.

**Comment by flores-o** [comment]
hey I am getting the same error as mentioned by @danielcarr 

Platform: Linux
Toggl Version: 7.5.324
OS Version: Ubuntu 16.04.6 LTS

I downloaded and unpacked the tarball and when I run

```
oana@pg:~/Coding/toggl$ ./TogglDesktop.sh 
oana@pg:~/Coding/toggl$ Log path  "/home/oana/.local/share/Toggl/Toggl Desktop/toggldesktop.log"
DB path  "/home/oana/.local/share/Toggl/Toggl Desktop/toggldesktop.db"
QObject::connect: No such signal org::freedesktop::Notifications::NotificationClosed(uint,uint)
QObject::connect: No such signal org::freedesktop::Notifications::ActionInvoked(uint,QString)
DBus backend doesn't support notifications
displayUpdate update_url= "
```

Practically I am not seeing the idle notification after the 5 minutes are passed, and I guess it's because of this error message. I thought it was fixed, might it not be fixed for Ubuntu?
