### ISSUE TITLE
Timer stops recording after 2-3 times

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl/toggldesktop#2820]
There is a report that the Toggl Desktop 7.4.330 on mac doesn't work well when recording the Time after 2-3 tries.

We have to investigate it 💥 

### 💻 Environment
Platform: macOS
Toggl Version: 7.4.330

### 🐞 Actual behavior
- After 2-3 times, the Timer couldn't start new Time Entry

### 💯 Expected behavior
- It should work as usual

### 📦 Additional info
- conversations/20834692686
- conversations/20884514460

**Comment by IndrekV** [comment]
This issue is fixed with 488fb120d0fd81b9f4f7ac46b10b093966c87ab6
It's not yet released. Latest beta does not have this fix. We need to do a new beta release soon.
