### ISSUE TITLE
Windows: Cursor Jumps During Actions

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggldesktop#2833]
### 💻 Environment

Platform: Windows
OS Version: Windows 10
Toggl Version: .345

### 🐞 Actual behavior
The cursor strangely "jumps" when syncing an entry while entering a new entry.

### 💯 Expected behavior
No strange cursor actions. 

### 📦 Additional info
[case link ](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/20900781215) 

Case link includes screenshot video

**Comment by zdericnina** [comment]
> when I try to adjust existing time entries something goes wrong : when I select an entry field for adjustment (for example ‘starting time’) the cursor randomly and automatically keeps on jumping to the ‘new time entry’ field

[same issue but with the latest mac beta version](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/search/conversations/21016810483?q=cursor%20jumps)

**Comment by zdericnina** [comment]
[another case for mac](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/21096110893)

**Comment by ricotheque** [comment]
[Another macOS case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/21101321770). User is on 7.4.365 beta

1) Change mode from timer to manual entry using ⌘D
2) Click Add time entry
3) Click in Description field (or any field, really) and focus is briefly in the field and then is removed from the field. Using tab to move between fields is ineffective. This only seems to affect manual entry, not timer mode.

**Comment by ricotheque** [comment]
[Another macOS case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/21098488488), also on 7.4.365 beta

**Comment by ricotheque** [comment]
[Another macOS case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/21102726328), same version

**Comment by ricotheque** [comment]
[Another case, macOS 7.4.365](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/21114591474)

**Comment by ricotheque** [comment]
[Another macOS case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/21107355512), same version

**Comment by zdericnina** [comment]
[another macOS case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/21153882727)

[one more](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/21155199523)

**Comment by zdericnina** [comment]
[macOS](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/21159088209)
[macOS](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/21161345877)

**Comment by ricotheque** [comment]
[macOS 7.4.365](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/21162255957)

**Comment by IndrekV** [comment]
Fixed in version 7.4.371 and newer.
