### ISSUE TITLE
Some colors lose contrast on macOS Dark Mode

### ISSUE THREAD

**Issue by ricotheque** [toggl/toggldesktop#2834]
### 💻 Environment

Platform: macOS

### 📒 Description
When Dark Mode is enabled on macOS, some of the text become harder to read due to contrast issues. Some examples:

![image](https://user-images.githubusercontent.com/5687885/53621392-56de8b00-3c31-11e9-953b-975855bd0bc1.png)

![image](https://user-images.githubusercontent.com/5687885/53621399-5c3bd580-3c31-11e9-9313-baeb781c839b.png)

### ⭐️ Why do you want this?
This will make our app more usable for macOS users.

Raised by this [case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/21014792247)

**Comment by ricotheque** [comment]
Another [case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/21005997237)

**Comment by tobias-isakeit** [comment]
There is no explicit dark mode in the settings, it just looks like this on my Mac (El Capitan):
![toggl-dark-bad](https://user-images.githubusercontent.com/15213758/53720561-53c9e180-3e61-11e9-82ec-010ac4d54008.png)

**Comment by epagnini** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2146384/conversations/21012091691)

**Comment by ricotheque** [comment]
Hey @tobias-isakeit! It looks like you have a different issue. I've created [#2840](https://github.com/toggl/toggldesktop/issues/2840) for that.
