### ISSUE TITLE
Can't start the Time Entry in some scenarios

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl/toggldesktop#2838]
Mari reported that she can't start the Time Entry by pressing the Start button in Timer Bar.

We have to investigate it carefully.

### 💻 Environment
Platform: macOS
OS Version: macOS 10.14 
Toggl Version: Stable 7.4.330

### 🐞 Actual behavior
- Sometime, we can't start the Time Entry, even we already fill the Description in TimerBar
- Restart the app will resolve this problem

### 💯 Expected behavior
- Should work as expected 💯

**Comment by IndrekV** [comment]
It is fixed in latest beta with 488fb120d0fd81b9f4f7ac46b10b093966c87ab6
