### ISSUE TITLE
Desktop app showing Dark Mode colors even if it hasn't been enabled in macOS 

### ISSUE THREAD

**Issue by ricotheque** [toggl/toggldesktop#2840]
### 💻 Environment

Platform: macOS
OS Version: Various (in progress)
Toggl Version: 7.4.365

### 🐞 Actual behavior
macOS users find their desktop app showing dark colors — even if Dark Mode (or its menu-bar only counterpart on earlier macOS versions) haven't been enabled.

### 💯 Expected behavior
The desktop app should only show Dark Mode colors if running on a macOS version that has its respective Dark Mode activated.

### 📦 Additional info
[Screenshot from one user](https://github.com/toggl/toggldesktop/issues/2834#issuecomment-469165130) 

[Another case with screenshot](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/21012091691)

A potential workaround: turn off Dark Mode / "User dark menu bar and Dock" (older versions of macOS)

![image](https://user-images.githubusercontent.com/5687885/53847853-34f85600-3fed-11e9-9fb3-2efe0e6ebbbc.png)

**Comment by NghiaTranUIT** [comment]
Confirmed that this issue is still happened on macOS 10.11 with dark menu and Dock mode 💥 
I will investigate and double check in all available OSs 💻
