### ISSUE TITLE
Manual mode date issue if selected date is prior to Jan 1st, 2019

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggldesktop#2841]
### 💻 Environment

Platform: Windows
OS Version: Windows 10
Toggl Version: 7.4.345 

### 🐞 Actual behavior

A user reported that if they select Dec 31st, 2018 as the date for the time entry in manual mode and then click away to add a tag, as soon as they select the tag the date resets to Jan 1st, 2019, if they initially select any date that's for the current year this does not happen. 

Here's a recording they sent over (no sensitive data): **[video link 🔗](https://drive.google.com/open?id=1HbSnPXq3XZ_ls-bGYH0ofELPBd-7dMqr)** 

### 💯 Expected behavior
The date should not change, the app should allow the user to select any date from the past. 

### 🔨 Steps to reproduce
I was not able to reproduce this issue I'm afraid. We tried with clearing the app's local data manually by deleting all the files and installing the latest stable version again it didn't help the user. 

### 📦 Additional info
**[Case link 🔗](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/20931118973)**

**Comment by VeljkoTN** [comment]
Just following up on this one :)

**Comment by skel35** [comment]
Probably related to the user's custom date format settings. Usually, the year is also shown in the date field (e.g. `11-Jun-19`), but in this user's case the year is not even a part of the date field string.
