### ISSUE TITLE
Date issue when editing existing time entries 

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggldesktop#2842]
### 💻 Environment

Platform: Windows
OS Version: Windows 10
Toggl Version: 7.4.345

### 🐞 Actual behavior
A user reported that when they click on an existing TE to change the date the change doesn't save. They change the date, close the edit window and click on the entry again to see the same date again. 

They included two recordings of this happening, the recordings were made on their home computer for the purpose of testing and recording this on their home network, it was a fresh install of the latest stable version. You can find the recordings in the **[case 🔗](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/21016833707)** 

### 💯 Expected behavior
The date should change when they close the time entry editing window and the TE should be allocated to a different section on the timer window, under a different date. 

### 🔨 Steps to reproduce
I was not able to reproduce this on our end. 

### 📦 Additional info
Video of the issue in the case linked above

**Comment by VeljkoTN** [comment]
Just wanted to follow up on this one and see if you need anything else to investigate the issue

**Comment by skel35** [comment]
Fixed in #2969.
Fix is already in the latest stable release.
