### ISSUE TITLE
Add keyboard shortcuts for moving in listing

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2865]
### 💻 Environment
Platform: Linux

### 📒 Description
Continuation of PR: #2823 

Shortcuts needed:
- jump to listing (We're using shift down in mac so it could also work for linux)
- Moving in list with UP/DOWN keys. The selected item is highlighted and the same keys that open up running item in edit view will now open the item selected in the listing.

**Comment by MartinBriza** [comment]
This is probably already fixed
