### ISSUE TITLE
[Linux] Autocomplete adding Project and Client into description

### ISSUE THREAD

**Issue by ricotheque** [toggl/toggldesktop#2867]
### 💻 Environment

Platform: Linux
OS Version: 
Toggl Version: 7.4.122

### 🐞 Actual behavior
When the user selects an item from the autocomplete list, it creates a new Time Entry, but with the Project and Client as part of the Description.

### 💯 Expected behavior
Selecting from the autocomplete list should populate the Time Entry with the Description, Project, and Client added to the correct fields.

### 🔨 Steps to reproduce and 📦 Additional info
Log at [case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/21176026924)

**Comment by DaveSophoServices** [comment]
Debian Linux, debian_version 9.7

**Comment by IndrekV** [comment]
Try the latest beta release. It has a totally new autocomplete that doesn't have this issue.
https://github.com/toggl/toggldesktop/releases/download/v7.4.358/toggldesktop_linux_x86_64-7_4_358.tar.gz

**Comment by DaveSophoServices** [comment]
Thank you. It works great!
