### ISSUE TITLE
Improve flathub presence

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2868]
### 💻 Environment
Platform: Linux

### 📒 Description
It seems that some fields are empty right now (version, developer etc)

- Screenshots are missing
- Info during installation is missing
- Download seems very large (over 1Gb)

**Comment by MartinBriza** [comment]
* Screenshots should be present in the next release.
* I'll look into why there's some info missing
* The app itself is actually 7.2MB. The rest is the runtime, some plugins and locale (?? dunno, why it gets pulled in, too). However, the runtime itself is 488MB which is quite a lot. I'm not sure if we can affect this.

**Comment by MartinBriza** [comment]
The runtime gets shared with the other apps, at least, so a lot of people likely already have it.
