### ISSUE TITLE
Timeline UI - changing days

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2890]
### 💻 Environment
Platform: macOS

### 📒 Description
Add LEFT and RIGHT keyboard keys to switch the visible day data in the timeline view

**Comment by skel35** [comment]
> We can skip LEFT/RIGHT keys support as it made sense in prototype design but not this one where timer is always visible.

https://github.com/toggl/toggldesktop/issues/3016#issuecomment-508739895
