### ISSUE TITLE
Timeline UI - Vertical detailed view

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2892]
### 💻 Environment
Platform: macOS

### 📒 Description
Displays scrollable vertical timeline list that shows all the details about tracked info in 15-minute chunks.

Main functionalities:
- Show gaps and overlaps.
- Allow creating time entries to the empty spaces in the day
- Allow solving overlaps. Clicking on overlap shows a context menu with 3 choices:
    - change first entry stop time
    - change last entry start time
    - create a new entry of overlap
(The texts should be improved, they should be shorter)

**Comment by NghiaTranUIT** [comment]
From what I understand, the Timeline will automatically add the `Empty space` in the gaps, so the user is able to create new time entry. However, in the design, there is only one `Empty Space`.

Do it means:
1. Is there only one Empty Space?
2. How about others? (Red Rectangle in screenshot)

![Screen_Shot_2019-06-27_at_17_25_32](https://user-images.githubusercontent.com/5878421/60259133-bb200b80-9900-11e9-8b8f-c067bacfb31f.jpg)

**Comment by IndrekV** [comment]
The empty entry should be added only when there are no entries at all. This screenshot does not show the most common picture of a users day. Usually, there are no overlapping entries and the empty entry is placed in places where no entry has been tracked so that it is easy to fill that empty space.

From this logic, the empty space on this screenshot should be only the top one and it should end before the purple item on the second column starts.

**Comment by NghiaTranUIT** [comment]
Close by https://github.com/toggl/toggldesktop/pull/3050
