### ISSUE TITLE
Timeline UI for Mac

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2893]
### 💻 Environment
Platform: macOS and Lib

### 📒 Description
Adds a Timeline UI view to mac app. We'll be using the old timeline prototype as a base. The main functionalities are;

- Data handling in library #2889
- Timeline view header with arrows to change the days #2890
- Timeline horizontal global view with vertical bars #2891
- Timeline vertical details view with all the detailed timeline data and time entries #2892

**Comment by IndrekV** [comment]
@NghiaTranUIT This is the main issue for Timeline UI. The only important part is the data handling #2889 all other things cannot be used as they were based on the prototype design.

**Comment by NghiaTranUIT** [comment]
The acceptance criteria are fulfilled 👍 Need new ticket if we have any UI changes
