### ISSUE TITLE
Start and end time of entries is +1hr

### ISSUE THREAD

**Issue by ta-stott-oe** [toggl/toggldesktop#2902]
### 💻 Environment
Platform: Windows
OS Version: Windows 10 Pro (v10.0.17763)
Toggl Version: 7.4.345

### 🐞 Actual behavior
I start a new time entry in the desktop app. The entry start time is one hour ahead of the current time in the United Kingdom. My Toggl settings online have the correct timezone (Europe/London). The time entry has the correct start time when viewed online.

### 💯 Expected behavior
I start a new time entry. The entry start time is the current time in the United Kingdom.

### 🔨 Steps to reproduce
1. Set Toggl timezone to *Europe / London* (I assume this or some other condition is necessary for the bug, otherwise it would affect everyone and you'd have fixed it by now!)
2. Start a new time entry in the desktop app
3. Observe that the start time of the new entry is one hour ahead of the current time in London.

### 📦 Additional info
![image](https://user-images.githubusercontent.com/4686546/55170882-40afe600-516f-11e9-9d28-5e9e95092070.png)

**Comment by IndrekV** [comment]
Fixed with #2969
