### ISSUE TITLE
Labels are unreadable on Linux

### ISSUE THREAD

**Issue by tobias-kuendig** [toggl/toggldesktop#2909]
![image](https://user-images.githubusercontent.com/8600029/55606956-149df180-577b-11e9-95f3-6c45e3256f1e.png)

Date labels are hard to read, time entry descriptions are invisible (maybe white?)

The readable text was of course pixelated by me. I just downgraded to v7.4.379, there the labels are displayed fine.

I'm on KDE using a dark theme.

```
Distributor ID: neon
Description:    KDE neon User Edition 5.15
Release:        18.04
Codename:       bionic
```

**Comment by MartinBriza** [comment]
On a second thought, I'm closing this as it's the same issue as #2882
