### ISSUE TITLE
Entry stops running when locking computer

### ISSUE THREAD

**Issue by EagleWizard28** [toggl/toggldesktop#2914]
### 💻 Environment

Platform: Windows
OS Version: Windows 10 version 1803
Toggl Version: 7.4.345

### 🐞 Actual behavior
"Idle detection" is on and "Stop running entry on computer sleep/shutdown" as well. 
An entry is running and I lock my computer. When I log back on I see that the time entry has stopped running.

Also no "Idle" message is being displayed.

### 💯 Expected behavior
The preference states that the entry should only stop on "sleep" or "shutdown". 
I expect the time entry to continue running (it is not because my computer is locked that I stop working on the running item). When logging back on to my computer, it should ask me if I would like to add the "Idle" time to my current running entry.

### 🔨 Steps to reproduce
1.  Start a time entry
2. Lock your computer
3. Login again
4. The time entry has stopped working

**Comment by NghiaTranUIT** [comment]
Ideally, the app shouldn't stop when the computer is locked. From what you're mentioning, it could be a bug somewhere in the Desktop Library about the idle detection.

We will investigate it 👍 Thank for the report
