### ISSUE TITLE
Linux Mint desktop reminder won't stop after uninstall 

### ISSUE THREAD

**Issue by alintz1** [toggl/toggldesktop#2915]
Using: Linux Mint 19 Tara Bionic

Installed Toggl desktop 2-4 months ago. Decided to uninstall today and have been getting a reminder to track time every 10 or so minutes since. Have tried to search through file system and delete anything Toggl related, Synaptic package manager uninstall... Nothing seems to work.

The reminder is very clearly from the desktop version not the Chrome extension which is still installed (says 'Reminder from Toggl desktop'). 

![image](https://user-images.githubusercontent.com/25709577/56040888-be5f1e80-5d37-11e9-9690-bcb6f9fe6b7f.png)

**Comment by IndrekV** [comment]
It seems that the app is running in the background. Shutting down the app or a plain restart should fix this.

**Comment by MartinBriza** [comment]
Yes, if it is uninstalled, it's probably still running in the background. The message will go away after a reboot (or finding the process `TogglDesktop` in the process manager and killing it).
