### ISSUE TITLE
Reminder tab disabled on elementary OS 5.0

### ISSUE THREAD

**Issue by haggen** [toggl/toggldesktop#2916]
### 💻 Environment

Platform: Linux
OS Version: elementary OS 5.0 juno
Toggl Version: About says 7.0.0 but I downloaded a Linux build tagged 7.4.409.

### 🐞 Actual behavior

In Preferences, when I click at the Reminder tab I get the message below overlayed on top of the controls, rendering all the everything unclickable.

> Notifications are not available on your system. You do not have a notification daemon running.

### 💯 Expected behavior

I expected the tab to be fully operational. I wanted to enable the "Remind to track time" feature since I keep forgetting to track time. 😬️

### 🔨 Steps to reproduce

1. Install build 7.4.409 of Toggl for Linux (deb package) on elementary OS.
2. Open Toggle.
3. Click Toggl Desktop > Preferences > Reminder.

### 📦 Additional info

![Screenshot from 2019-04-13 18 46 45](https://user-images.githubusercontent.com/270076/56085619-a8775980-5e1c-11e9-93c7-3c8b678f0750.png)

**Comment by MartinBriza** [comment]
Sorry for the issues, these new deb packages are quite experimental, still.
Hm, I'll have to test the .deb on Elementary then. Even the fact you don't get the right version string in the About section is wrong.
