### ISSUE TITLE
Add notarizing to mac app release process

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2919]
### 💻 Environment
Platform: macOS

### 📒 Description
We should add notarizing to our release process
https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

**Comment by NghiaTranUIT** [comment]
We could update our script by following this Apple instruction here:
https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution/customizing_the_notarization_workflow?language=objc 

## My proposals for the script:
1. Generate app-specific for `altool`
2. Store username/password in keychain 
3. After the build is archived, update the script to upload the zip to Apple Service by using `altool` -> Store the UUID
4. Check the status of this UUID after 10 mins
5. Staple the Ticket to TogglDesktop if the 4th steps is OK
6. Bundle to DMG file as usual

**Comment by NghiaTranUIT** [comment]
- Script: https://gist.github.com/shpakovski/31067c499d69d1d4180856be3d67e5a5
- Fastlane plugin: https://github.com/zeplin/fastlane-plugin-notarize
