### ISSUE TITLE
[Mac] new icon is inconsistent with rest of macOS circular icons

### ISSUE THREAD

**Issue by gee-forr** [toggl/toggldesktop#2921]
### 💻 Environment
Platform: macOS 7.4.373 Stable release channel

### 📒 Description
Thank you for the new version. The dark mode is great! The new icon is slightly bigger than all the other circular icons you find on macOS. It's not a huge deal, it's just a visual inconsistency of Toggl with the rest of the OS. Please see below the screenshot to see what I'm talking about:

![Screenshot 2019-04-18 at 16 50 44](https://user-images.githubusercontent.com/345730/56370390-66bf2800-61fb-11e9-88a9-0e13fd7c50ab.png)

Please could you shrink the macOS icon down a tiny bit so that it fits in with the rest of the similarly shaped icons?

**Comment by NghiaTranUIT** [comment]
## Problem
The size of the outer circle on Toggl Desktop icon is **off**. I carefully double check the size of some well-known apps. 

Here is the report on 512@2x icon, which means 1024x1024px

### Spark is 52px
<img width="909" alt="1" src="https://user-images.githubusercontent.com/5878421/57913823-9a9f7300-78b7-11e9-8314-a97fd1f73e79.png">

- Proxyman is 52px
<img width="940" alt="3" src="https://user-images.githubusercontent.com/5878421/57913916-c7ec2100-78b7-11e9-8f6a-2ac8822dc98d.png">

### Spotify is 62px
<img width="556" alt="4" src="https://user-images.githubusercontent.com/5878421/57914323-9a53a780-78b8-11e9-8a03-75361bb137d2.png">

### iTune is 62px
<img width="933" alt="5" src="https://user-images.githubusercontent.com/5878421/57914335-a0498880-78b8-11e9-9898-4ba651e2e074.png">

### Toggl is 32px
<img width="941" alt="2" src="https://user-images.githubusercontent.com/5878421/57914360-ab9cb400-78b8-11e9-8b5e-2ec7d719b441.png">

## Solution
I suggest that our designer should take it into account and adopt 52px or 62px rule.

**Comment by NghiaTranUIT** [comment]
### Zeplin
We're using 16px (@1x) as a padding, which cause the inconsistent of icon size.

<img width="756" alt="Screen Shot 2019-05-17 at 15 13 21" src="https://user-images.githubusercontent.com/5878421/57914568-0cc48780-78b9-11e9-9150-92fbcd670a6a.png">

**Comment by AlicjaSuska** [comment]
I've just changed icons in Zeplin. It should work with 62px standard now.
