### ISSUE TITLE
Pressing Enter while adding title to running timer does not commit it

### ISSUE THREAD

**Issue by Leland** [toggl/toggldesktop#2922]
### 💻 Environment

Platform: macOS
OS Version: 10.14.4 (18E226)
Toggl Version: 7.4.373

### 🐞 Actual behavior
1. Click running timer
2. In edit window, add title
3. While title input is still focused, press <kbd>Enter</kbd>.
4. Edit window closes, title is not changed

### 💯 Expected behavior
Edit window closes, title is committed

### 📦 Additional info
![Screen Recording 2019-04-18 at 11 44 AM](https://user-images.githubusercontent.com/714017/56373653-6a3cba00-61cf-11e9-9cec-0bd22fa7f270.gif)

**Comment by zdericnina** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/22105689449)
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/22105659785)
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/22104992339)

**Comment by IndrekV** [comment]
Fixed with latest beta (7.4.430)
