### ISSUE TITLE
Moving selection off of timer list, deleting, causes crash

### ISSUE THREAD

**Issue by Leland** [toggl/toggldesktop#2924]
### 💻 Environment

Platform: macOS
OS Version: 10.14.4 (18E226)
Toggl Version: 7.4.373

### 🐞 Actual behavior
1. Delete any remaining items in Toggl window via selection (up/down arrows to move around list, <kbd>Del</kbd> to actually delete)
2. Once all removed, press <kbd>Del</kbd> again
3. Alert with title `Delete time entry "(null)"?` appears
4. Click OK
5. Crash

Or

1. Press down arrow to move selection off of list
2. Press <kbd>Del</kbd>
3. Alert with title `Delete time entry "(null)"?` appears
4. Click OK
5. Crash

### 📦 Additional info

![Screen Recording 2019-04-18 at 12 22 PM](https://user-images.githubusercontent.com/714017/56375923-b0e0e300-61d4-11e9-91a7-1c0bb054257a.gif)

**Comment by IndrekV** [comment]
Fixed with latest beta (7.4.430)
