### ISSUE TITLE
macOS dark mode lacks highlighted color on nested, duplicate timer entries

### ISSUE THREAD

**Issue by Leland** [toggl/toggldesktop#2925]
### 💻 Environment

Platform: macOS
OS Version: 10.14.4 (18E226)
Toggl Version: 7.4.373

### 🐞 Actual behavior
macOS dark mode lacks any highlighting as a user navigates up and down timers with arrow keys.

### 💯 Expected behavior
Similar behavior to macOS light mode:

![Screen Recording 2019-04-18 at 12 02 PM](https://user-images.githubusercontent.com/714017/56374787-fa7bfe80-61d1-11e9-820c-f5bcd1b81ec6.gif)

**Comment by IndrekV** [comment]
Have you tried the latest beta with the new design?

**Comment by IndrekV** [comment]
This is fixed in latest Beta
