### ISSUE TITLE
Windows App Crashing During Project Selection

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggldesktop#2931]
### 💻 Environment

Platform: Windows
OS Version: 10 Pro x64
Toggl Version: 7.4.345

### 🐞 Actual behavior

A user is reporting that the Windows app is crashing when attempting to select a project. He's attempted a clean install after clearing the app cache, all to no avail.

### 💯 Expected behavior
When creating or editing a time entry in the desktop app, project selection should work without issue. 

### 📦 Additional info
Intercom [case link](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/21735133323)

**Comment by skel35** [comment]
Not enough info to reproduce it, no similar crashes in Bugsnag either.
Closing it, but you can reopen if logs or steps to reproduce are provided.
