### ISSUE TITLE
Mac app shifts focus to edit the previous time entry instead of the selected one

### ISSUE THREAD

**Issue by zdericnina** [toggl/toggldesktop#2933]
### 💻 Environment

Platform:  macOS
OS Version:  10.14.3
Toggl Version:  7.4.373

### 🐞 Actual behavior

Clicking on the newly saved entry to edit it, the popup opens the edit window for the previous entry instead

### 💯 Expected behavior

The entry user wants to edit should be edited and not the previous one which hasn't been selected.

### 🔨 Steps to reproduce

1. Start the timer and then stop it after several seconds
2. Click to edit it, you can already see that the previous TE has been opened
3. Any changes would apply to the previous time entry and not the one user intended to

### 📦 Additional info

Screencast of the issue is in the [case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/21767864701)

**Comment by DmitrySinclair** [comment]
I experienced the same issues. Also focus start to randomly travel from currently edited fields (inside time entry) to "What are you working on". It seems related.

**Comment by murrayrm** [comment]
Same issue.

**Comment by ricotheque** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/21883425728)
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/21892601276)

**Comment by zdericnina** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/21910965632)

**Comment by zdericnina** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/22012064445)

**Comment by lise-toggl** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/22040688378)

**Comment by VeljkoTN** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/22060980907)

**Comment by zdericnina** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/22266933738)

**Comment by nidarasheed** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/22464415627)

**Comment by nidarasheed** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/22460192585)

**Comment by IndrekV** [comment]
Fixed in latest beta (7.4.444)
