### ISSUE TITLE
When Editing, Date Field Reverts To Previous Day 

### ISSUE THREAD

**Issue by Michelle112** [toggl/toggldesktop#2936]
Nghia believes there was previously as issue closed related to this but was unable to find it and asked me to create a new one.

### 💻 Environment

Platform:  Windows

OS Version: 

windows_native_app/7.4.345-obm-87-obm-98-obm-99-obm-101 
Toggl Version:  Version: 7.4.345

### 🐞 Actual behavior

The User writes; 

"Start timer when it is PM, Stop, Edit that entry and set the start time to any time that is before 12:00 like 10:00, Notice that the Date field is automatically set to yesterday and you can&#39;t manipulate it to today again."

### 💯 Expected behavior

Date field reflects current date.

### 📦 Additional info

Case: /conversation/21775004221

**Comment by skel35** [comment]
Related #2561, #2455, #2012

**Comment by skel35** [comment]
STR which work for me:
- Windows 10
- Set time zone to (UTC+12:00) Auckland, Wellington
- Set time to between 12:00 AM and 01:00 AM
- Update the time zone in the Toggl profile
- Start the timer
- While the timer is running, switch the date to 1 day before the current day.

Actual Result:
- The date is switched to 2 days before the current day.
