### ISSUE TITLE
Time Editor Bug. User can't input description.

### ISSUE THREAD

**Issue by Michelle112** [toggl/toggldesktop#2939]
I have a user who can start a time entry and input a description and a project and it logs it fine. However, when they try to enter a project first and a description second, the description doesn't stick. I've been unable to replicate this.

User created video showing this behavior is available in the case. Case : 2931915/conversations/21781532440. User agent: osx_native_app/7.4.373. Version: 7.4.373
UpdateChannel: stable

**Comment by IndrekV** [comment]
This will be fixed with new design that will be in beta next week
