### ISSUE TITLE
Over-flooding error logs in Linux

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl/toggldesktop#2941]
### Description
There is a user's report that Toggl accidentally floods the system with huge number of message log. It logs repeatedly every single 11 microsecond, so it results in out of disk space.

We have to investigate it on Desktop Library, since it potentially affects all platform, not just Linux.

### 💻 Environment
Platform: Library and Lunix in particular

### 🐞 Actual behavior
- Flooding the system with tons of line error message.

### 💯 Expected behavior
- Only write 1 error message log.

### 📦 Additional info
conversations/21895615070

**Comment by MartinBriza** [comment]
This is coming from the QtWebEngine library we're using for Google Login. It doesn't affect any other platform, most likely.

**Comment by IndrekV** [comment]
Can we somehow manage or restrict the error logged from QtWebEngine?

**Comment by MartinBriza** [comment]
Yes, we can try that with `QTWEBENGINE_CHROMIUM_FLAGS="--disable-logging"`. I'll prepare a patch for this.
