### ISSUE TITLE
Input Field Start/End Time Jump to Project Search (Mac)

### ISSUE THREAD

**Issue by chrisspiegl** [toggl/toggldesktop#2944]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.14
Toggl Version: 7.4.407

### 🐞 Actual behavior

Opening an already finished time entry and then trying to edit the start or end time. More specifically deleting, for example, the number representing the minutes and then it jumps out of the field and somewhere random another place (looks like the search for projects).

### 💯 Expected behavior

When editing the start time I want to edit the start time and not some other field. It should not jump away and just stay where it's at.

### 🔨 Steps to reproduce

1. Open Finished Time Entry
2. Click into Start or End Time Field
3. Start typing numbers or removing numbers
4. It shows the project search as if I am starting a new timer and sometimes jumps into that field completely (very disturbing and annoying).

**Comment by JackHowell** [comment]
+1

Platform: macOS
OS Version: macOS 10.14.4
Toggl Version: 7.4.365

I have the same error occurring, following the same steps as OP. 

![toggl-mac-app-tapping-error](https://user-images.githubusercontent.com/2869884/57455986-5b907280-7264-11e9-9283-ddb546683e1b.gif)

Full-length screen recording: https://drive.google.com/file/d/1caAZGCD5xa_V-rWZ39M9X_i2UZETleZS/view?usp=sharing

**Comment by NghiaTranUIT** [comment]
@JackHowell It's known-issue on old `7.4.365` version. We've already fix this https://github.com/toggl/toggldesktop/pull/2854 and released in the latest `7.4.373` Stable Toggl.

You can download it here https://toggl.com/toggl-desktop/

**Comment by JackHowell** [comment]
OPs version is Toggl Version: 7.4.407 ?

**Comment by NghiaTranUIT** [comment]
No, the version 7.4.407 is the DEV version. We don't guarantee that it's stable for production, but you can try.

I just do a quick test on `7.4.373`, and this issue is gone.

In the meantime, I will investigate this issues on 7.4.407.

**Comment by NghiaTranUIT** [comment]
Thank for the report @chrisspiegl, we just investigate this issue, and it's already fixed in https://github.com/toggl/toggldesktop/commit/0fda7e90d1ed4a288a0a48c258950994c6c2be0a from v7.4.410 (https://github.com/toggl/toggldesktop/releases/tag/v7.4.410)

Unfortunately, we haven't released this commit in DEV channel yet. We will do it in next week when our team is settle-down from vacations 👍 

It's also related to https://github.com/toggl/toggldesktop/issues/2943

@IndrekV

**Comment by chrisspiegl** [comment]
@NghiaTranUIT Thanks for investigating and figuring out what's going on. I'll see the next DEV channel release for the fix then. 💪
