### ISSUE TITLE
Couldn't launch Toggl Desktop in Windows

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl/toggldesktop#2945]
From a user's report, Toggl Desktop worked flawlessly before, and now it couldn't launch again even they tried to uninstall, clear cache and re-install.

There are many possible reasons, such as failed .NET framework, corrupted database, ..., which potentially causes the crash on launch.

We should investigate it since it's a serious issue.

### 💻 Environment
Platform: Windows
OS Version: Window 10 Pro 64bit
Toggl Version: Latest

### 🐞 Actual behavior
- Couldn't launch

### 💯 Expected behavior
- Be able to launch as usual 

### 📦 Additional info
conversations/21906546739

**Comment by nidarasheed** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/21906546739)

**Comment by nidarasheed** [comment]
Update from [Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/21906546739)
User cleared local data and the app started working again.

**Comment by jianbinwen** [comment]
Please provide details about how to clean the local data? I'm experiencing the same issue.

**Comment by jianbinwen** [comment]
Tried to clean the local data following https://support.toggl.com/desktop-apps/clearing-the-local-data-from-toggl-desktop but the app still won't launch. Please advise. Thanks.

**Comment by IndrekV** [comment]
@jianbinwen Did you install the app in the default location and did you already try manually deleting the database file.

```
1. Using Windows Explorer navigate to: C:\Users\<username>\AppData\Local\TogglDesktop. 

The easiest way to open up the correct location is to copy %LOCALAPPDATA%/TogglDesktop into the Windows Explorer address bar and press Enter.

2. Remove the file named toggldesktop.db.
```

**Comment by IndrekV** [comment]
We don't have enough details to replicate this.
