### ISSUE TITLE
Add description field + Project behaving oddly

### ISSUE THREAD

**Issue by TEmminghamCHub** [toggl/toggldesktop#2949]
### 💻 Environment
toggl Timer

Platform: 
Windows

### 📒 Description
Until recently we were able to enter discriptions or Projects in any order to record our time. Now in some cases users are prompted with an error message “Add Description
Fill out the required fields to stop the timer and save this time entry” and they cannot stop Timer until they go back into the description field and update it again. The issue appears to be difficult to repro or perhaps impacts just some users. In any case this is not how the app has functioned in the past and it's making a quick entry process more time intensive. Please provide guidance on best practice or fix, if it's a bug.

Terry Emmingham
temmingham@commercehub.com
(206) 971-8930

**Comment by skel35** [comment]
Hi @TEmminghamCHub ,
Can you check whether you have Description set as a required time entry in the Workspace Settings? 
Refer here for more info https://support.toggl.com/team-management/advanced-team-features/required-fields-for-time-entries . If you want to allow stopping the entries without filling in the Description, then it has to be unchecked from Required fields.

Let me know if it helps with your problem.

**Comment by skel35** [comment]
Closing due to no response from the user, as it looks like it's the Required fields feature and not a bug.
Feel free to reopen this if you believe it is indeed a bug.
