### ISSUE TITLE
Cannot select top entry in the app

### ISSUE THREAD

**Issue by Stosiu** [toggl/toggldesktop#2951]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.14.4 (18E226)
Toggl Version: 7.4.373

### 🐞 Actual behavior
I cannot select top entry no matter where I click. Click on the first element opens second entry details.

https://www.loom.com/share/8968994a8a0e4a08ab46d2828ccd93a0

### 💯 Expected behavior
Click on a top entry should show the popup with entry details and feature to edit the data.

### 🔨 Steps to reproduce

1. Add several entries to your Toggle account.
2. Try to select a top listing.

### 📦 Additional info
I tried to resize the window, but it didn't help. I have this issue for quite a long time, but in the feature sooner or later it got working after some window resizing, not it's completely broken, and I cannot edit it.

**Comment by NghiaTranUIT** [comment]
Thank for the report. However, this known-issues was addresses and resolved in https://github.com/toggl/toggldesktop/pull/2950.

We will push the fix from to Stable soon 👍

**Comment by Stosiu** [comment]
Duplicate of #2933
