### ISSUE TITLE
Create 64 bit release

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2954]
### 💻 Environment
Platform: Windows

### 📒 Description
We will add a 64bit release to Windows. Also what we need to do is add a check into the current app that downloads the 64bit update when the user is on a 64bit machine.

List of tasks to be completed:

- [x] Create 64bit configuration and successfully build the app in 64bit #3025
- [x] Add 64bit build command to our build cycle (branding) #3026

This will fix the issue with timeline tracking/autotracker where 32bit Toggl Desktop could not get info of 64bit apps because of the architecture difference restrictions.

Timeline/Autotracker issues connected to the described restriction: (64bit release should fix them all)
Close #2145 
Close #2228
Close #2254 
Close #1861 
Close #2139
Close #2712

**Comment by IndrekV** [comment]
If issue has a PR please add label `has-pr` and move the issue to the `Issues waiting for PR review` milestone. Also move the PR to current milestone or the next one. I moved the PR to the next milestone.

**Comment by skel35** [comment]
PR doesn't fix the entire issue yet, do we still move it to `Issues waiting for PR review` milestone in this case?

**Comment by IndrekV** [comment]
If it's not ready (not ready for review), just add [WIP] to the title so it's clear it in progress.

**Comment by skel35** [comment]
It's ready for review, #2954 is just too big for a single PR, imo.
Is every PR supposed to close some github issue? In that case, I'll just split it into more issues.

**Comment by IndrekV** [comment]
jep the buildbot part is better to be separate.
