### ISSUE TITLE
Update bugsnag version and data

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2958]
### 💻 Environment
Platform: macOS/Windows/Linux

### 📒 Description
We should update our bugsnag versions (At least on windows it's old)

Also we should make sure we send all additional data in correct format so we can search the error logs properly.

We should also update the code so we only send bugnsnag notifications when in production to nowt crowd bugsnag with development exception reports.

**Comment by skel35** [comment]
Also there is a problem that Windows 10 and Windows 8.1 are detected as Windows 8 in Bugsnag. In order for `Environment.OSVersion` to return a correct version, this version has to be enabled in the application manifest https://docs.microsoft.com/en-us/windows/desktop/SysInfo/targeting-your-application-at-windows-8-1.

**Comment by IndrekV** [comment]
Latest NuGet package for windows app.
https://www.nuget.org/packages/Bugsnag/

**Comment by IndrekV** [comment]
Sending user ID in #C is described in Callback section https://github.com/bugsnag/bugsnag-dotnet#callbacks

**Comment by IndrekV** [comment]
Windows and mac are done. We now need to double check the linux implementation. Linux uses custom made solution. What we need to check is if Linux sends the userID correctly.

**Comment by IndrekV** [comment]
This is done now, Linux PR is also already merged.
