### ISSUE TITLE
Counter Keeps Running when Stopping via Keyboard Shortcut

### ISSUE THREAD

**Issue by chrisspiegl** [toggl/toggldesktop#2961]
### 💻 Environment

Platform: macOS
OS Version: 14.4
Toggl Version: 7.4.407

### 🐞 Actual behavior

I start a timer (no matter if with the buttons on the interface or shortcut). When I stop it with the button on the Toggl window it stops per usual, when I stop it via Keyboard Shortcut the Toggl interface keeps the timer (even though it is stopped and listed below in the list as a stopped timer entry).

### 💯 Expected behavior

The timer should stop and the interface should reflect that.

### 🔨 Steps to reproduce

1. Start Timer
2. Stop Timer via Keyboard Shortcut (note: I have mine set to **OPTION + CMD + X**, so don't know if that makes a difference)
3. See timer still counting on Toggl window.

### 📦 Additional info

![ScreenRecording20190516at1](https://user-images.githubusercontent.com/1096384/57850137-7bccae00-77dd-11e9-833f-dbffd0f097af.gif)

**Comment by IndrekV** [comment]
It seems that the global shortcut for start/stop is not working. Also selecting "Stop" from menu bar menu does not properly stop the entry.

**Comment by chrisspiegl** [comment]
That was quick 💪.
