### ISSUE TITLE
Add possibility to create private projects in Windows app

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2967]
### 💻 Environment
Platform: Windows

### 📒 Description
There should be a checkbox named `Public (visible to the whole team)` that allows to choose if the created project is public or private

Same logic is present in mac app

![Screenshot 2019-05-20 at 10 54 03](https://user-images.githubusercontent.com/842229/58005128-a83e3e00-7aed-11e9-90b0-429772211e28.png)

**Comment by skel35** [comment]
Should we save the user's previous selection or have it unchecked by default right after "New project" was clicked?

**Comment by IndrekV** [comment]
It is reset every time the "New project" form is opened. So it's unchecked by default.
