### ISSUE TITLE
Calendar disabled when timer running

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2974]
### 💻 Environment

Platform: Windows

### 📒 Description
On mac we currently have the calendar disabled when the timer is running. We should add this functionality to Windows also as editing date on a running timer can cause issues. For example, when time is set to future the error appears about "Stop time needs to be later than start time"

Also, the fact that tracking time should be a current event not in the far future.

If the user needs to have the start date set to yesterday they can do so with duration.

Things to do:

- When editing running timer -> Calendar input disabled
- When editing stopped timer -> Calendar input enabled.

**Comment by skel35** [comment]
![calendar-disabled](https://user-images.githubusercontent.com/16451391/58236828-6ced7a80-7d4c-11e9-9099-f0c4706e4818.png)

I think we could visually indicate that the calendar is disabled by hiding this calendar button when date picking is disabled. What do you think?

**Comment by IndrekV** [comment]
Sounds good. Also I think the text will be gray when input is disabled.
