### ISSUE TITLE
Handle cases where project is unsynced

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2986]
### 💻 Environment
Platform: All (library)

### 📒 Description
In some cases, the project or any other item could be not synced and also not marked as "needs sync".

I saw this with an un-synced project that did not have an id (it was NULL), the project was visible in the autocomplete but selecting it would clear the project selection.

- First of selecting a non-synced project should still work
- Secondly, the project that is not synced should be marked as to be synced when loaded

**Comment by NghiaTranUIT** [comment]
I wonder that old implementation doesn't store any project_guid after creating, how it handles if the project remains unsync?

I don't see any complain about the unsync project in old code, it means that it always works, isn't it?

Ref: https://github.com/toggl/toggldesktop/blob/b5064ec91eafd104b1d1c7d6baab59da3fe5db42/src/ui/osx/TogglDesktop/TimeEntryEditViewController.m#L396-L421
