### ISSUE TITLE
Restrict the maximum width of client name to 50% of total client+project name label width

### ISSUE THREAD

**Issue by skel35** [toggl/toggldesktop#2993]
### 💻 Environment
Platform: Windows

### 📒 Description
Restrict the maximum width of client name to 50% of total client+project name label width

### ⭐️ Why do you want this?
When the client name is too long, the project name is not visible. For the user it is important to see the project name in order to be able to differentiate between different projects of the same client.

![image](https://user-images.githubusercontent.com/16451391/58783213-0c322d80-85e9-11e9-8820-5a8bbbbe6dd6.png)

**Comment by lise-toggl** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3155115/conversations/22290478770)

**Comment by skel35** [comment]
We've decided instead to change the order of client and project name, so that project name is before client name, the same way as it is in the Mac version. This is done.
