### ISSUE TITLE
Unable to build on Linux

### ISSUE THREAD

**Issue by godfrey-cw** [toggl/toggldesktop#3000]
### 💻 Environment

Linux environment, latest TogglDesktop.

Platform: 
OS Version: 
Toggl Version: 
Ubuntu 19.04

### 🐞 Actual behavior

Failed to build with error code 
```
In file included from /home/charlie/Documents/Xperiments/toggldesktop/third_party/poco/NetSSL_OpenSSL/include/Poco/Net/NetSSL.h:24,
                 from /home/charlie/Documents/Xperiments/toggldesktop/third_party/poco/NetSSL_OpenSSL/include/Poco/Net/HTTPSClientSession.h:21,
                 from /home/charlie/Documents/Xperiments/toggldesktop/src/netconf.cc:13:
/home/charlie/Documents/Xperiments/toggldesktop/third_party/poco/Crypto/include/Poco/Crypto/Crypto.h:30:10: fatal error: openssl/opensslv.h: No such file or directory
 #include <openssl/opensslv.h>

```

### 💯 Expected behavior

Build.

### 🔨 Steps to reproduce

1. Follow the instructions in `README.md`, including build with live servers.

**Comment by MartinBriza** [comment]
Hi,
you'll need to install the OpenSSL development headers. I suppose the package is `libssl-dev` in Ubuntu but I'm not 100% sure.
I'm closing the bug but please feel free to ask follow up questions in this thread.

**Comment by godfrey-cw** [comment]
Ah okay -- so I didn't really read the readme I guess. Many thanks!
