### ISSUE TITLE
[Linux] KDE Breeze Dark Coloring Problem

### ISSUE THREAD

**Issue by mjdr** [toggl/toggldesktop#3001]
### 💻 Environment
Platform: Linux (ArchLinux)
Desktop Environment: KDE Plasma
Theme: Breeze dark

### 📒 Description
App has light background and basically unusable.

![image](https://user-images.githubusercontent.com/10014514/58951068-e51a5e00-8798-11e9-9d14-04fc716b3d5d.png)

And Preferences Tab
![image](https://user-images.githubusercontent.com/10014514/58951284-5fe37900-8799-11e9-9612-0ed988b934f9.png)

Here is Preferences Tab for default file manager

![image](https://user-images.githubusercontent.com/10014514/58951385-a8029b80-8799-11e9-9e1e-22757b12c1f1.png)

**Comment by IndrekV** [comment]
This was already fixed with #2917
It will be available with next release.

Thank you for reporting.
