### ISSUE TITLE
Issues with new design and MacOs 10.11

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#3002]
### 💻 Environment
Platform: macOS

### 📒 Description

- [x] Mouse click on list items does not open edit popup (Using keyboard works ok and opening the edit popup for running timer is also ok)
- [x] In edit view the autocomplete dropdowns and tags dropdown does not work. Tags dropdown opens but at the very bottom of the screen. Probably an issue with fetching the coordinates. Might be needed to do it differently in older OS.
- [x] UI issues in Edit view. Some parts have gray background. I think it is caused by the fact that we use the system color in some places and in other places we use our predefined colors (like white). We should unify this and use the same color in all the places that need to have the same color.

Example: Delete button in edit view has gray background but the group button in the time entry list item has a correct white (or whatever the system color is) color.

I'll add a screenshot of the app on 10.11:

![62057520_457795428304377_7975765500011479040_n](https://user-images.githubusercontent.com/842229/58957491-611ca200-87a9-11e9-9bb7-191b53615a86.png)

These issues should be fixed before the stable release.

**Comment by RobertoGongora** [comment]
Not sure if this is useful, but this is how the edit UI looks for me. The main UI looks perfect though.

Running High Sierra 10.13.6, dark menu bar and Dock option is selected in the General options.

![image](https://user-images.githubusercontent.com/1845147/59779304-a054f380-927d-11e9-9026-147daf69eb17.png)

**Comment by NghiaTranUIT** [comment]
Thank for the feedback @RobertoGongora, we will take it into account now 👍

**Comment by NghiaTranUIT** [comment]
Confirmed that this issue has been gone in https://github.com/toggl/toggldesktop/pull/3019. We're gonna push this PR forward and release the fix soon 👍
