### ISSUE TITLE
Add notification fallback to all notifications we use

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#3008]
### 💻 Environment
Platform: Linux

### 📒 Description
We should also add fallback for Idle detection popup and anything else we use to notify the user.

Connected to #2916 

Similar solution as #2999

**Comment by MartinBriza** [comment]
Idle notifications benefit from the mentioned PR as well so I'm not sure if this is a valid issue, can you please elaborate on what functionality would you like to be added?

However, we have four possible actions when this occurs and most notification backend in Linux don't support as many buttons in the notifications. It's better to just show a warning and then let the user choose how to deal with the situation in the main window.

**Comment by IndrekV** [comment]
You are correct the previous solution changes how the logic works in general not just for specific type of reminders. Closing this.
