### ISSUE TITLE
Idle popup too small

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#3009]
### 💻 Environment
Platform: Windows
OS Version: Windows 10
Toggl Version: Master

### 🐞 Actual behavior
The idle popup is very small. As big as it's title bar.

### 💯 Expected behavior
Idle popup should have a minimum size so that it is always possible to interact with the buttons in the popup

### 📦 Additional info
User feedback:
>Idle dialog still needs a minimum size specified. When it appears on a locked Windows 10 system that uses DisplayPort and multiple monitors, it can appear as a tiny box no bigger than its title bar, and then it can't be interacted with.

**Comment by nicktoggl** [comment]
(Reference)[https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/22344213621]
