### ISSUE TITLE
lib: context.cc: weird line, investigate later

### ISSUE THREAD

**Issue by MartinBriza** [toggl/toggldesktop#3013]
around line 741:
```
 group_entry_view.GroupItemCount = entry_groups[group_entry_view.GroupName];
```
`entry_groups` is `std::map<std::string, bool_t>`
`group_entry_view.GroupItemCount` is `uint64_t` 

Probably very wrong, need to find out what exactly is it supposed to do.

**Comment by IndrekV** [comment]
The `entry_groups` is used to keep track which of the groups are opened and witch are closed. The  
```
// To cache grouped entries open/close status
  708:     std::map<std::string, bool_t> entry_groups;
```

The line 741 should not work and the number of group item should be always be 0 or 1 in that case.

That line can be removed as it is never used. 
The correct number of items that is used in the UI is set a few line later.
```
                            group_view.GroupItemCount = group_items[group_view.GroupName].size();
```
