### ISSUE TITLE
Focus on the description field after using the ⌘ N shortcut

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggldesktop#3014]
Toggl Desktop (for macOS) allows you to start a time entry using ⌘ N. However, once the time entry is started you can't change any of the properties without using the mouse. 

Make it so that the app focuses on the description field after using ⌘ N. 

---
[Requested here](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/search/conversations/22127513234)

**Comment by IndrekV** [comment]
There is a setting called "Open edit view when starting entry with shortcut", If this is enabled the edit popup will appear and description is focused. I'd say close this.

**Comment by vedr4n** [comment]
😮 

I feel dumb. Thanks @IndrekV! Closing.
