### ISSUE TITLE
Timeline U - header

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#3016]
### 💻 Environment
Platform: macOS

### 📒 Description

Timeline view header has 2 components:
- Record activity switch to turn timeline tracking on and off
- Date Picker. This should be the same component used in edit view with the exception that calendar popup *cannot* be opened (reason being that we only show about 9 days of data to the user and there is no need to have a fully functional calendar view here). Left / Right arrows move the day forward or backward. 

Connected to #2890

**Comment by NghiaTranUIT** [comment]
```Left / Right arrows move the day forward or backward.``` @IndrekV There is some conflicts for this idea 

---------------

<img width="543" alt="Screen Shot 2019-06-18 at 16 33 44" src="https://user-images.githubusercontent.com/5878421/59670949-fe82c780-91e6-11e9-8ef2-00d006817da5.png">

As you can see, by default, the Timer will always be focused. Thus, If we support "Left/Right arrows to move to next/previous days", it would conflict with the action to move the Cursor in Timer Text Field. 

How could we do it?

**Comment by NghiaTranUIT** [comment]
Currently, I'm supporting the "Tab to navigate to all controls"

![2019-06-18 16 37 38](https://user-images.githubusercontent.com/5878421/59671207-7b15a600-91e7-11e9-9752-11a032d6c87d.gif)

**Comment by IndrekV** [comment]
We can skip LEFT/RIGHT keys support as it made sense in prototype design but not this one where timer is always visible.

**Comment by NghiaTranUIT** [comment]
Close by https://github.com/toggl/toggldesktop/pull/3036
