### ISSUE TITLE
Timeline UI - time entries list

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#3017]
### 💻 Environment
Platform: macOS

### 📒 Description
Vertical list that displays time entries in a timeline

- Every full hour is shown as a label (8:00 AM etc)
- Time entries are the color of their project
- Time entry item height is based on it's duration.
- If time entries overlap they are horizontally positioned side by side
- Empty slots or gaps in the day area marked with an element with a dotted line border.
- Hovering items will show the info about the item (https://zpl.io/VQv3jz4)
- Clicking on items will show edit popup for the item
-

**Comment by NghiaTranUIT** [comment]
Close by https://github.com/toggl/toggldesktop/pull/3050
