### ISSUE TITLE
Timeline UI - activities list

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#3018]
### 💻 Environment
Platform: macOS

### 📒 Description
List of data collected with the timeline

- Vertical list with items that represent 15 minutes of data.
- Every hour has 4 vertical items
- Items are always blue
- The size and color depend on the activity during this 15 minute period. Data is given as time in seconds. The less it is the lighter is the blue color.
- Hovering items will show all info about the data tracked in this 15-minute timeslot.

Both lists are connected and are scrollable together. (#3017 entries list)

**Comment by NghiaTranUIT** [comment]
During development, I have a couple question, please help me to clarify it 😄 

## The length of the activity?
<img width="646" alt="Screen_Shot_2019-08-20_at_13_31_23" src="https://user-images.githubusercontent.com/5878421/63323027-fa8e3580-c34e-11e9-8cc7-0008aaf13af4.png">

Activity model: https://github.com/toggl/toggldesktop/blob/24fe1dcbbeab4deb552d58d81691d8c0932118e1/src/toggl_api.h#L95-L113

From our requirement and activity model, each hour consist of 4 15-mins activity. 
1. Do we mean the the length of one activity is the total of duration of events?

## The activity hover
<img width="317" alt="Screen Shot 2019-08-20 at 13 38 24" src="https://user-images.githubusercontent.com/5878421/63323379-d41cca00-c34f-11e9-96b1-da4542f4d8da.png">
From the screenshot, the hover Activity is from 8:00 -> 8:15, but the data is various from 6:53, 1:57, 0:17, 1:00, ... 
2. Why is it happen? 
3. Why aren't the time of events are in 8:00->8:15?

## Group
<img width="492" alt="Screen_Shot_2019-08-20_at_13_38_24" src="https://user-images.githubusercontent.com/5878421/63323569-50171200-c350-11e9-9f5c-a80f3dc6872e.png">
4. How does even group together? From the screenshot, it's grouping, but the event in `Group 2` isn't relevant?

**Comment by NghiaTranUIT** [comment]
## Additional question:
5. I'm not sure, but our logic to fetch the activities and events seem are not working. From what I observer that:
- The library always return many activity, but none of them has the Events (I tried to Tick the Timeline record, and start the TE), but at the end, there is no events as well.

https://github.com/toggl/toggldesktop/blob/ae4c79b442e252da955393ac6bbbad3fa272af86/src/gui.cc#L508

**Comment by skel35** [comment]
> 1. Do we mean the the length of one activity is the total of duration of events?

Yes. If total duration of events in 15-minute chunk is 10 minutes, then the length of one activity should be 2/3 of the max length.

> From the screenshot, the hover Activity is from 8:00 -> 8:15, but the data is various from 6:53, 1:57, 0:17, 1:00, ... 2. Why is it happen? 3. Why aren't the time of events are in 8:00->8:15?

6:53, 1:57, 0:17, 1:00, ... are the lengths of the events, not the start time.

> 4. How does even group together? From the screenshot, it's grouping, but the event in `Group 2` isn't relevant?

Why isn't the event in `Group 2` relevant? These look like the titles of a Google Chrome page.

This is all mostly the same as the Timeline in the webapp. Did you have a look at it?

**Comment by NghiaTranUIT** [comment]
Thank @skel35. I'm gradually understanding the answer for those questions when looking back the Indrek's implementation on `TimelineChunkView` 👍
