### ISSUE TITLE
Double-clicking on mini-timer does not open desktop app 

### ISSUE THREAD

**Issue by nidarasheed** [toggl/toggldesktop#3034]
### 💻 Environment
Platform: Windows
OS Version: Windows 10 
Toggl Version: 7.4.422

### 🐞 Actual behavior
Users used to be able to double click on the minitimer's description to pop up the regular Toggl window and set the current tasks category. 

Double clicking on the minitimer no longer does anything, and they have to use the system tray icon to bring up the main window. 

This is much less convenient

### 💯 Expected behavior
Double-click on mini-timer should open the regular app. 

### 🔨 Steps to reproduce
See above
### 📦 Additional info
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/22471764546)

**Comment by lise-toggl** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/22253668658)

**Comment by lise-toggl** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/22525008942)
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/22529797776)
