### ISSUE TITLE
Load more button is not shown if the user's latest entry was more than 10 days ago

### ISSUE THREAD

**Issue by skel35** [toggl/toggldesktop#3035]
### 💻 Environment
Platform: Windows
Toggl Version: 7.4.431

### 🐞 Actual behavior
Load more button is not shown, the app looks as if there are no entries at all.

### 💯 Expected behavior
Load more button should be shown. See Mac version for example.

### 🔨 Steps to reproduce
1. Make sure the latest time entry is more than 10 days ago.
2. Launch Toggl Desktop.

**Comment by lise-toggl** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/22978136249)
