### ISSUE TITLE
Pomodoro break doesn't stop the timer after the notification

### ISSUE THREAD

**Issue by zdericnina** [toggl/toggldesktop#3037]
### 💻 Environment

Platform:  macOS
OS Version:  macOS 10.14.5
Toggl Version:  7.4.430 

### 🐞 Actual behavior

Timer continues running past the 5-minute mark set in Pomodoro break.

### 💯 Expected behavior

The timer should stop after the Pomodoro break is over.

### 🔨 Steps to reproduce

1. Turn on the Pomodoro timer in the desktop app
2. Set the break to 5 minutes
3. After the break finishes, the notification gets displayed but the timer doesn't stop, it continues running past the 5-minute mark.

### 📦 Additional info

I was also able to replicate this in the latest beta app release.
Cases:
[case 1](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/22534280314)
[case 2](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/search/conversations/22127513234)

**Comment by fangzhzh** [comment]
same here. Toggle desktop version 7.4.430 on Mac OS.

It looks just an UI issue it doesn't really increase the break time data but the UI is still disturbing

**Comment by skel35** [comment]
Might be the same issue as #3030

**Comment by fangzhzh** [comment]
@skel35 yes, the same. It's ok to close this and I'll track #3030

**Comment by NghiaTranUIT** [comment]
Thank all for the feedback, I will investigate this issue today 👍
