### ISSUE TITLE
Dropdown list of projects in detail view is too small

### ISSUE THREAD

**Issue by stranljip** [toggl/toggldesktop#3040]
### 💻 Environment
Platform: macOS

### 📒 Description
The dropdown list for projects is not broad enough to display enough content of the project title. Therefore, I cannot select the right project without trial and error. 
Suggestions:
* allow resizing of the detail view (preferred)
* add ellipsis
* add tooltip on hover

### ⭐️ Why do you want this?
I have project titles containing the JIRA issue number and the meta-project. I need these to enable automatic creation of log entries in JIRA (https://github.com/DisyInformationssysteme/toggl-jira-integration). With this additional information, I cannot identify the right item.

**Comment by NghiaTranUIT** [comment]
Thank for the feedback. 

We notices this issue too. Resizable Detail View and tooltip could be potential approaches 👍

**Comment by stranljip** [comment]
Cool, thanks!

**Comment by stranljip** [comment]
Just as a thought: Resizable with remembering the new size would be the optimum ... :-)
