### ISSUE TITLE
Description is focused after clicking "+ Add project" or the tag icon

### ISSUE THREAD

**Issue by skel35** [toggl/toggldesktop#3041]
### 💻 Environment
Platform: macOS
OS Version: macOS 10.14
Toggl Version: 7.4.430

### 🐞 Actual behavior
Edit view is open and the Description field is focused

### 💯 Expected behavior
When "+ Add project" is clicked in the time entry list, the Edit view should be open with Project field being focused. Same applies to the tag icon or the Client name.

### 🔨 Steps to reproduce
1. In the Time entry list click on "+ Add project"
![description_is_always_focused](https://user-images.githubusercontent.com/16451391/60008369-a3385580-967c-11e9-8ec7-af8187238eb8.gif)

**Comment by NghiaTranUIT** [comment]
To be clear, the Editor should focus on a specific textfield, which we clicked in Time Entry. For instance:
1. Click on Description -> Editor will focus on Description
 2. So all for Project and Tag

**Comment by skel35** [comment]
Fixed by #3042
