### ISSUE TITLE
Idle notification no longer appears in foreground

### ISSUE THREAD

**Issue by lise-toggl** [toggl/toggldesktop#3070]
### 💻 Environment

Platform: macOS
OS Version: OS X 10.14.5
Toggl Version: 7.4.444 (beta)

### 🐞 Actual behavior
The idle notification doesn't pop up in the foreground any more, so you need to look for it in the background.

[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3155115/conversations/22685373790), reproduced by Nick.

### 💯 Expected behavior
The notification should appear in the foreground like in the previous version.

### 🔨 Steps to reproduce

1. Start the app
2. Wait for the idle notification

**Comment by nidarasheed** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/22750849424)

**Comment by nidarasheed** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/22729727263)
