### ISSUE TITLE
The grey background issue on macOs 10.11.

### ISSUE THREAD

**Issue by skel35** [toggl/toggldesktop#3076]
### 💻 Environment
Platform: macOS
OS Version: macOS 10.11.6
Toggl Version: 7.4.444 (latest beta)

### 🐞 Actual behavior
Sadly the grey background issue still shows on my macOs 10.11.6 machine. As the timer description field seems to work as expected maybe we can use the same logic in edit view fields to fix them.

Screenshot of the grey fields.
![Screen Shot 2019-06-26 at 07 45 07](https://user-images.githubusercontent.com/842229/60151879-14941780-97e7-11e9-945a-c3019bac296b.png)

_Originally posted by @IndrekV in https://github.com/toggl/toggldesktop/pull/3019#issuecomment-505717439_

**Comment by nidarasheed** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/21918796562)
