### ISSUE TITLE
Improvements for new mac design

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#3077]
### 💻 Environment

Platform: macOS

### 📒 Description
>- Date format preferences should be taken from profile settings (logging this as a feature request)
>- In dark mode, some project colors are not clear (dark green and brown for example)
>- The rounding around fields should be consistent  (what you are doing box is rounded, the fields for editing entries are not rounded in the same way. Plus the remaining app has straight lines)

**Comment by nidarasheed** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/conversations/22793496533?redirectTo=feed)

**Comment by IndrekV** [comment]
> -Date format preferences should be taken from profile settings (logging this as a feature request)
Date format is based on MacOs  system date format and it is not possible to change this format in the date component.

>- In dark mode, some project colors are not clear (dark green and brown for example)
Just checked this out and the colors are a bit dark but usable. This is bound to happen when there is a possibility to use light and dark themes. All paid plans have additional color picker so there is a wider choice of colors to select for projects.

>- The rounding around fields should be consistent  (what you are doing box is rounded, the fields for editing entries are not rounded in the same way. Plus the remaining app has straight lines)

To emphasize timer part of the app it is clearly different by design. This logic is intended.
