### ISSUE TITLE
Latest Linux dev build looks for cacert in the wrong place

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#3078]
### 💻 Environment
Platform: Linux
Toggl Version: 7.4.410 tar.gz package

### 🐞 Actual behavior
Looks for cacert file in the build directory that has nothing to do with the release

### 💯 Expected behavior
Look for cacert in the correct locatio and not in the build path

### 🔨 Steps to reproduce

1. Download build 7.4.410 (tar.gz)
2. Unpack and start the app.
3. Error appears right at the top

### 📦 Additional info
![Screenshot from 2019-07-11 12 41 09](https://user-images.githubusercontent.com/842229/61040727-d3e8f080-a3d9-11e9-9856-1e07e074738e.png)

**Comment by IndrekV** [comment]
cacert file is also not shipped with the release.

**Comment by MartinBriza** [comment]
It is shipped, just in a different folder. See the PR for a fix.
