### ISSUE TITLE
Dissapointed with latest updates

### ISSUE THREAD

**Issue by endel** [toggl/toggldesktop#3091]
Hi there,

I'm very disappointed with the last few updates. The "discard idle and continue" feature which I loved the most doesn't exist anymore. It now shows two options and none of them actually do what it used to do before.

![Screenshot 2019-07-16 at 11 21 22](https://user-images.githubusercontent.com/130494/61302261-da9dac00-a7bb-11e9-897e-2d6bcc472d27.png)

Cheers

**Comment by skel35** [comment]
Hi @endel! Thanks for the feedback.
We've already decided to bring this button back and it's already back in `master`. Expect it in the new beta very soon.
Just to note, unfortunately, there have been some bugs in our `beta` version with a new design. If you wish to always use a more stable version with fewer bugs, please switch to `stable` channel.
If you find some other bugs in our new beta version, feel free to report them here if they are not already reported.

**Comment by endel** [comment]
Thanks, I don't know how I've got the beta actually. Must have searched quickly the web to download it and got the wrong one 😅 thanks!
