### ISSUE TITLE
List item continue button not working on first click

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#3120]
### 💻 Environment
Platform: Linux 
Toggl Version: Master

### 🐞 Actual behavior
If you click on a continue button of an entry that is not selected in the listing it will just select the item and will not trigger the continue action

### 💯 Expected behavior
Clicking on continue button in a listing entry continues the entry at first click

### 🔨 Steps to reproduce

1. Click continue arrow on any not selected item in the list
2. Entry will not start tracking

### 📦 Additional info
* First we click on an item that is not selected. It gets selected and the listing scrolls to make the selected item be in focus. The second click on the continue button triggers the timer start.

* Second time we select the entry we want with keyboard and then press continue button with the mouse. Now the timer is triggered right away.

![linux-continue](https://user-images.githubusercontent.com/842229/61697177-6b860180-ad3f-11e9-9c42-8c8dcc176db8.gif)

**Comment by MartinBriza** [comment]
Hmm, I can't reproduce this in GNOME, what environment is this?

**Comment by IndrekV** [comment]
Kubuntu KDE Plasma

**Comment by IndrekV** [comment]
I'll test it on another window manager

**Comment by IndrekV** [comment]
The issue seems to happen when list needs to scroll. If there are a lot of items in the list then clicking on an item will scroll this item to the center or something like this. If this happens the click on the continue button does not work. 

Try to add a lot of entries to the list and then start clicking around.

**Comment by MartinBriza** [comment]
Ah, thanks, the hint about multiple items in the list was the culprit. It was tough to find but it's related to how I was doing scrolling of the items when tabbing through the list.
