### ISSUE TITLE
Unable to log in with Google account

### ISSUE THREAD

**Issue by vahivsky** [toggl/toggldesktop#3146]
Unable to log in with Google account in both Toggl website and Toggl Desktop app (on Windows 10). My account is vahivsky@gmail.com.

I was using Toggl for a couple of years already under this account, but today I was unable to launch Desktop app (it would just close right after I launch it). After reinstalling with clearing cache, the app doesn't authenticate. 

I have also tried to authenticate at https://toggl.com/login (with Chrome browser), but when I click button "Log in with Google" and pass authentication, I can see error message under the password field: "This Google account is already associated with another Toggl account".

Expected behavior:
After passing Google authentication I should be logged in under associated Toggl account.

Platform: Windows
OS Version: Windows 10.0.17134
Toggl Version: 7.4.422

PS. I've also tried to use Incognito mode of Chrome, to make sure it is not some caching issue. Still see the same error.

**Comment by TheSoloJake** [comment]
Hello @vahivsky ! Can you send us an email at support@toggl.com with your issue? Just for privacy's sake, in case we need to discuss any account-related matters with you. We'll be on the lookout for your response!

**Comment by skel35** [comment]
Closing as it's related to login in general, rather than a desktop app specifically
