### ISSUE TITLE
Autocomplete Task Name Broken

### ISSUE THREAD

**Issue by BitForger** [toggl/toggldesktop#3158]
### 💻 Environment

Platform: macOS
OS Version: ^10.14.x
Toggl Version: 7.4.479 (latest)

### 🐞 Actual behavior

When I start a new time entry and start typing in the name of a task an autocomplete dropdown appears. When I select one the entry initially fills but on closing the popup the value reverts to what I had typed. Hitting `Enter/Return` also has the same behavior.

### 💯 Expected behavior

Hitting `Enter/Return` autofills the selected value into the task field and doesn't revert on closing the popup.

### 🔨 Steps to reproduce

1. Start new timer
2. Click on it to show popup
3. Select Autocomplete suggestion
4. Close popup

### 📦 Additional info

![](https://dsh.re/cfad4)

**Comment by IndrekV** [comment]
Thank you for reporting this issue has been fixed with latest release. U

**Comment by IndrekV** [comment]
Update the app from about page or download latest version from https://toggl.github.io/toggldesktop/download/macos-stable/
