### ISSUE TITLE
Fix gatekeeper assessment

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#3161]
### 💻 Environment

Platform: macOS

### 📒 Description
Gatekeeper assessment fails. We need to look into ways to solve this.

### References
Is connected to notarizing or event fixed when we add notarizing  #2919 

### Possible solutions
https://forums.developer.apple.com/thread/77430
https://stackoverflow.com/questions/42066545/successfully-codesigned-app-failed-to-pass-gatekeeper#comment95373004_42066545

**Comment by ScottSmith95** [comment]
This is preventing new users from installing the app without going in to their Gatekeeper settings and allowing the app to run.

**Comment by IndrekV** [comment]
This issue is now fixed and we created and we build with the correct signed app (the version is same 7.4.484). Get it from https://toggl.github.io/toggldesktop/download/macos-stable/
