### ISSUE TITLE
Autocomplete Deletes Selected Description

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggldesktop#3164]
### 💻 Environment

Platform: Mac
OS Version: Mojave
Toggl Version: 7.4.479

### 🐞 Actual behavior
(1) I start typing the details of my time entry in the “Details” pop-up box. Autocomplete matches appear as I type. I cursor-down or use the mouse to select one. 

(2) The details are populate on the timer. But then partially autocompleted task remains in “Details”. 

(3) When I click “X” - the partial text is saved back to the timer.

### 💯 Expected behavior
Selecting the suggestion should not copy the search term into the description

### 📦 Additional info
Screenshot video of action found here: https://drive.google.com/file/d/1dlMtVZrM9noKV8Y20nb3BnUJ-gI5tDo1/view?usp=sharing (only accessible by logging into TogglGoogle account)

**Comment by TheSoloJake** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/23053432208) with affected user

**Comment by lise-toggl** [comment]
@TheSoloJake this might be fixed in 7.4.484? Nick couldn't replicate it on that version :)

**Comment by NghiaTranUIT** [comment]
Yes @lise-toggl @TheSoloJake, confirmed that this bug has been fixed in `7.4.484` 👍
