### ISSUE TITLE
Project name clears from time entry

### ISSUE THREAD

**Issue by nidarasheed** [toggl/toggldesktop#3180]
### 💻 Environment

Platform: MacOS
OS Version: OS X 10.14.4
Toggl Version: Stable, 7.4.484

### 🐞 Actual behavior

After creating a new project for running time entry, the project field clears up. Video in [Intercom link](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/23125036438).

### 💯 Expected behavior

Project name that is created and selected should stay selected. 

### 🔨 Steps to reproduce
Video linked above. 

### 📦 Additional info
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/23125036438)

**Comment by nicktoggl** [comment]
[user case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/23137922777)

**Comment by lise-toggl** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/23581530568)
