### ISSUE TITLE
Very hard to see dark project colours when using dark mode.

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/toggldesktop#3182]
### 💻 Environment
MacOS

Platform: MacOS

### 📒 Description
When projects are created with dark colours they are very difficult to see in dark mode.

**Comment by ApocalypticFish** [comment]
[link](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2144650/conversations/23132559774)

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/23136081439)
