### ISSUE TITLE
Logic for "Resolve the conflicted Timeline Entry"

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl/toggldesktop#3187]
### Description
The UI is done at https://github.com/toggl/toggldesktop/pull/3050
This ticket is connecting with the last criteria in https://github.com/toggl/toggldesktop/issues/2892
```
Allow solving overlaps. Clicking on overlap shows a context menu with 3 choices:
- change first entry stop time
- change last entry start time
- create a new entry of overlap
(The texts should be improved, they should be shorter)
```

We need to elaborate more. Examples are welcome 👍 

### 💻 Environment
Platform: macOS

**Comment by skel35** [comment]
Basic Example:
TE 1: 06:45:10 - 06:55:10
TE 2: 06:55:00 - 07:00:00

If user picks "Change first entry stop time" ->
TE 1: 06:45:10 - 06:55:00
TE 2: 06:55:00 - 07:00:00
Else if user picks "Change last entry start time" ->
TE 1: 06:45:10 - 06:55:10
TE 2: 06:55:10 - 07:00:00
