### ISSUE TITLE
Timeline Improvements

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl/toggldesktop#3188]
### 📒 Description
It contains all minor things that we could improve the Timeline feature

### 💻 Environment
Platform: macOS

### Acceptance Criteria 
- [x] After creating new time entry, the Timeline view will be reloaded from the call in library -> Cause the editor jumps
- [x] Able to change current timeline date when selecting in DatePickerView

**Comment by NghiaTranUIT** [comment]
Additional issues: https://github.com/toggl/toggldesktop/pull/3036#issuecomment-519103677

**Comment by skel35** [comment]
Closed with #3195
