### ISSUE TITLE
Clicking reports from menu goes to timer page instead of reports page

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#3197]
### 💻 Environment
Windows 10
Desktop app v7.4.484

### 🐞 Actual behavior
Clicking on the reports tab on the settings menu goes to the timer page on the website.

### 💯 Expected behavior
Clicking on the reports tab on the settings menu should go to the reports page on the website.

### 🔨 Steps to reproduce
Open app, click reports from menu, check where website goes

Replicated by me, Nghia and a [user report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/23215920762)

**Comment by skel35** [comment]
Fixed on the backend
