### ISSUE TITLE
Remove Compact mode from API

### ISSUE THREAD

**Issue by skel35** [toggl/toggldesktop#3209]
### 💻 Environment
Platform: Library

### 📒 Description
We have methods in the library `toggl_get_compact_mode` and `toggl_set_compact_mode` which are exposed via the API but I haven't found a single usage of them. Seems like we can remove them from the API.

**Comment by IndrekV** [comment]
The compact view seemed to be an experiment we wanted to do years ago. We did not finish it so it seems it's ok to remove these unused parts.

Commits that added compact view code:
29e1b0cceed83e031ea87898ea7b34ea5b713916
bd61b6f333e069359e1f78148216405f2741287f

Issue: #1748
