### ISSUE TITLE
Tabbing for Mac app, keyboard preference

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#3212]
### 💻 Environment

Mac OS

### 📒 Description
As requested by Nghia - when tabbing on the description, project etc inputs, is the skipping of the tags tab intended?

"Technically, the Tag Input isn’t a TextField, so by default, when we tap, the Tag Input doesn’t focus until we change the setting in Keyboard Preference.

I will improve it, and ensure that it should work regardless of keyboard’s option"

**Comment by NghiaTranUIT** [comment]
Related #3210
