### ISSUE TITLE
Auto-complete for task description not working.

### ISSUE THREAD

**Issue by cyrusbowman** [toggl/toggldesktop#3232]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.12.6
Toggl Version: 7.4.479

### 🐞 Actual behavior

After autocompleting a description, when closing the popup modal, the description reverts back to what was typed.

### 💯 Expected behavior

After autocompleting a description, when closing the popup modal, the description would retain what was autocompleted.

### 🔨 Steps to reproduce

1. Make a new time entry
2. Start entering a description
3. Select any of the auto-completion suggests with keyboard or mouse.
4. Exit from the side modal.

### 📦 Additional info

![Autocomplete](https://user-images.githubusercontent.com/2474343/63284613-f21bf900-c281-11e9-92e9-3be91b4b09a9.gif)

**Comment by nidarasheed** [comment]
Hi there! 

This issue has been resolved in the latest MacOS app. You can download it from here: https://github.com/toggl/toggldesktop/releases/download/v7.4.484/TogglDesktop-7_4_484.dmg

Best Regards :)
