### ISSUE TITLE
Do not send "This entry can't be saved" errors to Bugsnag

### ISSUE THREAD

**Issue by skel35** [toggl/toggldesktop#3233]
### 💻 Environment
Platform: macOS/Windows/Linux (haven't really seen such errors from Linux though)

### 📒 Description
Do not send "This entry can't be saved - please add a project/tag/description/task" errors to Bugsnag as they just mean the user has some required fields set up and hasn't filled them yet. 
Such errors spam our Bugsnag, there are over 100K of these errors during the last month https://app.bugsnag.com/toggldesktop/toggldesktop/timeline?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[search][0][type]=eq&filters[search][0][value]=This&filters[search][1][type]=eq&filters[search][1][value]=entry&filters[search][2][type]=eq&filters[search][2][value]=can%27t&filters[search][3][type]=eq&filters[search][3][value]=be&filters[search][4][type]=eq&filters[search][4][value]=saved

**Comment by IndrekV** [comment]
We have `bool IsUserError(const error err)` in `error.cc` that filters out some errors that are user errors and do not need to be reported. Maybe we can add this to the list.
