### ISSUE TITLE
Keep time and Discard time stop working sometimes

### ISSUE THREAD

**Issue by MartinBriza** [toggl/toggldesktop#3238]
I suspect this happens when the idle notification gets displayed twice without user action.

### 💻 Environment
Platform: Linux
Toggl Version: `master`

### 🔨 Steps to reproduce
1. Set idle time period to 1 minute
2. Start tracking time
3. Wait 2 minutes (to be sure)
4. Move mouse
5. Wait 2 minutes again
6. Move mouse again
7. Try if Keep and Discard time buttons work in the Toggl main window

### 📦 Additional info
This may not reproduce this issue 100% but it happens time to time for sure

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/23324777123)
