### ISSUE TITLE
New project color should be random

### ISSUE THREAD

**Issue by skel35** [toggl/toggldesktop#3263]
### 💻 Environment
Platform: macOS
Toggl Version: 7.4.529

### 🐞 Actual behavior
When creating a project the color the default color is always purple
![image](https://user-images.githubusercontent.com/16451391/63770687-6425bb00-c8de-11e9-98df-a74401b8dd0a.png)

### 💯 Expected behavior
When creating a project the color the default color should be randomly picked from the list of predefined project colors.

**Comment by NghiaTranUIT** [comment]
I don't think that it should be randomized since it didn't describe in the requirement at the first place, but it's good point.

@IndrekV how do you think?

**Comment by IndrekV** [comment]
It was not described to be random at the firs specification but let's make it random. It makes more sense.
