### ISSUE TITLE
Toggl icon issue when pinned to taskbar in Win

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggldesktop#3274]
### 💻 Environment

Platform: Windows
OS Version: Windows 10
Toggl Version: 7.4.529 
Case link: [🔗 ](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/23460205155)

### 🐞 Actual behavior
A user reported that they have pinned the Toggl app icon to the taskbar and when they click on it nothing happens - the app doesn't show up, but when they check Task Manager it's listed there. Only after clicking the tray icon the app shows. They shared a recording of this issue, I uploaded to drive and if you are logged in with a "@toggl.com" email you can access it **[HERE](https://drive.google.com/open?id=1XJeq2-NJj1fqWuZ-LzBb9JXe65RiL_MQ)**.

### 💯 Expected behavior
The app should start normally when the taskbar icon is used

### 🔨 Steps to reproduce

This will not work every time:
1. Pin the Toggl icon to taskbar in Windows
2. Open Toggl by clicking on the taskbar Toggl icon
3. Nothing happens - it might be in tray and you need to click there to get the app to show or you might need to search windows for the app and start it again.

### 📦 Additional info
This happens to me from time to time with Slack (the only app I have as a taskbar icon) and I'm wondering if this is a Windows thing?

**Comment by skel35** [comment]
Very nice and detailed explanation from the user, the video recording and even the monitor scheme, loving it!
I was able to reproduce it and I promise I'll look into it in the next week or two.

**Comment by skel35** [comment]
@VeljkoTN BTW, there is a workaround for this issue. In Preferences, there is a shortcut `Show/Hide Toggl`. The user can set it up and open the app window instantly.

**Comment by VeljkoTN** [comment]
@skel35 good to know! I'll let the user know about this 😃

**Comment by skel35** [comment]
related to #3274

**Comment by lise-toggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/23595558653)
