### ISSUE TITLE
After computer restart, Windows app doesn't load

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#3285]
### 💻 Environment
Windows app, v7.4.529

Platform: 
OS Version: 
Toggl Version: 

### 🐞 Actual behavior
Several users report that after restarting their computers, the desktop app appears as if doesn't open (it runs in the tray and the window doesn't get shown).

### 💯 Expected behavior
App should open without any issues after a computer restart.

### 🔨 Steps to reproduce
Cannot replicate but will include case links below for additional information

### 📦 Additional info
[User report](https://app.intercom.io/a/apps/ayixs927/conversations/23457346153)

[User report](https://app.intercom.io/a/apps/ayixs927/conversations/23537109097)

[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/23537874830)

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/23553626599)
