### ISSUE TITLE
Timeline UI Improvements - Scroll to right now

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#3287]
### 💻 Environment
Platform: macOS

### 📒 Description

**Scroll the timeline view list to the current time**
When switching to timeline view I always want to see what's happening right now. Currently, the list is always scrolled to the top and I have to scroll to see the actual data. It is a bit confusing as the first idea is that something is broken because there is no data visible (Because usually, you don't track anything at night

**Comment by NghiaTranUIT** [comment]
Currently, if we switch to Timeline Mode or switch next/previous day. It will scroll automatically to the first visible TimeEntry bar.

I guess it's a small bug when the TimeEntry in Timeline is empty, but we have Timeline Entry -> Doesn't scroll since I've not supported it yet 😄

**Comment by NghiaTranUIT** [comment]
Fixed in https://github.com/toggl/toggldesktop/pull/3237
