### ISSUE TITLE
Clicking "What are you doing" doesn't open side window

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggldesktop#3290]
### 💻 Environment

Platform: Windows
OS Version: Windows 10
Toggl Version: 7.4.529

### 🐞 Actual behavior
Clicking on "What are you doing" allows you to start typing a time entry description and start a timer but it doesn't automatically open the side window to also allow you to add more details like project or tag. 

### 💯 Expected behavior
Clicking on "What are you doing" should open a side window and move the focus there as is the case with the Toggl app for Mac. 

### 🔨 Steps to reproduce
1. Click on the "What are you doing" field and type a description
2. Side window will not appear
3. You need to start the timer and click it again to get the side window 

Case link: [🔗 ](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/23552074772)

**Comment by IndrekV** [comment]
I read the conversation with the user and it seems that there is some confusion there. There is no feature to open edit popup when user focuses the "What are you doing?" field on any platforms. The only way to open the edit popup from timer is when manual mode is selected or when timer is running. 

With manual mode there is a button instead of the "What are you doing?" field and clicking it will open edit popup.

With running timer clicking on the timer (description, project or duration part) will open the edit popup.

Closing this issue. Thank you come again!

**Comment by VeljkoTN** [comment]
@IndrekV before creating this issue I asked people with Macs to check what happens when they click on "what are you doing" and the side windows opens up as soon as they click it..  on the other hand on Windows it just lets you type a description and start a timer, no way to select a project.. then you have to stop it, click on it from the list of time entries to get the side window and attach it to a project.. there surely needs to be a way to allocate a time entry to a project while creating it when it's not in the manual mode right?

**Comment by VeljkoTN** [comment]
![side window ](https://user-images.githubusercontent.com/36152180/64521744-dc39ab00-d2f8-11e9-8462-0efbf5dbd0dd.gif)

OK so I created a GIF of what I am referring to. Is it like that on a Mac?

**Comment by VeljkoTN** [comment]
It requires that second click after starting the timer to be able to select a project

**Comment by IndrekV** [comment]
Side window does not open up when you click the "what are you doing?" field on mac.

You can't specifically select a project from the timer. You can use the description field autocomplete for that if needed.
I'll add a GIF to illustrate.

- First I type in the project name (Another day at the office working with Hugo Boss)
- Then I type in description

![mac_acomplete_project](https://user-images.githubusercontent.com/842229/64522252-3e4ade00-d302-11e9-9f8a-acc4d14d6a9e.gif)

**Comment by skel35** [comment]
@VeljkoTN @IndrekV Mac app has a setting to allow opening an Edit window as soon as the timer is started. We have an issue about adding that to Windows as well #3143.

**Comment by VeljkoTN** [comment]
Oh nice, thanks for clarifying @skel35 🙌

**Comment by IndrekV** [comment]
Yes, good point there is a setting on mac that opens the edit popup right after the entry is started.
it's called `Open edit view when starting entry with shortcut`

I think we need to update the description as it now also works when you start the entry by pressing the start button. It use to only work with shortcuts.
