### ISSUE TITLE
Newly created project is cleared

### ISSUE THREAD

**Issue by lise-toggl** [toggl/toggldesktop#3291]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.14
Toggl Version: 7.4.484

### 🐞 Actual behavior
The newly created project is cleared from the Project field:
![mac-project-problem](https://user-images.githubusercontent.com/50156618/64511838-782edb00-d328-11e9-9b32-ac2df3cf4dd0.gif)

### 💯 Expected behavior
The project should be selected

### 🔨 Steps to reproduce
See gif

### 📦 Additional info
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/23581530568)

**Comment by NghiaTranUIT** [comment]
Related to https://github.com/toggl/toggldesktop/pull/3215 I believe

**Comment by lise-toggl** [comment]
Oops, sorry 👀
