### ISSUE TITLE
Timeline (maybe) not working on Mac

### ISSUE THREAD

**Issue by lise-toggl** [toggl/toggldesktop#3312]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.15
Toggl Version: 7.4.1000

### 🐞 Actual behavior
Timeline entries don't appear on the web app

### 💯 Expected behavior
Timeline entries should appear

### 🔨 Steps to reproduce

1. Enable timeline recording
2. Check the web app

### 📦 Additional info
@NghiaTranUIT did a little testing and it seems like the timeline entries are being recorded but maybe not uploaded.

[User report with logs](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/23645433664)

**Comment by NghiaTranUIT** [comment]
Just double check again. All good in dev, beta and stable version 👍 

The timeline_entries in database are successfully uploaded to the server.
