### ISSUE TITLE
[Mac] Add support for context menu on Dock icon

### ISSUE THREAD

**Issue by shantanuraj** [toggl/toggldesktop#3314]
### 💻 Environment

Platform: macOS

### 📒 Description

Current dock context-menu

![image](https://user-images.githubusercontent.com/1716853/64873709-4ccd2880-d667-11e9-82b5-1a431b9e7082.png)

It'll be great to have some shortcuts in dock context menu actions like

- Start entry
- Stop entry
- Continue latest

Maybe all the shortcuts that the menu bar icon supports

![image](https://user-images.githubusercontent.com/1716853/64873889-a33a6700-d667-11e9-95df-53b5d50c2eec.png)

Spotify's context menu just for reference

![image](https://user-images.githubusercontent.com/1716853/64873761-67070680-d667-11e9-96c8-1d10dcaac432.png)

### ⭐️ Why do you want this?

- Other mac apps have it
- I like quick shortcuts from the Dock icon 🤷‍♂

**Comment by NghiaTranUIT** [comment]
Thank @shantanuraj. It's really good point and I realize that often do quick actions (Next/Previous song) in Spotify too 😄 

We would put it in backlog and will implement it soon.
