### ISSUE TITLE
Selected tab should be marked

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#3331]
### 💻 Environment
Platform: macOS

### 📒 Description
Selected tab should be indicated, currently it is not possible to understand which one is selected

![image](https://user-images.githubusercontent.com/842229/65233844-2d595400-dadc-11e9-930c-ea3682a24be7.png)

**Comment by NghiaTranUIT** [comment]
I couldn't reproduce this bug on latest commit in Timeline PR  https://github.com/toggl/toggldesktop/pull/3032

![2019-09-20 16 23 12](https://user-images.githubusercontent.com/5878421/65315833-01fd6480-dbc3-11e9-8fb6-e5a12e937b78.gif)

Please double check 👍

**Comment by IndrekV** [comment]
Everything is ok in the current state of timeline branch
