### ISSUE TITLE
Timeline popover show/hide delay

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#3332]
### 💻 Environment
Platform: macOS

### 📒 Description
This popup shows immediately and has a delay in disappearing. Should be the other way around.

It should appear with delay and disappear fast.

![image](https://user-images.githubusercontent.com/842229/65233967-6691c400-dadc-11e9-802f-3564e7941db3.png)

**Comment by NghiaTranUIT** [comment]
I'm not sure what the delay is.

1. There no animation when the Popover in Timeline, Activity and Editor (See the GIF)
![2019-09-20 16 13 12](https://user-images.githubusercontent.com/5878421/65315129-c615cf80-dbc1-11e9-9a2e-042435c00bc2.gif)

2. I intentionally disable all animations in the code with `popover.animates = false`
https://github.com/toggl/toggldesktop/blob/d04de0c0223f180e589dac2e33dc6100420d5286/src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.swift#L43-L68

-----------
@IndrekV please double check it.

**Comment by IndrekV** [comment]
No delay detected in the current state of timeline branch
