### ISSUE TITLE
It is impossible to continue a task

### ISSUE THREAD

**Issue by kapooostin** [toggl/toggldesktop#3345]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.14.6
Toggl Version: 7.4.1012

### 🐞 Actual behavior
An attempt to continue a task log a 0 sec length entry and stops a timer.
I tried to use context menu from menubar, green arrow in the app on the right of the task I want to continue. Also a `Discard idle time and continue` button from a popup does the same.

### 💯 Expected behavior
I should be able to continue a task I logged before. 

### 🔨 Steps to reproduce

1. Log a task
2. Stop it
3. Try to continue in any way the app offers

### 📦 Additional info
I tried to downgrade the app down to 7.4.484, but the issue persists. It seems that the bug occurs ever since I upgraded OS from 10.14.5 to 10.14.6.

The chrome extension, the iOS app, and a timer on the site all work as expected.

**Comment by NghiaTranUIT** [comment]
Thank @kapooostin I would investigate this issue in this milestone 👍

**Comment by IndrekV** [comment]
@kapooostin 

It sounds like you have `manual mode` turned on. Please check the menubar icon menu and disable manual mode by clicking `Use timer`.

![Screenshot 2019-09-23 at 13 32 09](https://user-images.githubusercontent.com/842229/65419111-a3c0c380-de06-11e9-9538-024bba4231e6.png)

**Comment by kapooostin** [comment]
Oh, that's hellarious! Thanks, it worked. I must've turned it on from keyboard while Toggl was in focus. Is there a way to disable all shortcuts for the app?

**Comment by IndrekV** [comment]
No, we don't have a functionality to disable shortcut. Sorry. Good to hear it's solved.
