### ISSUE TITLE
Mac Touch Bar - Add global button to Touch Bar

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#3349]
### 💻 Environment

Platform: macOS

### 📒 Description

**Design:**
- Add preference `Show Toggl in Touch Bar`
- This setting should be visible **only** with systems that have touch bar support.
- If the setting is enabled a Toggl touch bar button is added to the touch bar when Toggl Desktop starts and removed when the app closes.
- The touch bar button changes state based on if the timer is running or not.

**Functionality:**
The global button shows the same state as the menubar icon. Pressing the button will either start or stop the timer based on the current status. (This is the basic functionality. If possible we will extend this in version 2 of Touch Bar implementation)

Connected to: #2388

**Comment by NghiaTranUIT** [comment]
Add https://github.com/toggl/toggldesktop/issues/3370 since it's crucial to submit to AppStore

**Comment by NghiaTranUIT** [comment]
> There is no need, and no API, for your app to know whether or not there is a Touch Bar available. Whether your app is running on a machine that supports the Touch Bar or not, your app’s onscreen user interface (UI) appears and behaves the same way. 

According [TouchBar documentation](https://developer.apple.com/documentation/appkit/nstouchbar), there is no way to physcically determine if the MacBook has Touch Bar hardware or not.

I suppose that we should hide the `Show Toggl in Touch Bar` whether macOS < 10.12.2.
