### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by MartinBriza** [toggl/toggldesktop#3361]
So as you know, we're planning to implement GitHub Actions in our repository to create releases in the future (when they get released officially, or if we get invited to Beta).
So far the current status looks like this:

## Features
 - [x] Building (duh)
 - [ ] Running tests (tests are not working yet)
 - [x] Upload to GitHub Releases

### Build events
 - [x] On tag created
 - [x] On PR opened
   - Not sure if this actually does not work
 - [x] On each commit
   - Need to separate this case from "tag created" because we're not uploading anything anywhere.

### Linux
- [x] Tarball build
- [x] Ubuntu 18.04 `deb64` build 
  - [x] Signing
- [ ] Ubuntu 16.04 `deb64` build
  - probably not 100% necessary, hard to do
  - [x] Signing
- [x] Flatpak build (same as Flathub but built by us)
### Windows
- [x] 32bit build
  - [x] Installer
  - [x] Signing
- [x] 64bit build
  - [x] Installer
  - [x] Signing
- [x] Store build
  - [x] Signing
### macOS
- [x] Basic build
  - [ ] Signing
  - [ ] `dmg` generation

**Comment by NghiaTranUIT** [comment]
**macOS PR**: https://github.com/MartinBriza/toggldesktop/pull/1

**Comment by IndrekV** [comment]
Bot test
