### ISSUE TITLE
Strange error message

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggldesktop#3372]
### 💻 Environment

Platform: macOS
OS Version: iMac 5K running 10.14.6 (18G103)
Toggl Version: 7.4.1012

### 🐞 Actual behavior
The user reported getting the following error:
![image](https://user-images.githubusercontent.com/36152180/65864493-3ff04a80-e372-11e9-8331-977bc8d85f25.png)

The app works fine but this pops up just as the app is launched. He can close it and keep working.

### 📦 Additional info
[Link 🔗 ](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/20904802128)

**Comment by keimag** [comment]
I have this error message as well, but it will only connect to the internet for the first few seconds it is open. And then the error above changes to this:

<img width="320" alt="Screen Shot 2019-10-01 at 11 57 13 AM" src="https://user-images.githubusercontent.com/56042061/65983882-291a2880-e444-11e9-9b15-2321a0826403.png">

**Comment by NghiaTranUIT** [comment]
Related to https://github.com/toggl/toggldesktop/issues/3381

**Comment by bigsee** [comment]
I have also started experiencing this error, even though there is no problem with my Mac's Internet connection. And lots of my items now show as unsynced...

![Screen Shot 2019-10-02 at 17 14 18](https://user-images.githubusercontent.com/11768967/66056951-34e71700-e538-11e9-8795-d3a72608d7b4.png)

**Comment by nickharty** [comment]
I started experiencing this error two days ago. And, coming into work this morning, my total time worked yesterday was at 520 hours.

Most of my entries are showing the wrong times, and some have had the projects they were tied into removed.

<img width="934" alt="toggl-01" src="https://user-images.githubusercontent.com/56108598/66107183-88e51080-e5b7-11e9-9111-d78527579b6f.png">
<img width="927" alt="toggl-03" src="https://user-images.githubusercontent.com/56108598/66107193-8d112e00-e5b7-11e9-86bd-da05c55d263e.png">

**Comment by NghiaTranUIT** [comment]
Hey, @nickharty please upgrade to 7.4.1023 (https://toggl.github.io/toggldesktop/#mac), which fixes the duplicated Time Entry bug.

Regarding to the "Too many request", we're applying the rate-limit to all Desktop app for temporary. Read more at https://github.com/toggl/toggldesktop/issues/3379#issuecomment-537391710

**Comment by nickharty** [comment]
Hey @NghiaTranUIT, thank you for the recommendation and further reading. Have updated my Toggl Desktop app now. Hope all's going well with it all.

**Comment by NghiaTranUIT** [comment]
If you're still encountering some issues (rate-limit), we suggest that you can try the Toggl Web version (https://toggl.com/login/) for temporary until all issues are gone. 

Thank you in advance 👍

**Comment by bigsee** [comment]
Now I'm getting the version error again (despite the fact I've been on the Toggl website twice this week to download the latest app):

![Screen Shot 2019-10-04 at 14 41 26](https://user-images.githubusercontent.com/11768967/66208363-312ccf00-e6b5-11e9-813b-606f64be7772.png)

I also get lots of duplicate tasks appearing with different times, which I have to manually delete.

Anyone got an idea what's going on and how I get this to stop? It's almost unusable this week.

**Comment by bigsee** [comment]
I've finally managed to upgrade to 7.4.1023. The desktop apps update functionality was stuck in an infinite loop and not actually updating:

![Screen Shot 2019-10-04 at 14 49 53](https://user-images.githubusercontent.com/11768967/66208986-c086b200-e6b6-11e9-9569-58f65311658b.png)

...after restart it downloads for a while then the restart button is shown again:

![Screen Shot 2019-10-04 at 14 49 26](https://user-images.githubusercontent.com/11768967/66208987-c086b200-e6b6-11e9-9dca-62eecb4cde7a.png)

Resolved by going to the link given in the recent (Oct 1) blog post about the disruption. Not sure whether this update issue should have its separate ticket? Please let me know if you would like me to raise it.

**Comment by NghiaTranUIT** [comment]
Hey @bigsee, We're so sorry for this inconvenience that we stop supporting the version 7.4.1022, which cause the duplication issue.

Here is the brief for this incident: https://blog.toggl.com/toggl-desktop-issue-october-2019/

Please download or upgrade to 7.4.1023 at https://toggl.github.io/toggldesktop/#mac

**Comment by bigsee** [comment]
No problem @NghiaTranUIT - thank you for your advice. Please see my latest post above: I finally managed to upgrade but seems there was an additional issue preventing me from upgrading from within the app. Other users may try to update this way - not sure whether it is worth looking into?

**Comment by NghiaTranUIT** [comment]
Just test myself and I'm able to directly upgrade to .1033 from .1022 within the app. 

Not sure what's in your side but please keep open this ticket. We will keep investigate and observe this problem.
