### ISSUE TITLE
Can't select a project from autocomplete popup

### ISSUE THREAD

**Issue by lise-toggl** [toggl/toggldesktop#3378]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.14
Toggl Version: 7.4.1012

### 🐞 Actual behavior
Selecting a project from the autocomplete dropdown doesn't do anything

### 💯 Expected behavior
The project should be selected

### 🔨 Steps to reproduce

1. Type in the start of a project name
2. Select a project from the dropdown
3. It doesn't do anything :(

### 📦 Additional info
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/mentions/conversations/23896588412)

**Comment by lise-toggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/23928424383)

**Comment by l3mma** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/search/conversations/23997307433)

**Comment by lise-toggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/search/conversations/23997307433)

**Comment by lise-toggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24009965375)
