### ISSUE TITLE
App looks distorted with the Numix GTK theme

### ISSUE THREAD

**Issue by MartinBriza** [toggl/toggldesktop#3383]
### 💻 Environment
Platform: Linux with GNOME (or a different GTK based environment)
Toggl Version: 7.4.528

### 📦 Additional info
There is only the GTK variant of the Numix theme (we're using Qt for the UI on Linux) so it's possible the source of the issue is there. Will need to check how does it behave in this situation.

**Comment by ApocalypticFish** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2144650/conversations/23872088114)
