### ISSUE TITLE
All my time entries for yesterday are ruined..

### ISSUE THREAD

**Issue by TomDobbelaere** [toggl/toggldesktop#3392]
### 💻 Environment

Platform:  Windows
OS Version:  Windows 10 x64 1809
Toggl Version:  7.4.1023

### 🐞 Actual behavior

Yesterday I logged my time entries like I normally do, through the desktop app. I use the start/stop button to start and end entries. All the durations and end times were normal.

I log in the next day, I see that the end times for some of the entries are now set to 9 AM, instead of when I clicked the stop button yesterday. Now I have no idea how long I did take on any of the tasks and it has caused me a lot of work trying to go back and fix it.

![image](https://user-images.githubusercontent.com/13522621/66188778-74247d80-e688-11e9-8401-144774ba775d.png)

![image](https://user-images.githubusercontent.com/13522621/66188905-d4b3ba80-e688-11e9-9061-700b4520cd82.png)

![image](https://user-images.githubusercontent.com/13522621/66188984-fdd44b00-e688-11e9-8e76-ccf0863224c9.png)

![image](https://user-images.githubusercontent.com/13522621/66188992-0462c280-e689-11e9-8490-0a84dcfbacb8.png)

This means I'll lose a lot of time going back and fixing this, I don't even know what the end times were.

### 💯 Expected behavior

Toggl Desktop should correctly sync the end times when I stop a certain time entry and login the next day.

### 🔨 Steps to reproduce

1. Make some time entries
2. Close Toggl Desktop completely
3. Log back in and notice how the time entries have an end time equal to the time you logged back in

**Comment by TomDobbelaere** [comment]
Update: I just realized the entires with a huge end time are actually duplicate entires that I can just delete, thus fixing the calculated time

**Comment by IndrekV** [comment]
This duplicate entries issue was caused by the previous version of the app. Current version 7.4.1023 has this fixed and there will no more be entry duplications. Sorry for the inconvenience this has caused you.
