### ISSUE TITLE
Cannot Create Tags Issue

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggldesktop#3410]
### 💻 Environment

Platform: macOS
OS Version: Latest
Toggl Version: 7.4.1023

### 🐞 Actual behavior
When attempting to create a tag that has a similar tag appearing in the suggestion dropdown, no option appears to create a new tag. 

### 💯 Expected behavior
No matter what, a "create tag" option should appear at the bottom of the dropdown. 

### 🔨 Steps to reproduce
(In the following example, the tag "10dec" is already present, and one wishes to create the tag "10") 

1. Click on Tags dropdown
2. Start entering "10" 
3. No option appears to simply allow "10" as a new tag; the dropdown only allows for the selection of "10dec" and nothing else. 

### 📦 Additional info

![Screen Shot 2019-10-08 at 4 10 15 PM](https://user-images.githubusercontent.com/25573455/66433764-a87c9e80-e9e6-11e9-99d3-c9a4571d8451.png)

[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/23989124039)

**Comment by nicktoggl** [comment]
I had a similar case yesterday, but if I added a space after the proposed tag, an option to create appeared.
