### ISSUE TITLE
Autotracker and OSX Catalina

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#3422]
### 💻 Environment
OSX Catalina v10.15

Platform: MAC OSX
OS Version: macOS 10.15
Toggl Version:  7.4.1023

### 🐞 Actual behavior
Since the latest update to Catalina, I've been unable to get autotracker to work with the Toggl desktop app. Users are also reporting problems.

### 💯 Expected behavior
Autotracker should work as normal

### 🔨 Steps to reproduce
Update to Catalina and attempt to use autotracker with the desktop app

### 📦 Additional info
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/24025181609)

**Comment by loic294** [comment]
I also have this problem since I updated to Catalina.

**Comment by NghiaTranUIT** [comment]
Related #3427

**Comment by sensedbalazs** [comment]
I also have the same problem. OS Catalina 15.5, Chrome Version 77.0.

**Comment by NghiaTranUIT** [comment]
Due to new Security on macOS 10.15, it causes the empty Window's title in Timeline event and the AutoTracker won't work properly.

We're working on the new design to instruct the users to grant the Screen Recording permission in Security, so the Lite Version as we expected in #3445 is postponed.

**Comment by sensedbalazs** [comment]
Can I grant my OS to give permission for toggl?




*Web, UI, Logo and Identity Design*
+36 20 261 8447     I     Behance:  behance.net/sensed
<https://www.behance.net/sensed>     I     Instagram:   @sensed
<https://www.instagram.com/sensed/>

**Comment by NghiaTranUIT** [comment]
Unfortunately, we couldn't manually grant the permission to Toggl in the latest Toggl version (7.4.1023) since we haven't implemented the logic to add Toggl to Security Panel.

I tried to drag the app to Screen Recording in Security, but no luck too.
