### ISSUE TITLE
OSX Catalina and timeline filenames/websites

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#3427]
### 💻 Environment

Platform: MacOS 
OS Version: MacOX Catalina 10.15
Toggl Version: 7.4.1023

### 🐞 Actual behavior
The timeline no longer displayed the filenames/websites when using different applications. 

### 💯 Expected behavior
The filename when using a particular application should appear.

### 🔨 Steps to reproduce

1. Run timeline with some sort of application and check the filename/websites to see if any appear

### 📦 Additional info
User case with screenshot of behaviour [User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/24083752282)

**Comment by NghiaTranUIT** [comment]
From macOS Catalina, all macOS apps are restricted to access to other app (Get the filename, website) by default. Therefore, we have to request the access permission from end-users in order to successfully get the data for the timeline features.

I will take a look later and come up a proposal 👍

**Comment by dianetoggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3540765/conversations/21275211311)

**Comment by dianetoggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/conversations/24114769402)

**Comment by dianetoggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/conversations/24114769402)

**Comment by dianetoggl** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3540765/conversations/24114769402)

**Comment by dianetoggl** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3540765/conversations/24114769402)

**Comment by dianetoggl** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3540765/conversations/24114769402)

**Comment by dianetoggl** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3540765/conversations/24114769402)

**Comment by lise-toggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/mentions/conversations/24114769402)

**Comment by dianetoggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3540765/conversations/24185093221)

**Comment by NghiaTranUIT** [comment]
From Catalina, it's impossible to get the Window name unless granting "Screen Recording" permission.

- `kCGWindowName` is nill

<img width="1450" alt="Screen Shot 2019-10-21 at 17 37 34" src="https://user-images.githubusercontent.com/5878421/67198593-809b2b00-f429-11e9-800a-94d2b36c72df.png">

Ref: https://developer.apple.com/videos/play/wwdc2019/701/

**Comment by dianetoggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3540765/conversations/24213961188)

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24239351280)
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/23958292350)
