### ISSUE TITLE
Add option to remove tags while editing TE with keyboard (backspace) 

### ISSUE THREAD

**Issue by nidarasheed** [toggl/toggldesktop#3429]
### 💻 Environment

Platform:  MacOS

### 📒 Description

Allow users to remove tags on existing TE by tabbing to tags field and pressing backspace. 

### ⭐️ Why do you want this?

A user is saying the previous version of the app allowed them to remove tags by pressing backspace (while editing an existing TE). They would like this functionality added back. 

[User](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24103673112)

**Comment by NghiaTranUIT** [comment]
It's good idea to quick remove the current tag by pressing the backspace.

We will consider and implement it soon 👍
