### ISSUE TITLE
New entry - description and project is not blank, but same as last entry

### ISSUE THREAD

**Issue by lise-toggl** [toggl/toggldesktop#3432]
#2894 # 💻 Environment

Platform: macOS
OS Version: macOS 10.14
Toggl Version: 7.4.1023

### 🐞 Actual behavior
Sometimes, the "What are you doing?" section is already pre-populated with the previous entry's details.

### 💯 Expected behavior
It should be empty.

### 🔨 Steps to reproduce
Could not reproduce internally. Video available from user [here](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/24106937479#part_id=comment-24106937479-3935662612)

### 📦 Additional info
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/24106937479)

**Comment by fuzzy76** [comment]
I'm seeing this constantly. It's incredibly irritating, because I often just press the play symbol to continune the same entry, but Toggl starts a blank timer instead.
