### ISSUE TITLE
Highlight the Tag Text Field after selection

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl/toggldesktop#3438]
### 📒 Description
Some users complains that the Tag Text Field is clear and present all the Tag Result after selecting new tags. This behavior cause confused that they have to type again in order to select a new tag.

We have to improve it.

### 💻 Environment
Platform: macOS

### ⭐️ Acceptance Criteria
- [ ] Keep and Highlight the Tag Text Field after the selection
- [ ] Don't reset the Tag result. Keep it as it is

**Comment by nidarasheed** [comment]
[User Request](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24142966719)
