### ISSUE TITLE
Project Autocomplete Dropdown Does Not Allow for Project Selection

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggldesktop#3460]
### 💻 Environment

Platform: macOS 
OS Version: 10.15 
Toggl Version: 7.4.1023

### 🐞 Actual behavior
When typing in a project name from the "What Are You Doing" area, a dropdown appears where suggested projects are listed. Projects on this list are not able to be selected by a cursor. Occasionally, quitting and restarting the app helps.

### 💯 Expected behavior
Projects in the dropdown should be selectable. 

### 🔨 Steps to reproduce

1. Open app
2. Start typing in a description and/or project name in the "What Are You Doing" window 
3. Attempt to click on a project name to select it

### 📦 Additional info

[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/24198113271) 

(above report includes log files)

**Comment by NghiaTranUIT** [comment]
I would close this ticket since it's already fixed in https://github.com/toggl/toggldesktop/pull/3419.

We're aiming to release the BETA on next Monday 👍

**Comment by TheSoloJake** [comment]
@NghiaTranUIT Can you ping me in Slack if/when ready so I can inform the user?

**Comment by NghiaTranUIT** [comment]
Sure, will notify you when we release the DEV today and the BETA for next Monday. It would include the fix 👍
