### ISSUE TITLE
task and project autofill not working properly

### ISSUE THREAD

**Issue by cucaracha21** [toggl/toggldesktop#3466]
Platform: 
Windows

Description:

- The autofill function in the desktop version does not seem to work very well at all.
- I am not sure if it works better in the browser version.
- If i have not been working on a job/task for a couple weeks, the autocomplete seems to forget about it about that task.
- It is easy to see that this will lead to _almost_ identical "duplicate" entries being added, which are annoying to rectify later.

**Comment by lise-toggl** [comment]
Hi there, the autocomplete function only works for time entries which are shown in the list below for performance at the moment. You can use the "Load more" button to see older entries, which will then work for autocomplete.

The team are still thinking about how to best handle this so thank you for your feedback! :)

**Comment by IndrekV** [comment]
Projects and Tasks are always autocompleted against all data in the account. For time entries only recent time entries are kept in memory as keeping all of them would create a gigantic amount of data to be kept in the memory.

**Comment by cucaracha21** [comment]
Dear IndrekV,
can you define "recent"?
it seems to me that "recent" is not a very good measure of how many to keep in memory. this would mean if i was working on one project for a couple weeks, the myriad other tasks i regularly complete would be forgotten.
Also, how much is gigantic? how much memory is say 100 recent tasks with a 5 word description?

this is literally the only thing preventing our organisation from rolling out this software. it wouldnt be so bad if one could easily do back and fix it, but it is rather tricky to repair old records. 

clearly it is not acceptable to send an invoice to a client with 3 different entries for the same task...

regards,
jono
