### ISSUE TITLE
Projects are listed by Workspaces and grouped by client in project autocomplete

### ISSUE THREAD

**Issue by cborgia** [toggl/toggldesktop#534]
I know you guys are busy, but the app has not seen advancements in project selection in some time (a fundamental aspect of the app).

I encourage you to revisit the design of the project dropdown ASAP, and offer us a view similar to the dropdown on the WEB UI. Projects are listed by Workspaces and grouped by client.

**Comment by cborgia** [comment]
can't wait to see how you addressed this. new build?

**Comment by cborgia** [comment]
just built the latest src, seems all that was done was grouping of workspaces (still needs some design work). Can you also group by Client so instead of:

```
project x - client 1
project y - client 1
project z - client 2
````
we get:

````
client 1
    project x
    project y
client 2
    project z
````

**Comment by tanel** [comment]
Will try.

**Comment by tanel** [comment]
Tried the grouping, but does not look good. We'd need custom comboboxes (autocompletes) now.
