### ISSUE TITLE
Linux: Start typing, hit enter (to use a previous time entry description / project) - result doesn't have a project

### ISSUE THREAD

**Issue by jgindin** [toggl/toggldesktop#779]
I'll start typing (e.g., "Review") and a prior time entry comes up, like "Review for Bob - Code Reviews".

When I hit enter, I've actually seen two different results, both wrong:
  * Normally, the description is present ("Review for Bob"), but the time entry has no project. I then have to go manually add the project.
  * Once (only once...I can't reproduce this) the " - Code Reviews" was actually copied in as part of the time entry description. It still had no project...

(This is from the toggldesktop_x86_64-7_1_73-2014-09-24-13-58-19.tar.gz tarball.)

**Comment by tanel** [comment]
Seems to work fine in master branch.
